### ISSUE TITLE
More Than One LG TV

### ISSUE THREAD

**Issue by greztaylor** [merdok/homebridge-webos-tv#100]
I have two of the same LG TVs in my house. How would I go about adding 2 x TVs in my home app? What would my config.json need to look like?

**Comment by creinhart** [comment]
`"accessories": [
    {
      "accessory": "webostv",
      "name": "Living Room TV",
      "ip": "192.168.0.148",
      "mac": "00:51:ED:35:AF:DC",
      "keyFile": "/Users/chrisreinhart/.homebridge/persist/lgtvKeyFile",
      "pollingInterval": 3,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    },
      

{
      "accessory": "webostv",
      "name": "Bedroom TV",
      "ip": "192.168.0.112",
      "mac": "20:3D:BD:FA:A4:E0",
      "keyFile": "/Users/chrisreinhart/.homebridge/persist/lgtvKeyFile2",
      "pollingInterval": 3,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    }
  
]`

**Comment by creinhart** [comment]
"accessories": [
    {
      "accessory": "webostv",
      "name": "Living Room TV",
      "ip": "192.168.0.148",
      "mac": "00:51:ED:35:AF:DC",
      "keyFile": "/Users/chrisreinhart/.homebridge/persist/lgtvKeyFile",
      "pollingInterval": 3,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    },
      

{
      "accessory": "webostv",
      "name": "Bedroom TV",
      "ip": "192.168.0.112",
      "mac": "20:3D:BD:FA:A4:E0",
      "keyFile": "/Users/chrisreinhart/.homebridge/persist/lgtvKeyFile2",
      "pollingInterval": 3,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    }
  
]

**Comment by creinhart** [comment]
"accessories": [
    {
      "accessory": "webostv",
      "name": "Living Room TV",
      "ip": "192.168.0.148",
      "mac": "00:51:ED:35:xx:xx",
      "keyFile": "/Users/xx/.homebridge/persist/lgtvKeyFile",
      "pollingInterval": 3,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    },
      

{
      "accessory": "webostv",
      "name": "Bedroom TV",
      "ip": "192.168.0.112",
      "mac": "20:3D:BD:FA:xx:xx
      "keyFile": "/Users/xx/.homebridge/persist/lgtvKeyFile2",
      "pollingInterval": 3,
      "tvService": true,
      "inputs": [
          
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    }
  
]

**Comment by merdok** [comment]
Yup, exactly like @creinhart posted :p
