### ISSUE TITLE
Constant App Approval Requested

### ISSUE THREAD

**Issue by frizby66** [merdok/homebridge-webos-tv#101]
Hi, having an issue where the module works but I get the message on the TV asking me to approve external app popping up for less than a second, every 10 sec or so. Anyone else seeing this?

**Comment by frizby66** [comment]
It appears to write the key file ok and all other modules work fine. Message is up for such a short amount of time you can’t react. Deleted key file and message stays on screen, accept it, key file gets created and after a whim the message starts again!

**Comment by merdok** [comment]
What TV do you have?

**Comment by frizby66** [comment]
OLED55B7 LG

**Comment by merdok** [comment]
Well, i guess then this either an issue with your environment (permission) or with your TV.

**Comment by frizby66** [comment]
Could it be an issue with the module only having 3 HDMI inputs and my TV has 4? Is there some form of mismatch?

**Comment by merdok** [comment]
No, this has nothing to do with this plugin.

**Comment by frizby66** [comment]
So the keyfile gets written by the plugin with no issues. Does it ever have to write to it again or is it only for reference when a command is issued? Does the plugin poll the tv to check the status (active input, on/off state, etc?). Could be a request/response delay issue (pi is taking too long to respond with the keyfile)?

**Comment by merdok** [comment]
start hombridge in debug mode. reproduce the issue and post the log here from homebridge. Maybe that will help to see what is happening.
