### ISSUE TITLE
Add Sleep timer control

### ISSUE THREAD

**Issue by luluhoc** [merdok/homebridge-webos-tv#102]
Hey,

Can you add sleep timer control?

**Comment by merdok** [comment]
Sorry, there is no documented way by LG to control that. If i ever find a way to do that then i will think about it.

**Comment by 2nm** [comment]
You could just have a HomeKit automation.  Or use something like the Eve app or another HomeKit automation app to create a timer of some form.  I’d guess that Siri shortcuts will eventually allow for state change automation and that way you’ll have it ie state change, timer, action.  But I’d have a look at third party apps controller for HomeKit?

**Comment by merdok** [comment]
I guess that could be done like that.
