### ISSUE TITLE
New HomeKit integration no inputs

### ISSUE THREAD

**Issue by Hazza42** [merdok/homebridge-webos-tv#103]
After switching to using the new HomeKit integration, I can’t get any inputs to show up, either in the ‘input’ list via force touching, or by going into settings. There is simply nothing there. 

If I manually add inputs via the config file, they appear as separate accessories (which do nothing when tapped) and still don’t appear under ‘inputs’ or in settings.

**Comment by creinhart** [comment]
You may have to completely remove your Homebridge from HomeKit and re-add it. Fixed it for me.

**Comment by Hazza42** [comment]
> You may have to completely remove your Homebridge from HomeKit and re-add it. Fixed it for me.

Unfortunately I’ve already tried that to no avail. I’ve also tried restarting homebridge, restarting my iPhone and force quitting the Home app, sadly nothing has helped.

**Comment by merdok** [comment]
You have to remember that iOS 12.2 is just a beta so it has a lot of bugs. This is one of those bugs. Simply force close the Home app and reopen it again.

**Comment by Martvvliet** [comment]
I did remove the accessories and persist folder. remove homebridge from homekit and than add it again. If you don't remove those files it will keep some cache. after that it worked fine for me.

**Comment by Hazza42** [comment]
> You have to remember that iOS 12.2 is just a beta so it has a lot of bugs. This is one of those bugs. Simply force close the Home app and reopen it again.

No luck unfortunately, force quitting the home app has no affect, for me at least. I’ve even tried removing and re-adding  Homebridge and deleting the accessories and persist folders too. 

It’s odd since literally yesterday all the inputs were appearing but weren’t functioning, so I updated the plugin and now I can’t get any inputs to appear at all.

**Comment by merdok** [comment]
Please note that i removed all the default inputs in the 1.5.2 release, because they couldn't be renamed. So you have to add all the inputs that you want manually now through the config. Maybe that is the case here?

**Comment by Hazza42** [comment]
Thats 

> Please note that i removed all the default inputs in the 1.5.2 release, because they couldn't be renamed. So you have to add all the inputs that you want manually now through the config. Maybe that is the case here?

Thats what I thought could be the problem originally, but manually adding inputs had a different effect. It simply adds extra accessories to my Home app that don't function and doesn't add any inputs to the inputs section under my TV. Is there a way of adding inputs manually without them appearing in the home app as accessories that perhaps I'm missing?

**Comment by merdok** [comment]
Inputs appearing as accessories is the Home app bug which i was already talking about above. You need to force close the Home app (kill with the app switcher) and/or restart your hombridge.

**Comment by Hazza42** [comment]
> Inputs appearing as accessories is the Home app bug which i was already talking about above. You need to force close the Home app (kill with the app switcher) and/or restart your hombridge.

Ah I see, well thats triggered a new issue in that adding inputs manually no longer has any affect! They don't appear as accessories, but they also don't appear in the inputs section either, even after going through the usual restart/force quit/remove/re-add process. I do have multiple TVs in the house, perhaps that could be a contributing factor?

**Comment by Hazza42** [comment]
Here's my current config setup, is there anything here I've perhaps setup wrong?

![screen shot 2019-01-29 at 16 59 02](https://user-images.githubusercontent.com/44146784/51925857-d802f200-23e7-11e9-859c-63f69a25bbf9.jpg)

**Comment by merdok** [comment]
Everything is ok with your config. This is simply a Home app bug related to iOS12.2 Beta. You need to try some combination of the steps mentioned above to fix it.

**Comment by Hazza42** [comment]
Shame it’s an issue with iOS. Keeping my fingers crossed that the next beta will fix this!

**Comment by merdok** [comment]
Yes, but you can simply fix it yourself by just restarting the home app. I had the issue myself. Just restart the home app and it should be good.

**Comment by Hazza42** [comment]
Honestly tried that so many times. No luck unfortunately, on both my iPhone and iPad. Perhaps my issue is deeper than that. I’m thinking setting Homebridge up again from scratch might solve the issue.

**Comment by th3cure** [comment]
@merdok I updated the plugin on my mac, deleted the persist and accessories folders and readied Homebridge to my home app. in version 1.5.2 you seem to have removed the default inputs but they are still showing up for me.. do I have to delete anything else on my Mac?

**Comment by henkied** [comment]
have installed ios 12.2. Still a question, I see in the app, bottom left, "input" that everything is empty. How can I add a function to this?

see att

below the config:

"accessories": [
        {
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "PS4"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "com.webos.app.photovideo",
                    "name": "Photo Video"
                }
            ],
            "name": "LGwebOSTV",
            "ip": "10.0.1.78",
            "mac": "7c:1c:4e:98:28:9b",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "tvService": true,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": true,
            "mediaControl": false,
            "accessory": "webostv"
        }
    ],
![IMG_0954](https://user-images.githubusercontent.com/20031014/54951805-cdc32700-4f44-11e9-8af3-8c4c46ef4f97.jpg)
