### ISSUE TITLE
Can i use volume Button as trigger?

### ISSUE THREAD

**Issue by meinname** [merdok/homebridge-webos-tv#106]
Hi, 
as my AV Receiver isn't supported by the LG Magic Remote and LG doesn't seem to change this, i had an idea: 
Use the the homebridge webos plugin as trigger for sending IR Volume Up or Down Button press to a Broadlink Device (don't have this yet)

Would this work? And how would the trigger look like? Cause i tried some things but the fakebulb i made for testing wasn't switched

**Comment by merdok** [comment]
Sorry, this has not really anything to do with this plugin. You would need to use a separate plugin which can control your Broadlink Device.

**Comment by meinname** [comment]
Sorry for being unclear:
i have set:             "volumeControl": "switch",

When i set an automation for the switch TV Volume Down being pressed it works (most times - it seems sometimes the On status is changed to off too fast) when i toggle it via homekit.

But when i use my LG Magic remote the switch isn't toggled. Though i get in log:
[TV] webOS - audio status changed

Can this be changed to be able to get the event? - maybe with a delay on status change from on to off?
