### ISSUE TITLE
Persist ConfiguredName characteristic value for input

### ISSUE THREAD

**Issue by KhaosT** [merdok/homebridge-webos-tv#107]
The implementation should try to persist values of “ConfiguredName” to avoid having user experience input name getting reverted when homebridge restarts.

If persisting those values are not possible, it’s better to omit the ConfiguredName characteristic in input source service so HomeKit won’t try to update local name on iOS to match what’s on the accessory.

**Comment by merdok** [comment]
I noticed that too, that the input names are reverted back to its default name after homebridge is restarted. For that reason i removed the default inputs completely so people can define their own names in the config, but of course that still will revert when they change it in the Home app.
So what you are saying is that i should write the name which a user enters in the Home app to the disk and load it back after a restart? Do i understand that correctly? How i would know that a user change a name of an input?

**Comment by KhaosT** [comment]
Yeah that's correct. When user make a change to input source name in Home app, HomeKit will write the new name to `ConfiguredName` characteristic, if you want to keep that characteristic, it would be great to save the written value and restore it when you reinitialize the accessory.

Honestly it would probably be a lot less work if you just omit that characteristic completely since it's not possible to communicate about name changes back to LG TV using their existing API. Omitting characteristic will allow user to keep their local input name on HomeKit side.

**Comment by KhaosT** [comment]
(Actually ignore the omission part... Didn't realize it's a required characteristic 😅)

**Comment by merdok** [comment]
Ok, that makes sense. But how would i know that this characteristic changed, like the user typed a new name? Is there some kind of event when that happens?

This reverting back the name of the accessory is an annoying thing...

**Comment by KhaosT** [comment]
It go through the normal characteristic update logic, like `inputSourceService.getCharacteristic(Characteristic.ConfiguredName).on('set', ...)`.

**Comment by merdok** [comment]
Makes sense. Thanks for the info, will try to implement this so that the name doesn't revert back on every restart...

**Comment by merdok** [comment]
Added in version 1.5.4.
