### ISSUE TITLE
remoteControlButtons  ON/OFF

### ISSUE THREAD

**Issue by marcodesantis71** [merdok/homebridge-webos-tv#112]
Hello,

I have configured the plugin and set the channels with the remoteControlButtons option.

The channels are changed.

But the light of the corresponding button is turned off after a few seconds.

Is it possible to make the light remain active?

**Comment by merdok** [comment]
The switch will be always on as soon as you open the corresponding channel. Maybe there is an issue with your setup?

**Comment by marcodesantis71** [comment]
Hi,

this is my conf:

 "accessories": [
    {
      "accessory": "webostv",
      "name": "LG Camera",
      "ip": "192.168.123.36",
      "mac": "xxxxxx",
      "broadcastAdr": "192.168.123.255",
      "keyFile": "/home/thegod/.homebridge_multimedia/lgtvKeyFile",
      "pollingInterval": 5,
      "volumeControl": "slider",
      "mediaControl": false,
      "inputs":[
          {
            "appId": "com.webos.app.livetv",
            "name": "TV"
          },
          {
            "appId": "com.webos.app.hdmi1",
            "name": "AppleTV"
          }
      ],
"remoteControlButtons": ["MUTE","HOME","MENU",0,1,2,3,4,5,6,7,8,9]
    }
],

**Comment by merdok** [comment]
Your remoteControlButtons are not all strings, you need to change that.

**Comment by marcodesantis71** [comment]
Hi

which string ?

**Comment by merdok** [comment]
Just put the numbers as quotes "0", "1"...

**Comment by merdok** [comment]
That how it should be because this is a stateless switch and it has not state (it is always off),
