### ISSUE TITLE
Volume Control greyed out on TV service.

### ISSUE THREAD

**Issue by jonlonergan** [merdok/homebridge-webos-tv#116]
I’ve been using homebridge webOS tv in my HomeKit setup for a while. Today I updated and changed config.json to use the new HomeKit TV service in iOS 12.2. So far so good, except that the TV volume control is greyed out on iOS. Previously, the volume as lightbulb service was working fine.

Any ideas?

More details - Apple TV 4K running tvOS 12.2 PB1
LG 55UH8500-UA running webOS 05.30.30

**Comment by jonlonergan** [comment]
Update: I think this may be an iOS issue, as I can control the TV volume from the 3rd party “Home” app

**Comment by merdok** [comment]
I also do not think this is related to the plugin. But i never seen something greyed out in the Home app so i have no idea from where it comes...
