### ISSUE TITLE
TV stops responding after being off for extended period of time

### ISSUE THREAD

**Issue by gid204** [merdok/homebridge-webos-tv#117]
My issue is whenever I turn the TV off and leave it for an extended period of time I can no longer turn the TV on using HomeKit (first party home app).

If I manually turn the TV on, it is then completely responsive in HomeKit until I leave it again for an extended period of time.

Not sure if this is a plugin issue (I think this is least likely), issue with iOS 12.2 beta or possibly the fact that my TV is using Wifi not the RJ45 connection.

**Comment by merdok** [comment]
I guess this an issue with your TV or environment (homebridge device or network). 
What you can do is try to send a magic packet manually from your PC using any wake on lan tool and see if that powers on the TV.

**Comment by gid204** [comment]
Figured out tv doesn’t actually support WOL. For some reason for a short amount of time it listens to packets coming in but then completely goes to sleep which was causing the issue. Found some other issues from this plugin from over a year ago with same issue. Reverted to using my broadlink IR blaster for turning it on.
