### ISSUE TITLE
Can't  use the Volume Switch as event for automation

### ISSUE THREAD

**Issue by meinname** [merdok/homebridge-webos-tv#120]
Sorry for being unclear on my other issue by speaking also about an external plugin.

i have set:             "volumeControl": "switch",
and             "notificationButtons": [
                "VolumeUP",
                "VolumeDown"
            ],

I have set an automation for the switch "TV Volume Down". When changed to Status On it activates the notification "VolumeDown. - It works most of time (it seems sometimes the On status is changed to off too fast) when i toggle it via homekit.

But when i use my LG Magic remote the switch isn't toggled. Though i get in log:
[TV] webOS - audio status changed

Can this be changed to be able to get the event? - maybe with a delay on status change from on to off?

_Originally posted by @meinname in https://github.com/merdok/homebridge-webos-tv/issues/106#issuecomment-460718123_

**Comment by meinname** [comment]
not totally:
i did a "set volume to 5" + notification up scene  and also same for down. 
And an automation to set the scene for up if volume is 6 and one for down if volume is 4 
(the set volume to 5 was for "resetting" back to 5)

worked good as i wanted.

Until i noticed that the volume values are only there when i control the internal volume.
But as the final result should be to control optical output i set the tv to optical out.
And there is no volume value (or better the value last set is frozen on raising or lowering the volume)

**Comment by merdok** [comment]
Unfortunately i cannot test that scenario since i do not have any external audio device connected to my TV.
About the volume buttons, i am not sure if that makes sense to update the switches when the volume on the changes. Those buttons should be stateless switches so they should not have any state any not be used for automation.

**Comment by meinname** [comment]
That's a problem when someone wants to check a state on smth stateless ;)

Well i didn't expect a real solution. I just wanted to be sure that i haven't overseen smth.
I think i go now for a different solution with an IR Receiver and build with the Blaster I get a Homekit based IR Translator :D

So thnx for your help.
