### ISSUE TITLE
Only one of my TVs shows up in CC remote

### ISSUE THREAD

**Issue by 2nm** [merdok/homebridge-webos-tv#121]
I have two oled LG webos TVs identical (thanks to my OCD sad times for my bank account) though only one of the two TVs shows up in the remote app.  I haven’t tried running two incidents of homebridge to see if that works as I had hoped that it would work as is.  Other than the remote issue all working well.  Running the latest version of node, homebridge, iOS dev beta and this plugin.  Any ideas on how to resolve?

**Comment by merdok** [comment]
Please post your config.json here, so i can have a look if this is correctly configured.

**Comment by jdawgydawg** [comment]
+1. I have 3 WebOS TV’s (all different models) and only one of them appears in the control centre remote. All appear in the home app and work perfectly there.

Will post config file when I can.

**Comment by merdok** [comment]
Oh, i guess this a bug in iOS then? When all of them appear in the home app they there is nothing wrong with your config.

**Comment by jdawgydawg** [comment]
I guess so. Here is my config:

` 

    "accessories": [
    {
      "accessory": "webostv",
      "name": "Living Room TV",
      "ip": "192.168.0.30",
      "mac": "XX:XX:XX:XX:XX:XX",
      "keyFile": "/homebridge/lgtvKeyFile",
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false,
      "tvService": true,
      "inputs": [
          {
            "appId": "com.webos.app.livetv",
            "name": "Live TV"
          },
          {
            "appId": "com.webos.app.tvguide",
            "name": "TV Guide"
          },
          {
            "appId": "com.webos.app.hdmi1",
            "name": "Apple TV"
          },
          {
            "appId": "com.webos.app.hdmi3",
            "name": "PS4"
          }
        ]

    },

     {
      "accessory": "webostv",
      "name": "Bedroom TV",
      "ip": "192.168.0.26",
      "mac": "YY:YY:YY:YY:YY:YY",
      "keyFile": "/homebridge/lgtvKeyFile2",
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false,
      "tvService": true,
      "inputs": [
          {
            "appId": "com.webos.app.livetv",
            "name": "Live TV"
          },
          {
            "appId": "com.webos.app.tvguide",
            "name": "TV Guide"
          },
          {
            "appId": "com.webos.app.hdmi1",
            "name": "Apple TV"
          },
          {
            "appId": "com.webos.app.hdmi2",
            "name": "PS4"
          }
        ]

    },

    {
      "accessory": "webostv",
      "name": "Kitchen TV",
      "ip": "192.168.0.21",
      "mac": "ZZ:ZZ:ZZ:ZZ:ZZ:ZZ",
      "keyFile": "/homebridge/lgtvKeyFile3",
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false,
      "tvService": true,
      "inputs": [
          {
            "appId": "com.webos.app.livetv",
            "name": "Live TV"
          },
          {
            "appId": "com.webos.app.tvguide",
            "name": "TV Guide"
          },
          {
            "appId": "com.webos.app.hdmi1",
            "name": "Apple TV"
          },
          {
            "appId": "com.webos.app.hdmi2",
            "name": "HDMI 2"
          }
        ]

    }

 
`

**Comment by merdok** [comment]
No issue with the config, i guess this is a bug in iOS.

**Comment by 2nm** [comment]
Weirdly new beta has changed the remote app but the problem persists

**Comment by merdok** [comment]
What if you change the order of the TVs in the config.json, does this has an effect?

**Comment by homohurre123** [comment]
No this is an IOS bug for sure. I have the same Issue with the Harmony Plugin running alongside the WebOs one. It seems only one TV appears per hub. I guess with two Homebridge Pis or so it would show 2 TVs and so on.

**Comment by jdawgydawg** [comment]
> What if you change the order of the TVs in the config.json, does this has an effect?

I swapped my Bedroom TV with Living Room TV and there was no change. Living Room TV only appears in the remote picker.

**Comment by merdok** [comment]
Ok, then I guess that this still might be a bug in the iOS Beta. I have no other ideas why it doesn't work...

**Comment by Hatika78** [comment]
Same issue sometimes when I restart Homebridge also in Beta 2. A quick restart resolve the problem for me. Hope it can help you.

**Comment by Hatika78** [comment]
I think it’s a bug. I’ve one TV LG and one with Harmony Plugin. And just the LG appears. When I put tvService to false on the LG config, the Harmony appears.

**Comment by merdok** [comment]
Let's see if something changes in the next Beta...

**Comment by gotschi** [comment]
I experience the same behaviour with two self written plugins (Kodi/old bravia)
I only got it working to show up more remotes when running multiple Homebridge instances for each remote.

**Comment by merdok** [comment]
This could also be a homebridge issue then...

**Comment by merdok** [comment]
How about iOS12.2 Beta 4?

**Comment by 2nm** [comment]
Still only one.  Are we definitely sure that nothing is happening in the mapping only because surely if we could get two TVs working before HomeKit then surely the only thing that changed was how it’s routed to the UI?  I am probably be totally wrong, just asking.  Otherwise I’ll try to set up two incidents of HomeBridge

**Comment by merdok** [comment]
Before HomeKit there was no remote in the CC so i am not sure what you mean. You stated that both TVs show up in the HomeKit just not in the remote that if that is the case then else this is not yet supported by the Beta or there is something in in HomeKit what was not yet been discovered.

**Comment by 2nm** [comment]
Okay cool, I meant that the remote functionality was supported through switches before so iOS can play well with it (though I guess this is more homebridge can convert well from LG input to switch input).  It was just a muse. I reported this to Apple via the feedback in the last beta.

**Comment by merdok** [comment]
This is still supported by switches.

**Comment by 2nm** [comment]
Fair enough, then the behaviour is weird but also it must be something specific to homebridge for I don’t feel something like this would go unaddressed up to this stage in the betas when this will be a flagship development at the event in late March

**Comment by merdok** [comment]
We will have to wait till the final release to be sure about that.

**Comment by jarvismeier** [comment]
There’s another thread where they are using HomeKit tv to control Sonos and there they mention you’re limited to one TV per HomeKit bridge.

**Comment by merdok** [comment]
Oh, really? That is really unfortunate. Then i guess this is not a bug just a limitation from Apple...
@jarvismeier Thanks for letting us know!

**Comment by plainsane** [comment]
> There’s another thread where they are using HomeKit tv to control Sonos and there they mention you’re limited to one TV per HomeKit bridge.

Man, that is really boeboe

**Comment by rossco57** [comment]
If it was only limited to one tv then I would not have my harmony working as well as my LG tv as both appear in home kit but only my atv and LG appear in cc not sure if harmony should appear in cc

**Comment by merdok** [comment]
@rossco57 In HomeKit you can have multiple TVs, just the CC remote for some reason will allow to control one of them...

**Comment by huongminh** [comment]
Confirm this issue is homebridge related. I put each of my 3 TVs in one homebridge instance and all show up in the remote in iOS control center.

**Comment by KhaosT** [comment]
It's kinda lame Apple shipped the iOS 12.2 with this behavior. I added a new API to homebridge to allow plugins to publish separate (non-logical?) accessories to workaround this. You can check API version 2.4 and use [publishExternalAccessories](https://github.com/nfarina/homebridge/blob/master/lib/api.js#L104) to do so. You'll need to manually construct a [PlatformAccessory](https://github.com/nfarina/homebridge/blob/master/lib/platformAccessory.js) to utilize the API.

**Comment by merdok** [comment]
@KhaosT Thanks for the info. 
Will check that out! Is there any example code for this that i can have a look at?

**Comment by KhaosT** [comment]
Something like this https://github.com/KhaosT/homebridge-camera-ffmpeg/blob/master/index.js, just switch the publishCameraAccessories with the new API.

Two main differences, you need to register as a platform, and publish TV accessories in didFinishLaunching notification.

**Comment by merdok** [comment]
@KhaosT Thanks! Will have a look at it most probably during the weekend.

**Comment by taimurasad** [comment]
@merdok any update on the multiple tv issue in control center remote widget? Thanks!

**Comment by merdok** [comment]
@taimurasad i did not have time yet to have a look at it. Will try to do in the next days. Please note that i just have one TV so i am not sure yet how i should test this properly...

**Comment by luowilliam326** [comment]
@merdok I saw this app on Mac App store for linking Logitech Harmony Hub to Homekit, the demo shows multiple TV accessories in the control center remote. I wonder how they did it? Did you have time to take another look?

**Comment by luowilliam326** [comment]
@merdok. I saw this app on Mac App store for linking Harmony Hub to Homekit. The demo I attached shows multiple TV in the control center remote so Homekit is capable of showing multiple TV accessories. I wonder how they did it. Did you have time to look into this more?
https://youtu.be/cGVeSTe9DMs
Thanks!

**Comment by Hatika78** [comment]
@luowilliam326 what is the name of the app on Mac App Store ?
@merdok You do a really good job but I really want to stop to have 2 Homebridge just for this. 
Thanks.

**Comment by merdok** [comment]
The biggest problem here for me is that i do not own 2 TVs to be able to test it...

**Comment by luowilliam326** [comment]
@Hatika78 the app is called Harmony Bridge. I think it’s just a nicely packaged homebridge with a skin on it. 
Harmony Bridge by Guy Brooker you can google it.
I just got 2 harmony hubs. I will try install the homebridge harmony plug in using the TV accessory config and see if I can get 2 remote for 2 TVs. If that’s works maybe there’s something that can be learned for this LG app.

**Comment by Hatika78** [comment]
Ok Thanks. I have just one TV but I use a Logitech Harmony. And I can’t have your plugin and the Harmony of @nicoduj on the same Homebridge. And I think he could see with the app you talk about @luowilliam326 how it’s work.

**Comment by nicoduj** [comment]
With my plugin you can publish as an external accessory even the first hub so you can have it with other plugins :) just use 1.0.0 and publishalltvasexternalaccessory option

Nicolas

**Comment by Hatika78** [comment]
Thanks @nicoduj I will try this after my holidays. Good work for your plugin. 😉

**Comment by 2nm** [comment]
>@taimurasad i did not have time yet to have a look at it. Will try to do in the next days. Please note that i just have one TV so i am not sure yet how i should test this properly...

@merdok is it possible to duplicate the same TV having two incidences of the same accessory?  Therefore allowing you to see if both show up?

**Comment by nicoduj** [comment]
> > @taimurasad i did not have time yet to have a look at it. Will try to do in the next days. Please note that i just have one TV so i am not sure yet how i should test this properly...
> 
> @merdok is it possible to duplicate the same TV having two incidences of the same accessory? Therefore allowing you to see if both show up?

That is how I did it for my harmony plugin, declaring the device twice with different names ;)

**Comment by 2nm** [comment]
>> > @taimurasad i did not have time yet to have a look at it. Will try to do in the next days. Please note that i just have one TV so i am not sure yet how i should test this properly... ...

@nicoduj and what did that give you?

**Comment by nicoduj** [comment]
I allowed me to ensure that both device were visible in remote app after adding the second one as an external one.

**Comment by huongminh** [comment]
I’m sure 1 TV can be duplicated as 2 accessories. I use this setup because I need extra buttons for my automation which are available only with the old tv service. Just change the accessory name and It works. 


Sent from Yahoo Mail for iPhone


On Wednesday, May 1, 2019, 2:26 PM, 2nm <notifications@github.com> wrote:



@taimurasad i did not have time yet to have a look at it. Will try to do in the next days. Please note that i just have one TV so i am not sure yet how i should test this properly...


@merdok is it possible to duplicate the same TV having two incidences of the same accessory? Therefore allowing you to see if both show up?

**Comment by huongminh** [comment]
What did you mean by “an external one”?


Sent from Yahoo Mail for iPhone


On Wednesday, May 1, 2019, 2:31 PM, Nicolas Dujardin <notifications@github.com> wrote:


I allowed me to ensure that both device were visible in remote app after adding the second one as an external one.

**Comment by 2nm** [comment]
>I’m sure 1 TV can be duplicated as 2 accessories. I use this setup because I need extra buttons for my automation which are available only with the old tv service. Just change the accessory name and It works.  ...

@huongminh the new TV service used to output power state etc to third party apps so you do some really neat automations but something with HomeKit seemed to change that when 12.2 was officially released - not sure what.

**Comment by huongminh** [comment]
I mean buttons for input sources and apps so I can play in my scene setup like movies time, apple TV time for example. 


Sent from Yahoo Mail for iPhone


On Wednesday, May 1, 2019, 2:42 PM, 2nm <notifications@github.com> wrote:



I’m sure 1 TV can be duplicated as 2 accessories. I use this setup because I need extra buttons for my automation which are available only with the old tv service. Just change the accessory name and It works.  ...


@huongminh the new TV service used to output power state etc to third party apps so you do some really neat automations but something with HomeKit seemed to change that when 12.2 was officially released - not sure what.

**Comment by merdok** [comment]
> > @taimurasad i did not have time yet to have a look at it. Will try to do in the next days. Please note that i just have one TV so i am not sure yet how i should test this properly...
> 
> @merdok is it possible to duplicate the same TV having two incidences of the same accessory? Therefore allowing you to see if both show up?

@2nm Interesting, will check it out if that helps me to fix the issue.

**Comment by plainsane** [comment]
Other authors are using a platform to become a bridge, it seems worth while as I had to spin up 4 instances of homebridge to get all my. Tvs to show

**Comment by merdok** [comment]
Do you need to run 4 instances of homebridge? Isn't it enough to initialize just the plugins in the config.json multiple times?

**Comment by grzegorz914** [comment]
@merdok 
any progress with adaption to new homebridge api and use TVs as external accessory?

https://github.com/nfarina/homebridge/blob/master/lib/api.js

**Comment by merdok** [comment]
Sorry, not yet. Did not have the time, but i definitely did not forget about it.

**Comment by grzegorz914** [comment]
OK, 
I’ll cant waiting on this adaption....

**Comment by merdok** [comment]
Did have a small look at it. The issue which i see is that i need to change the type from accessory to platform which will basically break the plugin for everyone after update. Everyone would need to adjust the config.json first to make it work again...

**Comment by grzegorz914** [comment]
Chenge the config.json is not a problem, just inform about this in changelog.

**Comment by merdok** [comment]
Lots of people do not read changelogs... This will just lead to people coming here and opening bugs.

**Comment by grzegorz914** [comment]
OK,
in that case the solution would be to release a separate version.

**Comment by merdok** [comment]
Currently i do not really have any good solution for this. I will try to make the platform and accessory work both simultaneously...

**Comment by grzegorz914** [comment]
waiting for test release...

**Comment by grzegorz914** [comment]
@merdok 
any thing new with this adaption to new api, or will still as it is?

**Comment by merdok** [comment]
Hopefully soon i will have some time to have a look at it. But i am still kind of unsure because when i switch to the new api it will break the plugin for everyone and the config need sto be adjusted...

**Comment by grzegorz914** [comment]
Can U make new plugin with new api.?

**Comment by merdok** [comment]
I will definitely not do a new plugin. That would just unnecessary confuse people and i would have to maintain 2 codebase's

**Comment by grzegorz914** [comment]
OK, no problem,
 it's important to adapt the plugin to the new api.

**Comment by merdok** [comment]
Hopefully i will find time to do that during the holidays.

**Comment by agneevX** [comment]
Any update on this?

**Comment by grzegorz914** [comment]
> Any update on this?
look here: 
https://github.com/grzegorz914/homebridge-lgwebos-tv

**Comment by agneevX** [comment]
@grzegorz914 I'm facing an issue there https://github.com/grzegorz914/homebridge-lgwebos-tv/issues/9

**Comment by merdok** [comment]
I already have 70% of the work done locally, unfortunately due to lack of time i did not have the chance to finish it up. I try to wrap it up soon.

**Comment by merdok** [comment]
Platform is now supported in version 1.7.0 👍
