### ISSUE TITLE
LG wants permission when you reboot Homebridge

### ISSUE THREAD

**Issue by JDogg016** [merdok/homebridge-webos-tv#122]
So every time homebridge is rebooted. The LG device will not work until I approve the connection all over again. 

Does this happen for others?

**Comment by merdok** [comment]
You have insufficient permissions to the keyFile directory which you specified in the config.json. Make sure that you have write permissions there. You can also try to remove that line completely from the config file.

**Comment by JDogg016** [comment]
Ok. Adjusted my permissions. I will report back.

Thank You,




Justin Bennett, Esq.
General Counsel
Bennett Auto Supply

3141 S.W. 10th Street
Pompano Beach, Florida 33069
www.bennettauto.com
Office: tel:954-335-8725
Fax: tel:954-564-6620
Mob: tel:954-261-2266

**Comment by JDogg016** [comment]
This has been fixed by removing the line from config.json.  

Second time I removed the line, the solution worked.

**Comment by merdok** [comment]
Thanks for the info.
