### ISSUE TITLE
Beta 3 Inputs don't show the names anymore

### ISSUE THREAD

**Issue by homohurre123** [merdok/homebridge-webos-tv#124]
https://imgur.com/a/KFlx1eF
Those were perfect in Beta 2. Maybe an IOS bug or meant to be. I thought I would point it out :)
Edit: The Harmony plugin ( https://www.npmjs.com/package/homebridge-harmony) Is still displayed correctly if this helps you in any way :)

**Comment by merdok** [comment]
I am also already on Beta 3 and the input names are showing fine as before. Are you sure that you did not change anything?

**Comment by homohurre123** [comment]
Well I'm on Beta 2 on my iPad and there its correct. Didn't change anything just updated my iPhone.
Ipad beta 2: https://imgur.com/a/bgxv5wV
Config: `{
	"accessory": "webostv",
	"name": "My webOS tv",
	"ip": "XXX.XXX.XXX.XX",
	"mac": "XX:XX:XX:XX:XX:XX",
	"pollingInterval": 10,
	"tvService": true,
	"inputs": [{
			"appId": "com.webos.app.livetv",
			"name": "Live TV"
		},
		{
			"appId": "netflix",
			"name": "Netflix"
		},
		{
			"appId": "com.webos.app.hdmi4",
			"name": "Apple TV"
		},
		{
			"appId": "youtube.leanback.v4",
			"name": "YouTube"
		},
		{
			"appId": "de.zdf.app.zdfm3",
			"name": "ZDF Mediathek"
		},
		{
			"appId": "ard.mediathek",
			"name": "ARD Mediathek"
		},
		
		{
			"appId": "dazn",
			"name": "DAZN"
		},
		{
			"appId": "cdp-30",
			"name": "Plex"
		}


	],
	"volumeControl": false,
	"channelControl": true,
	"mediaControl": false,
"channelButtons": [1,2,9,10,11,20,31,32,37,46,140,200,303,304,305,306,307,308,683,744,745,746,747,748,749,750,751,752,757]
}`

**Comment by merdok** [comment]
Sorry, i cannot reproduce this issue on any of my devices (all are on Beta 3).  My suspicion is that you might have changed something which affected that.

**Comment by homohurre123** [comment]
Well I seriously didn't ;) Before I updated It was showing correctly after update it was like that. Didn't touch Homebridge at all in between. And on The iPad with beta 2 you can see it's still how it should be.
I will wait a few days It might become normal by itself..

**Comment by homohurre123** [comment]
I just saw I can change the input names in the Home app anyway so its not an issue @ all I guess. Still  a bit weird but I guess not important..

**Comment by merdok** [comment]
Yes, you can change the input names in the Home app. I guess this must have been just a weird bug related to the update. You should investigate this more and post here if something similar appears again.
