### ISSUE TITLE
CC remote trouble Beta 3

### ISSUE THREAD

**Issue by Hatika78** [merdok/homebridge-webos-tv#125]
Thanks a lot for your work it’s really cool ton control my TV with the new feature of iOS 12.2. But with the new design on Beta 3 of the remote, the back button, info button and volume control no longer work. 
Also do you think we could have the menu button like on the Apple TV remote or change the mapping of the Info button for the menu?
Thanks a lot.

**Comment by Hatika78** [comment]
I've tried volume with my Harmony Plugin and no longer working in Beta 3,like the Back button. Probably a bug of iOS and not your plugin. Can you confirm you have the same problem ?

**Comment by homohurre123** [comment]
Volume doenst work with Apple TV either.

**Comment by Hatika78** [comment]
Ok so it looks like an iOS bug

**Comment by merdok** [comment]
I think on Beta3 the mapping of some buttons on the CC Remote changed. I guess this would need to be adjusted in homebridge itself. 
@KhaosT do you know anything about changes for the CC remote on iOS12.2 Beta3?

**Comment by Hatika78** [comment]
Yes I've tried with Harmony Plugin and volume doesn't work on Beta 3. But on my iPad on Beta 2 it's good. I think you are right with this mapping change on iOS.

**Comment by KhaosT** [comment]
Might be a bug in b3. Some people reported that  switching target in remote control widget from your TV to Apple TV, and then switch it back made the volume control works again.

**Comment by merdok** [comment]
@KhaosT Unfortunately i do not have an Apple TV to test that...
How about the "Info" and "Back" buttons on the CC remote? They also do not work anymore. Do you think this is the same issue?

**Comment by homohurre123** [comment]
@KhaosT i tried and Can confirm it Works When switching 2 Times
But only If you don't interact with it while doing it

**Comment by merdok** [comment]
With the latest iOS12.2 beta 4 the remote control should now work properly again 👍

**Comment by NajibNour** [comment]
Sorry, I'm just wondering I see you guys talking about the CC remote, would it be the remote in control center. I do not get the option for volume (after selecting WebOS) but i do see the info and back buttons.  I do have my volume set to the slider at the moment. any ideas? or am I thinking of it wrong??..

**Comment by merdok** [comment]
When you open the remote then you can adjust the volume of the TV with the iOS device volume up/down buttons
