### ISSUE TITLE
Error: Sec-WebSocket-Accept header

### ISSUE THREAD

**Issue by dVIAN13** [merdok/homebridge-webos-tv#127]
Hello, I looked through some of the closed issues, but didn't necessarily find something to match..

every so often(not exact) I receive the error 'webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value ############'

it doesn't really seem to affect anything, but I see if randomly in the logs. anything I should be aware of? thanks!

**Comment by merdok** [comment]
You do not have to worry about this issue. I also get it randomly and never noticed any issues from it.
