### ISSUE TITLE
Sound Status configuration

### ISSUE THREAD

**Issue by huongminh** [merdok/homebridge-webos-tv#128]
Thanks for the plugin. It was a great work! I wish I could change the Sound out options from homekit i.e. "Internal speaker" when watching TV and say "Optical out" when watching a movie using my external home theater system. I notice in the homebridge log when I change my LG TV sound output by the remote control, the log prints out: sound status changed. So hopefully it can be integrated in the homekit.

**Comment by merdok** [comment]
I am note sure if it is possible but i will have a look into it.

**Comment by huongminh** [comment]
Thank you! your work was great!

**Comment by nihalgonsalves** [comment]
To add: The volume control doesn't seem to be ARC-aware. When not using HDMI ARC, the slider works fine, and the current status is accurate.

However when using HDMI ARC, as the TV itself does not know the volume of the receiver / sound bar, the slider does nothing (though the up/down switches still work perfectly!).

**Comment by merdok** [comment]
This is a know a limitation. The switches were added because of the slider issues with ARC :)

**Comment by nihalgonsalves** [comment]
@merdok Makes sense! :) I have two suggestions:

- Would it be useful to add a note in the README that the "Remote" tile using the physical buttons is the recommended way with the new HomeKit TV service? Could prevent a bit of confusion, like in my case.

- There's still one bug with the Volume Up/Down switches (though I've just removed them for now in favour of the way above): since the plugin doesn't know the actual volume, it often registers the volume at `0` when it isn't. This seems to make the Volume Down button register as "On". It could be nice to specify `"arcMode": true` in the config and thus not track the volume at all.

**Comment by merdok** [comment]
The physical buttons as volume is something from Homekit itself and not from this plugin for this reason i think that it is no necessary to include it in the README.

Sorry i do not get the second issue... Could you explain that more? The Volume Up/Down switches are stateless so i actually doesn't matter what the current volume is for them.

**Comment by nihalgonsalves** [comment]
Maybe a transient bug in the Home app, no worries.

Thanks for the responses and the plugin! :)

**Comment by merdok** [comment]
This has been added in version 1.5.6. Please check the README to see how to configure it and supported values.

**Comment by huongminh** [comment]
Thank you for your great work! I updated the plugin and see Buttons for Sound Output in the Home app. However, only TV speaker works. My 2 other buttons (arc and external_speaker) not working when I pressed (the buttons are on in the home app but TV output does not change). When I manually use my remote to change the sound output, status only updates the TV speaker. However the log file shows all output changes:
Apr 15 09:32:13 raspberrypi homebridge[9738]: [4/15/2019, 9:32:13 AM] [LG TV] webOS - current sound output: external_speaker
Apr 15 09:32:16 raspberrypi homebridge[9738]: [4/15/2019, 9:32:16 AM] [LG TV] webOS - sound output changed
Apr 15 09:32:16 raspberrypi homebridge[9738]: [4/15/2019, 9:32:16 AM] [LG TV] webOS - current sound output: soundbar
Apr 15 09:32:18 raspberrypi homebridge[9738]: [4/15/2019, 9:32:18 AM] [LG TV] webOS - sound output changed
Apr 15 09:32:18 raspberrypi homebridge[9738]: [4/15/2019, 9:32:18 AM] [LG TV] webOS - current sound output: bt_soundbar
Apr 15 09:32:20 raspberrypi homebridge[9738]: [4/15/2019, 9:32:20 AM] [LG TV] webOS - sound output changed
Apr 15 09:32:20 raspberrypi homebridge[9738]: [4/15/2019, 9:32:20 AM] [LG TV] webOS - current sound output: lineout
Apr 15 09:32:21 raspberrypi homebridge[9738]: [4/15/2019, 9:32:21 AM] [LG TV] webOS - sound output changed
Apr 15 09:32:21 raspberrypi homebridge[9738]: [4/15/2019, 9:32:21 AM] [LG TV] webOS - current sound output: headphone
Apr 15 09:32:23 raspberrypi homebridge[9738]: [4/15/2019, 9:32:23 AM] [LG TV] webOS - sound output changed
Apr 15 09:32:23 raspberrypi homebridge[9738]: [4/15/2019, 9:32:23 AM] [LG TV] webOS - current sound output: tv_external_speaker
Apr 15 09:32:24 raspberrypi homebridge[9738]: [4/15/2019, 9:32:24 AM] [LG TV] webOS - sound output changed
Apr 15 09:32:24 raspberrypi homebridge[9738]: [4/15/2019, 9:32:24 AM] [LG TV] webOS - current sound output: tv_speaker_headphone

**Comment by huongminh** [comment]
Oh, I changed the Output source in the config.json to the exact term in the log and now it works like a charm! Please correct the sample config.json to avoid confusion.

**Comment by merdok** [comment]
Good that it works :)
What do you mean exactly what i should correct? The example config has the exact values which need to be entered and the description also lists all possible values (there might be more depending on the TV and setup, those are the possible values on my TV :p)

**Comment by huongminh** [comment]
I meant the possible values should be checked in the homebridge log as manually switching outputs. Some of my TV values are different from yours:   
   - tv_speaker - internal tv speaker,
   - external_optical - optical audio,
   - external_arc - hdmi arc,
   - lineout - line out,
   - headphone - headphones,
   - tv_external_speaker - tv speaker and optical,
   - tv_speaker_headphone - tv speaker and headphones
My TV has external_speaker instead of external_optical for optical audio .... that was why first it did not work until I changed the values to match my TV. 

Sent from Yahoo Mail for iPhone


On Monday, April 15, 2019, 12:47 PM, Marcin <notifications@github.com> wrote:


Good that it works :)
What do you mean exactly what i should correct? The example config has the exact values which need to be entered and the description also lists all possible values (there might be more depending on the TV and setup, those are the possible values on my TV :p)

**Comment by merdok** [comment]
That is true. I will add a note about it.
