### ISSUE TITLE
iOS 12.2 Beta 3+4 No Home Button in CC Remote

### ISSUE THREAD

**Issue by ImpulsePie** [merdok/homebridge-webos-tv#130]
In Beta 3 and 4 of iOS 12.2 there is no longer a "Home" button on the CC remote with homebridge-webos-tv accessories. Instead there is only a large "Back" button. Without the Home button, you cannot change apps with the CC remote app, only in the Home app. In Beta 1 and 2 there was a Home button in the CC remote.

Should look something like this:
![tvremotenewinterface-800x780](https://user-images.githubusercontent.com/31958880/54475073-0f393100-47e5-11e9-8ac2-2a431d6d6ce1.jpg)

Instead it currently looks like this:
![IMG_1436](https://user-images.githubusercontent.com/31958880/54475080-2aa43c00-47e5-11e9-850c-ef09e50e31b4.PNG)

**Comment by Hatika78** [comment]
Would it be possible to overwrite a command like the "information" button to have the Home button. @nicoduj do this on his Harmony plugin. 
https://github.com/nicoduj/homebridge-harmony/blob/master/README.md

**Comment by rossco57** [comment]
Same for me

**Comment by merdok** [comment]
Sorry, this is something I cannot control. Apple did those changes for whatever reason.

Override for buttons would be possible and that is something i could add in a future release. Currently i want to focus on replicating the HomeKit TV support.
