### ISSUE TITLE
No input in tv homekit

### ISSUE THREAD

**Issue by henkied** [merdok/homebridge-webos-tv#132]
have installed ios 12.2. Still a question, I see in the app, bottom left, "input" that everything is empty. How can I add a function to this?

see att

below the config:

"accessories": [
{
"inputs": [
{
"appId": "com.webos.app.livetv",
"name": "Live TV"
},
{
"appId": "com.webos.app.hdmi1",
"name": "PS4"
},
{
"appId": "youtube.leanback.v4",
"name": "YouTube"
},
{
"appId": "com.webos.app.photovideo",
"name": "Photo Video"
}
],
"name": "LGwebOSTV",
"ip": "10.0.1.78",
"mac": "7c:1c:4e:98:28:9b",
"prefsDir": "~/.webosTv",
"pollingInterval": 5,
"tvService": true,
"volumeControl": "false",
"volumeLimit": 100,
"channelControl": true,
"mediaControl": false,
"accessory": "webostv"
}
],
![IMG_0954](https://user-images.githubusercontent.com/20031014/54952107-770a1d00-4f45-11e9-8d3b-cd91f95e3fcc.jpg)

**Comment by stefanrenne** [comment]
Got the same issue

**Comment by Scream57** [comment]
Got it. A combination of force-quitting the Home app and rebooting the iPhone fixed it.

**Comment by merdok** [comment]
@henkied 
@stefanrenne 
You need to force close the Home app and sometimes restart homebridge, after that the input list will update.
