### ISSUE TITLE
Homebridge Issue

### ISSUE THREAD

**Issue by crawfordandjohn** [merdok/homebridge-webos-tv#133]
These are the current errors I am getting for this plugin! Any advice?

```
/homebridge/node_modules/homebridge-webos-tv/index.js:86
    this.inputNamesFile = this.prefsDir + 'inputs_' + this.mac.split(':').join('');
                                                               ^
TypeError: Cannot read property 'split' of undefined
    at new webosTvAccessory (/homebridge/node_modules/homebridge-webos-tv/index.js:86:64)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:29)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

**Comment by merdok** [comment]
I guess that this is related to nodejs. I would suggest that you try to update your nodejs to a more recent version.

**Comment by cantchooseaname8** [comment]
I'm getting errors too and have already upgraded the nodejs. It crashes homebridge and everything gets a No Response error. As soon as I remove this from config.json everything goes back to working again. Any ideas?

**Comment by merdok** [comment]
@crawfordandjohn @cantchooseaname8 You did not specify a mac address in your config.json which is required for the plugin.

**Comment by cantchooseaname8** [comment]
> @crawfordandjohn @cantchooseaname8 I suppose you did not specify a mac address in your config.json which is required for the plugin.

I have both a mac address and static IP for the tv specified in config.json. Anytime I add the plugin configuration to config.json, it results in errors and homebridge won't load. I get No Response for all of my devices in homebridge. Any other ideas of what it could be?

Thanks.

**Comment by merdok** [comment]
There is an issue with your config.json. If you are not sure what some of the parameters are then i would suggest that you start with one of the examples.

**Comment by yepecece** [comment]
I am having a similar issue.
I think the problem comes when using Homebridge Config UI X when you setup homebridge-webos-tv via the settings editor.
When saving, volumeControl is set to "true" instead of true.

Could you check that and see if there are any other problems with that feature?

Thanks

**Comment by cantchooseaname8** [comment]
> There is an issue with your config.json. If you are not sure what some of the parameters are then i would suggest that you start with one of the examples.

I copied the example directly from the site, added my mac and ip address and then confirmed everything in jsonlint. Everything was then copied directly from jsonlint so it doesn't transfer any formatting or anything else weird. It doesn't even work when I do that. Any ideas?

**Comment by justinlohmeyer** [comment]
I’ve got the same issues... plugin worked for 5 seconds, than Homebridge crashed and I had to reinstall Homebridge completely.

**Comment by heijberg** [comment]
> I’ve got the same issues... plugin worked for 5 seconds, than Homebridge crashed and I had to reinstall Homebridge completely.

I’ve got the same issues....over and over, anyone find a solution yet ??

**Comment by yepecece** [comment]
Same here. 
I had it disabled for a couple of months because of this and everything was working perfectly.

Then, I reactivated it to see if the new updates had fixed the problem. It was working fine for a couple of days, then all homebridge devices show "No response". This only happens when LG TV plugin is activated.

Thanks.

**Comment by merdok** [comment]
This issue has something to do with the way you setup your homebridge and environment, without any details on that there is no way for me to know what is causing this is in those rare cases.
