### ISSUE TITLE
TV homebridge buttons disappear after a while

### ISSUE THREAD

**Issue by thehauntedmattress** [merdok/homebridge-webos-tv#134]
After the release of iOS 12.2, I decided to switch to the new TV service so that they would work together.  After doing this, I had to re-add my HomeKit and Homebridge.  I did this and had everything working with this plug-in (including tv on/off, volume, and the new way to change inputs).  However, after a day or so, all of these buttons disappeared from HomeKit (but still exist in Homebridge config-ui-x).  I was wondering if I could get your help here.  Thanks.

**Comment by merdok** [comment]
Did you try to force close your home app or restart homebridge?

**Comment by thehauntedmattress** [comment]
Yes multiple times.  I have switched back to the old TV service for now.

**Comment by merdok** [comment]
I am pretty sure this is an issue with your Home app or homebridge. Most of the issues can be solved by force closing the Home app and sometimes also rebooting your iPhone. There is really nothing i can do about it.

**Comment by thehauntedmattress** [comment]
Hey @merdok , someone using [homebridge-samsung-tizen](https://github.com/tavicu/homebridge-samsung-tizen/issues/79) has the exact same issue as this.  I also ran into the issue using that plugin as I own both an LG WebOS TV and a Samsung Tizen TV.  So therefore, I have experienced the same exact issue using both plugins.  I have a feeling it has to do with adding inputs to the TV button itself.

**Comment by merdok** [comment]
If this is even happening on the other plugin then i guess that this is a homebridge issue.

**Comment by mfmgold** [comment]
hi @merdok I have exactly the same issue with the webos-tv plugin, I own and LGTV Webos 1.4

**Comment by merdok** [comment]
I did not experience any such issue on my setup so i do not think this is plugin related. I guess this is more related to the environment.
