### ISSUE TITLE
Loss of HomeKit TVs in Third Party Apps

### ISSUE THREAD

**Issue by 2nm** [merdok/homebridge-webos-tv#138]
Has anyone else lost the TVs from third party apps?  Using ‘Controller for HomeKit’ and ‘Eve’ apps.  Homebridge is there though other bridges aren’t.  And when using ‘Controller for HomeKit’ app I get a read out of Control Point ‘not supported’ and state 0 not sure if that is a read out of HomeKit official authentication or not or whether it is essentially now saying they can’t control homebridge devices??? Or if it is something else all together.

**Comment by merdok** [comment]
I would guess that 3rd party apps need an update to support the new TV devices introduced in iOS12.2

**Comment by 2nm** [comment]
I thought the same but the apps have been updated since iOS 12.2 they were there before but have now gone, so I’m guessing it must be something changing with Apple.  But maybe thought it might be a new set up or something?  I have also experience the inability to switch the TVs on since updating to 1.5.5 (like another thread).  Trying to implement 2 instances of homebridge but failing (with systemd, got any links or helpful tips? I’ve tried copying and editing the /etc and /var files to no avail.

**Comment by merdok** [comment]
Sorry, i have no idea about the 3rd party app issues, but i guess this has nothing to do with plugin. 

Could you post your homebridge log when you try to turn on the TV and it fails?

**Comment by 2nm** [comment]
@merdok just wondering did you change the read out on power status?

**Comment by merdok** [comment]
I did not change anything with power status since a long time...
