### ISSUE TITLE
Volume setting as speaker

### ISSUE THREAD

**Issue by misanthrophy** [merdok/homebridge-webos-tv#139]
Hi,
Thanks for the great plugin, it even works on webOS1, except for the turning off option, which is not supported. 

Any chance to change the type of volume for the Home App? So instead of exposing the volume as a lightbulb, show it as a speaker or even better directly integrated into the TV itself, same like the channels etc.

**Comment by merdok** [comment]
If you are on iOS12 you can use the TV Homekit integration, which allows you to control your TV's volume with the volume up and down buttons on your iPhone/iPad. You can also change te lightbulb to a switches like the channel switches. Just search for `volumeControl `here: https://github.com/merdok/homebridge-webos-tv#configuration-fields
