### ISSUE TITLE
iphone control center 

### ISSUE THREAD

**Issue by henkied** [merdok/homebridge-webos-tv#140]
Hello I'm searching but can't find it.
Is it possible to control the sound from the TV via the control center? I only see music and I don't get to see TV.

The sound from the TV goes through sonos playbar.
![IMG_1020](https://user-images.githubusercontent.com/20031014/56242313-4591f680-6098-11e9-8b6c-6c99dc270220.jpg)

**Comment by merdok** [comment]
When you open the remote app you can control the sound with the iPhone/iPad volume up and down buttons. As an alternative you can enable the volumeControl for the plugin, this will add buttons to your Home app to control the volume.

**Comment by henkied** [comment]
thx i know that but that is not the question, i wonder if it is possible to do that with the control center on the iphone

**Comment by merdok** [comment]
No, this is not possible.
