### ISSUE TITLE
Feature Request: TV Brightness

### ISSUE THREAD

**Issue by dalewright** [merdok/homebridge-webos-tv#141]
Hey Merdok

Last week we successfully added our TV to HomeKit and the family loves it. Thank you so much.

Question for you, would the WebOS API allow you to expose screen brightness? It would be great to be able to set the TV brightness to low for when we get up with the kids in the middle of the night. Our TV is great but it lights up the room :)

**Comment by merdok** [comment]
Hi,

Unfortunately, right now i am not aware of an possibility to change the TV brightness through the WebOS API. At least there is no official way to do it...

**Comment by dalewright** [comment]
Thank you sir.
