### ISSUE TITLE
[Feature Request] Option to have Source Inputs as both buttons and in the input pad when using the new TV service 

### ISSUE THREAD

**Issue by huongminh** [merdok/homebridge-webos-tv#143]
I came to a scenario of automation where I need the input sources (like HDMI1, HDMI2....and selected apps) as buttons to do the automation but I also want to use the new TV service so that my TV appears as a TV type in home kit. It would be great to have a config option like: " input source buttons": true then the input sources and apps are available as buttons as an extra to what the new TV service option already offers.

**Comment by merdok** [comment]
I have also already thought about that. There are definitely some scenarios where it could be useful like for automation as you say. But on the other side this would again just spam the home app with buttons and scrolling is required to find the right one.
Also i was hoping that in the final iOS12.2 Apple will enable automation based on inputs but that did not happen. 

I would like to hear what other people think about this. If enough people would like to see that feature then i guess i will add it.

**Comment by huongminh** [comment]
Thank you very much for your consideration. It is especially useful if you want to bring the buttons to Amazon Alexa via the homebridge alexa plugin. Currently I have to install 2 accessories for 1 TV to have the buttons. 1 with the new TV service and 1 with the old one. Obviously this way is not optimal. 


Sent from Yahoo Mail for iPhone


On Wednesday, April 24, 2019, 12:47 AM, Marcin <notifications@github.com> wrote:


I have also already thought about that. There are definitely some scenarios where it could be useful like for automation as you say. But on the other side this would again just spam the home app with buttons and scrolling is required to find the right one.
Also i was hoping that in the final iOS12.2 Apple will enable automation based on inputs but that did not happen.

I would like to hear what other people think about this. If enough people would like to see that feature then i guess i will add it.

**Comment by palasinio** [comment]
Hi, I vote for the ability to have both.

**Comment by merdok** [comment]
Added in 1.6.1 👍  Let me know if it works as expected.

**Comment by huongminh** [comment]
Yes. It works like a charm! Thank you for your update. Btw, it would be perfect for automation purpose if the picture modes like movie, game, sport ...can be selected as buttons so viewing effect can be optimized. 


Sent from Yahoo Mail for iPhone


On Wednesday, May 15, 2019, 5:27 AM, Marcin <notifications@github.com> wrote:


Added in 1.6.1 👍 Let me know if it works as expected.

**Comment by palasinio** [comment]
I confirm that it’s working, too.
