### ISSUE TITLE
Channel button stuck ON prevents TV turn on

### ISSUE THREAD

**Issue by pteasima** [merdok/homebridge-webos-tv#145]
Love the work!

Following scenario breaks the remote control:
- tv is ON
- "Hey Siri, turn on channel 1" (using "channelButtons")
- "Hey Siri, turn off the tv"
- "Hey Siri, turn on the tv" / "Hey Siri, turn on channel 1" / "Hey Siri, turn on channel 2". At this point its stuck and all Siri / Home app commands error out. Also, Home app on iOS shows channel 1 switch as still ON (and cant turn it off). Manually turning on the TV using the LG remote fixes things.

Following scenario works just fine:
 - tv is ON
- "Hey Siri, turn on channel 1" (using "channelButtons")
- "Hey Siri, channel up". The point is that channel up command **sets the "channel 1 switch" to OFF, which prevents it from getting stuck** if I turn off the tv in the next step.
- "Hey Siri, turn off the tv"
- "Hey Siri, turn on the tv" / "Hey Siri, turn on channel 1" / "Hey Siri, turn on channel 2"

Anything I can do to help solve this? Im not too comfortable in javascript but im open to trying.

**Comment by pteasima** [comment]
Its not 100% reproducable, just happens most of the time. I had a brief period where the first scenario also worked as expected.

I tried changing the polling interval to 1 second but I can still break it.

**Comment by merdok** [comment]
Can you try that in debug mode and see if there si something in the console?

**Comment by pteasima** [comment]
sorry man I dont have my Pi right now. Ill let you know if I ever get back to this.

**Comment by merdok** [comment]
Closed this due to inactivity. Like you said, if you ever get back to this then post it here ;)
