### ISSUE TITLE
Using this plugin leads to all my homebridge devices being blocked

### ISSUE THREAD

**Issue by jamesmulcahy** [merdok/homebridge-webos-tv#146]
When I install and configure this plugin, all accessories on my homebridge end up being blacklisted by HomeKit, and I have to delete everything and re-configure from scratch.

I've narrowed this problem down to this plugin by setting up a separate homebridge, and gradually adding/removing plugins to narrow it down, and I'm 100% certain that it's down to this plugin.

Is anyone else seeing this issue?  There's nothing interesting in the logs, even when running in debug mode.

**Comment by UnixAkenator** [comment]
I think that i have the same issue ... what should i do ?

**Comment by merdok** [comment]
I do not think that the issue is related to this plugin... I would guess that this is an outdated/wrong dependency or maybe conflict?

**Comment by jamesmulcahy** [comment]
I'm not sure what you mean by outdated dependency?  I'm building a clean image to validate this, so the dependencies being pulled are whatever is specified by this plugin.  What sort of conflict are you thinking -- happy to share some versions/npm lock files if that helps gather data here.

**Comment by merdok** [comment]
There is nothing really i can do about it since this issue is related to your environment. This can have multiply causes and outdated (or too new) dependencies can be just one of them.

**Comment by yepecece** [comment]
Hi, I have the same problem. All works fine foe a couple of days and then everything becomes unresponsive. I have to change Mac address and re-add in order to regain functionality.

Thanks
