### ISSUE TITLE
Can you add/find the settings button so it can be added to the list of buttons available?

### ISSUE THREAD

**Issue by AlexPygin** [merdok/homebridge-webos-tv#148]
If there's anything I can do to help find the enum value for settings I'd be more than willing to help figure it out. I need some way to turn on and off Eye Comfort Mode on my tv and that requires going through the remote's settings button

**Comment by merdok** [comment]
You will need to randomly try out some values for the `remoteControlButtons ` property. Also you could sniff packets send from the LG remote control app if it is available there.

**Comment by AlexPygin** [comment]
Welp, modified my local config.schema.json and realized that "MENU" works for what I need, and you already had it in the config. Sorry for the bother
