### ISSUE TITLE
[Enhancement] CHANGELOG.md

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-webos-tv#149]
@merdok Thanks for your great work and sharing with us. Wouldn't want to miss your plugin. 👍🏻
Any chance to have a CHANGELOG.md in the future to have a easy way to find what has changed. Bonus, looks great when updating with config-ui-x by @oznu

Thanks again.

**Comment by merdok** [comment]
I usually try to name my commits so it is clear what has changed, but maybe dedicated changelog file would be indeed better.

**Comment by DJay-X** [comment]
I got feedback from onzu 
https://github.com/oznu/homebridge-config-ui-x/issues/51#issuecomment-492660224
