### ISSUE TITLE
Buttons in Apple Home App but not in Eve App anymore?

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-webos-tv#150]
I hope not to bother, but I'm stuck.
I updated to lates plugin version v1.6.1 and I noticed that I can't see any webTV buttons in the Eve App anymore. When I switch to Apple Home App they are available, also Siri and automations work as expected. Just not seeing them in my primary used Eve App. 
Am I doing something wrong with the config, or has something changed?
Obviously I can't see the wood for the trees. 
Thanks for any help.

```
        {
            "accessory": "webostv",
            "name": "LG webOS TV",
            "ip": "xxx.xxx.xxx.xx",
            "mac": "xx:xx:xx:xx:xx:xx",
            "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
            "volumeControl": "slider",
            "mediaControl": true,
            "showInputButtons": true,
            "pollingInterval": 10,
            "inputs": [
                {
                    "appId": "maxdome",
                    "name": "Maxdome"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Hauptbildschirm"
                }
            ],
            "notificationButtons": [
                "Backofen vorgeheizt.",
                "Wasserkocher fertig.",
                "Haustür klingelt.",
                "Luftqualität in der Wohnung schlecht. Bitte lüften.",
                "Temparatur im Schlafzimmer ≥24°C. Klimaanlage einschalten?"
            ]
        },
```

**Comment by DJay-X** [comment]
Adding `"legacyTvService": true,` fixed it. I was not aware that the buttons show up in Home App but not in Eve App, when legacyTvService is false. 
Anyway, works for me now.

**Comment by merdok** [comment]
As of version 1.6.1 the tv service from iOS12.2 is default. If you want to use the old service where the TV was emulated as a switch you have to use the `"legacyTvService": true` property.
