### ISSUE TITLE
Using new Homekit TV with iOS 10 on one device causes no response

### ISSUE THREAD

**Issue by lockyt** [merdok/homebridge-webos-tv#151]
Hi merdok - can I just start with saying this is an awesome homebridge plugin and an integral part of the home automation.  Thanks for all the hard work.

I seem to have come across a problem and I don't think it's something you can do about but thought I'd check for your thoughts on it.

I have an LG OLED using homebridge and and a variety of apple devices controlling including iPhones, iPads, HomePod etc.  They are all using iOS 12.2 except for an old iPad that I have in the wall that I run all my home automation off (using Home Assistant). 

I recently decided to upgrade the settings in homebridge-webostv to use the new TV service instead of the older legacy method of buttons and I immediately found it would work for about 30 seconds but would then show a 'no response' for all my homebridge icons in HomeKit (on the iOS 12.2 devices).  I tried running debug but it would not give any hints.  In fact, the TV and nest etc would keep reporting to homebridge console but HomeKit would say no response.  So it seemed it was a homebridge -> HomeKit communication issue of some kind.

After trying a heap of things, I had a theory that maybe the old iPad using iOS 10 was causing the problem as it would come up in it's HomeKit but would say 'unsupported'.  So I turned off the iPad, removed persist, re-added the accessory etc (like I have been doing each time trying to fix it) and voila it worked!   Although the iPad was set as 'disabled' as a HomeKit hub, it seems having the iOS device connected with a component that needs iOS 12.2 causes the whole lot to stop working, even when I have a heap of other iOS 12.2 devices running, including the primary hub (HomePod).

Now unfortunately I don't have another iPad to replace this old one and it works fine for everything else.  I don't even need the TV to come up on it, just as long as I can use my homepod or Apple Watch to voice control it.  However I do need the iPad in the wall for other reasons.

I am suspecting this is a HomeKit thing but thought I would ask for your help in case it was something you might be able to control.  In the meantime I think I'll have to go back to the legacy control although I did like the remote capability in the control centre on my phone.

Thanks.

Lachlan.

**Comment by merdok** [comment]
Hi,
i do not think that there is something i can do about it. It would be difficult for me to reproduce the issue since all my device are on iOS12.2+. Maybe the iOS10 device cannot really work with the new TV devices introduces in iOS12.2 and because of that you have the issues.

**Comment by borewicz9** [comment]
There's the same problem in iOS 12.4.4 iPhone 5s - device not response

**Comment by merdok** [comment]
device not response has usually something to do with homebridge itself and not this plugin.

**Comment by borewicz9** [comment]
I'm just using this plugin, but i could be Homebridge (HOOBS) fault too.
There's quite new Note js 12.14.1...
