### ISSUE TITLE
Inputs are active only when TV is on

### ISSUE THREAD

**Issue by GalBrill** [merdok/homebridge-webos-tv#152]
I have multiple LG tv setup, when a TV is off - I have no inputs when force touch, when I'm watching something - I have the indication on source and I can force touch and use inputs.

Any idea what can be wrong?

**Comment by merdok** [comment]
Sorry, i do not understand what the issue is...

**Comment by GalBrill** [comment]
Maybe the screenshots will clarify 

When a tv is off - no 'input' 
![IMG_1276](https://user-images.githubusercontent.com/48237471/58759417-28bf5e80-8532-11e9-8dd3-3163c247ad1a.png)

When a tv is on - the 'input' is back
![IMG_1277](https://user-images.githubusercontent.com/48237471/58759430-6cb26380-8532-11e9-94b8-23dcd2bbced2.png)


Hope that helps...

**Comment by merdok** [comment]
This is not a bug, this is how Apple designed it.
