### ISSUE TITLE
My TV controls shows as regular switches

### ISSUE THREAD

**Issue by alc7328** [merdok/homebridge-webos-tv#153]
Hi. First: thanks for this plugin and all the work you made.
I can see the controls and use them but not as part of a "TV" type accesory, thay are all regular sitches. 
Is it possible to have a TV homekit type? How? 
Thanks!
![Screen Shot 2019-05-30 at 12 44 47](https://user-images.githubusercontent.com/12431644/58644949-be5fb180-82d8-11e9-8411-63e401b0a984.png)

**Comment by merdok** [comment]
You have to set the `legacyTvService ` property to false or completely remove it from your config.

**Comment by alc7328** [comment]
I did not have it and also tried adding it and setting it to false. My iOS version is the latest (12.3.1). What could it be?

**Comment by merdok** [comment]
Do you have the latest update installed?
