### ISSUE TITLE
TV not responding when it's turned Off

### ISSUE THREAD

**Issue by alc7328** [merdok/homebridge-webos-tv#154]
Im using this plugin for the first time and I can't get it working really well: when my TV (LG 49UJ6560) is On, I can control it from HomeKit but when I turn it Off, it does not work anymore (no error from HomeKit tough).
I tought it could be the WiFi turning off, but with ethernet cable is the same.
Any comments? What I'm doing wrong? Thanks

**Comment by merdok** [comment]
Please read the configuration section: [Configuration](https://github.com/merdok/homebridge-webos-tv#configuration)

You need to enable **mobile TV on** on your TV and also **LG Connect Apps**

**Comment by alc7328** [comment]
Hi. Thanks for your answer, but I'd read the Configuration before asking you (and setting it up it). I have both options enabled: "Mobile TV On" and "LG Connect Apps". 

![IMG_2064](https://user-images.githubusercontent.com/12431644/58754309-70e37000-84a3-11e9-82e8-40963acb1d0c.jpeg)
![IMG_2065](https://user-images.githubusercontent.com/12431644/58754310-70e37000-84a3-11e9-85d8-f0ddaaed29bb.jpeg)

**Comment by merdok** [comment]
Then i guess this must be some kind of network issue with your environment.

**Comment by alc7328** [comment]
I'm bothering you asking here? Do you prefer me to write an email or some other channel? 
Network issue? Mmm, I don't think so because it turns on, everything works well except Power On. I think it is related with the TV and/or plugin.

**Comment by merdok** [comment]
This is not really an issue with the plugin. The issue is here how you did setup your environment. I cannot really help you with that since i do not know how your setup looks. You would need to investigate this by yourself and let me know what was the issue when you find.

**Comment by omriileviii** [comment]
I have same problem

**Comment by merdok** [comment]
@omriileviii you most probably have a similar environment where you run homebridge as @alc7328
