### ISSUE TITLE
Feature request: Info button in TV mode mapped to home?

### ISSUE THREAD

**Issue by torandreroland** [merdok/homebridge-webos-tv#156]
The info button in TV mode is correctly mapped to INFO of the TV.

Can you make a configuration possibility to map this button to HOME instead as this would be much more useful? At least on my TV model (OLED65B7V).

This would pretty much enable to control the whole of the TV using the remote control available from the control center in iOS.

**Comment by merdok** [comment]
This would be certainly possible. I will have a look at it when i have some spare time.

**Comment by torandreroland** [comment]
Cool and and thanks for the quick reply.

I changed from INFO to HOME in the code for testing and personal use and it works, but I haven’t made it configurable.

I think others will find it useful as well if available.

Thank you for a very nice plugin by the way :-)

**Comment by Catta1997** [comment]
I used the same structure as Play/Pause and it's perfect! the Info button may be useful

**Comment by stanislawbejm** [comment]
Please add this as a future I can send You some money as a donation! Just leave Your PayPal account name

**Comment by merdok** [comment]
Sorry i was long time on holiday, will add this feature sometimes soon.

**Comment by stanislawbejm** [comment]
Merdok leave Your PayPal account name. I want to do some donation to You

**Comment by merdok** [comment]
@stanislawbejm i wrote it to you on twitter. Thanks!

**Comment by merdok** [comment]
This feature is now available in the latest 1.6.2 release.

**Comment by torandreroland** [comment]
Cool! Thank you very much for your good work :-)
