### ISSUE TITLE
Turn on tv after restart

### ISSUE THREAD

**Issue by omriileviii** [merdok/homebridge-webos-tv#157]
Hi
First thank a lot that amazing plug!
all was work fine but I moved Homebridge from Mac to Raspberry.
and I also replace my router.
now If I try turn on tv that's didn't work.
I turn MobileTv On.
if tv is On all work but I only can't turn on tv.

	"accessories": [
    {
      "accessory": "webostv",
      "name": "TV",
      "ip": "XX.XXX.XX.XX",
      "mac": "XX:XX:XX:XX:XX:XX",
      "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
      "pollingInterval": 10,
      "inputs": [
          {
            "appId": "com.webos.app.hdmi2",
            "name": "AppleTV"
          },
          {
            "appId": "com.webos.app.hdmi1",
            "name": "PS4"
          }

          ],
          "showInputButtons": true,
          "volumeControl": "slider",
          "channelControl": false,
          "mediaControl": false,
          "volumeLimit": 100,

           "remoteSequenceButtons": [

          ]
        }
      ],

**Comment by Catta1997** [comment]
try to install https://www.npmjs.com/package/wake_on_lan. I have RaspberryPi and WebOS tv and in work for me

**Comment by merdok** [comment]
@omriileviii could be that your homebridge is on a different network then your TV, in that case you should try the `broadcastAdr` property.

**Comment by omriileviii** [comment]
@merdok what you mean ״broadcastadr”
That the same network .

**Comment by merdok** [comment]
You should read the README. I do not know your environment where you running homebridge in, so i can basically just guess. `broadcastAdr ` could be one of the issues but in order to be sure you need to investigate this by yourself.

**Comment by omriileviii** [comment]
its the same network host, Homebridge run on 10.100.102.XX and the Tv 10.100.102.XX.

**Comment by Catta1997** [comment]
@omriileviii have you tried to install https://www.npmjs.com/package/wake_on_lan?

**Comment by merdok** [comment]
@omriileviii Then you need to investigate this by yourself and let me know what the issue was when you find it. Maybe try @Catta1997 suggestion.

**Comment by omriileviii** [comment]
@Catta1997 @merdok yeah I try and I get this message:
options {"address":"10.100.102.17"} 
done sending WoL packets

and Tv still off.

**Comment by Catta1997** [comment]
@omriileviii, so try: 1) check if the option to turn on on the network is on on your tv. 2) wol with an app on your mobile phone to see if it’s a problem of the raspberry or the of the router
