### ISSUE TITLE
The way to use ip address based on mac

### ISSUE THREAD

**Issue by Rjayone** [merdok/homebridge-webos-tv#159]
Hi @merdok, i tried to inject the module, which scan the local network and check the ip address of the tv at current moment by the mac address. This approach more flexible to check ip and the start connection. But i really don't understand where i should to past this code.
I used module 'local-devices'. and the following code:
`function findDevice(mac, completion) {
	localDevices().then(devices => { devices 
        devices.forEach(function(item) {
            if (item.mac == mac) {
                console.log('tv ip ' + item.ip)
                completion(item.ip)
            }
        })
    })
}
`
Hope you will can to do this :)

**Comment by merdok** [comment]
I do not think that this is a good idea to include that. I mean if someone can find the ip address then he/she can also find the mac address very quickly. The scanning would just unnecessary complicate the plugin and could lead to potential bugs.

**Comment by Rjayone** [comment]
I think it is a good option to decide what the way do you prefer: provide your ip address and mac in the config, or just mac :)
Ok, maybe you can advice to me, where i should call this method, to receive the tv ip by the mac, and only after that start homebdridge configuration?

**Comment by merdok** [comment]
It is written in your router at the same place where you found the TV mac address.

**Comment by Rjayone** [comment]
Not really, i faced with the issue, when the TV starts to use different ip address in local network. Reserving ip address for the specific mac unfortunately not working for me :(
Therefore i start to investigate the possibility to bind ip and mac in runtime

**Comment by merdok** [comment]
If you cannot reserve an ip address for the the tv then this is clearly an issue without router/network.

**Comment by Rjayone** [comment]
Sure, but i offer to make the workaround to resolve this issue. Someone who will use your library will decide the way to bind a tv by mac or ip.
By the way, it will be very helpful if you could explain where i can use async method 'local-deivces' and only after that continue accessory configuration?

**Comment by merdok** [comment]
Sorry, i do not know what you mean by `async method 'local-deivces'`
