### ISSUE TITLE
iOS 13 Question

### ISSUE THREAD

**Issue by marcodesantis71** [merdok/homebridge-webos-tv#160]
Hi All,

I've installed iOS 13 Beta 1 and now the plugins does not work.

I know it's normal.

But any news about compatibility with the new iOS version?

**Comment by merdok** [comment]
Sorry, i do not have iOS13 Beta. What does not work?

**Comment by mcnahum** [comment]
and for me it's ok .. the look and feel change ... but it's working.
Probably new things to do with it

**Comment by marcodesantis71** [comment]
Hello,
I have 2 problems.
First: with the new user interface for Home App on iOS 13, the name of the buttons is not displayed, so I don't know which channel to change.
Second: when I press a channel, the button remains in the ON state. When I press another channel, both buttons remain in the ON state.
![IMG_2659](https://user-images.githubusercontent.com/23100741/59254078-cb14cb80-8c2f-11e9-8fa2-76798af9b287.png)
![IMG_2660](https://user-images.githubusercontent.com/23100741/59254079-cb14cb80-8c2f-11e9-9324-e0c596c6432d.png)
![IMG_2661](https://user-images.githubusercontent.com/23100741/59254080-cb14cb80-8c2f-11e9-886a-ab55e7087c68.png)

**Comment by merdok** [comment]
Well, the user interface i cannot change. If the names are missing of the switches then i hope that those are bugs in the iOS13 Beta and hopefully they get fixed.

**Comment by ukypayne** [comment]
Follow up. I have the same issues on beta 2. I was trying to find some documentation for how TV Services should be written to work “as designed” for iOS 13. Ill follow back here with any info if I find some. The new layout for iOS 13 looks very promising and means I don’t have to have a “room” dedicated for 20 buttons that all control the same device.

**Comment by merdok** [comment]
@ukypayne Thanks for the update.

**Comment by netRunner0** [comment]
Beta 3 - without changes

**Comment by perrintong325** [comment]
I think currently the only workaround is to go into settings of it to toggle the switches with names on it

**Comment by ukypayne** [comment]
Beta 5 added small names below each switch. I don’t think the switch types could be changed yet.

**Comment by perrintong325** [comment]
Tbh I quite like how in ios13 everything is grouped together instead of individual switches, it just makes it cleaner

**Comment by merdok** [comment]
@ukypayne could you post a screenshot how it looks on beta 5?

**Comment by ukypayne** [comment]
![IMG_0359](https://user-images.githubusercontent.com/8541706/62415177-94d24780-b5f3-11e9-8353-b788c31b3734.PNG)
![IMG_0360](https://user-images.githubusercontent.com/8541706/62415180-9734a180-b5f3-11e9-977f-f77230b3df38.PNG)
![IMG_0361](https://user-images.githubusercontent.com/8541706/62415181-9996fb80-b5f3-11e9-950b-3ee65643716b.PNG)
![IMG_0362](https://user-images.githubusercontent.com/8541706/62415184-9b60bf00-b5f3-11e9-83b6-ac8790d08471.PNG)
![IMG_0363](https://user-images.githubusercontent.com/8541706/62415185-9d2a8280-b5f3-11e9-84fa-f705c5d7439f.PNG)

**Comment by merdok** [comment]
@ukypayne thanks, Looks nice.

**Comment by Gejza75** [comment]
Anything new regarding iOS13 compatibility?

**Comment by merdok** [comment]
Running on iOS13 and everything seems to work.

**Comment by Gejza75** [comment]
Thanks for the info merdok!

**Comment by juancpin** [comment]
Hi! Since ios13, plugins are working correctly, Home App is ok, but no TV is to be found in Control Center Remote. iPad, not yet working with iPadOS, is ok with Control Center.

Regards.

**Comment by merdok** [comment]
@juancpin For me on iOS13 i can control the TV with the Control Center remote without issues.

**Comment by juancpin** [comment]
Thanks, @merdok!! Which device do you use? I own an iPhone SE, previously I could use CC remote, but not now. 

I will reboot it to check twice. 

Regards!

**Comment by merdok** [comment]
iPhone X and iPad 6th gen.

**Comment by juancpin** [comment]
Just as I imagined, a reboot solved this issue. Control Center now sees it normally.

Thanks anyway!

**Comment by netRunner0** [comment]
@merdok 

We want the TV itself to be displayed as a separate service and not be in the same folder with the other buttons in ios 13

**Comment by netRunner0** [comment]
All switches must be made separate, not affiliated services
