### ISSUE TITLE
Television turns on by itself when input is Apple TV

### ISSUE THREAD

**Issue by wilkinsm89** [merdok/homebridge-webos-tv#162]
While using this plugin, if the television is turned off with the last input left as the Apple TV the television can turn itself on at seemingly random times. I have CEC enabled for the Apple TV source. 

It does not happen if I turn off this plugin or if any other source if left selected. 

Has anyone else experienced this?

**Comment by merdok** [comment]
I do not have an Apple TV so i cannot test this but i do not really see a reason why the plugin should cause this. When the TV turn on then it is most probably due to the CEC signal sent from the Apple TV.

**Comment by VrtlBrown** [comment]
This used to happen to me and i haven't installed the plug-in yet. updating the apple tv and fiddling with the TV's power settings seems to have made it better.

**Comment by afinucane** [comment]
There have been issues with CEC on LG's version of WebOS. Updating the firmware on the TV seems to have fixed most issues I was seeing. I was having these long before I started using Homebridge.
