### ISSUE TITLE
Plugins don't work in ioBroker Homebridge accessories manager

### ISSUE THREAD

**Issue by Anzic23** [merdok/homebridge-webos-tv#163]
the plugin does not work with [ham](https://github.com/ioBroker/ioBroker.ham#iobroker-homebridge-accessories-manager). Created  [issue](https://github.com/ioBroker/ioBroker.ham/issues/33), but the author of ham writes, that the problem in homebridge-webos-tv plugin. Can you check the information?
[log.txt](https://github.com/merdok/homebridge-webos-tv/files/3361642/log.txt)
[config.txt](https://github.com/merdok/homebridge-webos-tv/files/3361646/config.txt)

**Comment by merdok** [comment]
The method `findDevices() `is not present in my plugin, you are using a fork of my plugin or you modified it by yourself.
