### ISSUE TITLE
Control Center Rempte

### ISSUE THREAD

**Issue by perrintong325** [merdok/homebridge-webos-tv#165]
Hi,

I'm quite new to this so I please forgive if it sounds dumb, currently I have configured 3 LG TVs and they're working fine, however in the control centre remote, it can only control one of the TV. Can someone please help with this issue? Here's my config:
    {
      "accessory": "webostv",
      "name": "TV Room TV",
      "ip": "192.168.188.122",
      "mac": "xxx",
      "keyFile": "xxx\\lgtvKeyFile",
      "pollingInterval": 10,
      "inputs": [
        {
          "appId": "com.webos.app.livetv",
          "name": "Live TV"
        },
        {
          "appId": "com.webos.app.miracast",
          "name": "Screen Share"
        },
        {
          "appId": "com.webos.app.hdmi3",
          "name": "Onkyo HT-R695"
        },
        {
          "appId": "netflix",
          "name": "Netflix"
        },
        {
          "appId": "youtube.leanback.v4",
          "name": "YouTube"
        },
        {
          "appId": "com.webos.app.browser",
          "name": "Browser"
        }
      ],
      "showInputButtons": true,
      "volumeControl": "slider",
      "channelControl": false,
      "mediaControl": false,
      "channelButtons": [ 31, 32, 81, 82, 83, 84, 85, 96, 99 ],
      "soundOutputButtons": [
        "tv_speaker",
        "external_optical",
        "tv_external_speaker"
      ]
    },
    {
      "accessory": "webostv",
      "name": "Living Room TV",
      "ip": "192.168.188.138",
      "mac": "xxx",
      "keyFile": "xxx\\lgtvKeyFile1",
      "pollingInterval": 10,
      "inputs": [
        {
          "appId": "com.webos.app.livetv",
          "name": "Live TV"
        },
        {
          "appId": "com.webos.app.miracast",
          "name": "Screen Share"
        },
        {
          "appId": "com.webos.app.hdmi2",
          "name": "Sony BluRay Player"
        },
        {
          "appId": "netflix",
          "name": "Netflix"
        },
        {
          "appId": "youtube.leanback.v4",
          "name": "YouTube"
        },
        {
          "appId": "com.webos.app.browser",
          "name": "Browser"
        }
      ],
      "showInputButtons": true,
      "volumeControl": "slider",
      "channelControl": false,
      "mediaControl": false,
      "channelButtons": [ 31, 32, 81, 82, 83, 84, 85, 96, 99 ],
      "remoteControlButtons": [
        "UP",
        "DOWN",
        "LEFT",
        "RIGHT",
        "ENTER",
        "BACK",
        "HOME",
        "EXIT",
        "MENU"
      ]
    },
    {
      "accessory": "webostv",
      "name": "Dining Room TV",
      "ip": "192.168.188.134",
      "mac": "xxx",
      "keyFile": "xxx\\lgtvKeyFile2",
      "pollingInterval": 10,
      "inputs": [
        {
          "appId": "com.webos.app.livetv",
          "name": "Live TV"
        },
        {
          "appId": "com.webos.app.miracast",
          "name": "Screen Share"
        },
        {
          "appId": "netflix",
          "name": "Netflix"
        },
        {
          "appId": "youtube.leanback.v4",
          "name": "YouTube"
        },
        {
          "appId": "com.webos.app.browser",
          "name": "Browser"
        }
      ],
      "showInputButtons": true,
      "volumeControl": "slider",
      "channelControl": false,
      "mediaControl": true,
      "channelButtons": [ 31, 32, 81, 82, 83, 84, 85, 96, 99 ],
      "remoteControlButtons": [
        "UP",
        "DOWN",
        "LEFT",
        "RIGHT",
        "ENTER",
        "BACK",
        "HOME",
        "EXIT",
        "MENU"
      ]
    }
![IMG_0438](https://user-images.githubusercontent.com/44073041/61047565-61483700-a412-11e9-820e-9d90ab6dbfcd.PNG)
![IMG_0439](https://user-images.githubusercontent.com/44073041/61047569-6311fa80-a412-11e9-875c-0434193b68ad.PNG)
![IMG_0440](https://user-images.githubusercontent.com/44073041/61047572-65745480-a412-11e9-8251-b53d635f1699.PNG)
![IMG_0441](https://user-images.githubusercontent.com/44073041/61047575-673e1800-a412-11e9-8667-6ed696593e03.PNG)

**Comment by Hatika78** [comment]
For more information about your problem you can take a look to this issue already open:
https://github.com/merdok/homebridge-webos-tv/issues/121
 But the solution is to have one instance of homebridge per TV. But I've read that the dev of  of the plugin will try to work on a new version but doesn't have time now.

**Comment by merdok** [comment]
Well, apparently there can only be one TV controlled through the Control Center Remote. I am still not really sure if this is a homebridge or iOS issue. Anyway, yes i have it on my scope to have a look at it but since i only have one TV at home. it does not really make easy for me...

**Comment by WestCoast5550** [comment]
@merdok do you need a help with contribution?
I have two LG TV, and I know JavaScript:)

**Comment by merdok** [comment]
@WestCoast5550 If you have the time and want to contribute then you can do it :)

**Comment by vahov** [comment]
It is true that you can have only one TV per one instance of Homebridge. Just create the second instance of Homebridge (homebridge2), put the other TV to config.json there and they both appear in Remote. You can create mulptiple instances of Homebridge, look the web for instructions.
