### ISSUE TITLE
Volume slider not working on external speaker (connect thru HDMI ARC)

### ISSUE THREAD

**Issue by joseeduardoperes** [merdok/homebridge-webos-tv#166]
I have a home theater (external speaker connect thru HDMI ARC) connected to my webostv, the volume slider doesn't work when the external speaker is selected, otherwise the volume buttons work normal with external speaker. Is there a fix for this?

_Originally posted by @joseeduardoperes in https://github.com/merdok/homebridge-webos-tv/issues/90#issuecomment-513465566_

**Comment by merdok** [comment]
Hi,

unfortunately there is no fix for that. As far as i know it is not possible to control external volume with the slider. The volume buttons (up and down) were introduced to able to control external volume level so maybe you should try that?
