### ISSUE TITLE
LG B8 confirmation to allow access 

### ISSUE THREAD

**Issue by nicktodorov** [merdok/homebridge-webos-tv#168]
Hello,
I have installed homebridge, added and configured my tv. It is working, but I have this issue that on every initial interaction with it after power cycle (i.e. after electricity being down), on the TV appears confirmation to allow remote access. Once confirmed with physical tv remote, it is not appearing until next power cycle.
Today I got in the situation where I am not at home, I opened Home app and noticed electricity was somewhere during the night. I switched TV on with the idea to check if homebridge is still running on the Mac after reboot. Now I am not able to shut the TV off or do anything with it as that confirmation appeared on the screen (I can see it with my Circle camera). The other problem is that the volume is a bit high and I cannot lower it also...
So I am not in home, TV is on and loud and I cannot do anything until someone confirms with the physical remote :(
Is there a way to permanently allow this and avoid that message?

**Comment by perrintong325** [comment]
Hi,
I’m no expert on this or home ridge but it sounds like to me that you’re having an issue with the keyfile, try specifying a specific location in your config file as I don’t think the default address in the example works on mac, it should only work on raspberry pi or linux systems, but again I’m no expert in this but to me it really seems like it lacks the keyfile hence the prompt on each startup.
Hope this helps!

**Comment by merdok** [comment]
like @perrintong325  said, this is an issue with your keyfile. Most probably the location which you specified has no write rights.
