### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by MiranoV** [merdok/homebridge-webos-tv#170]
Good day,

i ahve an LG tv connected to a Receiver which is connected to my speakers, on my LG remote i can control the audio of the receiver through my normal audio controls, when trying to change control (using slider light bulb) this doesn't do anything and doesnt change thr audio of my receiver

Is this possible?

Config:

    "accessories": [
        {
            "name": "My webOS tv",
            "ip": "192.168.2.4",
            "mac": "aa:aa:aa:aa:aa",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 10,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "PS4"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "KPN Itv"
                },
                {
                    "appId": "cdp-30",
                    "name": "Plex"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "videoland2014",
                    "name": "Videoland"
                },
                {
                    "appId": "rtl",
                    "name": "RTLXL"
                },
                {
                    "appId": "spotify-beehive",
                    "name": "Spotify"
                }
            ],
            "infoButtonAction": "HOME",
            "accessory": "webostv"
        },

**Comment by merdok** [comment]
Unfortunately it is not possible to control the volume of external audio devices using the slider, you need to use the Volume Up/Volume Down buttons for that. 
Try with that property:

`"volumeControl": "buttons"`
