### ISSUE TITLE
Brightness configuration 

### ISSUE THREAD

**Issue by ayr-ton** [merdok/homebridge-webos-tv#172]
I'm emulating controller buttons for controlling brightness and energy-saving options for day and night, however, not always work as expected.

Do you folks know about any support for brightness options or if there any API calls for this on the webOS so I could try to work in a PR?

Thanks for your time brainstorming this.

**Comment by merdok** [comment]
Unfortunately there is no public API to control the brightness of the TV, at least i do not know about such.

**Comment by ayr-ton** [comment]
Okay 😢

**Comment by merdok** [comment]
I suspect that there might be a private API to do that (and many other things) but for that reason someone would need to jailbreak their TV and dig in the files there. There is jailbreak for webOS TVs 3.5 and lower.

**Comment by ayr-ton** [comment]
@merdok Do you have instructions for jailbreak?

**Comment by merdok** [comment]
https://forum.xda-developers.com/web-os/general/getmein-one-time-rooting-jailbreaking-t3887904
