### ISSUE TITLE
Recommendation for 13.1?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [merdok/homebridge-webos-tv#175]
Now that 13.1 is out I really dislike what it did to your plugin where it gathered 26 buttons for me under one button. My GF is refusing to use it at all. Any way you could circumvent that with code? I know it's not at all related to your plugin but maybe there is a workaround.

**Comment by merdok** [comment]
I am not sure what is that bad about it? 
I personally like it how iOS13 does the grouping since my rooms are now clean and not flooded with switches. But i guess Apple should at least provide some way of customizing this...

**Comment by PrzemyslawKlys** [comment]
![Image](https://i.imgur.com/Wl2HoLK.jpg) Well in my case 26 buttons for one TV is a bit too much grouping.

**Comment by merdok** [comment]
Well this is how Apple designed it...
Anyway, the only improvement i think that would be good is instead of putting all of them in one group it would be better to create multiple groups for specific categories like channel buttons, app/input buttons, remote control buttons. But for that i first would have to check if and how this is even possible.

**Comment by DKCroCo** [comment]
I'am not a fan of the grouping either. I really hope you can find a workaround. Or at least a way to sort how the buttons appear in the group.

**Comment by merdok** [comment]
We will have to see if homebridge provides such functionality. I am not sure if there is a way to sort it. I mean this is how Apple designed it, maybe they will change it if enough people will complain about it...

**Comment by mcnahum** [comment]
my solution there is to use shortcut, there you can use individual entries...

**Comment by PrzemyslawKlys** [comment]
https://www.reddit.com/r/HomeKit/comments/dceaqd/it_worked_apple_finally_listened_to_us_and/?utm_source=share&utm_medium=ios_app&utm_name=iossmf seems in 13.2 its going to be fixed.

**Comment by merdok** [comment]
Perfect 👍

**Comment by PrzemyslawKlys** [comment]
Just FYI - the Sony Homebridge wasn't affected when the change kicked in. It seems they are using it differently to you. I still have HDMI and sound on separate tiles on 13.1. Not that it matters, but maybe something to give you ideas.

**Comment by merdok** [comment]
Their implementation is not really correct, since the switches from them are not part of one single TV service.

**Comment by PrzemyslawKlys** [comment]
Right :-) Still delivers what we needed before 13.2 is released. It would be cool if apple let us treat homekit with folders.
