### ISSUE TITLE
What can be done for more stable response?

### ISSUE THREAD

**Issue by Olepir** [merdok/homebridge-webos-tv#176]
Turning TV On in Home.app not always working or not displaying correctly – TV can be on, but in Home.app it Off and vice versa. Also volume control latency is long.
What can be done for more stable response (except LAN connection)?

**Comment by merdok** [comment]
Might be that some other plugins are slowing down you Home app.

**Comment by Olepir** [comment]
> Might be that some other plugins are slowing down you Home app.

For example? Thanks

**Comment by merdok** [comment]
I have no idea what plugins you have installed :p You need to investigate this by yourself by removing plugins and seeing what is causing the slow down...

**Comment by rooi** [comment]
From my experience, you can get a significant decrease in latency when running multiple instances of homebridge. You can get a guide on hoe to do this here: https://github.com/jvmahon/homebridge-homeseer/wiki/Running-Multiple-Instances-of-HomeBridge
I’ve configured my setup such that there’s one instance for each plugin. This makes trouble shooting a whole lot easier as well

**Comment by Olepir** [comment]
> I have no idea what plugins you have installed :p You need to investigate this by yourself by removing plugins and seeing what is causing the slow down...

Everything was fine with same plugins, I don’t have much – webos, deconz, cmd2, cameras and config ui x.
Apparently a house owner replaced a router recently and after that issues appeared.
Any advices for troubleshooting wifi connections?

**Comment by Olepir** [comment]
Also noticed "[LG TV] webOS - Error: connect EHOSTUNREACH 192.168.1.76:3000” in ui x console, but IP is correct

**Comment by merdok** [comment]
This error is fine and should not affect your setup.

**Comment by Olepir** [comment]
> This error is fine and should not affect your setup.

How about this?
[LG TV] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of kTLtbQAPV+A8cyTK6qmoaTah5Ds=

**Comment by merdok** [comment]
This is also ok, just sometimes the data gets corrupted for some reason.

**Comment by Olepir** [comment]
Did everything I could to troubleshoot it (except replacing a router), but with no luck. Will use it PS4-Waker in automations for now.
