### ISSUE TITLE
Eye comfort mode

### ISSUE THREAD

**Issue by rooi** [merdok/homebridge-webos-tv#178]
Hi Merdok,

I was wondering if you've found an api command to enable.disable eye comfort mode. I could not find it myself.
On my device it can be found under display settings and a remote button sequence should allow setting it on demand, but hopefully an api command exists.

Roy

**Comment by merdok** [comment]
There is no api, at least i did not find anything. The best solution for now is like you said to use a sequence.

**Comment by rooi** [comment]
Thanks!
