### ISSUE TITLE
2 TV's not working

### ISSUE THREAD

**Issue by Ryan-Weston** [merdok/homebridge-webos-tv#179]
I have two LG TV's running web OS I have added 2 accessories in my config file but now just get errors when home bridge is running a TV's dont show in home app. Anyone any ideas?

{
	"bridge": {
		"name": "Homebridge",
		"username": "6666666666",
		"port": 566666,
		"pin": "66666666"
	},

	"platforms": [{
			"platform": "Yeelight-Platform",
			"rgb": true
		},
		{
			"platform": "Hue",
			"users": {
				"rthrthrthyh": "dghertherh"
			},
			"lights": true,
			"sensors": true
		},
		{
			"platform": "TplinkSmarthome",
			"name": "TplinkSmarthome"
		}
	],

	"accessories": [{
		"accessory": "webostvoffice",
		"name": "Office TV",
		"ip": "0.0.0.0",
		"mac": "11:11:11:11:11:11",
		"keyFile": "/home/pi/.homebridge/lgtvKeyFile",
		"pollingInterval": 10,
		"inputs": [{
				"appId": "com.webos.app.livetv",
				"name": "Live TV"
			},
			{
				"appId": "com.webos.app.hdmi1",
				"name": "Apple TV"
			},
			{
				"appId": "youtube.leanback.v4",
				"name": "YouTube"
			},
			{
				"appId": "com.webos.app.photovideo",
				"name": "Photo Video"
			}
		],
		"showInputButtons": true,
		"volumeControl": "buttons",
		"channelControl": false,
		"mediaControl": false,
		"channelButtons": [3, 5, 7, 8],
		"soundOutputButtons": [
			"tv_speaker",
			"external_optical",
			"headphone"
		],
		"remoteSequenceButtons": [{
			"sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
			"name": "volume_seq",
			"interval": 1000
		}, {
			"accessory": "webostvlivingroom",
			"name": "Living Room TV",
			"ip": "0.0.0.0",
			"mac": "00:00:00:00:00:00",
			"keyFile": "/home/pi/.homebridge/lgtvKeyFile",
			"pollingInterval": 10,
			"inputs": [{
					"appId": "com.webos.app.livetv",
					"name": "Live TV"
				},
				{
					"appId": "com.webos.app.hdmi1",
					"name": "Apple TV"
				},
				{
					"appId": "youtube.leanback.v4",
					"name": "YouTube"
				},
				{
					"appId": "com.webos.app.photovideo",
					"name": "Photo Video"
				}
			],
			"showInputButtons": true,
			"volumeControl": "buttons",
			"channelControl": false,
			"mediaControl": false,
			"channelButtons": [3, 5, 7, 8],
			"soundOutputButtons": [
				"tv_speaker",
				"external_optical",
				"headphone"
			],
			"remoteSequenceButtons": [{
				"sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
				"name": "volume_seq",
				"interval": 1000
			}]
		}]
	}]
}

ERROR:

[10/6/2019, 6:58:43 PM] [Office TV] webOS - Error: connect EHOSTDOWN ip of first tv:3000 - Local (ip of second tv:58208)

**Comment by grzegorz914** [comment]
U can not change accessory, need to be always:

`"accessory": "webostv",`

**Comment by Ryan-Weston** [comment]
"accessories": [{
                "accessory": "webostv",
                "name": "Office TV",
                "ip": "0.0.0.0",
                "mac": "00:00:00:00:00:00",
                "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                "pollingInterval": 10,
                "inputs": [{
                                "appId": "com.webos.app.livetv",
                                "name": "Live TV"
                        },
                        {
                                "appId": "com.webos.app.hdmi1",
                                "name": "Apple TV"
                        },
                        {
                                "appId": "youtube.leanback.v4",
                                "name": "YouTube"
                        },
                        {
                                "appId": "com.webos.app.photovideo",
                                "name": "Photo Video"
                        }
                ],
                "showInputButtons": true,
                "volumeControl": "buttons",
                "channelControl": false,
                "mediaControl": false,
                "channelButtons": false,
                "soundOutputButtons": false,
                "remoteSequenceButtons": [
                        {
                                "sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
                                "name": "volume_seq",
                                "interval": 1000
                        },
                {
                "accessory": "webostv",
                "name": "Living Room TV",
                "ip": "0.0.0.0",
                "mac": "00:00:00:00:00:00",
                "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                "pollingInterval": 10,
                "inputs": [{
                                "appId": "com.webos.app.livetv",
                                "name": "Live TV"
                        },
                        {
                                "appId": "com.webos.app.hdmi1",
                                "name": "Apple TV"
                        },
                        {
                                "appId": "youtube.leanback.v4",
                                "name": "YouTube"
                        },
                        {
                                "appId": "com.webos.app.photovideo",
                                "name": "Photo Video"
                        }
                ],
                "showInputButtons": true,
                "volumeControl": "buttons",
                "channelControl": false,
                "mediaControl": false,
                "channelButtons": false,
                "soundOutputButtons": false,
                "remoteSequenceButtons": [
                        {
                                "sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
                                "name": "volume_seq",
                                "interval": 1000
                        } 
                        },
                        {
                                "appId": "com.webos.app.hdmi1",
                                "name": "Apple TV"
                        },
                        {
                                "appId": "youtube.leanback.v4",
                                "name": "YouTube"
                        },
                        {
                                "appId": "com.webos.app.photovideo",
                                "name": "Photo Video"
                        }
                ],
                "showInputButtons": true,
                "volumeControl": "buttons",
                "channelControl": false,
                "mediaControl": false,
                "channelButtons": false,
                "soundOutputButtons": false,
                "remoteSequenceButtons": [
                        {
                                "sequence": ["VOLUMEUP", "VOLUMEDOWN", "MUTE", "MUTE"],
                                "name": "volume_seq",
                                "interval": 1000
                        } 
                ]
        }]
}
]
}

sorry that is up to date config it just connects to one TV not the other?

**Comment by grzegorz914** [comment]
Just use this config, replace with Yours data (ip, mac, keyFile, prefsDir):

```
"accessories": [
        {
            "name": "TV Salon",
            "ip": "192.168.1.8",
            "mac": "C8:08:E1:CB:62:FD",
            "keyFile": "/home/openhabian/.webosTv/lgtvKeyFileSalon",
            "prefsDir": "/home/openhabian/.webosTv",
            "pollingInterval": 10,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "HDMI 1"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Kino domowe"
                },
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "com.webos.app.discovery",
                    "name": "Sklep LG"
                },
                {
                    "appId": "ipla",
                    "name": "Ipla"
                },
                {
                    "appId": "com.accedo.videa.tvn",
                    "name": "TVN Player"
                },
                {
                    "appId": "com.4225994.175759",
                    "name": "TVN VOD"
                },
                {
                    "appId": "spotify-beehive",
                    "name": "Spotify"
                },
                {
                    "appId": "com.webcamera.player",
                    "name": "Web Kamery"
                }
            ],
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        },
        {
            "name": "TV Kamila",
            "ip": "192.168.1.82",
            "mac": "20:3B:BD:26:54:48",
            "keyFile": "/home/openhabian/.webosTv/lgtvKeyFileKamila",
            "prefsDir": "/home/openhabian/.webosTv",
            "pollingInterval": 10,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "com.webos.app.discovery",
                    "name": "Sklep LG"
                },
                {
                    "appId": "ipla",
                    "name": "Ipla"
                },
                {
                    "appId": "com.accedo.videa.tvn",
                    "name": "TVN Player"
                },
                {
                    "appId": "com.4225994.175759",
                    "name": "TVN VOD"
                },
                {
                    "appId": "spotify-beehive",
                    "name": "Spotify"
                },
                {
                    "appId": "com.webcamera.player",
                    "name": "Web Kamery"
                },
                {
                    "appId": "com.webos.app.photovideo",
                    "name": "Telewizja"
                }
            ],
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        },
        {
            "name": "TV Pokój",
            "ip": "192.168.1.9",
            "mac": "20:17:42:5C:16:88",
            "keyFile": "/home/openhabian/.webosTv/lgtvKeyFilePokoj",
            "prefsDir": "/home/openhabian/.webosTv",
            "pollingInterval": 10,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "com.webos.app.discovery",
                    "name": "Sklep LG"
                },
                {
                    "appId": "ipla",
                    "name": "Ipla"
                },
                {
                    "appId": "com.accedo.videa.tvn",
                    "name": "TVN Player"
                },
                {
                    "appId": "com.4225994.175759",
                    "name": "TVN VOD"
                },
                {
                    "appId": "spotify-beehive",
                    "name": "Spotify"
                },
                {
                    "appId": "com.webcamera.player",
                    "name": "Web Kamery"
                },
                {
                    "appId": "com.webos.app.photovideo",
                    "name": "Telewizja"
                }
            ],
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        }
]
```
