### ISSUE TITLE
Use input source for automation

### ISSUE THREAD

**Issue by yepecece** [merdok/homebridge-webos-tv#181]
When using automation I can only use tv state. Is it possible to use the source (passing from hdmi1 to hdmi2 for example)?

Thanks

**Comment by merdok** [comment]
I also noticed this and i am not sure where he problem is. Will need to check it out.

**Comment by yepecece** [comment]
Thanks.

I was trying to create conditional automation (if tv is on and on hdmi 2 do that) with Hesperus (https://hesperus.io/) but it doesn’t seem to support HomeKit TVs. Do you know of any app that supports this kind of automation?

Thanks

**Comment by merdok** [comment]
Sorry i do not know that. I use the Eve app.

**Comment by yepecece** [comment]
Do you see the tv in eve?

**Comment by merdok** [comment]
No, i do not see.

**Comment by gillesguillemin** [comment]
I was tempted to open an issue for that last point actually: for some reason, **homebridge-webos-tv** accessories do not appear in any 3rd party HomeKit app (Eve, Home+, etc). Appart from the native devices (i.e. AppleTV and HomePod) which Apple restricts access to, **homebridge-webos-tv** seems to be the only other Homebridge accessory behaving that way.
It’s a bit frustrating, especially for automation as Eve and Home+ offer additional automation functionalities and I’m using the webOS TV as one of my main trigger (e.g. automatically dimming lights off when TV turns on, then back when TV turned off, wake-on-lan gaming PC when the TV turns on on a specific input, etc).
Is it something new or just something I just happened to notice (and report)?

**Comment by merdok** [comment]
I already did notice that too and i do not quite understand why they do not appear. I myself also want to use inputs for auomations but till now i did not manage to make them work... If anyone has an idea why this happening then i would gladly have a look.

**Comment by gillesguillemin** [comment]
Well, since they do appear in Apple's Home app, I do manage to create automations based on homebridge-webos-tv, it is even possible to improve on those automations with additional rules in 3rd party apps (at least in Home+) _after_ creating the initial automation in Home, but it's definitely finicky and one false move in the 3rd party app and you're bound to start fresh again.
But yeah, that's odd this happens with this plugin specifically...

**Comment by merdok** [comment]
But you cannot create automations based on inputs which i do not like and would like to fix that.

**Comment by gillesguillemin** [comment]
You can. I did just that actually: checking whether hdmi 2 is on, which triggers a cmdSwitch2 command to turn my PS4 on and voilà!
I use the 3 inputs to turn the TV on directly to the right input with associated automations (one for Apple TV, one for PS4 and the last one for the Gaming PC).

**Comment by merdok** [comment]
Yeah, right but i need an automation to only trigger when an input is currently on which i guess is not possible with the Home app...

**Comment by yepecece** [comment]
> You can. I did just that actually: checking whether hdmi 2 is on, which triggers a cmdSwitch2 command to turn my PS4 on and voilà!

How do you do that?
When trying to create an automation I only see the options “TV turns on” or “TV turns off”.
![78FB5D34-58A9-4F0C-902D-4C66C9F19CE5](https://user-images.githubusercontent.com/9193616/70388405-918c0580-19b1-11ea-9c37-a14bf0427918.png)

We could maybe activate input “sensors” (created via an other homebridge plug-in such as “Plex Sensors”) When the input is selected. That way we could use those sensors to create more complex rules?

**Comment by gillesguillemin** [comment]
You need to set your inputs as separate accessories and then each input acts as a basic switch, although switching it off won't turn the TV off. So I basically have a custom automation triggered by when the _input_ is turned on, and another one when the _TV_ is turned off.
I've also got other sets of actions triggered when the TV is turned on, actions that I always want triggered, regardless of which input is selected (or either how I turned the TV on, wether it is via the home app, using the Apple TV remote control, the TV's magic remote or some Harmony activity).

**Comment by yepecece** [comment]
Thanks, I didn’t see the "showInputButtons" option. Will try with that.

**Comment by gillesguillemin** [comment]
> Yeah, right but i need an automation to only trigger when an input is currently on which i guess is not possible with the Home app...

A possible work around that would be to use [a dummy switch](https://github.com/nfarina/homebridge-dummy) which state can match the webOS TV state (you can automate that in Home) and then use the state of this dummy switch in whatever 3rd party app you're using as a condition.

Certainly not as desirable as finding out why the plugin is not exposed to 3rd parties, but that should still work (and I actually might try that).

**Comment by yepecece** [comment]
Instead of creating a dummy switch per input you could use a slider.

https://github.com/grover/homebridge-automation-switches/blob/master/docs/Slider.md

**Comment by gillesguillemin** [comment]
Sure, why not, whatever exposes the state outside of Home basically.

**Comment by adrianopery** [comment]
Guys, I'm using homebridge-webos-tv plugin and it works fine.
The only thing is, if I add any input option, "HDMI1" and "HDMI2" as example, in the first time, ok. when I open the accessory on Apple Home app I can select there HDMI1 or 2.
Now I added "HDMI3" and even if I restart service or homebridge, I can't see this update. My list keep with only 2 options.
Do you know if there is a way to force the update?

**Comment by merdok** [comment]
Try to force close your Home app.

**Comment by adrianopery** [comment]
I did, and appears HDMI 3 on a list.
So I tried to add Youtube as in the examples, but this create a new button on my room screen, called Youtube.
I was thinking it should listed on the TV button with other inputs like HDMI 1, 2 and 3.
Other thing is, this new button don't have action.

**Comment by merdok** [comment]
I think those are some Home app caches. Usually a combination of restarting homebridge and force closing the Home app works.

**Comment by adrianopery** [comment]
Yes, will try later. Thanks.

**Comment by isaiahfranco** [comment]
> You need to set your inputs as separate accessories and then each input acts as a basic switch, although switching it off won't turn the TV off. So I basically have a custom automation triggered when the _input_ is turned on, and another one when the _TV_ is turned off.

How do you do this? For the life of me, I can't find showInputButtons in the config at all. I feel dumb!

**Comment by merdok** [comment]
> How do you do this? For the life of me, I can't find showInputButtons in the config at all. I feel dumb!

I guess you are looking for `appButtons`
