### ISSUE TITLE
Error if TV is off

### ISSUE THREAD

**Issue by Tim2309** [merdok/homebridge-webos-tv#182]
If my LG TV is offline the log show an error instead of switched off:

 webOS - Error: connect EHOSTUNREACH 192.168.1.31:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1128:14) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.31',
  port: 3000
}

everything works fine but the log looks not clean

**Comment by merdok** [comment]
I would guess this is from the pooling, this is required to check if the TV is on or off.

**Comment by Tim2309** [comment]
I understand, but is it necessary to display it as an error?
Other plugins can display their devices „off“ without an error.

**Comment by merdok** [comment]
Yes this is necessary for error troubleshooting. I mean how often do you check your logs?
