### ISSUE TITLE
Turning the TV off, the tile in HomeKit then lights back up

### ISSUE THREAD

**Issue by FastLaneJB** [merdok/homebridge-webos-tv#184]
Awesome work, I’ve just added Homebridge in to get the functionality your plugin provides because Home Assistant doesn’t implement the full remote control options.

However one small issue but when I turn the TV off in HomeKit, the tile goes dark to show it’s off but then lights back up a few seconds later. Now if I have the Sound buttons added in it’ll actually also turn the TV back on.

I’ve removed those as in fairness I don’t really need them which solves it switching the TV back on but just it’s still lighting up. I suspect looking at the logs when the TV turns off, the Soundbar also turns off and I see it then detects it’s on TV Speakers. Hence the device configuration changed so it lights it up.

Is it possible to fix this? While Home Assistant cannot do the remote part properly, it handles if the TV is off correctly in HomeKit so feel it must be possible.

Thanks so much for your time and effort on this.

**Comment by merdok** [comment]
This was already explained multiply times. I guess you have an OLED TV. The LG OLED TVs do a pixel refresh every 4 hours of runtime. The pixel refresh takes around 8 minutes to run . In that time the TV seems to be off but actually it is still on, just the display is off. Till now i did not find a way to detect this state. So unfortunately when the pixel refresher is running the tv will appear as on until it finishes.

**Comment by FastLaneJB** [comment]
Ah thanks for the explanation and sorry I missed you've said it before.
