### ISSUE TITLE
Info button

### ISSUE THREAD

**Issue by Catta1997** [merdok/homebridge-webos-tv#185]
I have a suggestion. Can you make possible to use the "info" button of the remote control on the iOS device to behave differently depending on whether the info button has already been pressed? as the play / pause button already does. I've already set it in the file and it works.
in the variables section I put:
isInfo = false;

and so I modified the case
case Characteristic.RemoteKey.INFORMATION:
             if (this.isInfo) {
                 this.setRemoteControlButtonState (true, callback, 'INFO');
             } else {
                 this.setRemoteControlButtonState (true, callback, 'HOME');
             }
             this.isInfo =! this.isInfo;
             break;

**Comment by merdok** [comment]
I am not really sure if this makes sense. I think this would just unnecessary make it complicated.
