### ISSUE TITLE
Treat volume as a speaker

### ISSUE THREAD

**Issue by neobeppe** [merdok/homebridge-webos-tv#187]
Is it possible to have as an option the volume control as a speaker?

**Comment by merdok** [comment]
Possible yes, but for now i decided against that since the Home app does not support speakers. Or did that change in the latest iOS?

**Comment by creinhart** [comment]
In a sense it does support speakers. My ikea-Sonos Airplay 2 speaker shows up in the Home app as a speaker. But I’m not too sure if that would work for this application.

**Comment by merdok** [comment]
So can you set the volume of the speaker and mute it through the Home app? Can you post some screenshots?

**Comment by creinhart** [comment]
It has full playback and volume controls but only when audio is being airplayed to it.
![186E374A-29D6-45FA-8ABA-8DD5B0523397](https://user-images.githubusercontent.com/20129134/69884081-cce94e80-12a4-11ea-8725-bfd7e7662553.png)
![8B5ECD87-765E-43CB-9C46-49B8CE64937B](https://user-images.githubusercontent.com/20129134/69884082-cce94e80-12a4-11ea-9fd8-4c25169146a3.png)

**Comment by merdok** [comment]
Oh, this is the Airplay stuff. I guess this cannot be used...
