### ISSUE TITLE
Not working in iOS/iPadOS 13

### ISSUE THREAD

**Issue by bwalls** [merdok/homebridge-webos-tv#188]
I know an iOS 13 thread was closed because things seem to be working, but it is not working for me. It still works on the Home app on macOS Mojave, but on my iPhone with iOS 13.2.3 and iPad with 13.3 beta 2, I get a single Accessory named "Channel Up" that has a list of switches underneath that I can't scroll or control. Ideas?

![IMG_0867](https://user-images.githubusercontent.com/356693/69836951-d9709700-1211-11ea-9d2f-87dea80e819d.png)
![IMG_0868](https://user-images.githubusercontent.com/356693/69836952-d9709700-1211-11ea-8014-2f70bb2da196.png)
![IMG_7641](https://user-images.githubusercontent.com/356693/69836953-d9709700-1211-11ea-8433-7b476b51dc7e.png)
![IMG_7642](https://user-images.githubusercontent.com/356693/69836954-d9709700-1211-11ea-8ceb-a9bff4280104.png)
<img width="1135" alt="Screenshot 2019-11-28 18 39 02" src="https://user-images.githubusercontent.com/356693/69836968-f6a56580-1211-11ea-81c0-cb7afd2c8f72.png">

**Comment by merdok** [comment]
Working fine for me on iPhone and iPad with iOS13.2.3. Maybe you have some issues with your config? Or maybe your Home app on iOS got a glitch?

**Comment by bwalls** [comment]
Okay, figured out what was going on. The app wanted to list the status of all the "switches" before actually show the switches. I had enough content that the list completely filled the screen, so I had no control. 

After I deleted a bunch of controls, I had a section that allowed me to access a switch, and to scroll. At the very bottom of the control area, I can choose **Show as Separate Tiles** and get back to the old control format, with all the controls spread out in the TV "room". 

From there, you can choose a tile and have the option of **Group with Other Accessories...** or **Show as Single Tile**. That takes you right back to where it started – with all my controls, I'm powerless to do anything, or change it back. 

The interface is clearly suboptimal for controlling a TV, especially where the tile doesn't actually show enough to read the control. But it's slowly improving. 

Anyone know how to move directly to Netflix or Amazon Prime, like hitting the dedicated buttons on the LG remote?

**Comment by grrowl** [comment]
Set the key "inputs" with whichever of these values suit you:

```json
"inputs": [
                {
                    "appId": "com.webos.app.tvguide",
                    "name": "TV Guide"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Chromecast"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "V58"
                },
                {
                    "appId": "com.webos.app.hdmi4",
                    "name": "Playstation"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "cdp-30",
                    "name": "Plex"
                },
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "stan.webos2",
                    "name": "Stan"
                },
                {
                    "appId": "amazon",
                    "name": "Amazon"
                },
                {
                    "appId": "abc",
                    "name": "ABC"
                },
                {
                    "appId": "sbs",
                    "name": "SBS"
                }
            ]
```

You can also set `"showInputButtons": true` so they show up as individual switches, as well as a "selector" control (I find the channel selector control suffices)
