### ISSUE TITLE
Off status

### ISSUE THREAD

**Issue by zany92** [merdok/homebridge-webos-tv#191]
Hello,

First of all, congratulation for the good work, it is a very impressive piece of work.
Everything is working smoothly for me except for one thing.

If I turn off my TV with the remote control, the status remains on.
That's a problem for my Goodnight scenario.

Did I missed something or is it a bug?
Thanks

**Comment by merdok** [comment]
Well, this was already explained multiply times. I guess that you have an OLED TV. The LG OLED TVs do a pixel refresh every 4 hours of runtime. The pixel refresh takes around 8 minutes to run and in that time the TV seems to be off but actually it is still on, just the display is off. Unfortunately I did not find a way to detect this state, so when the pixel refresher is running the tv will appear as on until it finishes. This should not be a big deal but hopefully someday i find a way to fix this.

**Comment by zany92** [comment]
Thank you for your explanation. This is a very precious feedback I was not aware of, sorry for the dummy question. Congrats again for the good work, amazing.

**Comment by merdok** [comment]
I hope that i can fix this someday... This is not easy to debug because i have only a 8 minutes window to do my tests and after that i need to wait a long time again...
