### ISSUE TITLE
AirPlay 2 support?

### ISSUE THREAD

**Issue by Hiddecollee** [merdok/homebridge-webos-tv#192]
https://9to5mac.com/2019/12/05/airplay-2-cracked/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

It looks like Airplay 2 is cracked, will this make it possible that the TV will support airplay too?

**Comment by merdok** [comment]
Not sure if it will work but let's see.

**Comment by rooi** [comment]
Would it be possible to run homebridge-webos-tv on the lg webos tv itself? Webos seems to support nodejs services https://forum.webosose.org/t/how-to-run-a-web-server-in-web-os/589
If airplay 2 will be available, perhaps a similar approach could provide us with similar functionality os the latest tas from lg

**Comment by merdok** [comment]
I do not think that this would possible. I think the TV would need to be jailbroken for that...

**Comment by rooi** [comment]
I was under the impression you can create a developer account to create apps. I could be wrong though, haven't tried it myself (yet)
http://webostv.developer.lge.com/develop/app-test/
http://webostv.developer.lge.com/develop/js-services/webos-tv-service-basics/

**Comment by merdok** [comment]
But i do not think that you can simply install homebridge on a webos tv...

**Comment by rossco57** [comment]
Don’t think it would be homebridge you would install. Think it would be airplay/airplay 2 receiver app if it could be developed and installed with Dev account not likely to pass to downloadable app status as they want to sell you a new tv

**Comment by iRayanKhan** [comment]
Or just connect a Pi via HDMI once the AP2 crack comes out.
