### ISSUE TITLE
Key Not Saved

### ISSUE THREAD

**Issue by eliahuroash** [merdok/homebridge-webos-tv#193]
I get errors in homebridge when responding to the prompt for confirmation on my TV.

  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/.homebridge/lgtvKeyFile'

WebOS 3.8.0-61110

**Comment by merdok** [comment]
You probably do not have the correct permissions to write to that directory. Make sure that the homebridge has permissions to write in that location.

**Comment by eliahuroash** [comment]
Tried making the directory world-writeable. No joy. Same error. The instructions say this shouldn't be a directory, but there's no file extension on the path. What's the right way to configure this?

**Comment by merdok** [comment]
also make sure that the specified directory exists. Only the file will be created, not the directories. You can also try to remove the path completely from your config, then it will try to write it to the default directory.
