### ISSUE TITLE
Custom input names aren't shown

### ISSUE THREAD

**Issue by tDr1v3r** [merdok/homebridge-webos-tv#194]
Title says all. 

I don't know what broke it... both the iOS (13.1.3) and the macOS (10.14.6 - 18G48f) Home app shows the AppID instead of the custon names I've added to the inputs. It worked previously (like 3 months ago or so) and I don't see why it doesn't work properly now...

The Homebridge's version is 0.4.50, which I've just updated - along with npm.

![IMG_3437](https://user-images.githubusercontent.com/58704313/70463188-b5883d80-1abc-11ea-87c1-0c8b1dc78b04.PNG)

Here's the config I'm using:

```
 {
            "accessory": "webostv",
            "name": "[LG] WebOS TV",
            "ip": "192.168.1.41",
            "mac": "7C:1C:4E:4C:CD:38",
            "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
            "pollingInterval": 10,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Xbox One"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "hbogocev5",
                    "name": "HBO GO"
                },
                {
                    "appId": "amazon",
                    "name": "Amazon Prime Video"
                },
                {
                    "appId": "spotify-beehive",
                    "name": "Spotify"
                }
            ],
            "showInputButtons": false,
            "volumeControl": "false",
            "channelControl": false,
            "mediaControl": false,
            "channelButtons": "",
            "remoteControlButtons": "",
            "soundOutputButtons": "",
            "remoteSequenceButtons": false
        },
````

**Comment by merdok** [comment]
Works fine for me here, did you try to restart your homebridge? If this still does not work, could you please rollback your homebridge version and see if the new homebridge is the issue?

**Comment by tDr1v3r** [comment]
I didn't touched it for months, so it was offline for quite a while - with the same software versions on the server side I've used before. I tried updating everything, and it didn't fixed that...

...But it looks like the problem's cause was iOS 13 - after tinkering for a while I noticed that I can rename the inputs inside the phone's Home app, which reflects back to the Mac app as well. Interesting, the last time I've used Homebridge I had a pre-release iOS 13 beta on my phone, back in July or August... I guess I finally see why almost everyone complain about the new Home app.

**Comment by merdok** [comment]
I do not think that it has something to do with iOS13. It works fine for me on all device with iOS13. I suspect that maybe your homebridge messed something up. Maybe even the file where the names are stored has been modified.

**Comment by grzegorz914** [comment]
@tDr1v3r 

just replace positions  between “name” and “appId” in config:

```
{
"name": "YouTube",
"appId": "youtube.leanback.v4"
}
```

this trick working for me.

Thanks 
Grzegorz

**Comment by merdok** [comment]
That is interesting. Actually the order should not matter...

**Comment by grzegorz914** [comment]
Yes, it is interesting but fixed the problem for me😀

**Comment by merdok** [comment]
@tDr1v3r does that fix the issue for you?

**Comment by OberfragGER** [comment]
Dammit,
i have the same issue.
homebridge-webos-tv v1.6.3
I switched it- no effect

{
            "name": "LG TV",
            "ip": "192.168.178.88",
            "mac": "14:C9:13:D2:28:77",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "volumeControl": "slider",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "name": "Live TV",
                    "appId": "com.webos.app.livetv"
                },
                {
                    "name": "PS4",
                    "appId": "com.webos.app.hdmi1"
                },
                {
                    "name": "Kodi",
                    "appId": "com.webos.app.hdmi2"
                }
            ],
            "showInputButtons": false,
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        }

The wheel with the Inputs is empty :(

**Comment by OberfragGER** [comment]
After playing a bit around with the configuration inside the IOS Homemanager app - its suddenly working (the app scrambles the whole config.json upside down).

`{
      "accessory" : "webostv",
      "channelControl" : false,
      "infoButtonAction" : "INFO",
      "inputs" : [
        {
          "appId" : "com.webos.app.livetv",
          "name" : "Live TV"
        },
        {
          "appId" : "com.webos.app.hdmi1",
          "name" : "PS4"
        },
        {
          "appId" : "com.webos.app.hdmi2",
          "name" : "Kodi"
        }
      ],
      "ip" : "192.168.178.XX",
      "legacyTvService" : false,
      "mac" : "XX:XX:XX:XX:XX:XX",
      "mediaControl" : false,
      "name" : "LG TV",
      "pollingInterval" : 5,
      "prefsDir" : "~/.webosTv",
      "showInputButtons" : false,
      "volumeControl" : "slider",
      "volumeLimit" : 100
    }`

**Comment by merdok** [comment]
Maybe this was some sort of corruption of the file...

**Comment by adrianopery** [comment]
Hi, I'm trying to to add some

**Comment by merdok** [comment]
You need to check if the appId is correct. For that just start homebridge in debug mode in the console and then switch to the amazon app on the TV, in the console the appId should be displayed.

**Comment by adrianopery** [comment]
> You need to check if the appId is correct. For that just start homebridge in debug mode in the console and then switch to the amazon app on the TV, in the console the appId should be displayed.

Thanks, I found here...
For me is the app name is "amazon.global".
Now it's working.
