### ISSUE TITLE
Name Buttons vs. "Switch"

### ISSUE THREAD

**Issue by JerGitHub** [merdok/homebridge-webos-tv#196]
First off - great work on this so I can bring HomeKit to my OLED C8 since LG won't!

I didn't see it in the doc but is there a way to name buttons I have set - (remote control, sound output, remote sequence, and notification buttons) - instead of the generic name "switch" as shown in the screenshots attached? I can't tell what anything is when everything is named "switch". 

Also, is there any way to re-arrange them in the UI?

<img width="286" alt="Screen Shot 2019-12-26 at 3 48 32 PM" src="https://user-images.githubusercontent.com/16343534/71490402-bd541b80-27f8-11ea-8c48-f0a246930e4e.png">
<img width="288" alt="Screen Shot 2019-12-26 at 3 47 58 PM" src="https://user-images.githubusercontent.com/16343534/71490404-bd541b80-27f8-11ea-8b58-e53927e49b77.png">
<img width="288" alt="Screen Shot 2019-12-26 at 3 47 30 PM" src="https://user-images.githubusercontent.com/16343534/71490405-bd541b80-27f8-11ea-9d0a-95320a9a1ec7.png">
<img width="286" alt="Screen Shot 2019-12-26 at 3 47 14 PM" src="https://user-images.githubusercontent.com/16343534/71490406-bd541b80-27f8-11ea-9b5b-52fa078ee3c6.png">

**Comment by merdok** [comment]
You can simply just open the switch detail in the Home app and rename it there. As far as i know there is no way to rearrange the switches in a group.

**Comment by JerGitHub** [comment]
@merdok thanks! I'm an idiot! 

Of all my nearly 75 HK devices I have, I don't have any grouped together in this new ios13 grouping. So when I went in to see them per the screenshots above, I didn't see how to change the names. But scrolling all the way down....then hitting the prefs.....then scrolling down again to the 11 Accessories I had made in the TV group....then long pressing each one listed in the Accessories allowed me to change each one's name. A pain in the butt since you have no idea which one does what without trial and error - but not your fault! I wish I could name them in the .json when setting it up. 

P.S. The slider doesn't work for controlling volume but the button works. Have you seen this issue?

**Comment by merdok** [comment]
Slider works fine on my TV and i also have a C8 :)

**Comment by JerGitHub** [comment]
OK - tried the slider again. It works if I am controlling TV Speakers only but not if I am controlling audio via External ARC. 

For reference I have a Denon AVR hooked up to my C8 on HMDI2 (ARC) and is the only input in use on my C8. All inputs are controlled on my Denon. I have CEC on so it controls power on/off of TV and the Denon as well as volume up and down. I have this working fine on the C8 Magic Remote, AppleTV remote, and cable box remote. Using any one of those remotes can turn volume up or down on the AVR via CEC from the LG C8. The C8 volume HUD displays as well as the Denon HUD when adjusting volume. The slider using this accessory doesn't display either HUD when I use it but the buttons do. 

I wonder if there is a different command sent when using CEC for volume up and down? I doubt it since it works with the button here - just not the slider. I may have to TCPDUMP the controls on the AppleTV remote app via my iPhone with rvictl and see if I see anything different unless you have any other ideas?

**Comment by merdok** [comment]
Yes, because of that issue buttons were introduced since the slider only works on TV speaker.

**Comment by JerGitHub** [comment]
Ah bummer - Weird. I wonder why that is? Thanks again!
