### ISSUE TITLE
Mute isn’t working for ( i ) button after update

### ISSUE THREAD

**Issue by SerhiiAksiutin** [merdok/homebridge-webos-tv#197]
`"infoButtonAction": "MUTE", `

**Comment by merdok** [comment]
Just tested it and it works fine. No issues...

**Comment by SerhiiAksiutin** [comment]
Restarting PI helped to fix this. But volume was working while mute wasn’t. I’ll reopen it if there is a way to reproduce this. Thanks for checking.
