### ISSUE TITLE
npm WARN deprecated core-js

### ISSUE THREAD

**Issue by coalfield** [merdok/homebridge-webos-tv#198]
It looks like I am getting the error on install that the core-js dependency is out of date.  Has anyone else seen this issue?

**Comment by merdok** [comment]
did you try installing with `sudo`?

**Comment by coalfield** [comment]
No I didnt, I am running homebridge as a docker container and webos-tv is installed via regular npm install, I have manually updated core-js but would have thought it kept up to date within webos-tv?

**Comment by merdok** [comment]
It should actually update normally, no idea what went wrong on your machine...
