### ISSUE TITLE
Two LG TVs confrigured. Both turn Off and both wont turn On via Home app

### ISSUE THREAD

**Issue by mrjcohen** [merdok/homebridge-webos-tv#199]
I have an issue where both the TVs I have configured using homebridge will turn off and switch inputs just fine. I am unable to turn of the TVs though for some reason. Does anyone know what might cause this? I have included my config below. Any help would be greatly appreciated.

>     "accessories": [
        {
            "accessory": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv",
                "index": 0
            },
            "name": "The TV",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Switch"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Soundbar"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "AppleTV"
                },
                {
                    "appId": "com.webos.app.hdmi4",
                    "name": "PS4"
                }
            ],
            "infoButtonAction": "INFO",
            "ip": "192.168.20.7",
            "mac": "CC:CC:CC:CC:CC:CC",
            "keyFile": "/home/hoobs/lg/lgtvKeyFile"
        },
        {
            "accessory": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv",
                "index": 0
            },
            "name": "Livingroom TV",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "AppleTV"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Hub"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "Xbox"
                }
            ],
            "infoButtonAction": "INFO",
            "keyFile": "/home/hoobs/lg/lgtvKeyFile2",
            "ip": "192.168.20.9",
            "mac": "CC:CC:CC:CC:CC:CC"
        }
    ],

**Comment by mrjcohen** [comment]
Side note. Anyone know how to share the json file and not have it be one long contiguous line of unreadable code?

**Comment by mrjcohen** [comment]
>     "accessories": [
        {
            "accessory": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv",
                "index": 0
            },
            "name": "The TV",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Switch"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Soundbar"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "AppleTV"
                },
                {
                    "appId": "com.webos.app.hdmi4",
                    "name": "PS4"
                }
            ],
            "infoButtonAction": "INFO",
            "ip": "192.168.20.7",
            "mac": "CC:CC:CC:CC:CC:CC",
            "keyFile": "/home/hoobs/lg/lgtvKeyFile"
        },
        {
            "accessory": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv",
                "index": 0
            },
            "name": "Livingroom TV",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "AppleTV"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Hub"
                },
                {
                    "appId": "com.webos.app.hdmi3",
                    "name": "Xbox"
                }
            ],
            "infoButtonAction": "INFO",
            "keyFile": "/home/hoobs/lg/lgtvKeyFile2",
            "ip": "192.168.20.9",
            "mac": "CC:CC:CC:CC:CC:CC"
        }
    ],

**Comment by merdok** [comment]
For 2 TVs you would need to currently run 2 instances of homebridge as far as i know. There is some issue currently and i would need to rewrite the plugin to make it work but due to lack of time i did not start yet. I myself have only 1 TV but that is what i think the issue issue based on other reports...

**Comment by mrjcohen** [comment]
I’d like to thank you for creating and sharing such an awesome plugin. I should mentioned that the second tv was added 2 days ago. I was having the same issue prior to adding the second tv. I’m wondering if it has to do with the fact that my TVs are on a separate network (192.168.20.1) then my home bridge hub (192.168.1.1). I have avahi on a pfsense firewall that allows them to talk to each other but maybe it only allows me to turn off the tv and not turn it on

**Comment by merdok** [comment]
Sorry i cannot really answer any of your questions related to 2 TVs since i do only own one. Maybe someone else who has 2 TVs can help you...

**Comment by plainsane** [comment]
I have 4, but I’m running 4 instances of homebridge so they look like 4 discrete bridges.  I suspect your TVs are not configured for wake-on-lan though which is why they won’t turn on...

**Comment by mrjcohen** [comment]
Do you know where I can find the wake on lan setting in the lg’s OS? I can’t seem to find it

**Comment by merdok** [comment]
Look at the bottom of the [Configuration](https://github.com/merdok/homebridge-webos-tv#configuration)section.

**Comment by mrjcohen** [comment]
Its been a while since i posted but today I tried tackling this issue again. I did a clean install of homekit and only set up only one TV. I am still running into the same issue. I am able to turn the TV off but not on. When I turn the TV on the HomeBridge Logs reflect that:

`[3/6/2020, 12:19:52 AM] [Bedroom TV] webOS - connected to TV, checking power status
[3/6/2020, 12:19:52 AM] [Bedroom TV] webOS - power status - TV is On
[3/6/2020, 12:19:52 AM] [Bedroom TV] webOS - connected to TV
[3/6/2020, 12:19:52 AM] [Bedroom TV] webOS - subscribing to TV services`

But when the TV is off I just doesnt seem to be able to connect to it or turn it on even after sending the ma
`[3/6/2020, 12:21:42 AM] [Bedroom TV] webOS - disconnected from TV
[3/6/2020, 12:21:44 AM] [Bedroom TV] webOS - power service - Trying to power on tv, sending magic packet`

I am at a loss here. I would like to point out that my home network has a seperate VLAN for all my IOT devices but the TV and the HomeBridge hub are on the same network so I am not sure that matters.

Your last message mentions looking at the boot of the Configuration sections but I am not really sure what I am looking for.

Any help would be greatly appreciated

**Comment by merdok** [comment]
Maybe you have to play with the `broadcastAdr ` property...

**Comment by kladda** [comment]
I kind of have the same problem, but only with one TV. I two LG tv's and they both show up and i can turn one of the off and on (this after enable the Mobile TV on setting).
The other tv is newer, and i have enabled LG Connect Apps, but no luck. Is there anything else i need to do accept this? :)

thanks!

**Comment by mrjcohen** [comment]
I still haven’t been able to solve the problem. Let me know if you figure anything out

**Comment by merdok** [comment]
@kladda what exact TV models do you have? I suspect that such an issue has something to do with your home network.

**Comment by kladda** [comment]
@merdok Hi!
My models are 
43UH664V - this model has the Mobile TV-option and is working with both on and off.
55UF772V - this model does not have the Mobile TV option but has the "LG connect apps". It works turning off, but not on.

Thanks!

**Comment by merdok** [comment]
I think that this is caused by your network. Maybe the wol packet is not correctly routed in your network. If that is the case then you need to have a look at the `broadcastAdr` property.

**Comment by kladda** [comment]
Thanks merdok!
Sorry for being perhaps a bit stupid, but how would i broadcast address look? Is that an IP, Mac or what kind of adress are it looking for? :)
My host do have more then one network interface in the form of wifi, ethernet etc.

**Comment by merdok** [comment]
broadcast address is an ip adress. You need to figure out what is wrong with your network.

**Comment by ChristianMeier2202** [comment]
> I still haven’t been able to solve the problem. Let me know if you figure anything out

Hi, have you tried to set the tv in quick start mode already? For me that worked. The lg TVs seem to go to hibernation without this function activated.

**Comment by merdok** [comment]
Oh, you are right. That might be the fix for everyone who has this issue.

**Comment by merdok** [comment]
As of version 1.7.0 the plugin can be used as a platform hence enabling easy use of multiple TVs.
