### ISSUE TITLE
Keyfile not Autogenerating

### ISSUE THREAD

**Issue by alrightsure** [merdok/homebridge-webos-tv#200]
The directions specify that it should autogenerate a keyfile if it does not exist, but it does not appear to be doing that.

`[1/29/2020, 16:32:14] [Livingroom TV] webOS - [Error: ENOENT: no such file or directory, open '/homebridge/livingroomTVKey'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/homebridge/livingroomTVKey'
}`

running on a raspberry pi.

**Comment by merdok** [comment]
Make sure that homebridge has write permission to that directory. Also you can simply remove the `keyFile` from your configuration.
