### ISSUE TITLE
Suggestion: Possibility of passing params to apps

### ISSUE THREAD

**Issue by dkasipovic** [merdok/homebridge-webos-tv#201]
lgtv2 has a possibility where you can pass "params" when launching an app. For example this can be used to launch youtube directly to a certain video by using special link

Example:

```
lgtv2.request('ssap://com.webos.applicationManager/launch', {
	id: 'youtube.leanback.v4',
	params: {
		contentTarget: 'https://www.youtube.com/tv?v=Bey4XXJAqS8'
	}
});
```

This will open YouTube app directly to the example 4K video.

This would be great to be used in inputs. How I did it locally (modified homebridge-webos-tv/index.js)

1. Added "Demo 4K" input with `"appId": "youtube.leanback.v4|https://www.youtube.com/tv?v=Bey4XXJAqS8"`
2. Modified setAppSwitchState so that it does `appId = appId.split('|')` and if `length > 1` use `com.webos.applicationManage/launch` with `{ id: appId[0], params: { contentTarget: appId[1] }}`
3. Modified checkForegroundApp like: 
```
if (appId === undefined || appId === null) { // if appId undefined or null then i am checking which app is currently running; if set then continue normally
	callback(null, true, res.appId);
} else if (res.appId === appId) {
	callback(null, true, appId);
} else if (res.appId === appId.split('|')[0]) { // This is the added part
	callback(null, true, appId);
} else {
	callback(null, false, appId);
}
```

So now I have switch named "Demo 4K", which when clicked opens the Youtube app to 4K demo video

This is a crude way of accomplishing what I need, and there must be a better way to do this.

**Comment by merdok** [comment]
Oh, did not know about that. Does it also work for other apps? 
I can see that this could be useful. I will add such feature but most probably do it in a way where you can specify your params as a key/value pair in the inputs list like:

```         
          {
            "appId": "com.webos.app.livetv",
            "name": "Live TV",
            "params": "example params"
          },
```

**Comment by dkasipovic** [comment]
Yeah, it depends on the app itself, I accidentally stumbled on YouTube params when Googling for `com.webos.applicationManager/launch`.

I suspect that params is passed directly to the app that is being launched, and it is up to the application itself to do what it needs with those params.

Regarding the enhancement, I suspected you'd do something like that. I was thinking about doing it myself but I am not that familiar to the inner workings of Homebridge so I didn't want to break it. That's why I tried to make it work with minimum changes. Your way is definitely the way to go.

**Comment by merdok** [comment]
Done! This feature is included in the latest 1.6.4 release. Please check it out and let me know if works as expected :)

**Comment by dkasipovic** [comment]
Will do, as soon as I get home, I am at work now. If I understand it right, whatever I add in "params" will be passed as is to the launcher?

**Comment by merdok** [comment]
Yes, you can see an example configuration here: [https://github.com/merdok/homebridge-webos-tv#configuration](https://github.com/merdok/homebridge-webos-tv#configuration)

**Comment by dkasipovic** [comment]
It works perfectly. Thanks!
