### ISSUE TITLE
Suggestion: Possibility to accept functions as config parameters

### ISSUE THREAD

**Issue by dkasipovic** [merdok/homebridge-webos-tv#202]
It should be possible to pass function as a configuration parameter. For example

```
volumeLimit: () => {
  let h = new Date().getHours();
  return h > 20 ? 10 : 100;
}
```

Nothing like a good scare when you accidentally set volume to 100 using the brightness slider to bring new ideas to save your marriage :)

**Comment by merdok** [comment]
Hmm, the idea is good and would enable more customization, but i am not sure if this will work. Passing a function in the config json will probably not work...

**Comment by dkasipovic** [comment]
Yeah, you are probably right, I forgot that config is actually passed from Homebridge.

Maybe something like `volumeLimit: "volume.js"` which would mean that you need to import `volume.js`, and `volume.js` could be something like:

```
module.exports = {
  value: () => {
    let h = new Date().getHours();
    return h > 20 ? 10 : 100;
  }
}
```

And you could use something like `import('volume.js').value()` or similar,

It's just an idea, not sure how viable is that, or even useful.

**Comment by merdok** [comment]
I think this would not work or at least would just make everything to complicated. I think this is interesting feature but i am not sure if this is worth implementing. I mean you can create the same result by simply writing a script that will modify the config json at the specified times.
