### ISSUE TITLE
Channel switch not working with webOS 3

### ISSUE THREAD

**Issue by dkasipovic** [merdok/homebridge-webos-tv#203]
Channel switch is not working on WebOS 3. However, the issue seems to be with lgtv2 itself. Furthermore the core of the issue seems to be WebOS 3 in itself. It returns "no database to select from" if you try to select channel by channelNumber. However, selecting channel by channelId work.

So, the proposed solution:

1. Connect to WebOS via lgtv2
2. On connect, get channel list, and create a map, like `channelMap[channelNumber] = channelId`
3. When changing channel, instead of using `channelNumber: number`, use `channelId: channelMap[number]`

Do you think that is something viable?

**Comment by merdok** [comment]
Not sure about that one, keep the huge channel list on might not be a good solution. The channel list might change and in that case the logic will bring the user to different channel then specified...

**Comment by dkasipovic** [comment]
I can understand that. Maybe you could make it so that channel buttons work with object instead of an array.

For example, instead or 

> [1, 2, 3]

We could use

> [{channelNumber: 1, channelId: Xxx}, ...]

What do you think?

**Comment by merdok** [comment]
That does not change anything, if the channel number changes then object will still point to a different channelId. Switching to channelId's would just introduce a lot of complicated to logic which i would like to avoid. Maybe the issue lies somewhere else that it does not work on webos3? My previous TV was a webos3 tv and as far as i recall this was working...

**Comment by dkasipovic** [comment]
Yeah but as things now are, channel buttons are unusable (and my tv is not that new, at least 3 years old), so I was trying to find a solution.

If you think that clutters your code too much, I think I'll just go ahead and make local changes to make those buttons work, because as it is I can't use it. 

I was thinking about using same format as input, so it would be name, channelId, channelNumber.

So when I configure the channels I specify either the ChannelNumber or ChannelId, and based on which option is available, I'll send the corresponding command.

Also, name can be used as a button title, so instead of Channel 1 in Home, I'll have RTL or similar

What do you think?

**Comment by merdok** [comment]
Making it the same format as input would make the most sense from my perspective, but it would still introduce the issue that channelId is a cryptic number and in order to find it out the user would need to first do a debug in homebridge. For the inputs there is no other way to retrieve the appId so i had to go that direction...

**Comment by dkasipovic** [comment]
Imho, I dont think that the idea od getting channel list on connect is too bad. I dont think that channel number changes too often (most likely on re-scan of all channels or similar), and even in that case you could update the whole list periodically (daily).

Regarding the size, I dont think thats an issue since it's simple associative array, so even with 10k channels or so, that should not be annissue

**Comment by merdok** [comment]
Like i said, as far as i know the channelNumber was working on webos3, i only remember it was not working on webos1.4, so are you sure that you are using webos3 or maybe this is another issue on your side? Maybe you simple missing a channel list on your TV?

**Comment by merdok** [comment]
Added optional `channelId` property to the channel button service in version 1.8.2. If the `channelId` is specified then it will be used.
