### ISSUE TITLE
Possible to get information when hdr is turned on?

### ISSUE THREAD

**Issue by domeOo** [merdok/homebridge-webos-tv#204]
Hi Merdok,

first i want to thank you four your work on this project.
I’m asking if it’s possible to get the information from the tv that HDR is turned on. I think the TV uses the same function like our custom notifications. 

![image](https://user-images.githubusercontent.com/17083036/74578217-919d1880-4f93-11ea-89c7-d86dbe2417b5.jpg)

I you can tell me if it’s possible I can also try to implement it.

**Comment by merdok** [comment]
I do not think that this is possible. Honestly i do not even know for what such information would be useful...

**Comment by domeOo** [comment]
I have an DIY Ambilight and need to call a script for calibrating my Video-Grabber  when I’m Watching HDR content. with this information, I could automate the process.

**Comment by merdok** [comment]
I see, but like i said i do not think that this information can be retried from the TV. I only saw Information if 3D is turned on before.

**Comment by domeOo** [comment]
Thank you for the information
