### ISSUE TITLE
Can't see lg tv in homekit

### ISSUE THREAD

**Issue by deveylder** [merdok/homebridge-webos-tv#205]
i can see in the monitor from npm that everithing works fine

But homekit is not detecting a new accessory . So i do now have any tv icons

no clue

**Comment by merdok** [comment]
I  cannot tell what is happening on your side since you did not provide any information from your setup. What is your TV? How does your config.json look like? What do you see in the homebridge log output?

**Comment by deveylder** [comment]
Hey Merdok 

you are so right. Sorry about that I thought I was missing a parameter.
I primeraly work with Hassio except for Ring / cams and LG tv.

enclosed my json


Thank You


Bart
-------------
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Ring",
		"refreshToken": "eyJhbGciOiJIUzUxMiIsImprdSI6Ii9vYXV0aC9pbnRlcm5hbC9qd2tzIiwia2lkIjoiZGVmYXVsdCIsInR5cCI6IkpXVCJ9.eyJpYXsdfghjngfdeszqswxcvghyg2xpZW50Il0sInJlZnJlc2hfdXNlcl9pZCI6OTY2OTk1OCwicm5kIjoiRUpTY1M3SHFTSUM1dHciLCJ0eXBlIjoicmVmcmVzaC10b2tlbiJ9.C-3-iRKZ4d2zVwrIZ30_o-mbJ71iSqmRbKcdE3AtjAMx17h0fJMjlaR4VM_7-mqVYLbIZs_YKk-NDx1WpYGw9w"
	},
	{
	        "platform": "SamsungTizen",
	        "devices": [
	            {
	                "name": "Keuken TV",
	                "ip": "192.168.1.48",
	                "mac": "e4:7d:bd:1f:f1:33"
	            }
	        ]
	    },
	{
		"platform": "Camera-IP",

		"cameras": [{
				"name": "Street",
				"videoConfig": {
					"source": "-re -i rtsp://192.168.3.117:554/Streaming/Channels/101/",
					"stillImageSource": "-i http://192.168.3.117:80/ISAPI//Streaming/channels/101/picture",
					"maxStreams": 1,
					"maxWidth": 640,
					"maxHeight": 480,
					"maxFPS": 12
				}
			},
			{
				"name": "Parking_Achter",
				"videoConfig": {
					"source": "-re -i rtsp://192.168.3.105/live.sdp",
					"stillImageSource": "-i http://192.168.3.105/cgi-bin//viewer/video.jpg?resolution=640x480",
					"maxStreams": 1,
					"maxWidth": 640,
					"maxHeight": 480,
					"maxFPS": 12
				}
			},
			{
				"name": "Gate",
				"videoConfig": {
					"source": "-re -i rtsp://192.168.3.101/live.sdp",
					"stillImageSource": "-i http://192.168.3.101/cgi-bin//viewer/video.jpg?resolution=640x480",
					"maxStreams": 1,
					"maxWidth": 640,
					"maxHeight": 480,
					"maxFPS": 12
				}
			}
		]
	}],
	"accessories": [
{
	"accessory": "webostv",
	"name": "My webOS tv",
	"ip": "192.168.1.45",
	"mac": "78:5d:c8:53:b6:19",
	"keyFile": "/Users/bart/.homebridge/lgtvKeyFileX",
	"pollingInterval": 10,
	"inputs": [
			{
				"appId": "com.webos.app.livetv",
				"name": "Live TV"
			},
			{
				"appId": "com.webos.app.hdmi1",
				"name": "PS4"
			},
			{
				"appId": "youtube.leanback.v4",
				"name": "YouTube",
				"params":{
		"contentTarget": "https://www.youtube.com/tv?v=Bey4XXJAqS8"
				}
			},
			{
				"appId": "com.webos.app.photovideo",
				"name": "Photo Video"
			}
	],
	"showInputButtons": true,
	"volumeControl": "buttons",
	"channelControl": false,
	"mediaControl": false,
	"channelButtons": [3,5,7,8],
	"notificationButtons": [
		 "Motion detected - living room",
		 "Motion detected - kitchen"
	],
	"remoteControlButtons": [
		 "HOME",
		 "LIST",
		 "EXIT"
	],
	"soundOutputButtons": [
		 "tv_speaker",
		 "external_optical",
		 "headphone"
	],
	 "remoteSequenceButtons": [
			{
					"sequence": ["HOME","RIGHT","RIGHT","RIGHT","ENTER"],
					"name": "screen_share_seq"
			},
			{
					"sequence": ["VOLUMEUP","VOLUMEDOWN","MUTE","MUTE"],
					"name": "volume_seq",
					"interval": 1000
			}
	]
}
]
}

**Comment by deveylder** [comment]
<img width="592" alt="Schermafbeelding 2020-02-18 om 19 22 20" src="https://user-images.githubusercontent.com/31114918/74766031-dfac6780-5284-11ea-81a7-e9ded354bc36.png">

enclosed printscreen

**Comment by merdok** [comment]
Make sure you have all the settings enabled on your TV which are specified in the README. Also did the prompt pop up on your TV in which you need to confirm the connection?

**Comment by deveylder** [comment]
I did follow your readme file but you are correct I never had to confirm on the tv itself. My phone uw already (Leon DAPONTE app) connected and mobile access is enabled. I Will try to unregister the phone

**Comment by merdok** [comment]
Your ip or mac address could be wrong in that case. On your TV a confirmation popup needs to appear which you need to accept. Without this a connection cannot be established.

**Comment by deveylder** [comment]
I will double check something must be wrong. The strange thing is if I give a command with the remote I can see the instructions pop-up in the nmp monitor.

**Comment by merdok** [comment]
There is something for sure wrong with your setup. You would need to double check everything and make sure that the prompt appears on the tv which you then confirm.
