### ISSUE TITLE
”More Actions”-button (The 3 dots)

### ISSUE THREAD

**Issue by Rangvald** [merdok/homebridge-webos-tv#208]
I use the button next to 0 on the magic remote, 3 dots on it, to turn on and off my receiver. In the manual this button seems to be named ”More Actions”. I cant for the life of me figure out how to map this button in my config.

For the record, the receiver is old, no hdmi, using optical, and does not want to be powered on/off with the magic remote (volume works fine).

**Comment by merdok** [comment]
Sorry, i also do not know what the ID of that button is. This is basically try and error till something works. Maybe there is someway a way to intercept that to find it out more easier but i do not know any other´method...

**Comment by Rangvald** [comment]
Ah alright. I did find an ipk on lg dev page that tells you the number of the button, but not the name Unfortionally

**Comment by merdok** [comment]
Maybe it is not possible to trigger that button using the webos API, and this is only available with the remote?

**Comment by Rangvald** [comment]
I contacted LG in an attempt to find out. They said that they could not disclose what API Command this button sends. I read that as it is doable with API, but they dont want to Tell me what the Command is.

**Comment by merdok** [comment]
In that you would need to somehow find another way to get the correct button ID. You could continue to try out different names or do some sniffing.

**Comment by Rangvald** [comment]
Would you need the acctual name of it, or would the number work aswell? If numbers work I could basicly just do buttons for every number to 250 or whatever and Try them all.

**Comment by merdok** [comment]
This needs to be an ID as far as i know.
