### ISSUE TITLE
Volume as Lightbulb

### ISSUE THREAD

**Issue by siobhanellis** [merdok/homebridge-webos-tv#21]
Does HomeKit support Volume yet? It certainly has a speaker now.

Potentially how about using a dimmer switch, or make that an option?

You could use a dimmer switch to move between the inputs as well. e.g. 10% is one input, 20% another, etc etc.

Lastly, any chance we could have the option of just calling power "TV", or whatever we want? Closest I can get is "TV Power" 

Thanks v much.

**Comment by merdok** [comment]
As far as i know there is no Volume support yet in Homekit. Correct me if i am wrong, I was already looking at this but could not find anything.
I can have a look at the dimmer switch, that could work also good. Do you have an example of a dimmer switch UI in Homekit?

How you command to power on the TV is not controlled by me. It depends how you set it up in Homekit.

**Comment by siobhanellis** [comment]
There is support for a speaker in the HomeKit Accessory Protocol Specification. 9.29 defines a speaker, and part of that is Volume.

However, it seems that the Home App does not support it, but Eve can (BTW, I think EVE is a far superior interface)

When you say a good example of a dimmer switch UI in HomeKit, you mean screen shots?

**Comment by Dexwell** [comment]
I'm pretty sure that speaker support will be added to Home(Kit) with iOS 11.3, which also launches AirPlay 2.

**Comment by merdok** [comment]
Yes, that is what i meant. Homekit support speakers but the built in Home app for some reason doesn't support it...
I am also using the Eve app and i now that it has support for speakers but the goal is that my plugin works mainly on the Home app since this is what most people use and the integration with iOS is much better.

Yes, i mean a screenshot so i can see how it looks visually. 

@Dexwell hopefully... If that is the case then i can replace the Lightbulb with a speaker :)

**Comment by siobhanellis** [comment]
bugger! I looked at my one dimmer switch, and it looks like a light! Argh! BTW, someone else used a fan.

Another thought, though for switching between inputs, there is a programmable switch. Philip Hue Tap switch uses that. I can configure 4 buttons on that, but I see no way of hitting those buttons from Home App :-(

**Comment by merdok** [comment]
Fan and Light bulb are pretty much the same...

Yes, i know also know about the  programmable switch. I was investigating that, but like you already said you can't trigger the buttons from the Home app, this is only meant to do some actions on physical button press.

**Comment by Patrick-Ber** [comment]
Hello, i use this great plugin with my web os 3.5 device.
If i use the internal speaker , i can use the Volume Control
But if i choose my AV receiver on hdmi 2 for sound output, i can ´t use the volume control (only mute work). Is it possbile that i can use your plugin to control the sound if i use a external av receiver on hdmi2 ?

**Comment by merdok** [comment]
Hi,
thanks for the info. I will check out if i can reproduce this and fix this.

**Comment by Patrick-Ber** [comment]
Thank .. a another little problem. My tv ask me everytime i power on to allow that connect to the (lg) app. How can i fix this ?

**Comment by merdok** [comment]
This is written in the README:

> To prevent the tv from asking for permission when you reboot homebridge, specify a file path to store the permission token. If the file doesn't exist it'll be created. Don't specify a directory or you'll get an EISDIR error.

**Comment by Patrick-Ber** [comment]
Ahh .. that fix it :) ...

**Comment by w00master** [comment]
I have a "reverse" question re: the Volume button. Is there a way to remove it?  This is something that I wouldn't use as I drive the volume to my TV from my AVR.  I ask because since accessory in Homekit is considered a lightbulb, whenever I say: "Turn of all the lights in the Media room," Siri includes the volume / light button.

Thanks!

**Comment by merdok** [comment]
@w00master of course. Just add the **volumeControl** parameter to your homebridge configuration file and set it to **false** .

**Comment by w00master** [comment]
*slap forehead*  Thank you
