### ISSUE TITLE
Inputs problem with Hoobs.

### ISSUE THREAD

**Issue by ShapesOnShapes** [merdok/homebridge-webos-tv#211]
I'm trying to set this up with Hoobs. Can get the TV to show and respond in Home no problems, but when I try to edit the JSON to allow inputs, Netflix etc, I get a JSON error in Hoobs. I've contacted the developers and they've told me to ask directly if you've got any clues as to why? The JSON I'm writing is correct, no errors in Sublime when the whole text is pasted in, but it isn't accepted in HOOBS at all if I put in any type of input in, as it's written is below. 

[
{
	"name": "Live TV"
	"appId": "com.webos.app.livetv",
}
]

Any ideas?

**Comment by merdok** [comment]
This JSON which you posted above has an error in it. Properties should be comma separated and there should not be commas at the end.

**Comment by ShapesOnShapes** [comment]
Sorry, that was just an example. If using more than one I'd add the comma. I've just tried the "Live TV" one on its own with a comma and still getting the invalid JSON message.

**Comment by merdok** [comment]
Then you need to paste here your complete json.

**Comment by ShapesOnShapes** [comment]
`{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "-",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "-",
        "username": "-"
    },
    "description": "",
    "ports": {},
    "accessories": [
        {
            "accessory": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv",
                "index": 0
            },
            "name": "My LG TV",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "volumeLimit": 50,
            "channelControl": false,
            "mediaControl": false,
            "infoButtonAction": "INFO",
            "ip": "-",
            "mac": "-",
            "inputs": [
{
"name": "Live TV"
"appId": "com.webos.app.livetv",
}
],
            "remoteSequenceButtons": [],
            "channelButtons": [],
            "notificationButtons": [],
            "remoteControlButtons": [],
            "soundOutputButtons": []
        }
    ],
    "platforms": [
        {
            "platform": "Ikea Trådfri Gateway",
            "plugin_map": {
                "plugin_name": "ikea-tradfri"
            },
            "name": "Ikea Trådfri Gateway",
            "securityCode": "-",
            "host": "-"
        }
    ]
}`

Thanks for taking a look. This is it all, just dashed out any addresses for here. Only put live tv in there too, if I can get that working the rest should be ok!

**Comment by merdok** [comment]
So a [JSONvalidator](https://jsonformatter.curiousconcept.com/) tells you have errors there.

**Comment by ShapesOnShapes** [comment]
That it does! Any clues as to where I'm going wrong? Why is appId highlighted? What have I missed?

**Comment by merdok** [comment]
You have the error message there. There is no comma separating the properties...

**Comment by ShapesOnShapes** [comment]
Man, that's so annoying. The commas in the wrong place. I must have looked at it a hundred times and it not clicked. Thanks for help! All working now.
