### ISSUE TITLE
Provide variable to light/volume so it can be changed via Siri via variable number

### ISSUE THREAD

**Issue by mario** [merdok/homebridge-webos-tv#212]

**Comment by merdok** [comment]
Sorry, i do not understand what you mean?

**Comment by mario** [comment]
I'm using Siri shortcuts to be able to set the volume on my WebOS TV. So far this works by having three shortcuts:

- Set volume on TV to low
- Set volume on TV to medium
- Set volume on TV to high

It then triggers a change on the light via homebridge and sets it to 7/12/18, depending on what I invoke.

However, what I'd like to have is a shortcut that says:

- Set volume on TV to xyz

To do that, the lightning fixture must support a variable as an input.

Btw. you've done an awesome thing here - Homebridge WebOS integration supports way more things than just Homekit for this particular TV, and it's *really* new.

**Comment by merdok** [comment]
Still not sure what the issue is? You can simply ask Siri to change your volume to the desired level, there is no need for a variable.

Thanks 👍

**Comment by mario** [comment]
That's exactly the issue, I can't :)

- Asking: Hey Siri, set the TV volume to 10 gets a response of: That's beyond my abilities at the moment

On the other hand, telling Siri: Hey Siri, set lights to 10 actually sets the volume to 10 

(and yes, literally lights - because saying "TV lights" results in "You can only control one type of device at a time)

**Comment by merdok** [comment]
I think that you should use the new tv service. This sounds for me like you are using the old one where the volume was indeed controlled using lights.  Even is you use the old one, you just have to rename the volume switch to a more friendly name and then just tell Siri that name.

**Comment by mario** [comment]
Hm, I thought I already do. Would you be so kind to check the config to confirm?

>         {
>             "name": "LG TV",
>             "ip": "192.168.1.10",
>             "mac": "XX:XX:XX:XX:XX:XX",
>             "keyFile": "/home/homebridge/.webosTv/keyFile",
>             "prefsDir": "/home/homebridge/.webosTv",
>             "pollingInterval": 5,
>             "legacyTvService": false,
>             "showInputButtons": true,
>             "volumeControl": "slider",
>             "volumeLimit": 100,
>             "channelControl": true,
>             "mediaControl": false,
>             "inputs": [
>                 {
>                     "appId": "com.webos.app.livetv",
>                     "name": "Live TV"
>                 },
>                 {
>                     "appId": "youtube.leanback.v4",
>                     "name": "YouTube"
>                 },
>                 {
>                     "appId": "netflix",
>                     "name": "Netflix"
>                 }
>             ],
>             "infoButtonAction": "INFO",
>             "accessory": "webostv"
>         }

**Comment by merdok** [comment]
The volume control is only an addition, the new tv service has integrated volume control with the control center remote.

**Comment by mario** [comment]
OK, understand that - but is there something that I need to add to config to use it? I thought setting legacyTvService to false is enough?

**Comment by merdok** [comment]
It should work out of the box with native support from iOS.

**Comment by mario** [comment]
Well I do have the TV in the remote control center, but no volume controls there :-/ Let me investigate.

Thanks for your generous help.

**Comment by merdok** [comment]
Just use your volume up/down buttons from iPhone/iPad.

**Comment by mario** [comment]
Got it - that indeed works. Not with Siri though but at this point I'm sure it's just my fault :)
