### ISSUE TITLE
Stuck at prompt for confirmation....

### ISSUE THREAD

**Issue by Mikellas** [merdok/homebridge-webos-tv#213]
For some reason since yesterday my TVs except one,although seem available in homekit ,wont respond to any clicks.Homebridge keeps giving me to prompt for confirmation

Can someone assist?

**Comment by merdok** [comment]
Maybe permissions to your keyFile changed?

**Comment by Mikellas** [comment]
The thing is i never had that field included in my config file,and i also currently have one TV working perfectly.Is there something that im missing?

**Comment by Mikellas** [comment]
Config example(i have removed macaddress)

"accessories": [
        {
            "name": "Living Room TV",
            "ip": "192.168.88.248",
            "mac": ,
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "true",
            "volumeLimit": 100,
            "channelControl": true,
            "mediaControl": false,
            "remoteSequenceButtons": [
                {
                    "sequence": [],
                    "interval": 500
                }
            ],
            "infoButtonAction": "INFO",
            "accessory": "webostv"

**Comment by merdok** [comment]
I do not see any issues with your config. I do not think that this is an issue with the plugin, it has rather something to do with your environment.

**Comment by Mikellas** [comment]
I found the solution ,both tvs needed to be switched off entirely as they both didint prompt me to accept the connection,now all is good!Thanks for your help!

**Comment by merdok** [comment]
👍
