### ISSUE TITLE
Netflix button not working

### ISSUE THREAD

**Issue by Mikellas** [merdok/homebridge-webos-tv#214]
HI ,

I have been trying to make this work for a couple of days ,i itried different syntax at no success
Here are my inputs i only have a problem with Netflix though( I have already tried two ways)the one listed below and this com.webos.app.netflix.None of them seems to work

"inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "AppleTV"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "com.webos.app.photovideo",
                    "name": "Photo Video"
                },
                {
                    "appId": "Netflix",
                    "name": "Netflix"
                }
            ],

**Comment by merdok** [comment]
You need to find out the correct appId, and i am pretty sure that the appId is case sensitive...

**Comment by Mikellas** [comment]
Hi again,

Thanks for the help btw

This is what i get  from logs in homebridge when i run netflix  from the actual remote control
**[3/22/2020, 11:08:47 AM] [Bedroom TV] webOS - app launched, current appId: netflix**

Now i updated my code to be like this
**{
                    "appId": "netflix",
                    "name": "Netflix"
                }**

but still it wont work? 
It wont switch to netflix although  the restof the apps are fine(Youtube,appletv,livetv)

**Comment by merdok** [comment]
Seems like everything is fine. I am not using netflix so i have no idea what else might be wrong.
