### ISSUE TITLE
Adjust TV volume by siri

### ISSUE THREAD

**Issue by kennyevo** [merdok/homebridge-webos-tv#215]
I tried using the slider option for volumeControl, but can’t figure out how to adjust the volume dynamically and not setting fix values in shortcut.

Is there a way to do this?

**Comment by merdok** [comment]
Sorry, i do not understand your issue. What are you trying to achieve? 
As far as i know it is not possible to set TV volume using Siri.

**Comment by kennyevo** [comment]
It is possible to change a light bulb’s brightness by percent and since it shows up as a bulb with the slider option I thought it’s possible in some way.
I think it’s possible only with homekit accessories and not via a bridge.

2020. márc. 25. dátummal, 0:25 időpontban Marcin <notifications@github.com> írta:

**Comment by merdok** [comment]
Sorry, it is only possible to use what Siri supports.

**Comment by agneevX** [comment]
You could use Siri Shortcuts to achieve similar results.
