### ISSUE TITLE
webOS - Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by fluidof** [merdok/homebridge-webos-tv#216]
Hi all,
I received the following ETIMEDOUT error, could you pls help me to solve this issue?
Thanks

[2/4/2020, 16:32:28] [TV] webOS - Error: connect ETIMEDOUT 192.168.1.123:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.168.1.123',
  port: 3000
}

**Comment by merdok** [comment]
Does the plugin do not work anymore for you after you get the error?

**Comment by fluidof** [comment]
Plugin still work but in the home app says "not reachable". Then after a while it works again, but the error will happen again. Is it something related TV is going to sleep mode? Is there any option in the TV I have to search?

**Comment by merdok** [comment]
The error usually happens often when your network is not stable and for example your tv losses connection. Normally it can be ignored but if you have issues then you need to recheck your network.
