### ISSUE TITLE
Variable timeout for button sequence

### ISSUE THREAD

**Issue by rooi** [merdok/homebridge-webos-tv#217]
Hi Merdok,

Could you add the option to specify variable timeout when using button sequences?
I've suggest adding the following lines of code to allow both a single value as an array the matches the specified buttons with specific timeouts (@line 1513):

`if (seqObj.interval != undefined && Array.isArray(seqObj.interval)) {`
`if (seqObj.interval.length >= curRemoteKeyNum && isNaN(seqObj.interval[curRemoteKeyNum]) == false) {`
`tmpInterval = seqObj.interval[curRemoteKeyNum];`
`}`
`}`

Thx!

Roy

**Comment by merdok** [comment]
Sorry, i do not understand what your request is? You can already specify an interval which adds timeouts between button presses.

**Comment by rooi** [comment]
Hi,

Sorry about that, hopefully this explains ut better.

When the sequence gets larger, and especially when opening apps, some commands take longer than others. For example, when opening the music app, pressing OK takes significantly longer than navigating through the icons within the app after it opens.

I (mis)use the music app to turn of the screen while keeping the tv on. The sequence finds the music app, opens it, navigates to the sleep button and presses it. The slowest command takes about 2 seconds to complete. Most are fast, 0.5 seconds.

Without variable timeouts it will take x times 2 seconds to complete the seconds (>10 sec). With variable timeouts it will take x-1 times 0.5 seconds + 2 (4-5 seconds).

With the lines of code I you could specify the sequence normally, but also like this:

"sequence": ["VOLUMEUP","VOLUMEDOWN","MUTE","MUTE"],
"name": "volume_seq",
"interval": [500,500,2000,500] 

Roy

**Comment by merdok** [comment]
Makes and since you already provided some code i will check it out do some testing and if it works then i will add it :)

**Comment by merdok** [comment]
Included in version 1.6.5. Please try it out and let me know if it works!

**Comment by rooi** [comment]
Works great! Thanks!
