### ISSUE TITLE
[FEATURE] Eve App 4.2 Issue with homebridge-webos-tv

### ISSUE THREAD

**Issue by palasinio** [merdok/homebridge-webos-tv#218]
@merdok 
The lates Eve for HomeKit App v4.2 is causing issues with several Homebridge Plugins.
They changed something so that the serial number of a device is linked somehow in the background. This was not with previous Eve versions.
Problems causing now like described here.
homebridge/homebridge#2503
So all devices/switches from homebridge-ssh can't be sorted anymore and can't get an icon for each device separately.

Do you see a solution to fix this "Eve" Issue, by changing something in your plugin?

Thanks again for your work and the time you are investing generally.

**Comment by merdok** [comment]
The tv accessory already has a unique serial number, is that not enough?

**Comment by DJay-X** [comment]
It is looking good to me. I also use webos-tv Plugin and did not mention it in my main post.
Eve App 4.2 is not causing any problem with homebridge-webos-tv.
Al least not causing any issue in my scenario. Maybe @palasinio has another use case?

Thanks for your work @merdok and the time you are investing. Wouldn't want to miss your plugin.

![RPReplay_Final1587564010 2020-04-22 16_02_50](https://user-images.githubusercontent.com/3874239/79991893-13895080-84b3-11ea-9119-bf57b3baeaf6.gif)

**Comment by palasinio** [comment]
Hi, this is funny. I opened this ticket, because in my „Home“ app every accessory of this plugin has the same serial. In the Eve app I cannot see a single accessory of this plugin.

**Comment by merdok** [comment]
I always write the mac address of the tv as the serial number which should be unique. So if you added the same TV twice then of course those two accessories will have the same mac address, the question just would be why would you want to add twice the same accessory?

**Comment by DJay-X** [comment]
@palasinio I still would assume this is not an Issue of the Plugin. All good.

Eve App is showing things different than Apple Home App.
In the Home App you probably have just one tile including all other switches. See Video.
You have the option to separate them if you like.

![RPReplay_Final1587574637 2020-04-22 19_01_31](https://user-images.githubusercontent.com/3874239/80011136-b948b980-84cb-11ea-8303-1cdb029c0d8c.gif)


Anyway, the plugin is working with Eve App, even with the current Bug in Eve App.

**Comment by palasinio** [comment]
Okay - so I close this. Thank you very much. I messed up that one accessory can have more components. Why I can‘t see the WebOS accessory in EVE is a different thing.
