### ISSUE TITLE
Is Netcast also supported from this plugin ?

### ISSUE THREAD

**Issue by F3000** [merdok/homebridge-webos-tv#222]
I have version 03.11.33 installed

**Comment by merdok** [comment]
What do you exactly mean with Netcast?

**Comment by F3000** [comment]
@merdok  i have an LG TV 32LF5809-ZA

but I think it doesent have a right WebOS version .

But I can control my TV through other apps

**Comment by merdok** [comment]
Oh, this is unfortunately not supported. Your TV does not have webOS.
