### ISSUE TITLE
TVs disappear from Control Center remote

### ISSUE THREAD

**Issue by agneevX** [merdok/homebridge-webos-tv#223]
I have two TVs configured but none of them will show up in the Control Center remote but they show up in the Home app. 

I have removed and re-added the TVs but they show for a while and disappear randomly.

**Comment by merdok** [comment]
Did not experience anything like that, maybe someone else can help you...
Maybe there is something wrong with your homebridge installation?

**Comment by agneevX** [comment]
> Maybe there is something wrong with your homebridge installation?

No other issues anywhere, so I highly doubt that.

**Comment by agneevX** [comment]
Closing this until the issue occurs again...

**Comment by agneevX** [comment]
Issue still occurs. 

Remotes come and go. Removing from the Home app and readdding seems to be a temporary solution.

**Comment by merdok** [comment]
I am pretty certain this issue is not related to the plugin. It has most likely something to do with your setup.

**Comment by agneevX** [comment]
Not sure if related, but both TVs show this, because they're not powered:
```
[5/5/2020, 13:22:46] [webostv] webOS - Error: connect EHOSTUNREACH 10.0.0.63:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.0.0.63',
  port: 3000
}
[5/5/2020, 13:22:46] [webostv] webOS - Error: connect EHOSTUNREACH 10.0.0.62:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'EHOSTUNREACH',
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '10.0.0.62',
  port: 3000
}
```

Yet I'm only able to add one of the TVs to HomeKit.

**Comment by merdok** [comment]
Should not be an issue. I guess this comes up when the connection is lost.

**Comment by LeoSunSET** [comment]
I've experiencing the same behavior even with the TV on.
I couldn't relate any cause so far.

**Comment by merdok** [comment]
Like i said this should not be issue, it might sometimes pop up.

**Comment by merdok** [comment]
Is the issue still present?

**Comment by agneevX** [comment]
Well now I can't even add the TVs to the Home app :(

**Comment by merdok** [comment]
Your Home app or homebridge installation might be messed up. I would recommend to reset everything and start from scratch. You should make sure that all your dependencies are up to date.

**Comment by merdok** [comment]
@agneevX did you manually remove the TV from the Home app and now you are not able to add it anymore? Could you try to create a new home in the Home app and add it there, if that works?

**Comment by kkirby** [comment]
Yeah, same problem here. When I installed the plugin it worked great for a few days and now it won't show up in the control center remote. If I go to the Home app and open the settings for the TV it sometimes shows up in the remote, but not always. Not sure what's going on.

**Comment by merdok** [comment]
You would need to give me some specifics here, i need to be able to reproduce the issue in order to fix it or to find a solution for that. I mean there must be something in your setup which is causing this. Does the TV still appear in the log even when it doe snot appear in the home app?

**Comment by kkirby** [comment]
@merdok So the TV appears in the Home app. It does not appear in the control center remote. When I go to the Home app I can power the TV on/off and change the input. The TV appears in the HomeBridge log and shows status updates accordingly.

It just doesn't show up in the control center remote.

### Log

```
[6/21/2020, 10:14:56 AM] [webostv] [LG TV] App launched, current appId: com.webos.app.hdmi2
[6/21/2020, 10:14:56 AM] [webostv] [LG TV] Audio status changed
[6/21/2020, 10:14:56 AM] [webostv] [LG TV] Current volume: 9
[6/21/2020, 10:14:56 AM] [webostv] [LG TV] Muted: No
[6/21/2020, 10:15:34 AM] [webostv] [LG TV] Audio status changed
[6/21/2020, 10:15:34 AM] [webostv] [LG TV] Current volume: 8
[6/21/2020, 10:15:34 AM] [webostv] [LG TV] Muted: No
[6/21/2020, 10:15:34 AM] [webostv] [LG TV] Audio status changed
[6/21/2020, 10:15:34 AM] [webostv] [LG TV] Current volume: 7
[6/21/2020, 10:15:34 AM] [webostv] [LG TV] Muted: No
[6/21/2020, 10:15:35 AM] [webostv] [LG TV] Audio status changed
[6/21/2020, 10:15:35 AM] [webostv] [LG TV] Current volume: 8
[6/21/2020, 10:15:35 AM] [webostv] [LG TV] Muted: No
```

### Homebridge config

```
{
    "bridge": {
        "name": "Homebridge 1DAD",
        "username": "0E:9B:C4:76:1D:AD",
        "port": 51636,
        "pin": "925-03-608"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "LG TV",
                    "ip": "10.0.1.109",
                    "mac": "14:C9:13:DB:48:F3",
                    "prefsDir": "/var/lib/homebridge/webOSTV",
                    "pollingInterval": 5,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "slider",
                    "volumeLimit": 100,
                    "channelControl": false,
                    "mediaControl": false,
                    "infoButtonAction": "INFO",
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "BluRay Player"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "SHIELD"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "HDMI3"
                        },
                        {
                            "appId": "com.webos.app.externalinput.av1",
                            "name": "AV"
                        },
                        {
                            "appId": "com.webos.app.externalinput.component",
                            "name": "Component"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        },
        {
            "name": "UniFi Protect",
            "videoProcessor": "ffmpeg",
            "debugProtect": false,
            "controllers": [
                {
                    "url": "https://10.0.1.2:7443",
                    "username": "homebridge",
                    "password": "homebridge"
                }
            ],
            "videoConfig": {
                "sourcePrefix": "-re -rtsp_transport tcp",
                "additionalCommandline": "-preset slow -profile:v high -level 4.2 -x264-params intra-refresh=1:bframes=0",
                "mapaudio": "0:0",
                "mapvideo": "0:1",
                "maxStreams": 4,
                "maxWidth": 1920,
                "maxHeight": 1080,
                "maxFPS": 20,
                "packetSize": 564,
                "audio": false
            },
            "platform": "Camera-UniFi-Protect"
        }
    ]
}
```

### Homebridge Plugins

```
homebridge-webos-tv v1.8.9
homebridge-config-ui-x v4.23.0
homebridge-unifi-protect2 v1.3.5
```

**Comment by merdok** [comment]
@kkirby thanks, but you would need to post some debug log, ideally from the moment when you try to open the control center remote. We would need to check if anything popups up then.

**Comment by thehauntedmattress** [comment]
This is the [same issue](https://github.com/merdok/homebridge-webos-tv/issues/134) that I was having a year ago.

**Comment by merdok** [comment]
@thehauntedmattress do you still have the issue? If yes, could you post some debug log, ideally a full log from the start so i can see if there is something happening during initialization?

**Comment by thehauntedmattress** [comment]
Yeah I updated last night, and all the accessories disappeared.  Can you tell me how to do a debug again?

**Comment by merdok** [comment]
I think that this issue is very unlikely being related to the plugin itself. I suppose it is more of a local problem, but it would be still good to find out why it is happening.

See [README](https://github.com/merdok/homebridge-webos-tv#troubleshooting) on how to debug.

**Comment by thehauntedmattress** [comment]
Right now it's being stable.  But I'm wondering how long it will be before it goes away again.  I am having the exact same problem with the Tizen plugin.

**Comment by merdok** [comment]
That you have the exact same issue with the Tizen plugin should already be an indication that it is related to something local. 
BTW: i just setup a discord channel to discuss such issues easily so anyone who is using discord feel free to join:
 [homebridge-webos-tv](https://discord.gg/S2GxwQ)

**Comment by thehauntedmattress** [comment]
So with Tizen, the person updated it so that the TV is it's own accessory that you add instead of part of the bridge.  So I just added it as such.  Seems stable so far.  Hopefully it stays.  Right now both appear to be stable and still show up in the Home app.

**Comment by merdok** [comment]
So right now it is working?

**Comment by thehauntedmattress** [comment]
Appears to be yes.

**Comment by thehauntedmattress** [comment]
Nevermind.  Both TVs just disappeared again.  Uggh.

**Comment by merdok** [comment]
Well, so you can post the full debug log so i can at least have a look if there is something in there...

**Comment by agneevX** [comment]
Yeah I'm seeing similar things here. Homebridge Config UI X is showing the TV as on and in the correct Input. Says `No Response` in the Home app. I deleted it and I can no longer add it. 

Not sure if its related but I think this issue maybe related to adding a second TV (which I can add). 

Seems too complex to solve tbh

**Comment by merdok** [comment]
Might also be possible that the Home is messed up. Did anyone of you tried to create a new Home temporary and add the TV there?

**Comment by thehauntedmattress** [comment]
I just nuked my entire home setup.  I also finally added the WebOS TV as a platform instead of an accessory.  So now it shows up separately from the Homebridge bridge.  See how long this one lasts.

**Comment by agneevX** [comment]
> Might also be possible that the Home is messed up. Did anyone of you tried to create a new Home temporary and add the TV there?

I tried adding it to a new Home, but it did not show up there either.

**Comment by thehauntedmattress** [comment]
@merdok it's been more than 24 hours and both TVs are still in HomeKit.  This means that everything is working, so I am squared away!  I think updating and redoing my config helped.  Thanks again for your help.

**Comment by merdok** [comment]
Sounds good! Thanks for the info👍🏻

**Comment by martonky** [comment]
Hi guys, I did an update to v1.9.1, change config.json from accessory to platform and I am not seeing LG TV at Homekit. For your information, I can remote LG TV via homebridge-config-ui-x v4.23.2. That is work.

**Comment by merdok** [comment]
Hi,

there is an extra step required when adding a tv as a platform. Please check the README for more details.
