### ISSUE TITLE
sound outputl: undefined

### ISSUE THREAD

**Issue by Ufocultist** [merdok/homebridge-webos-tv#224]
Hello
I have an error in the log:
webOS - TV current sound outputl: undefined
Running homebridge in debug gives no clues. I tried to change sound output in tv settings but nothing in homebridge log.

**Comment by merdok** [comment]
What TV? Does changing sound output using the the plugin work?

**Comment by Ufocultist** [comment]
No, changing sound with plugin not work
{
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "features": {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     "3d": true,
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     "dvr": false
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "receiverType": "dvb",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "modelName": "50LB653V-ZK"
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: }
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: [Fri Apr 24 2020 19:52:22 GMT+0400 (+04)] [My webOS tv] webOS - tv info file already exists, not saving!
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: [Fri Apr 24 2020 19:52:22 GMT+0400 (+04)] [My webOS tv] webOS - sw information:
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "product_name": "webOS",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "model_name": "HE_DTV_WT1M_AFAAABAA",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "sw_type": "FIRMWARE",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "major_ver": "05",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "minor_ver": "05.70",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "country": "UA",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "device_id": "3c:cd:93:c5:a5:e0",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "auth_flag": "N",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "ignore_disable": "N",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "eco_info": "01",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "config_key": "00",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "language_code": "ru-RU"
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: }
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: [Fri Apr 24 2020 19:52:22 GMT+0400 (+04)] [My webOS tv] webOS - service list:
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   "services": [
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "api",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "audio",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "media.controls",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "media.viewer",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "pairing",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "system",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "system.launcher",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "system.notifications",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "tv",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 1
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     },
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     {
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "name": "webapp",
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:       "version": 2
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:     }
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]:   ]
Fri Apr 24 19:52:22 2020 daemon.info homebridge[3802]: }

**Comment by merdok** [comment]
Your TV is a webOS1 TV which is not officially supported so not everything might work...
