### ISSUE TITLE
Can't seem to get this working as a platform.

### ISSUE THREAD

**Issue by creinhart** [merdok/homebridge-webos-tv#225]
Using the platform sample code, but every time I add my bridge to Homekit, it says "Additional Setup Required". And going back into "Add Accessories" doesn't show anything. Not sure what I'm doing wrong.

{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3F:E3:BE:32",
    "manufacturer": "homebridge.io",
    "model": "homebridge",
    "port": 51826,
    "pin": "061-25-192"
  },

  
  "platform": "webostv",
  "devices": [
    {
      "name": "My webOS tv",
      "ip": "192.168.33.112",
      "mac": "20:3D:BD:FA:A4:E0",
      "pollingInterval": 10,
      "inputs": [
        {
          "appId": "com.webos.app.livetv",
          "name": "Live TV"
        },
        {
          "appId": "com.webos.app.hdmi1",
          "name": "PS4"
        },
        {
          "appId": "youtube.leanback.v4",
          "name": "YouTube",
          "params": {
            "contentTarget": "https://www.youtube.com/tv?v=Bey4XXJAqS8"
          }
        }
      ],
      "showInputButtons": true,
      "volumeControl": "buttons",
      "channelControl": false,
      "mediaControl": false,
      "channelButtons": [
        3,
        5,
        7
      ],
      "notificationButtons": [
        "Motion detected - living room",
        "Motion detected - kitchen"
      ],
      "remoteControlButtons": [
        "HOME",
        "EXIT"
      ],
      "soundOutputButtons": [
        "tv_speaker",
        "external_optical",
        "headphone"
      ],
      "remoteSequenceButtons": [
        {
          "sequence": [
            "HOME",
            "RIGHT",
            "RIGHT",
            "RIGHT",
            "ENTER"
          ],
          "name": "screen_share_seq"
        },
        {
          "sequence": [
            "VOLUMEUP",
            "VOLUMEDOWN",
            "MUTE",
            "MUTE"
          ],
          "name": "volume_seq",
          "interval": 1000
        }
      ]
    }
  ]
}

**Comment by gussyboy** [comment]
I'm having the exact same problem, I'm using the latest version of Homebridge (1.0.0) and latest of 
homebridge-webos-tv (1.7.1)

I believe my config to be right;

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "Homebridge for Homekit.",

    "accessories": [],

    "platform": "webostv",
    "devices": [
        {
            "name": "My webOS tv",
            "ip": "192.168.1.109",
            "mac": "14:c9:13:30:6c:97",
            "keyFile": "/homebridge/lgtvKeyFile",
            "pollingInterval": 10,
            "inputs": [
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Foxtel"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Apple TV"
                }
            ],
            "showInputButtons": false,
            "volumeControl": false,
            "channelControl": false,
            "mediaControl": false
        },
        {
            "name": "My webOS tv",
            "ip": "192.168.1.124",
            "mac": "38:8c:50:c8:6a:38",
            "keyFile": "/homebridge/lgtvKeyFile2",
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "Apple TV"
                }
            ],
            "showInputButtons": false,
            "volumeControl": false,
            "channelControl": false,
            "mediaControl": false
        }
    ]
}
```

Its worth pointing out in the 'oznu-homebridge' terminal window the last message is `Homebridge is running on port 51826` so its as if the webOS package doesn't even startup.

**Comment by grzegorz914** [comment]
Your config is wrong, "platform" must be inside "platforms": []

```
"platforms": [
    {
        "platform": "webostv",
        "devices": [
            {
                "name": "My webOS tv",
                "ip": "192.168.1.109",
                "mac": "14:c9:13:30:6c:97",
                "keyFile": "/homebridge/lgtvKeyFile",
                "pollingInterval": 10,
                "inputs": [
                    {
                        "appId": "com.webos.app.hdmi1",
                        "name": "Foxtel"
                    },
                    {
                        "appId": "com.webos.app.hdmi2",
                        "name": "Apple TV"
                    }
                ],
                "showInputButtons": false,
                "volumeControl": false,
                "channelControl": false,
                "mediaControl": false
            },
            {
                "name": "My webOS tv",
                "ip": "192.168.1.124",
                "mac": "38:8c:50:c8:6a:38",
                "keyFile": "/homebridge/lgtvKeyFile2",
                "inputs": [
                    {
                        "appId": "com.webos.app.livetv",
                        "name": "Live TV"
                    },
                    {
                        "appId": "com.webos.app.hdmi1",
                        "name": "Apple TV"
                    }
                ],
                "showInputButtons": false,
                "volumeControl": false,
                "channelControl": false,
                "mediaControl": false
            }
        ]
    }
]
```

**Comment by gussyboy** [comment]
> Your config is wrong, "platform" must be inside "platforms": []

Thanks for point out the obvious mistake, its all working now its all sitting the right array. Thanks

**Comment by creinhart** [comment]
Thanks!

**Comment by merdok** [comment]
Oh, maybe i should make the example more clear!
