### ISSUE TITLE
Question: What is the big button at the bottom

### ISSUE THREAD

**Issue by Tobix99** [merdok/homebridge-webos-tv#229]
Hey,
short Question: I've added my LGWebOS TV via this plugin to HomeKit, but there is a big square button at the bottom, which has to horizontal lines in the middle and does nothing when I press it.

Thank you for developing this excellent plugin.

**Comment by merdok** [comment]
Sorry, i have no idea what you are talking about. Could you please post a screenshot?

**Comment by Tobix99** [comment]
Sorry,
of course (should have done this in the first place).

![IMG_4327](https://user-images.githubusercontent.com/22603015/80678240-d88eaa80-8aba-11ea-8f6c-f401995ae31d.jpeg)

The left top one is the power button and the right one is the volume slider.

**Comment by merdok** [comment]
This is not a switch, it is the input selection item. Since i am guessing you have no inputs defined, this control will be empty.
