### ISSUE TITLE
homebridge - CC Remote and 2 TV (or more) 

### ISSUE THREAD

**Issue by tomcruces** [merdok/homebridge-webos-tv#233]
Hi, 

I have a issue with my CC (control center) Remote, because I can only watch a single TV in the app.

Do you have any idea how to solve it?

I have a homebridge (Hoobs) and this is my config.json

"accessories": [
        {
            "accessory": "webostv",
            "name": "TV Pieza",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "slider",
            "volumeLimit": 100,
            "channelControl": false,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                }
            ],
            "infoButtonAction": "INFO",
            "ip": "X.X.X.X",
            "mac": "X:X:X:X:X:X",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv",
                "index": 0
            }
        }
    ],
    "platforms": [
        {
            "platform": "BraviaPlatform",
            "tvs": [
                {
                    "name": "TV Sala",
                    "cookiepath": "/home/hoobs/.sonycookie",
                    "ip": "X.X.X.X",
                    "soundoutput": "speaker",
                    "tvsource": "tv:dvbc",
                    "applications": [
                        {
                            "title": "Netflix"
                        },
                        {
                            "title": "Prime Video"
                        },
                        {
                            "title": "Spotify"
                        },
                        {
                            "title": "YouTube"
                        }
                    ],
                    "sources": [
                        "extInput:hdmi",
                        "extInput:cec"
![D3173FB0-CF67-4859-919A-A66F89512F8A](https://user-images.githubusercontent.com/63136803/81578647-19b77200-9379-11ea-98ad-ea919584a7bd.png)

**Comment by merdok** [comment]
You have to configure your LG TV to use **platform** and not accessory (which you are using). Platform is the new recommended way to use this plugin. Accessory will still work, but it only makes sense if you have 1 TV.

**Comment by tomcruces** [comment]
Thank you @merdok , I added the tv on the platform and delete it on accessories, But now I don't watch television in my house app.

Could you help me with this?

    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "Tele Pieza",
                    "ip": "X.X .X.X",
                    "mac": "X:X:X:X:X:X",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 10,
                    "volumeLimit": 100,
                    "inputs": [
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "YouTube"
                        }
                    ],
                    "notificationButtons": [
                        "Movimiento detectado - Cocina"
                    ],
                    "remoteControlButtons": [
                        "HOME",

**Comment by tomcruces** [comment]
I fixed it and it worked !! Thank you!
