### ISSUE TITLE
Does not detect CEC "sub"-inputs

### ISSUE THREAD

**Issue by bwt615** [merdok/homebridge-webos-tv#234]
I have a Denon receiver. My TV detects/can change the inputs on the receiver. Both are listed under HDMI 1 as "sub inputs". When changing to these there is nothing recorded in the homebridge log. Can these inputs be switched to?

**Comment by merdok** [comment]
I do not think that this is possible. I guess those are inputs which the receiver sends to the tv but for the TV only the HDMI1 is a valid input.

**Comment by bwt615** [comment]
You’re closing this on the basis that you “think”?

**Comment by merdok** [comment]
I am closing this on a basis i "know"

**Comment by bwt615** [comment]
You don’t think you could emulate with key presses or something?
On May 17, 2020, 1:27 PM -0400, Marcin <notifications@github.com>, wrote:

I am closing this on a basis i "know"

**Comment by merdok** [comment]
You could emulate that with key presses by yourself, just a `sequence` for that.
