### ISSUE TITLE
BROKEN: Config schema

### ISSUE THREAD

**Issue by rpmartinez3** [merdok/homebridge-webos-tv#235]
Hi, your latest update broken the config Schema.

I’ve tried uninstalling and reinstalling the plugin but that did not resolve the problem.

Please help. Thanks

**Comment by merdok** [comment]
The config schema broke for you because now the recommend way of using the plugin is a platform and not accessory anymore. That is why i adjusted the config schema to work with a platform. You would need to switch your tv in the config json form accessory to a platform. 
This painless and can be done within seconds :)

**Comment by rpmartinez3** [comment]
I deleted the plugin and reinstalled it to see if that would fix the issue. What do I need to change to the following code Inorder to make it a platform?

},
            "name": "LG OLED TV",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "false",
            "channelControl": false,
            "mediaControl": false,
            "ip": "10.0.0.51",
            "mac": "xx:xx:xx:xx:xx:xx,
            "volumeLimit": 100,
            "infoButtonAction": "INFO"
        }

**Comment by merdok** [comment]
You do not have to delete or reinstall anything. Just check the README for an example config on how to use it as a platform.

**Comment by rpmartinez3** [comment]
What I’m saying is that I deleted it and re installed to see if that fixed it before posting on here. I’ll read the read me thanks

**Comment by merdok** [comment]
Is this issue solved?
