### ISSUE TITLE
Notification service title - bad character

### ISSUE THREAD

**Issue by mrdan** [merdok/homebridge-webos-tv#237]
When setting a notification button, it just shows up named 'Switch' in the home app. However, when I clear that I can seem (dimmed) that the name it was trying to use was "<My Tv Name> Notification: <Button name>". If I try to type that out, I get an error so it looks like the home app can't handle a `:` in the switch name.

I suggest changing the character to `-`, as the app did accept this

**Comment by merdok** [comment]
You are right. What is strange is that when you setup the tv as an accessory then it works, but when you do it as a platform then it does not...  Will check it out! 
Did you try with the `-` character and it works?

**Comment by mrdan** [comment]
Yes, `-` worked in the title for me

**Comment by merdok** [comment]
Hmm, just tried it out, but the switch is still shown with the name "Switch" even when using `-`. No idea what the issue is here. Some switches are shown as "Switch" but some have the name...

**Comment by merdok** [comment]
Replaced `:` with `-` in version 1.8.2 hopefully that fixes the issue.
