### ISSUE TITLE
error message at startup The accessory 'Telly' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set.

### ISSUE THREAD

**Issue by siobhanellis** [merdok/homebridge-webos-tv#238]
[5/23/2020, 12:39:58 AM] [webostv] webOS - init - initializing device with name: Telly
HAP-NodeJS WARNING: The accessory 'Telly' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!

It does seem to work OK though.

Homebridge V1.1.0

Here's my config

       {
            "devices": [
                {
                    "name": "Telly",
                    "ip": "192.168.1.28",
                    "mac": "38:8C:50:12:9E:42",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 5,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "false",
                    "volumeLimit": 100,
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Amplifier"
                        },
                        {
                            "appId": "com.webos.app.miracast",
                            "name": "Screen Share"
                        }
                    ],
                    "infoButtonAction": "INFO"
                }
            ],
            "platform": "webostv"
        }

**Comment by merdok** [comment]
Hi,
thanks for reporting. This will be fixed in the next release.
