### ISSUE TITLE
Slider volume control not working

### ISSUE THREAD

**Issue by iamkedzia** [merdok/homebridge-webos-tv#240]
Hi! Than you so much for overall great plugin. I'm unable to control my TV's (55B7) volume with the slider (bulb) function. It only works with buttons. My TV is connected to the soundbar via ARC. Do you guys have any solution for this?

**Comment by merdok** [comment]
Hi,
the volume slider cannot be used when controlling an ARC sound device is connected. Actually the buttons were introduced because of that issue. I think at this point i should include that in the README...

Sorry, this is a limitation from webos.
