### ISSUE TITLE
Channel buttons don't work

### ISSUE THREAD

**Issue by Hussamfhaily** [merdok/homebridge-webos-tv#241]
Hi. Channel service works well. I can go up or down but when I want to go to a specific channel, that doesn't work. Although the channel button changes automatically by going up or down.

**Comment by merdok** [comment]
Sorry, could you be more specific? And could you please include your config.json? Also did you check the debug log when trying to use the buttons?

**Comment by Hussamfhaily** [comment]
Thanks for your quick reply. The channel up and down buttons work well. The Channel button doesn't work. In log file clicking the channel up or down button prints channel info. But clicking the channel button doesn't give any info. Here is my config file:
{
            "devices": [
                {
                    "name": "Power",
                    "ip": "xxxxx",
                    "mac": "xxxxx",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 5,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "slider",
                    "volumeLimit": 100,
                    "channelControl": true,
                    "mediaControl": false,
                    "channelButtons": [
                        1,
                        2,
                        3
                    ],
                    "inputs": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Chromecast"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "YouTube"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "PS4"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "Pi"
                        },
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        }
                    ],
                    "notificationButtons": [
                        "Balkontür geöffnet"
                    ],
                    "remoteControlButtons": [
                        "MUTE",
                        "VOLUMEUP",
                        "VOLUMEDOWN",
                        "MENU",
                        "UP",
                        "DOWN",
                        "LEFT",
                        "RIGHT",
                        "BACK",
                        "EXIT",
                        "ENTER",
                        "PLAY",
                        "PAUSE",
                        "REWIND",
                        "FASTFORWARD"
                    ],
                    "remoteSequenceButtons": [],
                    "infoButtonAction": "INFO"
                }
            ],
            "platform": "webostv"
        }
    ],
    "id": "config"

**Comment by merdok** [comment]
Your config looks ok. I suspect that you have an old TV where switching to a channel per channel number is not possible. Can you tell me what TV do you have and webos version it is running?

**Comment by Hussamfhaily** [comment]
My TV is LG webOS TV LF6309. I think it is WebOS 2. By using 3rd party iOS app like LG TV Plus I can choose the channel directly.

**Comment by merdok** [comment]
Yes, so your TV does not support switching channels by channel number, it can only switch channels by the channel id. 
Unfortunately for now you cannot use the channel button service. I might add switching by channel id in a future release.

**Comment by Hussamfhaily** [comment]
Ok. Thank you very much for your valuable work.

**Comment by merdok** [comment]
Hi, 
can you do me a favor? Could you start homebridge with debug log enabled and then switch a channel on your remote control? In the console you should see something like: 
`Current channel status changed`
and below that should be info like channel name id and number. Could you post that debug log here?

**Comment by Hussamfhaily** [comment]
Hi, Sorry, I have seen your request today. Would you like me to do this yet?

**Comment by merdok** [comment]
Yes, that would be good.

**Comment by Hussamfhaily** [comment]
I can't add the TV to the Home App. I get this message:
[5/26/2020, 12:32:51] [webostv] [Power] TV channel status - error while getting current channel status
[5/26/2020, 12:32:51] [webostv] [Power] Error message: No information

**Comment by Hussamfhaily** [comment]
I did Homebridge reset then it worked. I got this info:
[5/26/2020, 12:49:24] [webostv] [Power] Current channel status changed
[5/26/2020, 12:49:24] [webostv] [Power] Current channel: 22, Sonnenklar TV, channelId: 3_5_22_0_33_32_133
[5/26/2020, 12:49:31] [webostv] [Power] Current channel status changed
[5/26/2020, 12:49:31] [webostv] [Power] Current channel: 21, Pro7 MAXX, channelId: 3_4_21_0_1107_17505_1
[5/26/2020, 12:49:36] [webostv] [Power] Current channel status changed
[5/26/2020, 12:49:36] [webostv] [Power] Current channel: 20, SAT.1 Gold, channelId: 3_4_20_0_1107_17504_1
[5/26/2020, 12:49:38] [webostv] [Power] Current channel status changed
[5/26/2020, 12:49:38] [webostv] [Power] Current channel: 12, SUPER RTL, channelId: 3_3_12_0_1089_12040_1
[5/26/2020, 12:49:41] [webostv] [Power] Current channel status changed
[5/26/2020, 12:49:41] [webostv] [Power] Current channel: 11, RTL2, channelId: 3_3_11_0_1089_12020_1

**Comment by Hussamfhaily** [comment]
When I try to change the channel through a button I get this:
[5/26/2020, 12:57:54] [webostv] [Power] Open channel - error while switching channel
[5/26/2020, 12:57:54] [webostv] [Power] Error message: db: no index for query
[5/26/2020, 12:57:54] [webostv] [Power] TV current channel: 9, phoenix, channelId: 3_2_9_0_1051_28725_1

**Comment by merdok** [comment]
Cool thanks, so as of version 1.8.2 you should be able to switch channels, just take note of the channelId which you see in the log for the channel and it to to channelButtons config. After that you should able to switch channels. Let me know if that works.

**Comment by Hussamfhaily** [comment]
I have done so already but it didn't work. I get this info while I try to change the channel.
[5/26/2020, 12:57:54] [webostv] [Power] Open channel - error while switching channel
[5/26/2020, 12:57:54] [webostv] [Power] Error message: db: no index for query
[5/26/2020, 12:57:54] [webostv] [Power] TV current channel: 9, phoenix, channelId: 3_2_9_0_1051_28725_1

**Comment by merdok** [comment]
Can you show me your config?

**Comment by Hussamfhaily** [comment]
{
    "bridge": {
        "name": "Homebridge CA5D",
        "username": "xxxxxxxx",
        "port": xxxxx,
        "pin": "xxxxxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": xxxxx,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Power",
                    "ip": "xxxxxx",
                    "mac": "xxxxxx",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 5,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "true",
                    "volumeLimit": 100,
                    "channelControl": true,
                    "mediaControl": false,
                    "channelButtons": [
                        "3_2_8_0_1051_28724_1",
                        "3_2_7_0_1051_28722_1"
                    ],
                    "remoteControlButtons": [
                        "VOLUMEUP",
                        "VOLUMEDOWN"
                    ],
                    "infoButtonAction": "INFO"
                }
            ],
            "platform": "webostv"
        }
    ]
}

**Comment by Hussamfhaily** [comment]
[Power] Channel button service - switching to channel number: 3_2_7_0_1051_28722_1, id: null
[Power] Open channel - error while switching channel
[Power] Error message: db: no index for query
[Power] TV current channel: 10, RTL Television, channelId: 3_3_10_0_1089_12003_1
[Power] TV current channel: 10, RTL Television, channelId: 3_3_10_0_1089_12003_1
[Power] TV current channel: 10, RTL Television, channelId: 3_3_10_0_1089_12003_1

**Comment by merdok** [comment]
Yeah, that is wrong.
`channelNumber` is mandatory, but you can enter a fake one if you want (in that case the button will not show a status), so i highly recommend putting there the real channel number.
`channelId` is what you have to set to make actually work for you
`channelName` is what the switch will be called, if you leave it empty then the name will be auto generated based on the channel number


channelButtons needs to look like that:
```

   "channelButtons":[
      {
         "channelNumber":"13",
         "channelId":"3_2_8_0_1051_28724_1",
         "channelName":"Some optional channel name"
      },
      {
         "channelNumber":"24",
         "channelId":"3_2_7_0_1051_28722_1",
         "channelName":"Some optional channel name"
      }
   ]

```

Let me know if that works.

**Comment by Hussamfhaily** [comment]
Ok. It works this way, I can change the channel by pressing the button. Thank you. Why can't I add the TV to Home App. I have tried to add it as a bridge manually using the Homebridge Pin, but the App doesn't see the TV.

**Comment by merdok** [comment]
Glad that the channel buttons work now.

Did you check the homebridge debug log?

**Comment by Hussamfhaily** [comment]
I am trying to install the Homebridge and the plugin on a new SD card. Thank you very much. You are doing great work.
