### ISSUE TITLE
Add device to Home app

### ISSUE THREAD

**Issue by elkorleone** [merdok/homebridge-webos-tv#244]
I just upload the plugin to latest version and it changes the device from accessories to platforms
it still works fine more or less... but I dont find my tv in Home app (or Eve app)
where is the device now???

**Comment by merdok** [comment]
When adding a device as a platform there are some additional steps required: [Adding the TV to Home app](https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-home-app)

**Comment by elkorleone** [comment]
I tried
doesn't appear

**Comment by elkorleone** [comment]
config

> {
            "devices": [
                {
                    "name": "My LG TV",
                    "ip": "192.168.1.106",
                    "mac": "38:8c:50:f4:77:86",
                    "keyFile": "/homebridge/lgtvKeyFile.txt",
                    "prefsDir": "~/.webosTv",
                    "pollingInterval": 30,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "true",
                    "volumeLimit": 100,
                    "channelControl": false,
                    "mediaControl": false,
                    "remoteSequenceButtons": [
                        {
                            "sequence": []
                        }
                    ],
                    "infoButtonAction": "INFO"
                }
            ],
            "platform": "webostv"
        }

**Comment by merdok** [comment]
Check the homebridge debug log. There should be written what is happening.

**Comment by elkorleone** [comment]
in red:

[My LG TV] Error occured, could not write TV info [Error: ENOENT: no such file or directory, open '~/.webosTv/info_388c50f47786'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/.webosTv/info_388c50f47786'
}
[webostv] [My LG TV] Error message: internal error

**Comment by merdok** [comment]
Someone already had this issue, this has something to do with homebridge permissions. Try to reinstall homebridge or the plugin.

**Comment by elkorleone** [comment]
no way
key file should be the directory or the file
last config was "keyFile": "/homebridge/lgtvKeyFile.txt"
but now it ask for directory, not file....

**Comment by merdok** [comment]
As specified in the README it is a file. This has something to do with the permissions of your homebridge instance.
