### ISSUE TITLE
Any tips for controlling volume with Siri?

### ISSUE THREAD

**Issue by realdannys** [merdok/homebridge-webos-tv#246]
I'm not sure if my naming conventions are breaking things but I have a rough time getting Siri to do anything with the TV volume.

It's inconsistent in that "set TV volume to 10" will work once and then not work the next ten times you try it!

Sometimes 10% works other times it doesn't

Sometimes "dim" works where "set" one, so I can say "Dim volume to 10%" and it'll work - other times Homepod gets mixed up with it's own volume and no matter what you say it won't change volume.

I'd have thought whatever you named the TV + volume, would have made it clear you want to control the light slider, but then I also guess it sees it as light and not a volume slider unfortunately.

Any tips or workarounds?

**Comment by merdok** [comment]
Hi,
as far as i know there is no native way to set the volume of a TV in HomeKit per Siri. Apple just does not provide such functionality. Using this plugin you can enable the volume as `slider`, in that case as you say volume can be adjusted using a light bulb. This in theory should work, but you have to name the light bulb in a way that it is understandable for Siri. If you keep your TV name there in most cases it will be hard for Siri to understand that, so i would recommend setting the name to simply words like "Television volume".

**Comment by realdannys** [comment]
Yeah I tried "TV volume" and "Television Volume" but none of them work consistently unfortunately. Shame...not sure why that isn't a native part of the TV feature in Homekit, especially when it knows what a TV is!

**Comment by merdok** [comment]
I mean when the TV is on then you will have a hard time changing the volume with Siri, if the you are using Siri in the same room. This is because the noise from the TV is of course confusing Siri. Maybe that is your issue here?

**Comment by realdannys** [comment]
Nah, even with the Homepod right next to the TV it does an excellent job of ignoring the TV and listening to me. It's not being confused by what it hears, it just doens't understand "TV Volume" consistently for whatever reason.

**Comment by merdok** [comment]
I mean i cannot control the volume of my tv neither on my Echo Alexa or Siri on my iPhone when i am in the same room as the TV. This is pretty much impossible, that is why normally when you talk to Alexa for example and music is playing then Alexa first dims the music down or there is no way she cannot understand you. My guess is that the problem lies on your Homepod beieng next to your TV.

**Comment by realdannys** [comment]
Marcin, this has NOTHING to do with it - it's irrelevant if the TV is muted or not, or if I speak to command directly into my iPhone. As i've just said the "hearing" of what i'm saying is not the issues - it's that Siri doesn't properly comprehend the device name or type for whatever reason and does different things.

For the record I contract everything in my house from HomePod with the TV on with not a single problem, that's why it has 8 microphones and beam forming.

**Comment by merdok** [comment]
Anyway, it seem that the issue is not related to the plugin itself, just how HomeKit handles TVs. there is unfortunately nothing more from my side that i can do except providing the additional light bulb to control the volume...
