### ISSUE TITLE
Announcement: Plans to remove the legacy TV service and accessory setup

### ISSUE THREAD

**Issue by merdok** [merdok/homebridge-webos-tv#247]
Hi,

so i plan to do some major changes to the plugin which include lot of  improvements and new features. I have lots of ideas for new features and improvements that will definitely bring the plugin to a new level 😃 

Unfortunately the legacy TV service and setup as an accessory are kind of blocking me from starting the work on the features.

- When the plugin first released there was no native HomeKit support for TVs that is why i had to emulate a TV with a basic On/Off switch. That was working pretty well. After the native HomeKit support was introduced from Apple i still left the legacy TV service in the plugin to allow users to slowly switch to the new TV service. I think right now after almost 1.5 years pretty much everyone should be using the new TV service so i guess i should be able to safely remove that from the plugin. 
The legacy TV service generally causes no problem, it just is a pain to still maintain that and especially with new features incoming this will make the implementation more complicated...

- As for the setup as an accessory, this was the first way provided by homebridge to setup devices. It works well, but unfortunately it has some limitations. The biggest is that i cannot create new services on the fly which limits me from adding new features which i have in plans. 

I plan to remove first the legacy TV service and later the setup as an accessory. 
If someone is still using the legacy TV service then i guess now it is a good time to switch to the new TV service. If you think that this is a bad idea to remove the legacy TV service, please let me know 😅 
People who are still using the setup as an accessory in the config should change that to a platform. There is already a warning if you are using an accessory instead of platform when starting homebridge. 

BTW: if you have ideas and features request then feel free to let me know here 😄

**Comment by sdtaheri** [comment]
I have a 2019 LG TV which adds itself natively as a HomeKit accessory. I used Legacy service to have channels in Home app. If I don't use legacy, I will have two TVs in the app which is fine by me but confusing for other family members.

**Comment by merdok** [comment]
Oh, that is a good point. But when you are using the legacy tv service with your 2019 LG TV then you still have a TV switch and your native tv in homekit, right? I mean both of them are able to control the tv and show the same status?

**Comment by sdtaheri** [comment]
They practically show the same result. Usually the native one is more reliable yet much more limited. It just lets me switch the input source; that's the reason I'm also using the homebridge plugin to be able to do other stuff.
Other than that, it's not that big a deal. If it's a huge overload for your awesome work, feel free to follow your decision.

**Comment by merdok** [comment]
I check if i can somehow provide an option for native TV Homekit users to hide the TV service but leave all other stuff.

**Comment by sdtaheri** [comment]
That's awesome. Once again, thanks for this great plugin.

**Comment by merdok** [comment]
As of version 1.9.0 the `legacyTvService` is now removed. Also a new `hideTvService` configuration property has been added which is useful for the users which already have a TV with native HomeKit support.

**Comment by rcmoliveira** [comment]
I understand that the legacyTvService allowed the TV to appear on the Eve app. Currently, with 1.9.0 is doesn't.

**Comment by merdok** [comment]
The `legacyTvService  `is removed as of version 1.9.0. What do you mean exactly?

**Comment by rcmoliveira** [comment]
Yes, I know. Up to 1.8.9 with "legacyTvService": true the tv would appear on the Eve app, not only on Home. With 1.9.0 I get the device on Home but not on Eve or Home+. Thanks!

**Comment by merdok** [comment]
The issue is that the Eve does not support TV devices as far as i know. If you still need the TV to appear in the Eve app then you need to downgrade to version 1.8.9

**Comment by rcmoliveira** [comment]
Thanks! It's then up to Eve to support them, I'll keep 1.9.0 ;-)

**Comment by Casuallynoted** [comment]
Is it possible that the legacy TV setup may be why WebOS plugin TVs show up as generic home objects under the iOS 14 beta? I noticed it after upgrading and thought it was super weird. Screenshot attached.

![B0BED5BF-D376-4373-B433-F7E680E64477](https://user-images.githubusercontent.com/6272557/86501595-492a9f80-bd68-11ea-82cf-4eb8aee6b00d.jpeg)

**Comment by AhmedHalat** [comment]
I also have IOS 14 and it works as a TV device for me.
I actually have a different issue where only the first input works and no other menu item appear (other than the power button)

**Comment by merdok** [comment]
@Casuallynoted the legacy tv service was removed in version 1.9.0.On iOS14 there should definitely  be a TV device in the Home app.

@AhmedHalat what do you exactly mean with your issue? Can you show an screenshot?

**Comment by bwalls** [comment]
I just put a backlight on my TV via MiLight LED strip, controlled by Homebridge. I'd love to have it turn on and off when the TV does. Is there any way to trigger based on the TV state? I'm guessing not, since the TV doesn't even show up in Eve or Home Manager?

**Comment by merdok** [comment]
You could do a home automation based on the default input which you use. If you use live tv then just do a home automation which triggers when the input becomes active.

**Comment by merdok** [comment]
As of version 1.9.1 the possibility to setup the plugin as an accessory is now removed. After a short transition period, to see if everything is stable for new and existing users, i will start to work on my new planned features  😄

**Comment by adrianopery** [comment]
merdok, sorry if I miss something. I was using as an Accessory and today stpos.
Now how can I do to add my TVs?
Looking on the Advanced Setup, all the config are there. But I don't have my TVs on Home app.
Please, could you guide me?

**Comment by merdok** [comment]
There is an extra step required to add the TV to Home app now. See here: https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-home-app

**Comment by adrianopery** [comment]
ok, My TVs are not homekit compatible, and they are not available when I try to add a new accessory.
Do I need to uninstall the current Plugin and reinstall?

**Comment by merdok** [comment]
No need to uninstall. You have to adjust your homebridge config -> move the TV config from `accessory` to `platform` section. After that just follow the instructions from the link above.

**Comment by adrianopery** [comment]
Hi merdok, now it's working as before.
Thanks!

**Comment by PrzemyslawKlys** [comment]
I've moved my config to platform, made all adjustments that I think were needed and I can control my TV from Homebridge UI X plugin. However, I can't see any buttons in HomeKit. All is gone. I've even readded 

```json
{
    "bridge": {
        "name": "HomebridgeLG",
        "username": "CC:CCC....",
        "port": 51826,
        "pin": "030-15-000"
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "lang": "auto",
            "sudo": true,
            "log": {
                "method": "systemd",
                "service": "homebridge"
            },
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "LG TV",
                    "ip": "192.168.240.215",
                    "mac": "78:5d:00:00...",
                    "keyFile": "/var/homebridge/lgtvKeyFile",
                    "pollingInterval": 10,
                    "volumeControl": "slider",
                    "volumeLimit": 100,
                    "channelControl": true,
                    "mediaControl": false,
                    "infoButtonAction": "INFO",
                    "inputs": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "Playstation 4"
                        }
                    ],
                    "channelButtons": [
                        {
                            "channelNumber": 7,
                            "channelName": "TVN"
                        },
                        {
                            "channelNumber": 10,
                            "channelName": "LG Comedy Central"
                        },
                        {
                            "channelNumber": 457,
                            "channelName": "LG HBO"
                        },
                        {
                            "channelNumber": 459,
                            "channelName": "LG HBO 2"
                        },
                        {
                            "channelNumber": 461,
                            "channelName": "LG HBO 3"
                        },
                        {
                            "channelNumber": 5,
                            "channelName": "TV Polsat"
                        },
                        {
                            "channelNumber": 11,
                            "channelName": "TV Paramount"
                        },
                        {
                            "channelNumber": 481,
                            "channelName": "TV Polsat Film"
                        },
                        {
                            "channelNumber": 487,
                            "channelName": "TV Fox"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        }
    ],
    "accessories": []
}
```

Do you see anything that's wrong?

**Comment by PrzemyslawKlys** [comment]
Never mind. I see I missed outlined new steps after migration. Sorry.

**Comment by fentonmatt** [comment]
Since these changes my TV status no longer displays correctly in Home app and I can no longer turn off. Only on. Then status goes back to "off" after a few seconds. Any suggestions? It is set up as a platform.

**Comment by merdok** [comment]
This changes should not affect the status of your tv. Those were changes purely related only to how you setup your setup TV.

**Comment by kbardai** [comment]
Hey,

Question about the new `hideTvService` setting.  I'm using your plugin for and older LG C7 and it works as expected.  I recently got a LG C9 with native HomeKit support, but it only seems to be working when the TV is on (lots of topics on google about it) and I get a "No Response" for the tv when it is off.

If I add this tv as a device in the config and set the `hideTvService` value, what will my experience be?  Will I be able to turn on the tv and/or add inputs/apps to the tv button?

Can you explain this feature a little bit more?

Take Care

**Comment by merdok** [comment]
The `hideTvService` property when set to `true `, as explained in the README, will hide the TV accessory created by my plugin so you do not have 2 TV accessories (one native and one from the plugin). That means you can use the native homekit from the TV for the basic features, and still you will be able to use the advanced features from this plugin. 

If you are unhappy with the native homekit implementation from LG then just remove it and use completely this plugin ;) In that case you want to have  `hideTvService` set to `false`

**Comment by kbardai** [comment]
> If you are unhappy with the native homekit implementation from LG then just remove it and use completely this plugin ;) In that case you want to have `hideTvService` set to `false`

Thanks, I am now using your plugin instead of the native homekit integration of the tv and it works as expected!

**Comment by merdok** [comment]
As the transition to platform is now complete, this issue can be closed. New info about planned features for the 2.0.0 update can be here: #275
