### ISSUE TITLE
Problem after update

### ISSUE THREAD

**Issue by borewicz9** [merdok/homebridge-webos-tv#248]
**Describe The Bug:**
Bug after update to v. 1.8.4

**To Reproduce:**
auto

**Expected behavior:**
just error log

[**Logs:**]()
[5/29/2020, 1:54:11 PM] [My LG TV] [My LG TV] Connected to TV
(node:20094) UnhandledPromiseRejectionWarning: TypeError: Promise.allSettled is not a function
    at webosTvAccessory.getTvInformation (/usr/lib/node_modules/homebridge-webos-tv/index.js:310:23)
    at webosTvAccessory.connect (/usr/lib/node_modules/homebridge-webos-tv/index.js:184:14)
    at lgtv.request (/usr/lib/node_modules/homebridge-webos-tv/index.js:142:26)
    at Object.callbacks.(anonymous function) (/usr/lib/node_modules/lgtv2/index.js:216:25)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:189:13)
    at WebSocketConnection.processFrame (/usr/lib/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/lib/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
(node:20094) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2036)
[5/29/2020, 1:54:12 PM] [My LG TV] [My LG TV] Error occured, could not write TV info Error: ENOENT: no such file or directory, open '~/.webosTv/info_60AB14A168B8'

**Homebridge Config:**

```json
        {
            "name": "My LG TV",
            "ip": "",
            "mac": "",
            "prefsDir": "~/.webosTv",
            "pollingInterval": 5,
            "legacyTvService": false,
            "showInputButtons": false,
            "volumeControl": "buttons",
            "volumeLimit": 100,
            "channelControl": true,
            "mediaControl": false,
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi2",
                    "name": "Denon"
                },
                {
                    "appId": "youtube.leanback.v4",
                    "name": "YouTube"
                },
                {
                    "appId": "com.webos.app.netflix",
                    "name": "Netflix"
                },
                {
                    "appId": "com.webos.app.photovideo",
                    "name": "Photo Video"
                }
            ],
            "channelButtons": [
                "1",
                "2",
                "4",
                "5",
                "34"
            ],
            "remoteSequenceButtons": [
                {
                    "sequence": [
                        "VOLUMEUP",
                        "VOLUMEDOWN",
                        "MUTE",
                        "MUTE"
                    ],
                    "name": "volume_seq",
                    "interval": 1000
                },
                {
                    "sequence": [],
                    "interval": 500
                }
            ],
            "infoButtonAction": "INFO",
            "accessory": "webostv"
        }
    ],
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 11.5.0
* **NPM Version**: 6.7.0
* **Homebridge Version**: 1.1.0
* **Operating System**: Raspbian
* **Process Supervisor**: Systemd

**Comment by borewicz9** [comment]
I've change plugin from accessories to platform, problem solved.

**Comment by merdok** [comment]
Oh, sorry that is my mistake. I forgot to update the dependencies...
You need to update your node js to at least version 12.9.0.

Could you try to update and check if that fixed your error?

**Comment by borewicz9** [comment]
I'm just worry about my other accessories at newer node.js.
Is it possible to fix it in next plugin update ?

**Comment by merdok** [comment]
I will just update the node js dependency in the next update to at least 12.9.0. So you will have to anyway update your node. That should not break other plugins.

**Comment by borewicz9** [comment]
I've update node js to v12.17.0 & npm to v6.14.4
error still remains
Homebridge Config UI X shows v11.5.0 hmmmm.....

**Comment by merdok** [comment]
Yes, you have to make sure with node -v command in the terminal that you are indeed using the latest node. I think that you might be still using the old node version...

**Comment by borewicz9** [comment]
at command line it show properly - v12.17.0
I've updated it using nvm

**Comment by merdok** [comment]
Then you need to make sure that homebridge also uses the version.

**Comment by merdok** [comment]
When configured as a platform you need to do some extra action. You find the details here: [https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-home-app](https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-home-app)

**Comment by borewicz9** [comment]
Thanks, it start working
I delete wrong tv before adding it once again, my bad.

Thank you for help !
