### ISSUE TITLE
incompatible with homebridge-mi-hygrothermograph plugin

### ISSUE THREAD

**Issue by Hussamfhaily** [merdok/homebridge-webos-tv#249]
Hi, everything works well until I install homebridge-mi-hygrothermograph plugin. Then homebridge is broken and I should uninstall homebridge-mi-hygrothermograph to make everything work again. Is it a matter of incompatibility? I would like to have both plugins work because they are very important to me.

**Comment by merdok** [comment]
Hi,
this is 100% a problem with your local setup, i have installed both this plugin and homebridge-mi-hygrothermograph and both work fine without any issues.

**Comment by Hussamfhaily** [comment]
Indeed it is strange what happened. I installed the Homebridge on a new SD then all the plugins I want. As I installed mi-hygrothermograph plugin, many plugins have error and Homebridge doesn't work. I will try to reinstall them again.

**Comment by MegaGio94** [comment]
I have both and zero problems so far.

**Comment by merdok** [comment]
Closing as there is no incompatibility between those plugins.
