### ISSUE TITLE
"getInputType error: Unable to determine input type for object" when opening config form

### ISSUE THREAD

**Issue by twistedpixel** [merdok/homebridge-webos-tv#251]
When I open settings for this plugin in Homebridge UI, I see this in the JS console (twice for each):

```
getInputType error: Unable to determine input type for object
schema – {title: "params", type: "object"}
```

I noticed this because whenever I try to select text or move a slider, the whole interface crashes. The Safari tab then becomes unresponsive and right click doesn't work It requires a page refresh to work again. Sorry if this has been reported before but I couldn't find anything related in previous issues.

I'm running the latest version of Homebridge (and your plugin) on a Pi Zero. Bug noticed in Safari (v13.1.1). The errors also appear in Chrome but the interface does not crash, it just behaves a little... odd.

Happy to provide anything you might need to figure this out but I suspect you'll see the same errors as I do since it happened right from fresh install (hadn't even filled out the initial config form yet).

**Comment by merdok** [comment]
Oh, you are right. I see the error now too. Will fix that! Thanks for reporting.

**Comment by merdok** [comment]
Should be fixed in version 1.8.7

**Comment by twistedpixel** [comment]
So the errors in the console are gone with v1.8.7 but my Safari tab still dies if I try to select text in the settings of your plugin.

In Chrome, it doesn't crash the whole tab but you can't select anything. It causes the dragging cursor to appear and you literally drag the whole form as if it were an image. This doesn't happen to any of the other plugins I've got installed.

Are you able to replicate the issue? I suspect it may be to do with <root-widget>. I'm just speculating since I can select the label "DEVICES" at the top, but inside that element I cannot select any labels or input text without this weirdness happening.

I can create a separate issue if you'd like (since the original errors don't seem to be related to this).

**Comment by twistedpixel** [comment]
Nope, scratch that, another plugin is doing this too. Must be something else going on.

**Comment by merdok** [comment]
I mean i know that the settings can be optimized and at the current form they are not perfect (that is why you see the dragging cursor) and i will try to optimize that in future.
