### ISSUE TITLE
TV appears "off" in Home App

### ISSUE THREAD

**Issue by solbadguy2010** [merdok/homebridge-webos-tv#252]
Since i changes my config from Accessories to Plattform and also updated to the latest Version i have a strange behavior.

I can power on my tv and all looks good. But after a few seconds the device in Home appears to be off again and i can not control it anymore. When i power it back on in home i can control if for a few seconds, then it goes back to be off, TV stays on the whole time.

I checked IP and Mac, all fine. No errors in the log, but it writes every few seconds 

`[6/2/2020, 23:56:39] [webostv] [Fernseher] Connected to TV
[6/2/2020, 23:56:43] [webostv] [Fernseher] Connected to TV
[6/2/2020, 23:56:47] [webostv] [Fernseher] Connected to TV`

What am i doing wrong?

Here is my config:

` {
            "devices": [
                {
                    "name": "Fernseher",
                    "ip": "10.0.1.90",
                    "mac": "04:4E:AF:5D:CE:E0",
                    "pollingInterval": 2,
                    "legacyTvService": false,
                    "showInputButtons": false,
                    "volumeControl": "false",
                    "volumeLimit": 100,
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Fernsehen"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Soundbar"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "Nintendo Switch"
                        }
                    ],
                    "notificationButtons": [
                        {
                            "message": "Program der Waschmaschine ist beendet.",
                            "name": "Waschmaschine fertig"
                        },
                        {
                            "message": "Das Program der Spülmaschine ist beendet.",
                            "name": "Spülmaschine fertig"
                        },
                        {
                            "message": "Achtung! Kohlendioxid zu hoch! Bitte Lüften!",
                            "name": "Achtung CO2"
                        }
                    ],
                    "infoButtonAction": "MENU"
                }
            ],
            "platform": "webostv"
        }`

**Comment by merdok** [comment]
At first everything looks ok. Seems like your TV is losing connection to homebridge but this is just a guess. You would need to check the debug log and maybe post the relevant information here.

**Comment by solbadguy2010** [comment]
Debug Log repeats this all the time:


[6/3/2020, 07:56:39] [webostv] [Fernseher] System info: 
{
  "features": {
    "3d": false,
    "dvr": true
  },
  "receiverType": "dvb",
  "modelName": "55UK6100PLB"
}
[6/3/2020, 07:56:39] [webostv] [Fernseher] TV info file already exists, not saving!
[6/3/2020, 07:56:39] [webostv] [Fernseher] Service list: 
{
  "services": [
    {
      "name": "api",
      "version": 1
    },
    {
      "name": "audio",
      "version": 1
    },
    {
      "name": "config",
      "version": 1
    },
    {
      "name": "media.controls",
      "version": 1
    },
    {
      "name": "media.viewer",
      "version": 1
    },
    {
      "name": "pairing",
      "version": 1
    },
    {
      "name": "settings",
      "version": 1
    },
    {
      "name": "system",
      "version": 1
    },
    {
      "name": "system.launcher",
      "version": 1
    },
    {
      "name": "system.notifications",
      "version": 1
    },
    {
      "name": "timer",
      "version": 1
    },
    {
      "name": "tv",
      "version": 1
    },
    {
      "name": "user",
      "version": 1
    },
    {
      "name": "webapp",
      "version": 2
    }
  ]
}
[6/3/2020, 07:56:40] [webostv] [Fernseher] Sw information: 
{
  "product_name": "webOSTV 3.5",
  "model_name": "HE_DTV_W17P_AFADABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "05",
  "minor_ver": "80.50",
  "country": "DE",
  "country_group": "EU",
  "device_id": "78:5d:c8:82:fc:e1",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "de-DE"
}
[6/3/2020, 07:56:42] [webostv] [Fernseher] Disconnected from TV
[6/3/2020, 07:56:44] [webostv] [Fernseher] Connecting to TV
[6/3/2020, 07:56:44] [webostv] [Fernseher] TV state: got response from TV, connecting...
[6/3/2020, 07:56:44] [webostv] [Fernseher] Connected to TV, checking power status
[6/3/2020, 07:56:44] [webostv] [Fernseher] Power status - TV is On
[6/3/2020, 07:56:44] [webostv] [Fernseher] Connected to TV
[6/3/2020, 07:56:44] [webostv] [Fernseher] Requesting TV information
[6/3/2020, 07:56:45] [webostv] [Fernseher] Launch points (inputs, apps): 
[
  {
    "appId": "com.webos.app.livetv",
    "name": "Live TV"
  },
  {
    "appId": "joyn",
    "name": "Joyn"
  },
  {
    "appId": "netflix",
    "name": "Netflix"

.... shortened this here....

 {
    "appId": "com.webos.app.connectionwizard",
    "name": "Geräteanschluss"
  },
  {
    "appId": "com.webos.app.accessibility",
    "name": "Barrierefreiheit"
  },
  {
    "appId": "com.webos.app.notificationcenter",
    "name": "Benachrichtigungen"
  }
]
[6/3/2020, 07:56:45] [webostv] [Fernseher] System info: 
{
  "features": {
    "3d": false,
    "dvr": true
  },
  "receiverType": "dvb",
  "modelName": "55UK6100PLB"
}
[6/3/2020, 07:56:45] [webostv] [Fernseher] TV info file already exists, not saving!

**Comment by solbadguy2010** [comment]
I reinstalled the Plugin and also re-checked all TV settings and plugged its power a few secs. Nothing helped. Ping is constantly going through. I think the network is not the problem.

**Comment by merdok** [comment]
Maybe try to re-add your TV to home again. There are some extra steps required when configuring the TV as a platform.

**Comment by solbadguy2010** [comment]
Already did that. Also deleted the TV from Homebridge Cache before re-adding it.

**Comment by merdok** [comment]
Well, something disconnects your tv.  Based on the logs everything looks fine, the tv loses connection and the plugin tries to reconnect. Why this is happening with your setup I cannot honestly tell. You can also try to set your pooling interval to higher value.

**Comment by solbadguy2010** [comment]
I just tried grzegorz914‘s plugin for testing. Same behavior in the Logs. Disconnect, then reconnect, except here the TV in the home app goes on and off all the time.

https://share.icloud.com/photos/0QPsFDcCs8pFgTwK_SESC_kpQ

Am i the only one with this error?

**Comment by merdok** [comment]
I did not hear any other reports of such issue before.

Like I already said, there is something in your setup which constantly disconnects your tv. If it is a network issues, homebridge issue or something else I cannot tell at this point. 
Maybe some of your dependencies are outdated? You could also try to reinstall homebridge.

**Comment by solbadguy2010** [comment]
I just rebooted my entire Network. Router, Pi, Tv. Everything. Nothing changed. 

I have one Idea left. I installed the newest beta firmware to my Fritz Box 7490 some days ago. Maybe this is causing the errors? If this is true, the problem will get bigger if the firmware is rolled out to all Fritz Boxes.

**Comment by merdok** [comment]
Can you not roll back the firmware on your FritzBox to check if that is indeed what is causing the issue?
I mean it could be plausible that the router disconnects the websocket because it thinks that it might be a security issue?

**Comment by solbadguy2010** [comment]
I can. I will do it asap. Currently working from home and need to stay online.

**Comment by solbadguy2010** [comment]
I rolled back to stable release firmware and set up my fritz box without using a backup.
Error stays the same...

**Comment by merdok** [comment]
Well then it is not related to your router i would guess. Another option would be to try reinstall homebridge, or even better try on a fresh image if you are running on a raspberry pi.

**Comment by solbadguy2010** [comment]
Flashed the SD with the official Homebridge Image and only installed your Plugin. Error stays the same :-/

**Comment by merdok** [comment]
Well, no ideas at this point anymore. I guess there has to be something that changed in your setup since you mentioned that it was working before...

**Comment by solbadguy2010** [comment]
Sadly i do not know when it stopped working. Last thing left is resetting the TV to factory defaults...

**Comment by solbadguy2010** [comment]
Can you tell me how the Plugin determines if the TV is on or not?

**Comment by merdok** [comment]
Connects to a websockets endpoint on the TV.

**Comment by keefar** [comment]
I have the same problem. I also updated to the newest plugin version today and my fritzbox installed the newest beta firmware a couple of days ago. But I'm experiencing the error since updating the firmware.

**Comment by merdok** [comment]
@keefar your issue is a not up to date node version. You need to use at least version 12.9 as specified in the package.json.

**Comment by solbadguy2010** [comment]
I also resettet the TV to factory defaults now. Nothing changed. I basically resettet all of my hardware now. nothing helped.
Can you tell me the Port of the Webhook you use, if Webhooks use ports...

**Comment by merdok** [comment]
Port 3000

**Comment by solbadguy2010** [comment]
some way we can try another port or an alternate way of checking the TV is on like "Ping"?

**Comment by merdok** [comment]
Unfortunately not, the port cannot be changed.
It is not about checking if the tv responds to a ping or not, this only gives me an info if the tv is reachable or not and does not tell me if the tv is on or not. A websocket connection needs to be all the time on or else you would not be able to control the tv.

**Comment by solbadguy2010** [comment]
Any general ideas what can disconnect a websocket connection?
What cought my attention: In germany a new app "Join" was pushed a few days ago. I deleted it, no change. But could LG have changed something in their firmware?

**Comment by merdok** [comment]
I do not think that lg changed something in the firmware. This would affect a lot of other users then.
I can certainly say that this is an issue related to your local environment. Since I never experienced this issue before I honestly have no idea what exactly causes this. I mean if it was working before then you just need to find out what changed recently with your setup and try to revert back temporary.

**Comment by Sebbl81** [comment]
I have the same Issue that my LG Web OS isn't shown as Online. Everything else is working like Notification,...

From my point of vi
<img width="487" alt="Bildschirmfoto 2020-06-05 um 10 37 19" src="https://user-images.githubusercontent.com/66466047/83855576-93444500-a718-11ea-8747-fb37c4ceaad4.png">

**Comment by solbadguy2010** [comment]
I also testet wired connection to the TV now. Same error. So its not the Wifi...

I rolled everything back i am aware of, what could have changed. I even unplugged my new Osram Bluetooth light strip, even if BT can not interfere... Only to be sure.

All i can not roll back are the software-updates happened to the WebOS, the Raspbian, Homebridge and your Plugin. I think we need to find the change in the Software???

Also just checked Sebbl81's post. His config looks linke mine. The error looks the same.

**Comment by Sebbl81** [comment]
Here is my Homebridge Configuration (Version)
<img width="349" alt="Bildschirmfoto 2020-06-05 um 10 45 17" src="https://user-images.githubusercontent.com/66466047/83856449-e074e680-a719-11ea-9b89-fcd19693de11.png">

**Comment by solbadguy2010** [comment]
@Sebbl81 Node and NPM Version are the same as mine.

**Comment by Sebbl81** [comment]
So it a bug in the Homebridge Plugin from my point of view....

**Comment by solbadguy2010** [comment]
@Sebbl81 only strange, that not more users have these errors. Maybe some error that only affects Fritz Box Users?
What Model is your TV?

**Comment by Sebbl81** [comment]
@solbadguy2010 I'm using Homebridge on a Synology Docker installation. My TV is WebOS TV EG9109 on Software Version 04.06.30

**Comment by merdok** [comment]
Oh, you both have both FritzBox. I start to suspect that the FritzBox indeed might be the issue.

@Sebbl81 your tv also clearly gets constantly disconnected as seen in the log. This is of course not as its supposed to be. You can only control your tv because you have a low pooling interval so the tv reconnects every 5 seconds.

I am pretty certain this issue is not related to the plugin itself.

**Comment by solbadguy2010** [comment]
I had the issue with three different Fritz OS Versions now:
FRITZ!OS-113.07.12
FRITZ!OS-07.19-78834 BETA
FRITZ!OS-07.19-78988 BETA

Most important here is the 7.12, which was released in July 2019. So even if the error is Fritz Box related, it is not caused by a change of Fritz OS recently. Maybe you changed something in your Plugin that triggers and Fritz Box related error that was already there?

@Sebbl81: What Fritz Box do you use and what OS is installed?

**Comment by Sebbl81** [comment]
@solbadguy2010 I tried the same Fritz OS and I tried it also with a Mikrotik as gateway.

I see also the problem on the plugin side.

**Comment by merdok** [comment]
@Sebbl81 can you post a debug log? Like that above just in debug mode. If it is too big you upload it somewhere like gist.

**Comment by phlexx** [comment]
I have the same issue. TV keeps disconnecting. Plugin is able to fetch launchpoints etc then disconnects. Not using a fritzbox. 

can i help?

**Comment by solbadguy2010** [comment]
@phlexx Please also post a debug log. You can enable Debug mode in the settings. 

![BAA0A017-C212-462A-AE63-F2B931AAE51B](https://user-images.githubusercontent.com/30244171/83901816-a593a280-a75b-11ea-8922-5b39cd3670cd.jpeg)

Please also list your used hardware. Pi? TV? Router?

**Comment by Sebbl81** [comment]
Here is my Debug Log
[homebridge.log](https://github.com/merdok/homebridge-webos-tv/files/4737515/homebridge.log)

**Comment by merdok** [comment]
Thanks, the log looks ok. I do not see anything which might close the connection. Could you try to revert back the plugin version by version and check if the issues disappears, if yes then you would need to tell me at which exactly version it happend, so at least i can have a look at the changes.

**Comment by solbadguy2010** [comment]
How can i install an older Version?
And where can i see which Versions released when?

**Comment by merdok** [comment]
`sudo npm -g install homebridge-webos-tv@1.8.6`

[https://www.npmjs.com/package/homebridge-webos-tv](https://www.npmjs.com/package/homebridge-webos-tv)

**Comment by shrimpbox** [comment]
I have the same problem. I tried different versions.
1.7.1 works for me. Versions > 1.8.x don't work anymore.

**Comment by solbadguy2010** [comment]
i can confirm @shrimpbox's test results.
1.7.1 is working without any problem. Starting with 1.8.0 the TV is "off" all the time.

While testing 1.8.0 terminal threw this at me when i played with TV power and switching inputs. Maybe it helps?

[6/5/2020, 20:53:50] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:53:52] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:53:54] [webostv] [Fernseher] App switch service - Trying to launch com.webos.app.livetv but TV is off, attempting to power on the TV
[6/5/2020, 20:53:54] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:53:56] [webostv] [Fernseher] Error - Error: Sec-WebSocket-Accept header from server didn't match expected value of VExVbYkcSCLrYXN5VuoTipJVfAE=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:315:20)
    at Socket.socketOnData (_http_client.js:503:11)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[6/5/2020, 20:53:57] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:53:58] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:54:00] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:54:02] [webostv] [Fernseher] Connected to TV
[6/5/2020, 20:54:04] [webostv] [Fernseher] Connected to TV

**Comment by merdok** [comment]
Ok, that is some progress now! But i am still not sure what exactly is causing the issue. Could somebody modify the index.js locally and do some testing for me?

**Comment by solbadguy2010** [comment]
@merdok If you tell me what i need to do... I'll add you on Twitter.

**Comment by shrimpbox** [comment]
I commented out the getTvInformation in the connect function. Now the TV gets connected.
// --== CONNECT/DISCONNECT METHODS ==--     
    connect() {
        this.logInfo('Connected to TV');
        this.connected = true;
//        this.getTvInformation().then(() => {
            this.logDebug('Got TV information proceeding with launch');
            this.updateTvStatus(null, true);
            this.subscribeToServices();
            this.connectToPointerInputSocket();
            this.updateAccessoryStatus();
//        });
    }

**Comment by merdok** [comment]
@shrimpbox can you just comment out this lines and check if that also helps?
https://github.com/merdok/homebridge-webos-tv/blob/f337f53435a0e1cfd13807eb47f42075af7e23dc/index.js#L286-L308

**Comment by shrimpbox** [comment]
@merdok This helps. Works for me.

**Comment by merdok** [comment]
@shrimpbox can you tell me what TV do you have and what webOS version?

**Comment by shrimpbox** [comment]
@merdok Here are some device infos. I used the log outputs. If you need any additional info, tell me.
```
"modelName": "OLED65B87LC"

"product_name": "webOSTV 4.0",
"model_name": "HE_DTV_W18H_AFADABAA",
"sw_type": "FIRMWARE",
"major_ver": "05",
"minor_ver": "10.50",
"country": "DE",
"country_group": "EU",
"auth_flag": "N",
"ignore_disable": "N",
"eco_info": "01",
"language_code": "de-DE"
```

**Comment by merdok** [comment]
So i most probably found the issue. This issue should be fixed in version 1.8.8. Please test and let me know. 

For some reason some TVs do not respond on the channel list request. I do not know yet why. At first that it might be on TVs with webOS 3.5 and lower but @shrimpbox just posted that he has a webOS4.0 TV so i am again in the dark now. 

@shrimpbox do you have Live TV with channels configured? Do you use Live Tv on your TV?

**Comment by solbadguy2010** [comment]
Couldn‘t wait. Can confirm 1.8.8 is fully working again. 

Danke!

**Comment by shrimpbox** [comment]
@merdok Same here, 1.8.8 is working, thanks a lot.
I'm using Live TV with channels configured.

Anything I can do to help?

**Comment by phlexx** [comment]
was about to uploud my log but 1.8.8 fixed it! 
Thank you!


for the records:

  "product_name": "webOSTV 3.0",
  "model_name": "HE_DTV_W16P_AFADABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "05",
  "minor_ver": "30.25",
  "country": "AT",
  "country_group": "EU",
  "device_id": "14:c9:XX:a6:XX0f",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "de-AT"

No Live-TV Channels. :)

**Comment by merdok** [comment]
@shrimpbox How many channels do you have configured?
@phlexx do you have any channels configured, even when you not using Live TV?

**Comment by Sebbl81** [comment]
Good morning together,
it works for me. Thank you for your great work merdok.

**Comment by merdok** [comment]
@Sebbl81 thanks for the info! Can you tell if you use Live TV and how many channels do you have configured in your Channel List?

**Comment by Sebbl81** [comment]
@merdok Hello Marcin, I don't use Live TV and no configuration in the Channel list.

**Comment by merdok** [comment]
@Sebbl81 no single channel configured in the channel manager(Sendermanager) in the settings?

**Comment by Sebbl81** [comment]
@merdok I don‘t Look linear TV. It‘s only a screen for my Apple TV

**Comment by merdok** [comment]
Okay. Thanks for the info!

**Comment by shrimpbox** [comment]
@merdok I checked my channel manager:
Satellite >> DTV >> 1398 channels
Satellite >> Radio >> 158 channels

**Comment by merdok** [comment]
Ok, that is a lot of channels, maybe the issue was also related to the channel numbers which are on the TV.
