### ISSUE TITLE
Inputs are apperaing with label 'Switch'

### ISSUE THREAD

**Issue by pjotal** [merdok/homebridge-webos-tv#253]
Environment:
- iOS v13.4.1
- homebridge v1.1.0
- node v12.10.0 and npm v6.10.3
- homebridge-webos-tv v1.8.7 (entry set up as a platform only).
- readded the entry after update just to be sure.
- rebooted homebridge after updates.

i am using the following sound inputs:
- tv_speaker
- external_optical
- external_arc
- lineout
- tv_external_speaker
- bt_soundbar

those are all appearing with the label "Switch" giving me no idea which one is which (see screenshot).
![IMG_2436-30](https://user-images.githubusercontent.com/7715321/83768751-2d3ebb80-a64d-11ea-9d08-35744cb0467c.png)

**Comment by merdok** [comment]
Hi,
I am aware of that issue but i am not sure yet what is the reason for that. Right now you can simply rename the switches manually in the Home app to your desired name.

**Comment by merdok** [comment]
Hi, so the issue should be fixed in the latest release. For the switches which i generate i try not to use special characters so thr auto generated switches should work. If you have inputs with special characters like "-" (dash) then i recommend on using a custom name for that.
