### ISSUE TITLE
configuration view changed - written into wrong area in main config file

### ISSUE THREAD

**Issue by sahotanick** [merdok/homebridge-webos-tv#256]
Hi,

Today I updated to the latest version of webos-tv and found that the configuration view has changed and no just shows the following

![image](https://user-images.githubusercontent.com/25302199/84491579-a87f1d80-ac9c-11ea-92d1-5e81dad72517.png)

I have found that now when I create my webos-tv config file that it writes the lines into the wrong area in the main homebridge config file.

Has anyone else experienced this?

**Comment by merdok** [comment]
Hi,

you are probably still using the plugin as an accessory. You would need to switch to using the plugin as a platform.

**Comment by sahotanick** [comment]
It wasn't that, for some reason updating the plugin then placed things in the wrong place. I resolved this by uninstalling the plugin and re-installing.
