### ISSUE TITLE
Can turn TV on but no other control

### ISSUE THREAD

**Issue by m11rphy** [merdok/homebridge-webos-tv#258]
Hi, I just upgraded version 1.8.8 and also converted to device however now I can only turn the TV on with HomeKit, once the tv is on I cant change inputs or turn the tv off from the home app. I tried a fresh install of homebridge via hoobs but still face the same issue. 

What I found strange is that the TV no longer provided the pop-up  to ask to allow the the mobile access
my config is as below;
{
    "server": {
        "port": 80,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISWTJ34HJ",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "fahrenheit",
        "country_code": "US",
        "postal_code": "94040"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-42-439",
        "username": "9A:10:24:B3:AF:C9"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "Bedroom TV",
                    "ip": "192.168.0.91",
                    "mac": "78:5D:C8:63:37:D0",
                    "pollingInterval": 10,
                    "tvService": true,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "HDMI 1"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "NDMI 2"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "HDMI 3"
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by merdok** [comment]
Please read the [README](prepareInputButtonService), there is an extra part which you have to do in order to add your TV when it is configured as a platform.

**Comment by m11rphy** [comment]
I dont get what I've missed? 

I have done all the below steps, and just tried again and still no luck. Sorry if im being dumb but can you spell out my mistake ?

You also need to enable mobile TV on on your TV for the turn on feature to work correctly.

This is located on your TV under Settings > General > Mobile TV On

On newer TVs LG Connect Apps under the network settings needs to be enabled.

Adding the TV to Home app

Since HomeKit expects only one TV per bridge they will be declared as external accessories and acts as a bridge.
This means that a TV will not appear in your Home app until you add it!

To add a TV to HomeKit follow this steps:

Open the Home app
Select Add Accessory
Tap on Don't Have a Code or Can't Scan?
The TV should appear on the accessory list
Tap on it and follow the steps
When you are asked for a pin then just use the pin from the bridge section in your config.json

**Comment by merdok** [comment]
If you did all those steps correctly then it should work. If not you can paste your debug log from homebridge here so i can have a look what is happening.

**Comment by m11rphy** [comment]
I dont think I can hoobs, can you confirm if I should still get the notification from the TV to allow access? As im not getting this now

**Comment by m11rphy** [comment]
The TV is in HomeKit, it shows as on I just cant control it, Ive checked IP and MAC they are both correct

**Comment by merdok** [comment]
No, you should not get the prompt to allow access when you are switching from accessory to platform, since the key from your TV should already be saved.

**Comment by m11rphy** [comment]
But I have a fresh install of HOOOBS (HOMebridge) now

**Comment by merdok** [comment]
Sorry i do not use hoobs so i am not quite sure what the issue is. Maybe some dependencies are not up to date?

**Comment by merdok** [comment]
Hi, I see you closed the issue. Did your Problem got resolved? If yes could you please tell me what the issue was? This could be helpful for the future...
