### ISSUE TITLE
Netflix Params

### ISSUE THREAD

**Issue by DavidWhicker** [merdok/homebridge-webos-tv#259]
If its possible to have the params feature to work with Netflix that would be great. It looks like it required contentId instead of params from the code found here: https://github.com/snabb/webostv/blob/master/mapps.go

If I can help anymore please let me know.

**Comment by merdok** [comment]
Hi,

are you able to test if that works? I unfortunately do not use Netflix and do not have an account there. We could also setup a teamviewer session where I test if that works on your tv.

**Comment by DavidWhicker** [comment]
Hi, no unfortunately it didn’t work. It always goes to the app but only ever where it was previously. 

Ive tried loads of different combos but nothing seems to work annoyingly. 

Yeah sure

**Comment by merdok** [comment]
I suppose that you tried it with my plugin? It will not work since the necessary parameter is not passed. The commit which you posted is also 2 years old, so might be that Netflix changed that by now, but that needs to be tested.

Can you add me on Twitter and DM me? We can discuss the details there about the teamviewer session.

**Comment by merdok** [comment]
@DavidWhicker are we able to do the testing? Like I cannot test it myself since i do not have a netflix account.  Another solution is that you somehow would provide me temporary a netflix account for testing...

**Comment by DarkSupremo** [comment]
You can check for an working example on how to launch netflix directly to an content here: https://github.com/DarkSupremo/lgtv2mqtt/blob/master/index.js#L183

**Comment by merdok** [comment]
@DarkSupremo do you know if specifying the `contentTarget` as above for the params works? At least the netflix app has this param defined. Could not try by myself since i do not use netflix...

**Comment by DarkSupremo** [comment]
@merdok i tested it and didn't worked, must be something different for Netflix, these parameters is defined by app owner..

**Comment by merdok** [comment]
@DarkSupremo 
Ok, so basically the netflix app is using `contentId `instead of `params`?

Would the request with the above content target look like that below?
``
"contentId": `m=http://api.netflix.com/catalog/titles/movies/80145130&source_type=4`
``
