### ISSUE TITLE
TV ip address is required for undefined

### ISSUE THREAD

**Issue by paolos7709** [merdok/homebridge-webos-tv#260]
Hi all,
trying to get this plugin up and running but struggling with config file apparently. Getting such king of error:
_Loaded plugin "homebridge-webos-tv".
[webostv] Init - initializing devices
[webostv] Error: TV ip address is required for undefined
[webostv] Failed to create platform device, missing mandatory information!
[webostv] Please check your device config!_

I copied example config and modified with my IP/Mac and it looks like this now:
_[
    {
        "platforms": [
            {
                "platform": "webostv",
                "devices": [
                    {
                        "name": "My webOS TV",
                        "ip": "192.168.1.15",
                        "mac": "3C:CD:93:CC:70:E5",
                        "pollingInterval": 10,
                        "inputs": [
                            {
                                "appId": "com.webos.app.livetv",
                                "name": "Live TV"
                            },
                            {
                                "appId": "com.webos.app.hdmi1",
                                "name": "PS4"
                            },
                            {
                                "appId": "youtube.leanback.v4",
                                "name": "YouTube",
                                "params": {
                                    "contentTarget": "https://www.youtube.com/tv?v=Bey4XXJAqS8"
                                }
                            }
                        ],
                        "showInputButtons": true,
                        "volumeControl": "buttons",
                        "channelControl": false,
                        "mediaControl": false,
                        "channelButtons": [
                            3,
                            5,
                            7
                        ],
                        "notificationButtons": [
                            "Motion detected - living room",
                            "Motion detected - kitchen"
                        ],
                        "remoteControlButtons": [
                            "HOME",
                            "EXIT"
                        ],
                        "soundOutputButtons": [
                            "tv_speaker",
                            "external_optical",
                            "headphone"
                        ],
                        "remoteSequenceButtons": [
                            {
                                "sequence": [
                                    "HOME",
                                    "RIGHT",
                                    "RIGHT",
                                    "RIGHT",
                                    "ENTER"
                                ],
                                "name": "screen_share_seq"
                            },
                            {
                                "sequence": [
                                    "VOLUMEUP",
                                    "VOLUMEDOWN",
                                    "MUTE",
                                    "MUTE"
                                ],
                                "name": "volume_seq",
                                "interval": 1000
                            }
                        ]
                    }
                ]
            }
        ]
    }
]_

I'm running HOOBS 3.2.6...

Any idea what have I done wrong please...?

**Comment by merdok** [comment]
I guess HOOBS  have some issues. Make sure that all the dependencies are up to date and that your config is valid using a online json validator.

**Comment by paolos7709** [comment]
Hello @merdok. Thanks a lot for your feedback.
I do modify JSON files in Code but checked the file also in online JSON validator and all looks fine. OS itself is up-to-date (sudo apt-get update && sudo apt-get upgrade) and Hoobs is running on version 3.2.6 and NodeJS is running on 12.16.2.
Is there anything else I can do?
Thanks for your time guys.

**Comment by merdok** [comment]
Your problem is pretty sure with the config file. I can see in the log that the config file could not be read (undefined instead of the tv name which you clearly have in your config). I think there is something wrong with hoobs and parsing the config. I guess someone already had a similar issue. You might want to check the closed issues recently.

**Comment by faiqc** [comment]
I'm having the same issue with hoobs

**Comment by faiqc** [comment]
It was a noob error
@paolos7709 
Use this on HOOBS, it should work:


[
    {
        "name": "LG TV",
        "ip": "192.168.xx.xx",
        "mac": "94:6A:B0:8A:AC:xx",
        "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
        "pollingInterval": 10,
        "inputs": [
            {
                "appId": "com.webos.app.livetv",
                "name": "Live TV"
            },
            {
                "appId": "com.webos.app.hdmi1",
                "name": "PS4"
            },
            {
                "appId": "youtube.leanback.v4",
                "name": "YouTube",
                "params": {
                    "contentTarget": "https://www.youtube.com/tv?v=Bey4XXJAqS8"
                }
            }
        ],
        "showInputButtons": true,
        "volumeControl": "buttons",
        "channelControl": false,
        "mediaControl": false,
        "channelButtons": [
            3,
            5,
            7
        ],
        "notificationButtons": [
            "Motion detected - living room",
            "Motion detected - kitchen"
        ],
        "remoteControlButtons": [
            "HOME",
            "EXIT"
        ],
        "soundOutputButtons": [
            "tv_speaker",
            "external_optical",
            "headphone"
        ],
        "remoteSequenceButtons": [
            {
                "sequence": [
                    "HOME",
                    "RIGHT",
                    "RIGHT",
                    "RIGHT",
                    "ENTER"
                ],
                "name": "screen_share_seq"
            },
            {
                "sequence": [
                    "VOLUMEUP",
                    "VOLUMEDOWN",
                    "MUTE",
                    "MUTE"
                ],
                "name": "volume_seq",
                "interval": 1000
            }
        ]
    }
]

**Comment by merdok** [comment]
@faiqc can you post what exactly was the issue?

**Comment by faiqc** [comment]
I don't have cable TV. I get this

[webostv] [LG TV] App launched, current appId: com.webos.app.channelsetting
[webostv] [LG TV] App launched, current appId: com.webos.app.livetv
webostv] [LG TV] Current channel - error while getting current channel info
[webostv] [LG TV] Error message: internal error

**Comment by merdok** [comment]
This is ok, since you do not have cable TV.

**Comment by faiqc** [comment]
> @faiqc can you post what exactly was the issue?

Hoobs has a different setup to type the config 
Theres a tab for plugins
![Screenshot 2020-06-24 at 12 24 55 AM](https://user-images.githubusercontent.com/44741842/85445659-3fa77780-b5b1-11ea-832c-1930b7ffb8af.png)

they have this by default
![Screenshot 2020-06-24 at 12 24 21 AM](https://user-images.githubusercontent.com/44741842/85445734-5948bf00-b5b1-11ea-9fb8-2ad4ef2e0237.png)


all plugins are separated and you have something like this to type your config
![Screenshot 2020-06-24 at 12 23 36 AM](https://user-images.githubusercontent.com/44741842/85445861-73829d00-b5b1-11ea-847e-1425375fa19a.png)


I was silly to copy and paste the whole thing into the separate config tab of LG webos

**Comment by faiqc** [comment]
> This is ok, since you do not have cable TV.

I still can't see anything in the home app

**Comment by merdok** [comment]
@faiqc thanks for the info,  I guess @paolos7709 will have a similar issues so hopefully that helps him out. 

> I still can't see anything in the home app.
I can see my other stuff.

What other stuff you mean? If you do not have cable TV then the error will appear since there is no channel list on your TV.

**Comment by faiqc** [comment]
> @faiqc thanks for the info, I guess @paolos7709 will have a similar issues so hopefully that helps him out.
> 
> > I still can't see anything in the home app.
> > I can see my other stuff.
> 
> What other stuff you mean? If you do not have cable TV then the error will appear since there is no channel list on your TV.

ok the channel issue was gone after I restarted and the tv is visible.
But every button is an on-off switch, except power button.
Is it supposed to be that way.
If yes, can you implement Apple TV style remote controls?

**Comment by merdok** [comment]
You have a remote control in the control center. Just select your tv from the list there.

**Comment by faiqc** [comment]
Just basic controls are available, any chance in future to get a better ui In home app or cc.
Would be possible for jailbreak users like me.

**Comment by faiqc** [comment]
> @faiqc thanks for the info, I guess @paolos7709 will have a similar issues so hopefully that helps him out.
> 
> > I still can't see anything in the home app.
> > I can see my other stuff.
> 
> What other stuff you mean? If you do not have cable TV then the error will appear since there is no channel list on your TV.

It would be nice to add this in Readme

**Comment by merdok** [comment]
keyFile is just a location on your device where to store the TV connection key file created upon first pairing. 
It is not possible to change the Home UI.

**Comment by faiqc** [comment]
> keyFile is just a location on your device where to store the TV connection key file created upon first pairing.
> It is not possible to change the Home UI.

Where do I locate the keyFile and how do I add it to the config file?

**Comment by merdok** [comment]
You do not add it to the config file. Just specify a path there where it should be stored and that's it, you do not have to care about it more.

**Comment by faiqc** [comment]
I'm Sorry, I still couldn't get it. where do I locate it?, I've SSH into the raspberry pie using Cyberduck(so I can get GUI and search), and am trying to locate the file. Plz Help.

**Comment by merdok** [comment]
The file is located under the path which you specified in the config.

**Comment by paolos7709** [comment]
> It was a noob error
> @paolos7709
> Use this on HOOBS, it should work:
> 
> [
> {
> "name": "LG TV",
> "ip": "192.168.xx.xx",
> "mac": "94:6A:B0:8A:AC:xx",
> "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
> "pollingInterval": 10,
> "inputs": [
> {
> "appId": "com.webos.app.livetv",
> "name": "Live TV"
> },
> {
> "appId": "com.webos.app.hdmi1",
> "name": "PS4"
> },
> {
> "appId": "youtube.leanback.v4",
> "name": "YouTube",
> "params": {
> "contentTarget": "https://www.youtube.com/tv?v=Bey4XXJAqS8"
> }
> }
> ],
> "showInputButtons": true,
> "volumeControl": "buttons",
> "channelControl": false,
> "mediaControl": false,
> "channelButtons": [
> 3,
> 5,
> 7
> ],
> "notificationButtons": [
> "Motion detected - living room",
> "Motion detected - kitchen"
> ],
> "remoteControlButtons": [
> "HOME",
> "EXIT"
> ],
> "soundOutputButtons": [
> "tv_speaker",
> "external_optical",
> "headphone"
> ],
> "remoteSequenceButtons": [
> {
> "sequence": [
> "HOME",
> "RIGHT",
> "RIGHT",
> "RIGHT",
> "ENTER"
> ],
> "name": "screen_share_seq"
> },
> {
> "sequence": [
> "VOLUMEUP",
> "VOLUMEDOWN",
> "MUTE",
> "MUTE"
> ],
> "name": "volume_seq",
> "interval": 1000
> }
> ]
> }
> ]

Thank you @faiqc ... This one works for me like a charm!

Thanks team for your help. Have a great day.
