### ISSUE TITLE
LG TV no longer appears in home app but functions as per log

### ISSUE THREAD

**Issue by sahotanick** [merdok/homebridge-webos-tv#261]
Hi,
 
I can no longer add the tv to my home app, i had to remove it initially because when I tried to rename switches it kept changing them back to Television automatically. After removing, I went to re-add using the add accessory button but nothing appeared.

I have checked the logs and the plugin is working, its registering volume changes, apps opening etc but for some odd reason it no longer can be added to the home app. I have removed homebridge from my home app altogether and then re-added, still nothing. My ring plugin seems to still work fine and it allows me to add and remove however I like.

Has something changed or is there anything I can try to sort this out?

Note - I didn't change any of my config, I only decided to remove the TV because the names of my switches weren't saving whereas previously they were.

**Comment by merdok** [comment]
Hi,

thanks for the report. I have a small suspicion what the issue might be, but you would need to give me more details on how did you proceed with removing the TV. Can you exactly describe what you did?
Also, did you try to create a new home in the Home app and try to add the tv there?

**Comment by grzegorz914** [comment]
@sahotanick 

Tip: Try to change its name in config, restart HB and try add it again.

**Comment by merdok** [comment]
Changing the name might work but this is not the correct solution for the problem.

**Comment by merdok** [comment]
@sahotanick just tried to remove and re-add my tv a few times and that was working without any issues. Are you sure that you actually removed the TV, maybe you just moved it to another room? If you are sure that indeed the TV was removed then detailed steps would be helpful for me to reproduce the issue.

**Comment by sahotanick** [comment]
> @sahotanick just tried to remove and re-add my tv a few times and that was working without any issues. Are you sure that you actually removed the TV, maybe you just moved it to another room? If you are sure that indeed the TV was removed then detailed steps would be helpful for me to reproduce the issue.

So I’ve fixed the issue on my side but let me explain how it came about it full detail and what I did to fix it:

Initially all my TV switches etc were included in favourites in the home app from the start, they were fine there for a while almost 3-4 months, the other day I removed the switches from my favourites for a small while, then when I went to put them back in favourites the name of all the switches had changed from things like YouTube/Amazon/HDMI1 etc to Television. Every time I would try to change the names back it wouldn’t save and switch it back to Television.

I tried to remove my bridge, re-add the tv etc but nothing, the TV stopped appearing in accessories.. I didnt create a new home as that was going to be my last resort

Now onto how I fixed this - I removed the bridge from my home app fully, my bridge is a Pi running hoobs, so from the hoobs UI I went to the Help screen and clicked on the Reset Connection button. This removes the persist and accessories folders, then I went through the process of adding the bridge again to the home app and then add accessories and viola, the TV was back.

@merdok so it seems like this could be 2 issues, one of removing from favourites and adding back which causes the name of switches to default to Television and two once removed from home I guess files remain in the cache/persist folders which cause conflicts when adding the accessory back. Hope this helps.

**Comment by merdok** [comment]
Thanks for the detailed description. 
For the switches names, you should use the config. Most of the configurable stuff can have a custom name, you can find that info in the README. That way your switches will always have the name that you desire.
For the second issue that is really strange since i also tried to remove my TV from HomeKit, and i was able to add it back without any issues, so i am not quite sure from where this issue came up on your side...
I will try to monitor this and see if someone else will also have this issue. I guess since your initial issue is fixed this can be closed.
