### ISSUE TITLE
How i can run app(ex. YouTube) with Siri command?

### ISSUE THREAD

**Issue by beautyfree** [merdok/homebridge-webos-tv#266]

**Comment by merdok** [comment]
You could simply enable the input buttons service. This will give you an button for each configured input, you could then control them with Siri.

**Comment by beautyfree** [comment]
Thank you! It works

**Comment by zx81uk** [comment]
What are the voice commands I can issue to Siri to make this work?

**Comment by merdok** [comment]
Like "Turn on YouTube"
