### ISSUE TITLE
Can’t add TV in iOS 14 HomeKit app

### ISSUE THREAD

**Issue by Hussamfhaily** [merdok/homebridge-webos-tv#267]
I have tried to add my TV to HomeKit app in iOS 14. The TV doesn’t appear in accessories list. Is there a solution? Thank you.

**Comment by merdok** [comment]
Using iOS14 myself without issues.  Just make sure you are following the steps as described in the README.

**Comment by Hussamfhaily** [comment]
Ok. I will try that again. Thank you.

**Comment by gillesguillemin** [comment]
There seems to be a problem indeed. It worked for me initially too as I had added the Homebridge bridge, along with the WebOS plugin a while ago on iOS 13.
But today I had to nuke my Raspberry Pi and so did a full reinstall of Homebridge, and had to re-add everything, in iOS 14 this time, and none of the buttons/switches associated with the WebOS plugin appear in Home.
They do appear in Homebridge’s web interface and can be interacted with in Accessories but, once again, nothing in Home.

**Comment by merdok** [comment]
Usually a force kill of the home app fixes such issues. Also using iOS14 here since a few weeks and no issues discovered yet.

**Comment by gillesguillemin** [comment]
First thing I tried of course, but to no avail. Not even sure iOS 14 is the (only?) cause but it is consistant between my devices (iPhone, iPad, Apple TV, Mac).
Problem also occurs with other WebOS plugin https://github.com/grzegorz914/homebridge-lgwebos-tv
Like I said, it used to work, until I had to reinstall everything. Some changes in Homebridge itself perhaps? Some dependency missing from Homebridge’s ready to use Raspbian image? (First time I’m using it)

**Comment by merdok** [comment]
ios14 is in currently in beta so it might be that there are some issues for some people. From my experience the plugin is working with no issue on iOS14. I tried removing and re-adding it from the home app multiply times now without any issues at all.
The issues which you mentioned are usually cache issues and have really nothing to do with the iOS version.

**Comment by gillesguillemin** [comment]
Ok, I'll keep investigating but that's a bit of a bizarre one.

**Comment by merdok** [comment]
That is true. 
I am starting to wonder if it works for me because I have a couple of changes locally...

**Comment by altercation** [comment]
FWIW I successfully added this plugin in home bridge and then added it in the Home app running on the current iOS 14.

However, I subsequently removed the plugin (and config) and then reinstalled it. After reinstalling (and restarting home bridge and the home app) the TV no longer shows up as an accessory.

Happy to test or provide more information.

**Comment by merdok** [comment]
@altercation did you try to change the name after you re added it?

**Comment by altercation** [comment]
I've tried with with the default name and a new name. Just tested again now with another renaming, no luck.

Just to note: the first time I did this it worked perfectly. And the accessories can be controlled fine via the web UI in home bridge. It's just that they aren't showing up in the Home app. Other accessories from Homebridge do show up fine in Home app.

Let me know if there are any other tests you want me to run. I'm moderately technical and don't mind doing some debugging.

**Comment by altercation** [comment]
@merdok - I've tried with with the default name and a new name. Just tested again now with another renaming, no luck.

Just to note: the first time I did this it worked perfectly. And the accessories can be controlled fine via the web UI in home bridge. It's just that they aren't showing up in the Home app. Other accessories from Homebridge do show up fine in Home app.

Let me know if there are any other tests you want me to run. I'm moderately technical and don't mind doing some debugging.

**Comment by merdok** [comment]
@altercation you could also try to clear the homebridge cache and see if that fixes the issue.

**Comment by ggroel** [comment]
I have iOS 14 and something similar happened to me... it only gave when I chose “forcing service restart” in homebridge options.

Gastón

**Comment by merdok** [comment]
@ggroel you mean the TV did appear back after you did that?

**Comment by ggroel** [comment]
Actually the television had disappeared because I had uninstalled the plugin, but when I reinstalled it I wanted to add it to the home application and it told me that this accessory was already added (and I did not see it in the application). The issue, basically, that the homebridge pairing code had not changed and apparently the home application had it "cached". Forcing the restart of the homebridge service I re-paired everything (even the tv).

Gastón

**Comment by merdok** [comment]
@ggroel thanks for the info!

@altercation and @gillesguillemin can you also try that?

**Comment by gillesguillemin** [comment]
All right, so I've followed @ggroel's suggestions, and also tried every other possible ways I could think of to clear some potential caching issues but still no dice.

I've noticed something _very_ peculiar though. During my numerous attempts, I hit the "I don't have a code or Cannot scan" button when trying to add an accessory in Home and I had the surprise to see the following:
![IMG_1E262076CF19-1](https://user-images.githubusercontent.com/108240/89728954-1f306100-da29-11ea-98ca-d41f129715b2.jpeg)

That was quite unexpected to see there the LG TV presented as a separate HomeKit accessory. Nothing that I could do with that though as I would need a PIN to actually add it but maybe that might point to why it doesn't show by just importing Homebridge?

**Comment by gillesguillemin** [comment]
Hang on, now I feel like a fool: that's actually the way to actually add the TV now, right?

Just looked at the terminal logs and found "Please add [LG OLED TV] manually in Home app. Setup Code: …-..-…"

I had no idea the process had changed (nor is it reflected on the plugin homepage...

**Comment by gillesguillemin** [comment]
Needless to say that after adding it manually everything now works as expected (but _pleeaaaase_ update your doc man!).

**Comment by merdok** [comment]
@gillesguillemin yes this is the process which you need to follow in order to add the TV to your Home. 
This is clearly stated in the README with the detailed steps on how to add you TV to the Home app: https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-the-home-app

What info is missing for you in the README?

**Comment by gillesguillemin** [comment]
Ahem, now I'm feeling twice as much a fool… 😬

Lame excuse but I hadn't updated the plugin for many months and didn't know the process had changed let's say so drastically (and just skimmed the doc, not seeing that crucial bit in the middle).

Feel free to ignore me from now on, I'm very much in Monday mode (even though this is still Sunday).

Sorry for the trouble!

**Comment by merdok** [comment]
No problem 😄 
I think the issue can be closed then.
