### ISSUE TITLE
TV not visible or accesible via HOME

### ISSUE THREAD

**Issue by Mikellas** [merdok/homebridge-webos-tv#268]
I have 3 Tvs ,two of them are working as exprected.My OLED which is also a newer model wont show up in Home app whatever i do.Config is exactly the same as two other TVs, i can control via Homebridge but the TV wont popup in Home no matter what i do.
I have checked Keys,IPs and config all seems good.Keep in mind that TVs where fine until yesterday when they started showing unresponsive,now only one has the isue a 65 inch LG OLED

**Comment by merdok** [comment]
Maybe you did not enable the required preferences on the TV? You could also post the debug log here when you start homebridge.

**Comment by Mikellas** [comment]
Hi Merdok,appreciate the reply.
All preferences were enabled on the device.
I reinstalled Homebridge and the TV showed up 
All good now thanks for the help
