### ISSUE TITLE
Volume switch missing

### ISSUE THREAD

**Issue by Tim2309** [merdok/homebridge-webos-tv#270]
My OLED C9 is missing the volume switches if I set "volumeControl": "switch"
With the setting "both" I see the slider AND the switches. I use HDMI arc and can't use the slider so I don't need it.

**Comment by merdok** [comment]
Hi,

You have to use "buttons" if you just want to have the volume Up/Down buttons.

**Comment by Tim2309** [comment]
if I set it to "switch" the 2 buttons are missing. I only see the channel up/down and the input-selection.
if I set it to "both" I see 4 buttons (channel up/down, volume up/down) and the volume slider

**Comment by merdok** [comment]
Please check the README for available values. There are only 3 possible:

- "both"
- "slider"
- "buttons"

The value "switch" does not exist for that property...

**Comment by Tim2309** [comment]
Ok now it works with "buttons"

The mistake is in the "Homebridge Config UI X" Plugin (see screenshot)

![Alt text](https://i.imgur.com/Q1zvpHs.png "Optional title")

**Comment by merdok** [comment]
Oh, this is a bug! Thanks for the info. I will fix that!

**Comment by Tim2309** [comment]
Ok perfect.
You can close the issue anytime after it's fixed.

**Comment by merdok** [comment]
Fixed in 1.9.2
