### ISSUE TITLE
Issue adding TV to Homekit

### ISSUE THREAD

**Issue by flyingsqu1d** [merdok/homebridge-webos-tv#271]
I've installed the plugin and successfully paired it with the TV. Changes in the TV's state are being logged by Homebridge but the TV is not appearing as an option to add as as an accessory in the Home app. I've tried removing the plugin, reinstalling it, rebooting homebridge. I'm following the directions for adding from the Readme.

**Comment by merdok** [comment]
Did you follow this point from the README: https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-home-app ?

**Comment by flyingsqu1d** [comment]
Yes, I've tried that many times and the TV never appears in the Home app as an accessory I can add.

**Comment by merdok** [comment]
Try to add it manually as specified  in the homebridge log. Should be something like:
`Please add [LG Tv] manually in Home app. Setup Code: 011-21-189`
Also you could try to change the name temporary and see if that helps.

**Comment by flyingsqu1d** [comment]
I resolved the issue by clearing my Homebridge cache. Required re-pairing with homekit but TV works great now. Thank you for your help.

**Comment by merdok** [comment]
Glad that it is fixed now!
