### ISSUE TITLE
Notification causes content to play when previously paused. 

### ISSUE THREAD

**Issue by mlaine2013** [merdok/homebridge-webos-tv#272]
Steps to replicate  

Open Netflix. 
Start playing content. 
Pause content. 
Trigger notification. 
Notification appears, however content starts playing automatically.

**Comment by merdok** [comment]
Sorry i do not use Netflix so i cannot test that, but i guess that this is most probably an issue caused by the Netflix app. There is no manual command which i issue to play the content when a notification is shown.

**Comment by DarkSupremo** [comment]
Yeah, it's probably an issue with netflix, on my LG Oled, when screens goes in ScreenSaver, and i move the remote, the screensaver goes off, and the content is unpaused aswell... it only happens on netflix...

**Comment by merdok** [comment]
@DarkSupremo thanks for confirming what i suspected. 

I think this can be closed then, since there is nothing really that can be done about it.
