### ISSUE TITLE
Defining more than 3 inputs doesn't work

### ISSUE THREAD

**Issue by saschaspeidel** [merdok/homebridge-webos-tv#274]
Hi there,

I just updated my config to use "platform" and looked over my config. So I added another HDMI to my inputs:

```
                    "inputs": [
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "XBOX"
                        },
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "Apple TV"
                        }
                    ],
```

I saved the config and restarted Homebridge but the newly added "Apple TV" is not showing up. I changed the order of the inputs and it seems like only 3 inputs are shown in Apple's Home App.
Can anyone confirm this issue?

Best regards 
Sascha

**Comment by ggroel** [comment]
I have this config and function very well!!!

            "platform": "webostv",
            "devices": [
                {
                    "name": "TV Living",
                    "ip”: "IPofTV",
                    "mac": “MACofTV",
                    "pollingInterval": 5,
                    "showInputButtons": false,
                    "volumeControl": "slider",
                    "channelControl": false,
                    "mediaControl": false,
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Telecentro"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi3",
                            "name": "PS4"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "YouTube"
                        },
                        {
                            "appId": "youtube.leanback.kids.v4",
                            "name": "YouTube Kids"
                        },
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        }
                    ]
                }
            ]

Gastón

**Comment by merdok** [comment]
Hmmm, that should not happen. I have about 30 inputs defined on my tv and all are available😅

Did you try to force close the home app? Sometimes this might be simply a cache issue. 
Also is there any error or warning in the homebridge debug log?

**Comment by saschaspeidel** [comment]
I deleted the device and re-added it. Now all 4 inputs are visible. Sorry I bothered you and thanks for your help.
