### ISSUE TITLE
Volume limit UX tweak

### ISSUE THREAD

**Issue by cknowles** [merdok/homebridge-webos-tv#276]
Currently if the volume limit function is used then the volume slider percentage is mapped directly to the volume value. So it does not perform much function after this value. e.g. set the limit to 20, using the slider sets the values as follows:
10% - 10 absolute volume
20% - 20 absolute volume
30% - 20 absolute volume
50% - 20 absolute volume
etc

Given the slider is a percentage, I think it would be more expected if it represents a percentage of the limit. e.g. set the limit to 20, using the sliders would set the values as follows:
10% - 2 absolute volume
20% - 4 absolute volume
30% - 7 absolute volume (closest to 6.67)
50% - 10 absolute volume
100% - 20 absolute volume

What do you think?

**Comment by ggroel** [comment]
I like the second option better ... maybe there could be a third option ... I don't know if it can be done, but that the slider stays at the limit ... that no matter how much I want to increase it, it cannot ...  example:

10% - 10 volume
15% - 15 volume
20% - 20 volume (limit)
25% -> 20% - 20 volume (limit)
30% -> 20% - 20 volume (limit)

Pardon for my bad English... I’m from Argentina.

Thanks,

Gastón

**Comment by merdok** [comment]
I think that changing the range of the volume slider depending on the volume limit is not a good idea and could bring confusion in.  The volume range of the TV is always 0-100, and this should be always clearly communicated. The volume limit adds an additional layer to the volume control which should not affect the range. Besides that i cannot adjust the range of volume display on the TV itself.
As of your concern that the volume slider does not have any function after reaching the limit is understandable. In the upcoming 2.0.0 update of this plugin the volume limit function has been improved, and as soon as you hit the volume limit on the slider then will instantly stop at that level, clearly indicating that the volume limit has been reached and no further volume adjustment is possible. 
@ggroel this is exactly how it will look like in the 2.0.0 update 😉

**Comment by ggroel** [comment]
ohh ... I'm liking 2.0.0 (without seeing it)

Gastón

**Comment by c-knowles** [comment]
@merdok I guess it depends if the absolute volume on the TV itself is treated as a percentage or a value. From the iOS Home app side, it’s definitely a percentage and labelled as such. But not on the TV. Understood the number cannot be change on the TV itself.

My thought was basically that I limited mine to 15-20 absolute value as that’s already very loud. So in my case the UI space to adjust on iOS is very tiny and hard to use.

**Comment by merdok** [comment]
The value which you see in the Home app should be the exact same as you see on the TV, that is why only absolute value makes sense here. When there are 2 different values then this just unnecessary confuses people.
