### ISSUE TITLE
Edit TV Screen

### ISSUE THREAD

**Issue by Supermarco333** [merdok/homebridge-webos-tv#277]
Hello,

I just want to know if it's possible to rearrange the buttons inside the Home app. I mean, I would like to place the volume slider next to the power button, is that possible ?

By the way, I just saw the announcement for the 2.0.0 update. I can't wait for it as I know that performance improvements were announced. Do you have any date @merdok ?

Thanks for your amazing job.

**Comment by merdok** [comment]
As far as i know the buttons cannot be rearranged, the only way is to show all the accessories from the TV as separate tiles but i guess that would make it more messy.

The 2.0.0 update should most probably be released in September. In mid September i am going on vacation, and i hope to get it out before that but if i do not make it till that time then it will be end of September.

**Comment by Supermarco333** [comment]
All right then. Perfect. :)
