### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jadomski** [merdok/homebridge-webos-tv#279]
Attempting to install using the current LTS version (12.18.3) of Node.js on an arm64 processor, getting the following output:

```gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jeff/n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-1015-raspi
gyp ERR! command "/home/jeff/n/bin/node" "/home/jeff/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jeff/n/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I've also attempted using the current version (14.9.0) of Node.js without any resolution. Finally I tried to update npm and that did not help either.

**Comment by merdok** [comment]
This is an issue with the the node-gyp package and not with the plugin. You probably have some configuration issues or maybe permissions are not correct, but it is for something with your local environment.

**Comment by jadomski** [comment]
I've tried stock installs of Node.js LTS and Current directly from nodejs.org on Ubuntu 20.04, so whatever is bundled with the stock versions seems to be incompatible

**Comment by merdok** [comment]
This is most probably a ubuntu specific issue with node-gyp you should maybe open an issue on their repo as the issue you are facing is completely not related to this plugin.

**Comment by jadomski** [comment]
I get what you’re saying, but I’m not using the Ubuntu repos. I’m using the official binaries from Nodejs.org

**Comment by merdok** [comment]
You could try those steps. https://codeforgeek.com/make-failed-with-exit-code-2/ Besides that i can only advice you to open an issue in the node-gyp repo.

**Comment by jadomski** [comment]
Thanks for that resource. Installing the build-essential package and it’s dependencies resolves the issue.
