### ISSUE TITLE
Can't Update homebridge-webos-tv, LG TV showing as Not Responding

### ISSUE THREAD

**Issue by philipamour** [merdok/homebridge-webos-tv#280]
My LG TV remote via Apple Home stopped working all of sudden. When trying to update homebridge-webos-tv, I get the following error:

`$ sudo npm install -g homebridge-webos-tv

> bufferutil@4.0.1 install /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
> node-gyp-build

gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.18.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil/.node-gyp'
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Running home bridge in debug shows this:
`[9/7/2020, 10:58:09] Error loading accessory requested in your config.json at position 1
[9/7/2020, 10:58:09] Error: The requested accessory 'webostv' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)`

Any suggestions? I'm on raspberry pi, latest raspbian, latest homebridge, npm v6.14.8, node v12.18.3

**Comment by merdok** [comment]
Thus is not an issue with this plugin! Your node permissions are not correct hence dependencies cannot be built, you need to fix your permissions or run the non install as sudo or with the flag --unsafe-perm

**Comment by philipamour** [comment]
Thank you so much! It was a combination of things. Had to reinstall npm, homebridge (with the new web ui and different way of launching on reboot), clear some directories, and redo config for lgtv because of the syntax change. Looks like I haven't touched home bridge and any of the plugins for a while, then updated node/npm + the plugins and things started breaking. All seems to be good now.
