### ISSUE TITLE
2.0.0 Not working with my config anymore and crash - LG Modell 55EG9209-ZA, Software 04.26.00, webOS 2.2.3-1351 (beehive-biscayne)

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-webos-tv#284]
Thanks for the ongoing development.
However I have some trouble with 2.0.0.
Nothing is working with my existing config.
Buttons show up in Home App but no function. Neither the control buttons nor the notifications work.
And I also got a shutdown after some time.

Going back to 1.9.3 and everything was working again.

```
{
            "platform": "webostv",
            "devices": [
                {
                    "name": "LG webOS TV",
                    "ip": "xxx.xxx.xxx.xx",
                    "mac": "a1:b2:c3:45:de:67",
                    "pollingInterval": 10,
                    "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                    "inputs": [
                        {
                            "appId": "maxdome",
                            "name": "Maxdome"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Hauptbildschirm"
                        }
                    ],
                    "showInputButtons": true,
                    "volumeControl": "buttons",
                    "channelControl": false,
                    "mediaControl": false,
                    "notificationButtons": [
                        "Backofen vorgeheizt.",
                        "Wasserkocher fertig.",
                        "Haustür klingelt.",
                        "Luftqualität in der Wohnung schlecht. Bitte lüften."
                    ]
                }
            ]
        },
```

```
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]: [2020-9-10 10:44:37] TypeError: Cannot read property 'information' of undefined
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at webosTvDevice.remoteKeyPress (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:988:71)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at RemoteKey.emit (events.js:315:20)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at RemoteKey.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at RemoteKey.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:652:12)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1439:24
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at Array.forEach (<anonymous>)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1281:10)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at HAPServer.emit (events.js:315:20)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:812:12)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at IncomingMessage.emit (events.js:315:20)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at endReadableNT (_stream_readable.js:1220:12)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]:     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Sep 10 10:44:37 raspberrypi-3BPlus homebridge[7583]: [2020-9-10 10:44:37] Got SIGTERM, shutting down Homebridge...
```

**Comment by merdok** [comment]
Lots of things changed in the latest update, one of them is the removal of the inputs property(as stated in the changelog). So you will have to slightly adjust your config, you even do not need that entry anymore.

The error which you are experiencing is most probably happening when you use the control center remote, and this is actually an issue. I will fix that one later today.

**Comment by DJay-X** [comment]
Thanks for your fast reply.
"notificationButtons": also didn't work anymore and there were showing a lot of other buttons I really don't need or my LG is not supporting. 
I will wait for a next update and give it another try then and hope to keep the small setup I have like it is. ;)
Thanks again.

**Comment by merdok** [comment]
You could try to re-add your tv to home. Maybe you have some caching issues? Also I would recommend you to always force kill the home app if you see some weird behavior. Usually sich issues are cache related...

The update was mostly meant to simplify the plugin. If you do not want to play around with anything, then you just simply install the plugin and that's it, the only config you need to do is to enter the ip and mac of your tv.
This basic installation will give you native HomeKit experience, and all other stuff can stay off.

**Comment by mrNakamura** [comment]
Whilst the update certainly has improved things, I got the same issue here for the home bridge crash on control centre remote.

Not sure how I feel about the removal of the input section, as the only thing showing in the input box on the home app is "Live TV".  I previously had other HDMI inputs in that list too that are now gone.    I did experiment by adding an App Button to represent say HDMI3 input so I could switch to that, but a side affect of this is also that in the iOS home app summary, it now adds an item to the summary saying 'switch is on'.  My query here is really, should the home app be showing more inputs than "Live TV" that it automatically reads from the TV itself, or have I misunderstood?

**Comment by merdok** [comment]
@mrNakamura the crash with the cc remote will be fixed later today.

Per default only Live TV and some inputs will be available in the spinner. You can add more apps to the spinner by simply opening the preferences section of your TV in the Home app and enable whatever other inputs you want to have in the spinner.

**Comment by mikementzmaersk** [comment]
Thanks, also good to know it’s called the spinner :-) will give it a try (thought i was misunderstanding something)

**Comment by merdok** [comment]
@mikementzmaersk well i call it the spinner or input spinner 😜

**Comment by mikementzmaersk** [comment]
Actually, where is the preferences section of the tv in the home app? after clicking the cog, i see the usual stuff like suggested scenes, include in favourites etc. but not much else.

**Comment by mrNakamura** [comment]
Cheers 😉
Actually, where is the preferences section of the tv in the home app? after clicking the cog, i see the usual stuff like suggested scenes, include in favourites etc. but not much else.

**Comment by merdok** [comment]
You need to dig a little bit inside. You are probably checking the preferences of the TV group, but you need to go on "devices" and then there on the TV accessory.

**Comment by mrNakamura** [comment]
Found it.  cheers 👍🏻

**Comment by merdok** [comment]
@DJay-X  @mrNakamura the crash should be fixed now in Version 2.0.1

**Comment by mrNakamura** [comment]
Yup, fixed for me.  Thanks. 👍🏻

**Comment by DJay-X** [comment]
@merdok 

Thanks for your help.
However I have serious problems with the Plugin.
Even with my basic use of features.

I changed my config. Did I do something wrong?

Notifications are not working at all.
The buttons show up in Home App but no toast message on the TV as with 1.9.3 was working perfectly.

Switiching to "Maxdome" or "Hauptbildschirm" is working but with a delay of nearly 30 seconds until the TV is doing something. Meanwhile the Button in HomeKit is showing off.
Turning back from "Maxdome" to "Hauptbildschirm" is doing the same. 25-30 seconds until anything is happening and then the button in HomeKit is showing off, even the TV is switched to "Hauptbildschirm" now. 

With 1.9.3 everything was working immediately in one second.

I hope you can help.

LG Modell 55EG9209-ZA, Software 04.26.00, webOS 2.2.3-1351 (beehive-biscayne)


```
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "LG webOS TV",
                    "ip": "xxx.xxx.xxx.xx",
                    "mac": "a1:b2:c3:45:de:67",
                    "pollingInterval": 10,
                    "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                    "appButtons": [
                        {
                            "appId": "maxdome",
                            "name": "Maxdome"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Hauptbildschirm"
                        }
                    ],
                    "volumeControl": "buttons",
                    "notificationButtons": [
                        {
                            "message": "Backofen vorgeheizt.",
                            "name": "LG Backofen Notify"
                        },
                        {
                            "message": "Wasserkocher fertig..",
                            "name": "LG Wasserkocher Notify"
                        },
                        {
                            "message": "Luftqualität in der Wohnung schlecht. Bitte lüften",
                            "name": "LG Luftqualität Notify"
                        }
                    ]
                }
            ]
        },
```

**Comment by merdok** [comment]
@DJay-X you need to provide me a debug log so I can check if there is something strange...

**Comment by DJay-X** [comment]
> @DJay-X you need to provide me a debug log so I can check if there is something strange...

How can I reach you confidential? I guess it's not a good idea to make a detailed log with probably sensitive information public. Are you on forum.smartapfel.de? 
https://forum.smartapfel.de/conversation-add/?userID=22

**Comment by merdok** [comment]
The log should be harmless, anyway you could also send it to me on discord, but please note that I currently have no access to discord for the next week.

**Comment by DJay-X** [comment]
@merdok What's your ID at Discord?
Or old fashioned you can send a email to daniel[at]smartapfel.de
Thanks again for trying to investigate.

**Comment by merdok** [comment]
My name on discord is the same as here.
You can also send me a private message on Twitter.

**Comment by DJay-X** [comment]
It's not meant to be.. 🤷🏼‍♂️

![Napkin 11 09 20, 10 34 49 PM](https://user-images.githubusercontent.com/3874239/92970490-0cbda300-f47f-11ea-92ef-3ffb2b18a05e.png)

**Comment by merdok** [comment]
Try now on Twitter

**Comment by 977hr** [comment]
I’m having the same problem with the plugin on my LG 65UF860V-ZA running webOS 2.2.3-2150.

        
    "devices": [
                {
                    "name": "Televizija",
                    "ip": "192.168.XX.XX",
                    "mac": "ee:ee:ee:ee:ee:ee",
                    "pollingInterval": 5,
                    "deepDebugLog": true,
                    "hideTvService": true,
                    "volumeLimit": 30,
                    "volumeControl": "slider",
                    "channelControl": false
                }
            ],
            "platform": "webostv"
        } 


![E15C3178-B3B7-4275-94DF-2969F200F1D9](https://user-images.githubusercontent.com/60018512/93016059-b0619d00-f5be-11ea-951f-2e50217da97c.jpeg)
![C803D098-C45D-4DEC-BD56-05151D5CD222](https://user-images.githubusercontent.com/60018512/93016062-b48dba80-f5be-11ea-9757-731053ff8c21.jpeg)

Would much appreciate any ideas on how on how to fix this problem!

**Comment by merdok** [comment]
@977hr webos 2.0 TVs has issues with the new update since they do not support a required service. For now please downgrade to 1.9.3

**Comment by merdok** [comment]
Should be fixed in Version 2.0.3. Can you please confirm?

**Comment by DJay-X** [comment]
@merdok Thanks a lot. With 2.0.3 my Notifications, Switch Hauptbildschirm/Maxdome are working smoothly again.

However, I got a few more buttons now with status "on" I don't need and want. My TV didn't even have this features like "Camera", "Programmführer", or "Webbrowser". Also the Inputs AV-x and HDMI-x are always on. But I also don't need them.
Please see Screenshot attached. 
In my config.json there is nothing except the things I need.

Thanks again for the 2.0.3 update and in advance for your help how the hide/remove the additional buttons.

```
       {
            "platform": "webostv",
            "devices": [
                {
                    "name": "LG webOS TV",
                    "ip": "xxx.xxx.xxx.xx",
                    "mac": "a1:b2:c3:45:de:67",
                    "pollingInterval": 10,
                    "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                    "appButtons": [
                        {
                            "appId": "maxdome",
                            "name": "Maxdome"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Hauptbildschirm"
                        }
                    ],
                    "volumeControl": "buttons",
                    "notificationButtons": [
                        {
                            "message": "Backofen vorgeheizt.",
                            "name": "LG Backofen Notify"
                        },
                        {
                            "message": "Wasserkocher fertig..",
                            "name": "LG Wasserkocher Notify"
                        },
                        {
                            "message": "Luftqualität in der Wohnung schlecht. Bitte lüften",
                            "name": "LG Luftqualität Notify"
                        }
                    ]
                }
            ]
        },
```

![Napkin 21 09 20, 11 26 57 AM](https://user-images.githubusercontent.com/3874239/93751832-01e0dc00-fbfe-11ea-854f-6c7541a78050.png)

**Comment by merdok** [comment]
@DJay-X  this is a caching issue. Just force close the Home app (swipe up in the task manager) and the switches will go away.

**Comment by DJay-X** [comment]
That worked. 👍 Now I'm up-to-date again. Thanks a lot.
From my point of view you can close this issue if you like.

**Comment by merdok** [comment]
Sounds good! Thanks for letting me know!
