### ISSUE TITLE
Energy Saving ?

### ISSUE THREAD

**Issue by domeOo** [merdok/homebridge-webos-tv#287]
Hello Merdok,

loving the new option to turn off the screen. Is it possible for us to also dim the screen like this?
Maybe u can share a link to the API references you're using.

Would love to do a PR for that.

**Comment by merdok** [comment]
Unfortunately it is not possible to control the tv settings (brightness, contrast, etc) by a public available API. I am still trying to find  a workaround for that and if i find it then i will certainly add that option :)
