### ISSUE TITLE
Adding a second tv

### ISSUE THREAD

**Issue by Ludelag** [merdok/homebridge-webos-tv#291]
I added a second tv to the code, but it seems that will be erased in the V2.0 my code waas following yours, just copy as a second, my question is how to add a second tv correct. nevertheless I got this messageThe dynamic platform webostv from the plugin homebridge-webos-tv seems to be configured multiple times in your config.json. This behaviour was deprecated in homebridge v1.0.0 and will be removed in v2.0.0!

Find please what i did, actually is working properly

{
            "devices": [
                {
                    "name": "My LG TV SALON",
                    "ip": "000.000.000.000",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true,
                    "soundOutputButtons": [
                        {
                            "soundOutput": "external_optical"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        },
        {
            "devices": [
                {
                    "name": "My LG TV TXOCO",
                    "ip": "000.000.000.000",
                    "mac": "xx:xx:xx:xx:xx:Xx",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true
                }
            ],
            "platform": "webostv"
        },

**Comment by merdok** [comment]
You configured it wrong. You just need to add the platform once and configure your TVs under devices.

**Comment by Ludelag** [comment]
@merdok Thank you. I did as you told me, I´ve remake the configuration but once the second tv is added under devices, the tv second tv dessapear and is not recognised by Apple Home, Bothe tv has different WeBos version.

So in cloclusion the second tv stop working in Home

**Comment by Ludelag** [comment]
{
            "devices": [
                {
                    "name": "My LG TV SALON",
                    "ip": "192.xxx.xxx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true,
                    "soundOutputButtons": [
                        {
                            "soundOutput": "external_optical"
                        }
                    ]
                },
                {
                    "name": "LG TXOCO",
                    "ip": "192.xxx.xxx.xxx",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true
                }
            ],
            "platform": "webostv"
        },

**Comment by merdok** [comment]
Your config seems ok now, did you add both of your TVs to the home app manually?

**Comment by Ludelag** [comment]
Yes, but only the first TV is recognised. The second seems to be working correctly in Homebridge but Apple Home doesn’t see the second tv. How ever when I configure a second plug-in web with Webos platform works back the second tv normal

**Comment by Ludelag** [comment]
I decided to asígnate a new ip to the tv and only so Apple home was able to see the LG tv and ws possible to add to home. Whatever does not respond to the commands as the other tv. Practically does not answer at all. The LG tv asked to allow connect to the device, I suppose was the HomeBridge, it was accepted.
Any it does not answer as was answering before the recent update.
Both tv were working quiet well with the previous plugin version beside both have different webos version and using twice the platform.
Is possible to get back to the previous version

**Comment by merdok** [comment]
Oh, is one of your TVs a webos 2.0 tv? If so then you need to downgrade to 1.9.3 for now since there is an issue with those
TVs on the recent update.

**Comment by Ludelag** [comment]
Yes, one of them is webos 2.0 How could I downgrade? uninstal the actual version and instal the 1.9.3 from stock?

Is it planned to fix the issue with the webos 2.0 in the coming versions?

Thank you !

**Comment by Ludelag** [comment]
I downgrade already, looks like the tv with Webs 2 is working again. Sorry for writing you so much and disturbing your activities. Just one more question, is planned to fix the issues with the webs 2 in the coming version of the plugin webos?
Thank you

**Comment by merdok** [comment]
Good to hear that it is fixed for now. 
About the fix, well I am still thinking on how to proceed here. Maybe there will be a separate plugin for webos 2.0 TVs, but if I find a way to include it in the main plugin then I will add it here.

**Comment by Ludelag** [comment]
Thank you for taking your time replying to me. If would like to have my thoughts, I think will be to much more easier and maybe more efficient to have two different plugins.

**Comment by merdok** [comment]
That would definitely be the best solution, but then I have to Mai rain 2 code bases which would be not that efficient. Anyway I will think about it.

If your problem is fixed for now, can this issue be closed?

**Comment by Ludelag** [comment]
Yes ! It can be closed, thank you again
