### ISSUE TITLE
Input not properly changing when turning on TV

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-webos-tv#294]
I have some automations and shortcuts running where the TV (LG OLED E6) is turned on and is supposed to change the HDMI input. This was working fine till 1.9.3.

Since 2.X the TV won’t change the input to what it is set in HomeKit when turned on. I have nothing changed in my setup. Any idea?

**Comment by stevenmarq** [comment]
I have the same issue.

**Comment by merdok** [comment]
You need to use `appButtons` for that. This is basically meant to be used for that.

**Comment by CooperCGN** [comment]
Wait, so I need to add further accessories to HomeKit just to get the right input at TV start up? Thought you said that 2.0 is almost like native HomeKit. I think I will revert then to 1.9.3, don’t wan to clutter up my HomeKit, it was already a hassle to get all family members on board ;)

**Comment by merdok** [comment]
Native homekit has no possibility to change inputs per automations, this was also the same in 1.9.3, this is a homekit limitation. You had to create buttons for each inputs to make automations work.

**Comment by CooperCGN** [comment]
Then I have no idea why 1.9.3 was switching my HDMI inputs properly depending on what I selected in the TV accessory itself inside the automation.

**Comment by merdok** [comment]
Please be more specific what was working before, at best please post a config which was working from you and some screenshots how you configured your automation in the Home app, so i can at least understand more clearly what you mean and try to reproduce it with my TV.

**Comment by CooperCGN** [comment]
Writing from the phone now so screenshots need to be added later.

What I meaning the following. Under 1.9.3 I had to manually configure my required inputs. For me these were only three HDMI ports. When I add the TV then to a scene (or automation) I was able to long press the TV icon and select the desired input in that scrollable list shown. When activating the scene the TV switched to that HDMI port automatically.

**Comment by CooperCGN** [comment]
Quickly made to screen shots
![1A45687C-376E-474D-BEAA-AF7E4DCA89A3](https://user-images.githubusercontent.com/29116509/93645376-28d3be00-fa04-11ea-8e97-0c7f04a1d258.jpeg)
![D802C547-A324-4916-8EB7-0C36594E8814](https://user-images.githubusercontent.com/29116509/93645382-2a9d8180-fa04-11ea-90bf-da4ec73896d7.jpeg)

**Comment by CooperCGN** [comment]
Now this is weird, maybe it is an iOS problem, I just updated my iPad to iPadOS beta 14.2 and now my shortcuts and scenes seem to run fine. Will do some further testing and let you know.

**Comment by merdok** [comment]
Just tried it with my TV and i do not see any issue, it works as you described it. Did not actually know that you can control inputs using scenes. Good stuff 👍

**Comment by CooperCGN** [comment]
Sorry but I have to come back. Something must have changed in the code regarding this, the change of input when turning on the TV only works when the TV is still in that pixel refresh mode. This morning after being off for several hours it doesn’t work anymore. Maybe there needs to be a slight delay?

**Comment by merdok** [comment]
I can confirm that in version 1.x.x there was a hardcoded delay which basically checked if the TV is on and then switched the input. In version 2.x.x i listen to an event which the TV sends me when it is turned on, maybe this is still to early and i need to wait a few more seconds before switching the input (might be TV dependent, the newer models are faster so maybe they can handle that better).

Anyway i will try to have a look at it today at the evening and see if i can find a fix for that.

**Comment by merdok** [comment]
Should be fixed in Version 2.0.3. Can you please confirm?

**Comment by CooperCGN** [comment]
Will check tomorrow, family is watching TV ;)

**Comment by CooperCGN** [comment]
So from my first try this morning it is fixed. Thank you very much.

**Comment by merdok** [comment]
Good to hear! Sorry for that, because of the big update some things might have broke since i could not test everything. If you find more issues then just let me know!
