### ISSUE TITLE
Version 2.0.3

### ISSUE THREAD

**Issue by Ludelag** [merdok/homebridge-webos-tv#296]
This is actually a question of verification, The new version 2.0.3 accept already the Webos 2.xx version? could be possible already to update to this version since I have 2 tv, one with Webos 2 and the other with 4?

Thank you

**Comment by merdok** [comment]
Yes, you can update safely to 2.0.3 and your webos 2.0 TV should work fine again! Please close the issue after you update and do not have any issues!

**Comment by Ludelag** [comment]
Yes !!!! is working properly, fast and good, thank you very much for you assitance, fast asnwer and for such a nice plugin!
