### ISSUE TITLE
Voice commands volume up down

### ISSUE THREAD

**Issue by Strike2001** [merdok/homebridge-webos-tv#297]
in homekit when you ask
siri ; set tv to louder , set tv to Volume ... %
 no respond , device do not have this option . this voice commands never worked before . remote sode buttons worked , remapping worked too , button slider working too , but voice commands ends in errors. also voice commands to change inputs .

**Comment by merdok** [comment]
All of the commands work. First of you need to enable the channel and volume service since Siri cannot change the volume of your TV natively. Also you need to make sure that when you ask Siri to change the volume or channel that you say the exact name of your configured switch.

**Comment by marioPS** [comment]
HI @Strike2001 - I think this is more an issue with HomeKit than Homebridge or this plugin in particular.
If I say "Set Living Room Volume to 13%", Siri adjusts the volume on my phone. If I then say "Set Living Room to News", it changes it to the News FTA Channel, *then* follow it with "Set Living Room Volume to 13%", Siri adjusts the volume on my LG TV.
There are so many variables and peculiarities in HomeKit - you may have to send a few 'known working' commands in first for Siri to get context for your volume command.
I hope this helps - let us know how you go!

**Comment by BonRm** [comment]
Hi, I have the same problem. With Siri I'm able to turn the TV on or off only. 
@merdok What do you mean with "to enable the channel and volume service since Siri cannot change the volume of your TV natively"? how to enable these services?

Thank you

**Comment by merdok** [comment]
@BonRm just check the configuration section in the README to see how to enable those services.

If you have an issue with the remote control then you need to post some debug log so i can check if there is something wrong.

**Comment by BonRm** [comment]
thank you @merdok yes, I read it, they are already enabled since I can see the buttons and are working good except using the voice commands. 
I just solved now changing the name of the volume buttons. 

Now it's not working with Siri to select the Input source like "live tv" or "HDMI1", CAn you suggest me wich syntax to use with siri?

**Comment by merdok** [comment]
Siri cannot change inputs as far as i know and this is again a limitation from HomeKit. But i prepared a workaround for that: simply create yourself the inputs which you use the most often as `appButtons`. This will allow you to use Siri to control them.

**Comment by BonRm** [comment]
ah ok, thank you for your help ;)
