### ISSUE TITLE
Key file dir broken....

### ISSUE THREAD

**Issue by grzegorz914** [merdok/homebridge-webos-tv#298]
Hi,

if we set our own key file directory then the file is not stored anymore and every restart need to pair TV again.

**Comment by merdok** [comment]
Hi,

this is a permission issue, if you change the directory of the keyfile then you need to make sure that homebridge has the correct permissions to access and write to that directory.

**Comment by Strike2001** [comment]
can confirm this error

**Comment by merdok** [comment]
@Strike2001 also here, this is most probably a permission issue.

**Comment by grzegorz914** [comment]
No,

it’s not permission issue, in same directory are stored TV info and inputs correct.

**Comment by merdok** [comment]
Just tried it with mine TV, tested various different locations and all work fine for me (also same directory as TV info and inputs). 

I suspect this is a permission issue on your side. If you have an error or log message can you provide that so we can have a look?

**Comment by grzegorz914** [comment]
Just tried again and same effect for all my 3TV, nothing in the log with debug mode, I use this directory "/var/lib/homebridge/lgwebosTv" as prefsDir and keyFile but only inputs and tv info data is stored here correctly, no any keyFile there. If use default directory the key is stored in "/home/user/.lgtv2/".

**Comment by Strike2001** [comment]
maybe a clean install of the npm can fix ? 

Von meinem iPhone gesendet

**Comment by merdok** [comment]
I hope you know that the `keyFile` property is should be a file not a directory... 
`"/var/lib/homebridge/lgwebosTv"` this of course will not work since there is already a directory with that name so a file named `lgwebosTv `cannot be created. Can it be that this is the issue?

**Comment by grzegorz914** [comment]
OK, 
working....
the description and title in settings need to change from "Key file location", to "Key file name and location",
"The location where to store the tv key file. Default is: ~/.lgtv2/keyfile" to "The location and key file name where to store. Default is: ~/.lgtv2/keyfile"

**Comment by grzegorz914** [comment]
I see the key file also do not use the prefsDir, if we set only name then is stored direct in Homebridge path. It is little misunderstanding. It will be better if "keyFile" use "prefsDir" as its path and we set only the "key name" in settings.

**Comment by merdok** [comment]
It is stated in the README that `keyFile` is a file and a directory should not be specified. 
Maybe it would be better to put the keyFile indeed into the prefs directory. Actually the keyFile property could be entirely removed. But it will break the tv permissions for all users after the update so i am not sure if this is a good idea to change it now. Will think about it.

**Comment by grzegorz914** [comment]
OK
