### ISSUE TITLE
Mute state not correct

### ISSUE THREAD

**Issue by grzegorz914** [merdok/homebridge-webos-tv#300]
Hi,

I have observed that the Mute state is not correct, if TV is Off the mute state on tile is OFF, if TV is ON the mute state on tile is ON. 
![FEBDECBD-2A71-4507-94BE-3373C46A6CC5](https://user-images.githubusercontent.com/28867813/93920280-3f815a00-fd0f-11ea-92cb-52189860080d.jpeg)

**Comment by merdok** [comment]
Probably related to #299 . Will check it out.

**Comment by merdok** [comment]
Should be fixed in version 2.0.4. Thanks for reporting!

**Comment by grzegorz914** [comment]
Yes, now is working correct.

Thanks
