### ISSUE TITLE
TV no response

### ISSUE THREAD

**Issue by Mikellas** [merdok/homebridge-webos-tv#301]
Since ios14 i get this error alot on all my Tvs.This happens especially when outside my network.Sometimes its fixed by simply restarting homebridge or even the Home app.Can someone assist?

Thanks

**Comment by Mikellas** [comment]
![Uploading CD423B03-B75B-4227-AEFB-29F8913903AB.png…]()

**Comment by merdok** [comment]
Maybe try to force close the Home app and see if that helps.

**Comment by Mikellas** [comment]
Hi Merdok,
As i said above force quitting Home or restarting Homebridge sometimes fixes this but it happens to me like 10 days during the day and these are the only accessories that wont respond

**Comment by merdok** [comment]
This more looks like a local issue on your side. I also have iOS14 and did not experience anything like that. Maybe your device on which homebridge runs is overloaded?

**Comment by Mikellas** [comment]
It might be a local issue but cant get around it ,since my machine still has alot of resources  and all other plugins have  no issue.
Could i maybe debug this somehow?

I am also attaching my config maybe you find something unusual there(i have removed mac addresses)

Thanks

"devices": [
                {
                    "name": "Living Room TV",
                    "ip": "192.168.88.248",
                    "mac": "------",
                    "keyFile": "C:\\LGkeys\\lgtvKeyFile",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "buttons",
                    "channelControl": true,
                    "mediaControl": false,
                    "appButtons": [
                        {
                            "appId": "netflix",
                            "name": "Neflix"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "Youtube"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.photovideo",
                            "name": "Videos and Photos"
                        }
                    ]
                },
                {
                    "name": "Master Bedroom TV",
                    "ip": "192.168.88.245",
                    "mac": "-------",
                    "keyFile": "C:\\LGkeys\\lgtvKeyFile1",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "buttons",
                    "channelControl": true,
                    "mediaControl": false,
                    "appButtons": [
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "Youtube"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.photovideo",
                            "name": "Videos and Photos"
                        }
                    ]
                },
                {
                    "name": "Kitchen TV",
                    "ip": "192.168.88.247",
                    "mac": "-------",
                    "keyFile": "C:\\LGkeys\\lgtvKeyFile2",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "buttons",
                    "channelControl": true,
                    "mediaControl": false,
                    "appButtons": [
                        {
                            "appId": "netflix",
                            "name": "Netflix"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "Youtube"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.photovideo",
                            "name": "Videos and Photos"
                        }
                    ]
                }
            ],
            "platform": "webostv"

**Comment by merdok** [comment]
Config looks ok and there is honestly nothing to debug. I suspect that this is basically a performerce issue on your side. Maybe a network issue?

**Comment by Mikellas** [comment]
Wouldnt that affect other plugins as well? Anyway i will try restarting my switch since the TVs are all wired,that might be an issue ill report my results in a while

**Comment by merdok** [comment]
Here was a similär issue #285. This was also related to some local things. Sometimes HomeKit can have issues so it usually helps to re-add device or do a complete Home clean.

**Comment by hylkefaber** [comment]
I might have a similar issue. Just installed Homebridge yesterday, tried this plugin for my 2019 B9. So I have no previous setup buttons in my homekit, it just doesn't show up when I try to add them. Might be the same issue? Weird thing is: the buttons on the HB-config-UI-x web-interface work as expected. They just do not show up in the Home iOS app. Running iOS 14.

**Comment by merdok** [comment]
@hylkefaber you need to add the tv to HomeKit first before it will appear there. Check the README on how to do that, there is an extra section for that describing the steps.

**Comment by Mikellas** [comment]
Forgot to post results it was my switch that had an issue after restart tvs where show correctly
