### ISSUE TITLE
TV being duplicated on Alexa

### ISSUE THREAD

**Issue by neo3** [merdok/homebridge-webos-tv#303]
Hello,

I have a big issue of my TVs options being duplicated in the homebridge-alexa plugin after 1-2 days configured.

After configuring everything correctly, after 1-2 days Alexa identifies my TVs as new devices and the old ones already configured stop working.

Only this plugin happens, the others kept normal without duplicating. Has anyone had this issue?

**Comment by merdok** [comment]
I think that you should open an issue at the homebridge-alexa plugin repo. I have no knowledge how that plugin works or what it does to identify the devices so i really cannot help you here.

**Comment by neo3** [comment]
I'm also trying to see with the Alexa plugin author, but I think there is something related to that part of this plugin:

[2020-9-25 11:47:26] [webostv] [TV do Quarto] Connected to TV
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Got TV information
[2020-9-25 11:47:27] [webostv] [TV do Quarto] TV webOS version: 3.5
[2020-9-25 11:47:27] [webostv] [TV do Quarto] App launched, current appId: com.webos.app.miracast
[2020-9-25 11:47:27] [webostv] [TV do Quarto] TV turned on!
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Sound output changed. Current sound output: tv_speaker
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Subscribed to TV services
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Connected to remote pointer input socket
[2020-9-25 11:47:27] [webostv] [TV do Quarto] Setup finished
[2020-9-25 11:47:27] [webostv] [TV do Quarto] TV setup finished, ready to control tv
[2020-9-25 11:47:44] [Alexa] alexaDiscovery - returned 40 devices

**Comment by merdok** [comment]
This is just a log output indicating that a tv was found and that the setup was successful.

**Comment by merdok** [comment]
@neo3 any update on that issue?

**Comment by elpocholo7** [comment]
Hello Merdok! First of all let me thank you for your totally awesome WebOS plugin, it changed the way I interact with my TV completely (for the better). 
Unfortunately I’ve been having (it’s been at least 5 months now) TV and TV inputs/buttons duplicates within Alexa after a few days. I don’t think it’s related to the Alexa homebridge plugin as this only keeps on happening on my TV device. I have many other devices configured on Homebridge and passed on to Alexa and none of them get duplicated over time. 
Is there anything I could help you with to try and troubleshoot it ? 
Thanks a lot!

**Comment by merdok** [comment]
Hi,
this is certainly an issue with the other plugin. The way that new devices are detected is not completely correct from what i understand. Each accessory has a unique id and basically a check missing in that other plugin if an accessory with such a id has been already added before. 
In short, basically the other plugin does not take into account that an accessory information service can be remove and re-added on the fly which is a valid use case.

**Comment by neo3** [comment]
This issue happens because the devices of this plugin sometimes show as Unknown instead of the name LG, this way the Alexa plugin considers it as a new device.

The solution for me was to disable devices on Alexa with Unknown in the name to continue controlling normally.

**Comment by merdok** [comment]
@neo3 a device will always appear as unknown after you restart homebridge since the plugin first needs to detect the TV. Without first connecting to the TV there is no way to know that TV is used.
Anyway this should not happen since even when the device appears as Unknown at the beginning the id of the accessory does not change, so the other plugin needs to check the id before adding a new device and right now (i suppose) it is name based which causes the issue. 
@neo3 do you consider this issue as solved for you?

**Comment by elpocholo7** [comment]
> This issue happens because the devices of this plugin sometimes show as Unknown instead of the name LG, this way the Alexa plugin considers it as a new device.
> 
> The solution for me was to disable devices on Alexa with Unknown in the name to continue controlling normally.

Thanks for the answer @neo3 !
Could you please instruct me on how to disable devices with Unknown in the name ? Thanks a lot

**Comment by bx67212** [comment]
I resolve adding "filter": "homebridge ip:port", in alexa plugin configuration

**Comment by merdok** [comment]
@bx67212 thanks for sharing your solution 👍 

I think this can be closed at this point!
