### ISSUE TITLE
LGTV2012 Plugin and Webos-tv plugin interfer to each other

### ISSUE THREAD

**Issue by Ludelag** [merdok/homebridge-webos-tv#304]
I have installed the plugin LGTV2012 to my homebridge, configured with the TV info, it has worked quiet well, but then I notice that when I turn off the TV connected to this device all homebridge stop working no shelly plugin and now webos.tv plugin works properly, it could be interference between the two LG Plugins ? I decide to uninstall the plugin LGTV and erease from the Json the confirguration, all came to normal. How to fix this issue?

My LGTV2012 JSON configurations was:

{
"platform": [
{
"platform": "lgtv-2012",
"name": "MY LG KITCHEN",
"ip": "192.00.00.00",
"pairingKey": "123456",
"min_volume": 2,
"max_volume": 20,
}
]
}
Any ideas how could I fix it?

Thank you

**Comment by merdok** [comment]
Sorry i do not understand what you exactly mean? You need to specify your TV model and debug log... Do i understand it correctly that you have a LG 2012 TV and try to use this plugin for that TV? If so then this will most probably do not work...

**Comment by Ludelag** [comment]
Yes, one of the tvs is with Netcast system which works well with the plugin LGTV2012. As the other TV´s are with WEBOS and there are working well with your plugin webos-tv, but when I turn of the tv that use the plugin LGTV2012 with netcast, the plugin webs stops working and it seems to me cause also that Homebridge stop working. I don't if could be interference between both LG plugins. Sorry If I am disturbing you with that is just interesting but not really important.

**Comment by Ludelag** [comment]
> Sorry i do not understand what you exactly mean? You need to specify your TV model and debug log... Do i understand it correctly that you have a LG 2012 TV and try to use this plugin for that TV? If so then this will most probably do not work...

There is a possibility that the tv with Netcast LG could work over the  WEBOS-TV Plugin ?

**Comment by merdok** [comment]
If homebridge stops working then you have an error log which you need to analyse. This plugin will not work with netcast TVs since that is a completely different API.

**Comment by Ludelag** [comment]
thank you, I will check it.
