### ISSUE TITLE
YouTube video link

### ISSUE THREAD

**Issue by borewicz9** [merdok/homebridge-webos-tv#306]
Hello
after using this config:
....."appId": "youtube.leanback.v4",
"name": "YouTube",
"params": {
"contentTarget": "https://www.youtube.com/tv......”
TV open YouTube & link but before playback there’s question (do You like to open externar link) have to confirm
Is there any way to skip this question ?
Do I have to create scene like open YT link and after 5 sek press OK to open video automaticly ?

**Comment by merdok** [comment]
Hi,
this is something that google changed in their recent update of the youtube app for webos. Maybe there is a param for the youtube app which skips that question when launching a video but this just a speculation. This needs to be investigated further. For now you could setup a remoteSequence in a an automation with the youtube app button.

**Comment by borewicz9** [comment]
There’s nothing in YT TV app.
I’ll try with remoteSequence
Thx !
