### ISSUE TITLE
remote buttons doesn't work

### ISSUE THREAD

**Issue by stanleyhanes** [merdok/homebridge-webos-tv#308]
hi, i just installed this plugin (version 2.0.5). i got power button and volume slider working fine, but not with other control like remote buttons and sequence button.
can anyone help ?

**Comment by merdok** [comment]
Hi,

can you post debug log when you try to use the buttons?

**Comment by stanleyhanes** [comment]
[10/5/2020, 8:01:04 PM] [webostv] [LG webOS TV] Connected to TV
[10/5/2020, 8:01:04 PM] [webostv] [LG webOS TV] Got TV information
[10/5/2020, 8:01:04 PM] [webostv] [LG webOS TV] TV webOS version: 5.0
[10/5/2020, 8:01:04 PM] [webostv] [LG webOS TV] TV turned on!
[10/5/2020, 8:01:04 PM] [webostv] [LG webOS TV] App launched, current appId: com.webos.app.hdmi1
[10/5/2020, 8:01:04 PM] [webostv] [LG webOS TV] Sound output changed. Current sound output: tv_external_speaker
[10/5/2020, 8:01:55 PM] [webostv] [LG webOS TV] TV turned off!
[10/5/2020, 8:02:03 PM] [webostv] [LG webOS TV] App launched, current appId: com.webos.app.hdmi1
[10/5/2020, 8:02:03 PM] [webostv] [LG webOS TV] TV turned on!

there is no log when i use the button

**Comment by merdok** [comment]
Because you have to enable debug log, you can check on how to enable debug in the README.

**Comment by stanleyhanes** [comment]
i have enabled it

here is my config

            "platform": "webostv",
            "devices": [
                {
                    "name": "LG webOS TV",
                    "ip": "192.168.1.16",
                    "mac": "AC:F1:08:09:19:DA",
                    "keyFile": "/home/pi/.homebridge/.webosTv/lgtvKeyFile",
                    "prefsDir": "/home/pi/.homebridge/.webosTv",
                    "pollingInterval": 5,
                    "deepDebugLog": true,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "remoteControlButtons": [
                        "HOME",
                        "EXIT",
                        "MENU",
                        "RIGHT",
                        "LEFT",
                        "UP",
                        "DOWN",
                        "ENTER"
                    ],
                    "remoteSequenceButtons": [
                        {
                            "sequence": [
                                "MENU",
                                "RIGHT",
                                "ENTER",
                                "LEFT",
                                "LEFT",
                                "DOWN",
                                "ENTER",
                                "RIGHT",
                                "RIGHT",
                                "RIGHT",
                                "RIGHT",
                                "ENTER",
                                "MENU"
                            ],
                            "name": "Sleep"
                        },
                        {
                            "sequence": [
                                "MENU",
                                "RIGHT",
                                "ENTER",
                                "RIGHT",
                                "RIGHT",
                                "ENTER",
                                "MENU"
                            ],
                            "name": "Game"
                        }
                    ]
                }
            ]
        }

**Comment by merdok** [comment]
Config looks ok 👌 But the log is not a debug log. I would need a detailed debug log in order to find out what the issue is.

**Comment by stanleyhanes** [comment]
where to look for detailed debug log ?

**Comment by merdok** [comment]
Just check the bottom of the README, you have all info there on how to get a debug log.

**Comment by stanleyhanes** [comment]
here you go: https://pastebin.com/sM6iZy4X

**Comment by merdok** [comment]
This log has no entries of the plugin, this log just shows that your instance is crashing because you have another one running. You need to first stop your other instance of homebridge before you can start the debug one.

**Comment by stanleyhanes** [comment]
https://pastebin.com/sKEY8DuL
i found ETIMEDOUT

**Comment by merdok** [comment]
Loos better, now you just need to provide me the log when you try to use the switches which are not working for you...

**Comment by stanleyhanes** [comment]
[10/5/2020, 10:12:29 PM] [webostv] [LG webOS TV] Remote input socket - tv not connected or remote input socket not established!

**Comment by merdok** [comment]
Seems like there is no connection to the tv remote input socket. Maybe you missed to enable something on your tv? There are some options which you need to enable on the tv before everything will work.

**Comment by stanleyhanes** [comment]
what setting need to enable ? TV On with mobile ?
first time i install the plugin, the button worked fine. like 1 hour later, it stopped working.
but i can't see the debug log

**Comment by merdok** [comment]
Yes, and also some other but it is all written in the README. If it worked the first time then it should also work now.

**Comment by stanleyhanes** [comment]
after i try disconnect homebridge tv from home, now i can't add accessory homebridge tv to my home app.
that i don't understand, i've been able to use buttons once. then after sometime (maybe after TV turn off for period time), it stopped working. but native button like power, volume, and channel buttons still working.
here is my new debug log: https://pastebin.com/1pXy4M2N

**Comment by merdok** [comment]
I think that you might have some issues with your homebridge installation. Try to clear the cache and also make sure that the homebridge user has permissions to write to the disk. Besides that the log looks ok.

**Comment by stanleyhanes** [comment]
i tried reinstall webos homebridge plugin, clear cache, and unpair device. but still can't add homebridge TV to home app.
in few days, i'll try fresh install raspi os. i'll come back here if there is still a problem.
thanks

**Comment by merdok** [comment]
ok 👍

**Comment by stanleyhanes** [comment]
hi merdok, after reinstall everything i still got this
[10/10/2020, 7:45:28 PM] [webostv] [LG webOS TV] Remote input socket - tv not connected or remote input socket not established!
i can control using LG thinQ, LG TV plus, and smart remote app on my phone, so i think the tv setting is fine

**Comment by merdok** [comment]
Yeah, like i already mentioned you need to most a complete debug log, the best would be a debug log with the deepDebugLog property enabled. You would need to post one from the startup when the connection to the TV is established and also another one when you try to use the button. Without those things everything is just speculation, there is for sure something not enabled or broken on your side, you just need to figure out what. The debug log could help with that.

**Comment by stanleyhanes** [comment]
here is the log https://pastebin.com/h73x4dvE
12:39:31 i use channel up and set volume button from homebridge and work fine.
12:39:42 i use ENTER, EXIT, RIGHT, LEFT, UP, DOWN


here is my config
{
            "platform": "webostv",
            "devices": [
                {
                    "name": "LG webOS TV",
                    "ip": "192.168.1.16",
                    "mac": "AC:F1:08:09:19:DA",
                    "keyFile": "/home/homebridge/.homebridge/.webosTv/lgtvKeyFile",
                    "prefsDir": "/home/homebridge/.homebridge/.webosTv",
                    "pollingInterval": 5,
                    "deepDebugLog": true,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "remoteControlButtons": [
                        "HOME",
                        "EXIT",
                        "MENU",
                        "RIGHT",
                        "LEFT",
                        "UP",
                        "DOWN",
                        "ENTER"
                    ]
                }
            ]
        }

**Comment by merdok** [comment]
From the log i see that your TV setup did not finish hence you cannot use the remote buttons. I do not see any error in the log, maybe it comes later or you did remove it?
Also try to start the TV with Live TV and then switch to HDMI and check if that helps?

**Comment by stanleyhanes** [comment]
here is the log https://hastebin.com/jawopeqiva.makefile

4:20:12 restart homebridge (TV on with live TV)
4:20:47-4:20:59 remote buttons work fine (Live TV and HDMI)
4:21:29 turn TV off
4:21:49 TV disconnected from homebridge
4:22:36 turn TV on
4:22:59 ERROR WebSocket
4:24:xx homebridge sending command but TV not responding

i think after TV disconnected from homebridge, remote buttons stop working.

**Comment by stanleyhanes** [comment]
i tried this

-restart homebridge (TV on with HDMI) -> TV setup did not finish
-remote buttons not work
-turn off TV until TV disconnected from homebridge
-turn TV on with Live TV -> TV setup finished
-remote buttons work (ERROR WebSocket still exist)
-turn TV off until TV disconnected from homebridge
-turn TV on -> remote buttons not work anymore

**Comment by merdok** [comment]
I kind of understand the issue partially now, what i do not understand is why your TV is not sending an error message back when trying to setup a service. I expect to receive a success or error message but actually nothing is coming in your case. 
Are you sure that everything is enabled on your TV required for the remote connection?

**Comment by stanleyhanes** [comment]
i'm pretty sure i enabled everything.

what success or error message should appear ?
like this ?

[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Connecting to remote input socket
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Message from TV 

[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV]  {
  type: 'utf8',
  utf8Data: '{"type":"response","id":"afaf7dce000d","payload":{"socketPath":"ws://192.168.1.16:3000/resources/788a4f9f7dd5e8f45de7e98da6881c4f3ddff8fc/netinput.pointer.sock","returnValue":true}}'
}
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Connected to remote pointer input socket
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Setup finished
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] TV setup finished, ready to control tv

**Comment by merdok** [comment]
Yes, this is exactly what should appear after everything is set up properly.
I do not think that this has anything to do with homebridge restart. If you set your TV to start in Live TV then it should always succeed. What i saw from your log you have set your TV to HDMI1 at start so that is why it is failing. Like i said i expect the TV to send a response back so i wait for that, but for some reason no response comes back when you have set HDMI1 at startup...
Can you confirm that when Live TV is set at startup that it works every time?

**Comment by stanleyhanes** [comment]
when Live TV is set at startup, this message always appear when i turn on TV.

[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Connecting to remote input socket
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Message from TV

[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] {
type: 'utf8',
utf8Data: '{"type":"response","id":"afaf7dce000d","payload":{"socketPath":"ws://192.168.1.16:3000/resources/788a4f9f7dd5e8f45de7e98da6881c4f3ddff8fc/netinput.pointer.sock","returnValue":true}}'
}
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Connected to remote pointer input socket
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] Setup finished
[10/11/2020, 4:20:12 PM] [webostv] [LG webOS TV] TV setup finished, ready to control tv


but if i turn off TV and turn on again, remote buttons stopped working and message above still appear.
i need to set to Live TV and restart homebridge for remote buttons to work again.

**Comment by merdok** [comment]
Turning off the tv should not have any effect on the remote buttons when Live TV is set at startup, if you get the `TV setup finished, ready to control tv` message then you should be able to use remote buttons. But there is still certainly something wrong with your TV or maybe your network, i cannot tell exactly, but the TV should send a response back in any case. I did not hear anyone else till now to report such issue on a webOS 5.0 so i am not really sure if maybe something changed.

**Comment by stanleyhanes** [comment]
i did get ‘TV setup finished, ready to control tv’ message everytime Live TV is set at startup. BUT second time i turn on TV, homebridge success sending remote buttons input to TV but nothing happen on TV

**Comment by marioPS** [comment]
OK - here's my weird 2c worth.

I initially found that the iPhone on-screen remote control buttons did not work (whether accessed via the home app by the Apple TV icon, or by the control centre Apple TV remote icon). 
The LG TV would come up as an option along with all the other Apple TVs, I could control the volume on the LG, I could press buttons & feel a vibration - but no change on TV. :(

Here's the weird bit: when I put Homebridge in debug mode - it works. :)

Go figure …

**Comment by merdok** [comment]
@stanleyhanes that is really interesting... maybe indeed something slightly changed there in webos 5.0. I do not really understand why the tv responds with success but still does not react to the commands...

@marioPS you also have a webos 5.0 tv right?
Could you do some more extensive testing? I am interested if you get the same pattern as @stanleyhanes 

We need to figure out if this is indeed related to webos 5.0 TVs, and why sometimes it works but other times not...

**Comment by marioPS** [comment]
Spoke too soon. Restarted homebridge. Doesn't work in or out of debug mode … continuing testing to see if I can detect a pattern.

**Comment by marioPS** [comment]
[10/12/2020, 8:30:46 PM] [webostv] [LG TV] Message from TV 

[10/12/2020, 8:30:46 PM] [webostv] [LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"response","id":"c38d03760002","payload":{"returnValue":true,"product_name":"webOSTV 5.0","model_name":"HE_DTV_W20P_AFADABAA","sw_type":"FIRMWARE","major_ver":"03","minor_ver":"10.60","country":"AU","country_group":"AJ","device_id":"64:95:6c:af:6c:26","auth_flag":"N","ignore_disable":"N","eco_info":"01","config_key":"00","language_code":"en-AU"}}'
}
[10/12/2020, 8:30:46 PM] [webostv] [LG TV] {
  "returnValue": true,
  "product_name": "webOSTV 5.0",
  "model_name": "HE_DTV_W20P_AFADABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "03",
  "minor_ver": "10.60",
  "country": "AU",
  "country_group": "AJ",
  "device_id": "64:95:6c:af:6c:26",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "en-AU"
}
[10/12/2020, 8:30:46 PM] [webostv] [LG TV] Retrieved SW info
[10/12/2020, 8:30:46 PM] [webostv] [LG TV] Got TV information
[10/12/2020, 8:30:46 PM] [webostv] [LG TV] TV webOS version: 5.0

**Comment by stanleyhanes** [comment]
good news.. i don't know how but my remote buttons work every time i startup as Live TV.
i did nothing to my TV since last night.
now my question is, how to finish TV setup while set HDMI as startup ?

**Comment by merdok** [comment]
Yes, this is what I meant. When you turn on tv with live tv enabled it should work.

I already added a check to make sure if the registration fails that the setup still finishes, but somehow I see now that webos 5.0 just don't care about that and do not send any response back for whatever reason🙄
Anyway my idea is that I will probably add a timeout, so if the tv does not respond for a while then I will just continue the setup without waiting for a response.

**Comment by stanleyhanes** [comment]
what you mean registration fail is when TV start as HDMI ?
so if you add a timeout to finish setup without TV response, then i can use my remote buttons even when HDMI is set as startup ?
if that is the case, i'll wait for your work :)

**Comment by merdok** [comment]
The thing is that this does not have to do with the remote control itself but with the channel service. This will of course fail on HDMI because the channel service only works on live tv. Anyway I expect it to fail but it doesn't and yes I do not get any response back from tv. 
Adding a timeout should fix the issue for you. If there is no response from tv within 15 seconds then I will consider it as a fail and the setup will continue😉

**Comment by stanleyhanes** [comment]
so even remote input socket fail to connect, i can still control my TV ?
anyway will wait for your work :)
thanks a lot

**Comment by merdok** [comment]
@stanleyhanes can you try version 2.0.6? The issue should now be fixed.

**Comment by stanleyhanes** [comment]
the issue fixed, but i found other issue.
i start tv as HDMI, then turn off tv as Live TV. when i turn on again as Live TV, buttons not work. i must turn off then turn on again then remote buttons work again.
do you need to see the debug log ? but i can’t send it right now

**Comment by merdok** [comment]
Yes, debug log would be good.

**Comment by stanleyhanes** [comment]
so it's not about inputs, HDMI or Live TV is the same.
it take turns like this, work->turn off->not work->turn off->work->...
this is debug log in order
1. https://hastebin.com/bohigoqutu.swift
2. https://hastebin.com/ofalijopal.yaml
3. https://hastebin.com/xejixegicu.swift
4. https://hastebin.com/enitojoxer.yaml
5. https://hastebin.com/lefibonubo.swift

**Comment by merdok** [comment]
Thanks for the logs. This is now a different issue. Honestly no idea why your tv is behaving so strange... It reports a successful registration for the remote input socket but nothing happens when you send the command...
I noticed some other small issues, but they should not be related to you issue.

@marioPS did you try the latest version and can report if the behavior is same for you?

**Comment by marioPS** [comment]
I've not been able to try extensively: updates to Homebridge Config UI X, Homebridge Tplink Smarthome  & your plugin all at once borked my system - I had to do some fixin'.

All is working now, so I'll investigate when I get a chance, and let you know as soon as possible.
