### ISSUE TITLE
Control Center Remote

### ISSUE THREAD

**Issue by m11rphy** [merdok/homebridge-webos-tv#311]
Hi, Firstly thank you so much for making such an amazing plugin, it really is fantastic. I have just reinstalled a fresh install of homebridge and moved away from HOOBs. The plugin is all set up and by 3 LG TVs are added to HomeKit so all good, I have one small issue which is the TVs are not showing in the Control Center Remote app on the iPhone. Not a major issue just wondered if its not supported by the plugin anymore or if I had made a mistake?

**Comment by merdok** [comment]
It has nothing to do with the plugin when your Control Center remote is not appearing. The remote should also be visible in control center even when you have no TVs setup. Maybe you did not configure your control center? You need to enable certain control center elements in the settings...

**Comment by m11rphy** [comment]
Sorry I should explain better, the remote is in control centre and I can select my Apple TV and use it. The issue is that none of my 3 LG TVs show up in the remote app and Im sure they did some months back using a older plugin version

**Comment by merdok** [comment]
Nothing changed there so they should still appear there if you have them correctly set up. Is there any error log? Did you try to add them one by one and see if they appear then?

**Comment by m11rphy** [comment]
Yes I did try that and they are not there, Im not getting any errors, is there anything I should get in the config that relates to the remote app?

**Comment by merdok** [comment]
There is nothing that needs to be added to the config. They simply need to appear there. Maybe after switching from HOOBs to homebridge your home in homekit got confused... Did you try to setup a new home or maybe delete local caches?

**Comment by m11rphy** [comment]
No I did not set up a new home, would be nice if they was in the remote app but I'm not concerned enough to set up a whole new home. Thanks for the advise anyway and thank you so much for such a great plugin :)

**Comment by merdok** [comment]
I think you can first try to create a separate new home and add one of the TVs there as a try. You do not need to delete all of your setup to try that out...
