### ISSUE TITLE
Encountered a crash error

### ISSUE THREAD

**Issue by newt10** [merdok/homebridge-webos-tv#317]
Plugin version: homebridge-webos-tv v2.0.5

ReferenceError: error is not defined
    at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:467:58
    at /home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:257:17
    at Timeout._onTimeout (/home/pi/.nvm/versions/node/v12.16.1/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:228:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by merdok** [comment]
You should update to version 2.0.7

**Comment by newt10** [comment]
I am going to try this for a few days and then close the issue if I don't see any crashes! Thanks!!

**Comment by merdok** [comment]
That would be good!

**Comment by newt10** [comment]
seems to be functioning well with the latest version so closing this issue
