### ISSUE TITLE
Issue adding a second TV. 

### ISSUE THREAD

**Issue by echtelerp** [merdok/homebridge-webos-tv#318]
first my config file: 
`{
    "bridge": {
        "name": "Homebridge 2D9C",
        "username": "0E:23:B6:CB:2D:9C",
        "port": 51532,
        "pin": "556-17-474"
    },
    "accessories": [
        {
            "type": "switch",
            "name": "Esszimmerlampe",
            "url": "http://192.168.2.30:1883",
            "topics": {
                "getOnline": "tele/lightswitches/LWT",
                "getOn": "stat/lightswitches/POWER",
                "setOn": "cmnd/lightswitches/power"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        },
        {
            "type": "switch",
            "name": "3D Drucker",
            "url": "http://192.168.2.30:1883",
            "topics": {
                "getOnline": "tele/anetA8/LWT",
                "getOn": "stat/anetA8/POWER",
                "setOn": "cmnd/anetA8/power"
            },
            "onValue": "ON",
            "offValue": "OFF",
            "accessory": "mqttthing"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "Aussen",
                    "videoConfig": {
                        "source": "-i http://192.168.2.30/stream/?action=stream",
                        "stillImageSource": "http://192.168.2.30/stream/?action=snapshot"
                    }
                },
                {
                    "name": "3D Drucker",
                    "videoConfig": {
                        "source": "-i http://192.168.2.70:8080/?action=stream",
                        "stillImageSource": "http://192.168.2.70:8080/?action=snapshot"
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "devices": [
                {
                    "name": "TV Wohnzimmer",
                    "ip": "192.168.2.139",
                    "mac": "78:5D:C8:98:81:D0",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true,
                    "mediaControl": false,
                    "screenControl": false,
                    "ccRemoteRemap": {
                        "arrowup": "VOLUMEUP",
                        "arrowdown": "VOLUMEDOWN",
                        "arrowleft": "CHANNELDOWN",
                        "arrowright": "CHANNELUP",
                        "select": "PROGRAM",
                        "back": "BACK",
                        "playpause": "YELLOW",
                        "information": "TELETEXT"
                    }
                },
                {
                    "name": "TV Schlafzimmer",
                    "ip": "192.168.2.141",
                    "mac": "78:5D:C8:90:34:57",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true,
                    "mediaControl": false,
                    "screenControl": false,
                    "ccRemoteRemap": {
                        "arrowup": "VOLUMEUP",
                        "arrowdown": "VOLUMEDOWN",
                        "arrowleft": "CHANNELDOWN",
                        "arrowright": "CHANNELUP",
                        "select": "PROGRAM",
                        "back": "BACK",
                        "playpause": "YELLOW",
                        "information": "TELETEXT"
                    }
                }
            ],
            "platform": "webostv"
        }
    ]
}`

then my logs: 
`[10/23/2020, 13:43:26] Homebridge is running on port 51532.
[10/23/2020, 13:44:48] [webostv] [TV Wohnzimmer] Connected to TV
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] Got TV information
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] TV webOS version: 4.0
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] TV turned on!
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] App launched, current appId: com.webos.app.hdmi4
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] Sound output changed. Current sound output: tv_speaker
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] Subscribed to TV services
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] Connected to remote pointer input socket
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] Setup finished
[10/23/2020, 13:44:49] [webostv] [TV Wohnzimmer] TV setup finished, ready to control tv
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] Connected to TV
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] Got TV information
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] TV webOS version: 4.0
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] TV turned on!
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] App launched, current appId: com.webos.app.hdmi1
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] Sound output changed. Current sound output: tv_speaker
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] Subscribed to TV services
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] Connected to remote pointer input socket
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] Setup finished
[10/23/2020, 13:46:16] [webostv] [TV Schlafzimmer] TV setup finished, ready to control tv
`

I can somehow only add the second TV to the HomeKit app, 
then after removing the first tv, I cannot add any of both? 
any ideas?

**Comment by merdok** [comment]
First off, every issue ticket should be like yours with config and log👍🏻 That makes a lot of issues easier to understand!

Your config looks ok and also the log look ok. The plugin connects to both TVs without any issues. This looks to me like a caching issue from homebridge. You should try to remove the homebridge cache, eventually try to rename the TVs.

**Comment by echtelerp** [comment]
I did uninstall the plugin, 
restart,
install plugin, 
restart,
paste config, 
restart, 

--- I can see the TV's in my HomeBridge UI, 
--- don't appear under the add section in my app.... 

what finally solved the issue: 
sorry, only in German: 
Entkoppele Bridges / Kameras / Fernseher / externes Zubehör 

<img width="1660" alt="image" src="https://user-images.githubusercontent.com/19430312/97016285-da5a9780-154c-11eb-9bfb-05ad79362520.png">

the first option... 


Thanks for the Hint :-)

**Comment by merdok** [comment]
Good to hear! Thanks for the info!
