### ISSUE TITLE
Everything looks like an on/off switch

### ISSUE THREAD

**Issue by jbbehar** [merdok/homebridge-webos-tv#319]
i'm not sure if this is a limitation of the functions and available controls of iOS home app, but each function looks like an on-off switch slider and takes up a lot of screen space on an iphone, and every app 

is there any other way to present the UI of the tv within home?

i'm using the plugin inside of HOOBS and my config looks like:

		  {
		  	"name": "LG webOS Kitchen TV",
		  	"ip": "1.2.3.4",
		  	"mac": "aa:bb:cc:dd:ee:ff",
		  	"pollingInterval": 10,
		  	"volumeControl": "buttons",
		  	"channelControl": true,
		  	"screenControl": true,
		  	"screenSaverControl": true,
		  	"mediaControl": true,
		  	"soundOutput": "external_arc",
		  }

**Comment by merdok** [comment]
Simply force close and restart your home app. That should fix the issue.

**Comment by jbbehar** [comment]
See attached video. This is what the results look like after a forced restart.

Perhaps my expectations are high but this is not a very useful UI. I don’t know if it’s a limitation of Home, the available controls, my configuration.


________________________________

[Relentless Computer Solutions]<http://www.relentlesssolutions.com>


Jim-Barry Behar

jbbehar@relentless.net<mailto:jbbehar@relentless.net>
1810 ne 144  street,  suite 200  •  north miami, fl  33181-1420
Direct Number: 786.600.7654 • t. 305.919.7890  • f. 305.919.7717
Disclaimers & Agreements<http://www.relentlesssolutions.com/emaildisclaimer.htm>



________________________________

________________________________

**Comment by merdok** [comment]
Sorry I do not see any video...

**Comment by jbbehar** [comment]
Try this link https://share.icloud.com/photos/0tZ-2GpHtn0V8kQ1cNuiS20tw


________________________________

[Relentless Computer Solutions]<http://www.relentlesssolutions.com>


Jim-Barry Behar

jbbehar@relentless.net<mailto:jbbehar@relentless.net>
1810 ne 144  street,  suite 200  •  north miami, fl  33181-1420
Direct Number: 786.600.7654 • t. 305.919.7890  • f. 305.919.7717
Disclaimers & Agreements<http://www.relentlesssolutions.com/emaildisclaimer.htm>



________________________________

________________________________

**Comment by merdok** [comment]
Well this is the standard home app UI for groups. There is nothing I can do about it. 
You could write feedback to Apple and maybe they improve that someday😅

The only thing which you could make is to ungroup the tv controls by scrolling to the bottom and using the button there. Then you will not have them grouped together but as single tiles.

**Comment by jbbehar** [comment]
Yep. That’s what I thought thanks for the very prompt replies. I think Apple has a bit of work to do to offer a full assortment of UI controls appropriate for things like up/down volume and channels and many others. They have some already in place for AppleTV remote but I suppose they are not exposed to HomeKit for use in accessories.

It would be ideal if it was truly interactive like X1 remote including guide from cable or other provider combined with full tv control like the AI-ThinQ app from LG. Someday.

Thanks again for your help!


________________________________

[Relentless Computer Solutions]<http://www.relentlesssolutions.com>


Jim-Barry Behar

jbbehar@relentless.net<mailto:jbbehar@relentless.net>
1810 ne 144  street,  suite 200  •  north miami, fl  33181-1420
Direct Number: 786.600.7654 • t. 305.919.7890  • f. 305.919.7717
Disclaimers & Agreements<http://www.relentlesssolutions.com/emaildisclaimer.htm>



________________________________

________________________________

**Comment by merdok** [comment]
I am not sure if you are aware but you can also use the control center remote with your tv. You can use the plugin to configure yourself the buttons so maybe that would be a better way for you.
