### ISSUE TITLE
Could not save config for device in HOOBS

### ISSUE THREAD

**Issue by DominicHochberg** [merdok/homebridge-webos-tv#321]
Hi, I only need to switch on/off the TV using Apple Home.
I installed the plugin but couldn't add the device correctly.
Tried to edit the whole lot into config.  (by the way, im using HOOBS.)

Device:

[
                {
          "name": "MY TV",
          "ip": "(SECRET)",
          "mac": "(SECRET)",
          "pollingInterval": 10,
          "volumeControl": "buttons",
          "channelControl": false,
          "mediaControl": false,
          "appButtons": “”,
          "channelButtons": “”,
          "notificationButtons": “”,
          "soundOutputButtons": “”,
          "remoteSequenceButtons": ””
      }
]

**Comment by merdok** [comment]
Your config does not look correct (at leas that what you posted here). Please check the README for an example.

**Comment by DominicHochberg** [comment]
got it, thanks.

**Comment by merdok** [comment]
Does it work now?

**Comment by DominicHochberg** [comment]
yes, however, all buttons (play, fast-forward etc.) are shown in sliders. I couldn't find to change these to buttons.

**Comment by merdok** [comment]
They show as sliders (actually big buttons) because per default they are grouped. you need to ungroup them and then they should appear as single tiles.

**Comment by DominicHochberg** [comment]
i see, im not very used to this at the moment, is it easily described? Otherwise I will teach me.

**Comment by DominicHochberg** [comment]
awesome help, thanks! Everything works smoothly

**Comment by merdok** [comment]
Good to hear 😄
