### ISSUE TITLE
Setting Picture mode eco

### ISSUE THREAD

**Issue by Luitwieler** [merdok/homebridge-webos-tv#322]
In the code I found the following lines:
  // not working, why?
  setSystemSettings() {
    this.lunaSend('luna://com.webos.service.settings/setSystemSettings', {
      category: "picture",
      dimension: {
        pictureMode: "eco"
      },
      settings: {
        brightness: 30
      }
    });
  }

I would be very interested having this exposed in HomeKit. Currently I am using a button sequence to change this value. This is quite error prone. Is there an update on this functionality and if it will be introduced in the plug-in soon?

**Comment by merdok** [comment]
Hi,
unfortunately this is not working and I do not know why. I will need to investigate this more, but for now I think that it is now possible. If I ever find a way to make it work then be assured that I will add that to the plugin👍
