### ISSUE TITLE
Cannot add TV after enabling ufw firewall

### ISSUE THREAD

**Issue by realweird** [merdok/homebridge-webos-tv#324]
Hi all,

I had no problem setting up my LG webOS TV using this plugin, but the moment I set up a firewall (using ufw), I can't connect.

Each time I restart Homebridge, my TV seems to be connecting to a random port. I've tried adding one of the ports to the config file (tried adding to both the "**"devices": [**" line and "**"platform": "webostv"**" line), but that doesn't work.

I've removed the TV from my accessories and when I try to re-add it, it appears as a "LG webOS TV" in HomeKit. But when I enter the 8-digit code, it eventually fails after about 3 minutes of trying to add.

I added specific ports to allow access to a camera that I've set up and the Homebridge UI, so this is the only plugin that I'm having problems accessing since enabling the ufw firewall.

Anybody have this issue or know how to work around it?

**Comment by merdok** [comment]
Hi,

I guess this is a network issue on your side. The tv needs to be reachable on port 3000 from your homebridge machine. You should recheck your network setup and make sure that both devices can speak to each other.

**Comment by realweird** [comment]
> Hi,
> 
> I guess this is a network issue on your side. The tv needs to be reachable on port 3000 from your homebridge machine. You should recheck your network setup and make sure that both devices can speak to each other.

In ufw, I allowed port 3000 and also allowed the random port that gets assigned to the TV, and that works. But when I restart Homebridge, the port for the plugin changes again to a random one and I lose the connection unless I manually allow the port. 

Also, the random port has always been a 5-digit port, and has never shown to be 3000, even though I know that’s the common port to be used.

Is there any way to set the plug in to assign a static port?

**Comment by merdok** [comment]
Again, this is an issue with your network. The websocket service on the TV runs always on Port 3000 and there is no way to change that, for that reason the plugin always uses that port to connect to the TV. I do not know how did you setup your network, but you need to make sure that the your router/firewall always allows the connection to the tv on port 3000. 
From the plugin and TV point of view the port will never change, it will always be 3000.

**Comment by realweird** [comment]
> Again, this is an issue with your network. The websocket service on the TV runs always on port 3000 and there is no way to change that, for that reason the plugin always uses that port to connect to the TV. I do not know how did you setup your network, but you need to make sure that your router/firewall always allows the connection to the tv on port 3000.
> From the plugin and TV point of view the port will never change, it will always be 3000.

Alright, it’s strange since I don’t have any special setup in my network and I’ve only installed Homebridge on a Pi without any additional plugins besides the camera one I mentioned earlier. 

I’ll mark this as closed since I haven’t seen others come across this issue.

**Comment by grzegorz914** [comment]
@realweird 

add this part to Your HB config:

```
`  "bridge": {
        "name": "Homebridge",
        "username": "AA:BB:CC:DD:EE:FF",
        "manufacturer": "homebridge.io",
        "model": "homebridge",
        "port": 9100,
        "pin": "123-45-678"
    },
    "description": "HomeKit Bridge",
    "ports": {
        "start": 9101,
        "end": 9150,
        "comment": "In this section set the port for Homebridge accessories."
    }, `
```

Here U can set the range of ports to used with accessories and after this open the range ports on Your router.

**Comment by merdok** [comment]
@realweird as @grzegorz914 mentioned, it might be the homebridge port which you have issues with so maybe try his suggestion.

**Comment by realweird** [comment]
@grzegorz914, perfect! That solved the issue and I can now access my LG TV as before when ufw wasn't enabled. Also restarted my Pi to confirm that the ports stayed the same and didn't encounter any issues.

Thanks for your help!
