### ISSUE TITLE
Feature request - Browser open in fullscreen mode

### ISSUE THREAD

**Issue by Maetran** [merdok/homebridge-webos-tv#326]
Hey there
I am using this addon some time now. I was wondering if there is an option to start the browser in full screen mode (i am handing an url as params- as m3u8 which works fine and starts a stream via browser and now i want to start it in full screen directly without an additional click)
Thanks for your support

**Comment by merdok** [comment]
Hi,

can you provide me some sample code how you now open the browser? If you could do that then I will check it out and see if it is possible to open it in full screen mode.

**Comment by Maetran** [comment]
Sure. ATM i use this config in appButtons. Question would be if there is an option to pass an additional command in params? Thanks in advance

(Sorry the bad formatting, working on mobile device atm..

```
"appButtons": [
                        {
                            "appId": "com.webos.app.browser",
                            "name": "JOJ LIVE",
                            "params": {
                                "contentTarget": "https://nn.geo.joj.sk/live/hls/joj-720.m3u8"
                            }
                        },
```

**Comment by merdok** [comment]
So i had a look and at first i did not find anything. Basically those params are configured on a per app basis, so we would need to get the source code of the web browser app and check what possible params are there defined. The problem is that we will not get that easy the source code of the browser app...

**Comment by Maetran** [comment]
Hi merdok
I have an additional issue coming up (mostly) every time I update your addon in HB. The snippet in my comment above is working fine and starting the stream right away (still not in fullscreen, but thats not the point). But if i update, the "params" : { /* */ } is disappearing and I have to add it manually every time. 

`"params": {
                                "contentTarget": "https://nn.geo.joj.sk/live/hls/joj-720.m3u8"
                            }`

Not a big deal, sure. But maybe you can take a look into it? 
Thanks, 
Gruss Mani

**Comment by Maetran** [comment]
Thanks.
Will take a closer look at it during next HB update. Might be an issue (or not an issue, since it causes no crashes) with Homebridge.
