### ISSUE TITLE
When turning off LG TV from HomeKit error occurs in HOOBS 3.3.1

### ISSUE THREAD

**Issue by vvdheuvel** [merdok/homebridge-webos-tv#327]
12/3/2020, 10:31:59 AM [webostv] [LG TV] TV turned off!
12/3/2020, 10:32:04 AM (node:2763) UnhandledPromiseRejectionWarning: Error while requesting turnOff from service system
12/3/2020, 10:32:04 AM (node:2763) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
12/3/2020, 10:32:14 AM [webostv] [LG TV] Disconnected from TV

**Comment by merdok** [comment]
Will have a look at it. Thanks for reporting!

**Comment by merdok** [comment]
@vvdheuvel can you please enable debugLog. And post the result here when the error appears?

**Comment by vvdheuvel** [comment]
I don't run homebridge, see title of my bug report 😉 I run HOOBS. I can run the plug-in with "deepDebugLog": true

**Comment by merdok** [comment]
I am not familiar with HOOBS but it should also be possible somehow to start that in debug mode. Maybe in the settings?

**Comment by vvdheuvel** [comment]
https://share.icloud.com/photos/0khFMoD156BkYkHvosA09CXZA

**Comment by merdok** [comment]
Not in the plugin settings, but HOOBS settings.

Google says:
HOOBS in debug mode, in terminal:
hoobs -D

**Comment by vvdheuvel** [comment]
https://github.com/hoobs-org/HOOBS/issues/709

**Comment by merdok** [comment]
Yes, here is the info on how to run in debug mode: https://support.hoobs.org/docs/5e764e72e87d1e02b6c19d4c

Please enable debug mode and try to reproduce the issue.

**Comment by Crusader2001** [comment]
I’m having the same issue and enabled debug mode. 
This is the output:
[12/5/2020, 11:43:20] [webostv] [LG TV HB] com.webos.service.tv.power service - turnOffScreen requested. 
[12/5/2020, 11:43:20] [webostv] [LG TV HB] Unknown error while requesting turnOffScreen from service com.webos.service.tv.power
(node:18367) UnhandledPromiseRejectionWarning: Error while requesting turnOffScreen from service com.webos.service.tv.power
(node:18367) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18367) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by merdok** [comment]
@Crusader2001 but the tv turns off fine?

**Comment by merdok** [comment]
Should be fixed in Version 2.0.8

**Comment by vvdheuvel** [comment]
👍🏻
