### ISSUE TITLE
Installation issue(latest version)

### ISSUE THREAD

**Issue by Mikellas** [merdok/homebridge-webos-tv#329]
This is what i get when trying to install the latest version

> bufferutil@4.0.2 install C:\Users\Nicolas Server\AppData\Roaming\npm\node_modu
les\homebridge-webos-tv\node_modules\bufferutil
> node-gyp-build

'node-gyp-build' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.2 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Roaming\npm-cache\
_logs\2020-12-07T04_55_03_820Z-debug.log

Command failed. Please review log for details.

I am on 1.2.3 Homebrdige should i downgrade?

**Comment by Mikellas** [comment]
Removed plugin, installed 2.0.3 and then tried updating it all worked

Thanks

**Comment by Mikellas** [comment]
My bad the plugin still has issues as TVs are not responding now

**Comment by AmauryVela** [comment]
I'm having the same issue with the latest version of this plugin :( I'm on raspberry pi, hombridge 1.1.7, node 14.5.1

**Comment by merdok** [comment]
The issue has nothing to do with the plugin, but with your homebridge setup. Try to reinstall and make sure that the permissions are correct.
