### ISSUE TITLE
MaxListenersExceeded warning

### ISSUE THREAD

**Issue by tobywstokes** [merdok/homebridge-webos-tv#331]
Any idea what's happened here? Can't turn the tv on via Home or Remote. I am currently quite unpopular at home!

```
(node:567) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 tvTurnedOn listeners added to [LgTvController]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by merdok** [comment]
I think you might have wrongly configured your plugin, recheck your config.json.

**Comment by tobywstokes** [comment]
My Homebridge install looks a bit sick. Hard to say this is anything to do with the plug-in. I did have to power cycle the tv. Thanks for getting back to me.

**Comment by merdok** [comment]
You should check the homebridge website for a guide on how to correctly set it up, maybe that will help you.

**Comment by infinitedr** [comment]
I'm also getting the same issue here. 
   MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 tvTurnedOn listeners added to       
   [LgTvController]. Use emitter.setMaxListeners() to increase limit
   (Use `node --trace-warnings ...` to show where the warning was created)

**Comment by merdok** [comment]
Could you post the result of running the node --trace-warnings command?
