### ISSUE TITLE
Turn on tv

### ISSUE THREAD

**Issue by barack65** [merdok/homebridge-webos-tv#332]
Hi,
I can't turn on my tv from the plug-in. Only turn off. 
Thanks you

**Comment by merdok** [comment]
Please check the configuration section in the README. There are additional steps which you need to do on the TV in order for turn on to work. https://github.com/merdok/homebridge-webos-tv#configuration

**Comment by indicava** [comment]
I have the same issue with an LG OLED55CX with software ver. 3.11.30 . 

I did all the steps in the configuration, as fasr as I know there is no "LG Connected Apps" or "Mobile TV" settings, but under Setttings/Connection/Mobile Connection Management/TV On with Mobile (which I assume is the the same setting) both "Turn on via Bluetooth" and "Turn on via WiFi" are enabled.

**Comment by merdok** [comment]
@indicava if all the options are enabled then in your case it is a local network issue. Your should be able to forward a magic packet to your tv, if that is not the case then it will not work.

**Comment by indicava** [comment]
I will try to forward a wakeup packet independently of the plugin (and HB) and see if that works.

**Comment by merdok** [comment]
Yes, that is a good start. If that works then the plugin will also work!

**Comment by barack65** [comment]
I have tv with webos3 that I can't turn on 
And 2 TVs with webos4 that can turn on 
I do all what necessary in tv and it's still don't work for me :/

**Comment by merdok** [comment]
@barack65 
you should also try to send a wakeup (magic) packet manually to the tv to try if it reacts to it.

**Comment by barack65** [comment]
sorry about the question but what is wakeup (magic) packet?

**Comment by indicava** [comment]
Just wanted to update that I solved my issue, I have two WiFi access points (that share the same LAN) at home and the webos TV was connected to a different access point from Homebridge. Once they were both on the same wlan the “on” feature works perfectly!

**Comment by merdok** [comment]
@indicava thanks for letting us know!
@barack65 your issue might be the same or similar. Make sure both TVs are in the same network and that all the TVs react to wakeup (magic) packet. You can use some tools to send that packet manually.

**Comment by barack65** [comment]
Still don't work for me :/ 
Will I try to connect in Wi-Fi?

**Comment by merdok** [comment]
It should not matter if you use WiFi or LAN, but to be sure you can connect your TV using LAN.  It might also be that your webos3 TV does not support that, but i am not sure if there are any webos3 TVs which does not support the wakeup packet...

**Comment by barack65** [comment]
It was wake up. In one of the update it's stop

**Comment by merdok** [comment]
Then LG changed something, you need to figure out what changed on webos3 TVs. The issue here lies either on your network side or the TV side.

**Comment by krisco64** [comment]
I am not able to turn my 2020 model LG on via HomeKit. I also get this message:

External port pool ran out of ports. Fallback to random assign

I am very new to this. Any help would be appreciated.

Thanks.

**Comment by merdok** [comment]
@krisco64 check your tv settings if everything which is required is enabled. If that still did not help then it is a network issue on your side. Like above, a very good start is to manually send a magic packet to the tv from your homebridge device and make sure that this works.
