### ISSUE TITLE
"Pixel refresher started!" in the logs

### ISSUE THREAD

**Issue by aspot** [merdok/homebridge-webos-tv#334]
Hi,

I have just setup this with an LG CX today, and am a bit alarmed how often I am seeing "Pixel refresher started!" in the logs. Every time I reboot the TV it seems like. I've only owned the TV for a month, and my understanding is the pixel refresher runs after 4 hours of screen time (not sure if this is consecutive in one session or cumulative no matter how many sessions).

I would assume it runs cumulative no matter how many sessions? If so, maybe I'm seeing "Pixel refresher started!" because I happened to install homebridge-webos-tv exactly after I've accumulated 4 hours of screen time?

Just want to make there's no bug wherein homebridge itself is triggering the pixel refresh.

Thanks!

**Comment by merdok** [comment]
Hi,

first off, homebridge cannot trigger the pixel refresher, only the tv itself can trigger it and it usually happens after around 4 hours of runtime like you say.

If the log says "TV turned off" straight after "Pixel refresher started!" then actually it was not triggered. The tv always first needs to check if it is time to start the pixel refresher, this check is what you see as "Pixel refresher started" in the log. If the tv decided it is not yet the time to run it then it will directly turn off. 
Then tv is only in pixel refresher mode when you actually see the log and nothing else after that for around 8 minutes.
