### ISSUE TITLE
Screen off/on no longer working

### ISSUE THREAD

**Issue by mrkita** [merdok/homebridge-webos-tv#337]
I'm using the latest (verison 2.0.8) with my LG CX 55 with Firmware version 3.11.30 (latest here in Europe).

So far this plugin is excellent!

I noticed one hiccup today... previously the "screen on/off" control worked directly, with it I could turn off the screen when I needed to.

Now the accessory simply does nothing, regardless of what application or input I am on.

As a workaround, I just setup a button sequence to a shortcut in the menu, but still weird how this stopped working.

Let me know if more info is needed.

**Comment by merdok** [comment]
Just tested it and the feature is working fine without any issues. Maybe something good stuck in your homekit? You could try to restart homebridge, clear the homebridge cache and maybe force close the Home app on your iDevice.

**Comment by mrkita** [comment]
Hmm I'll give it a try. I certainly tried restarting the homebridge without effect, but I'll check the cache. Thanks for the response

**Comment by merdok** [comment]
Please let me know if you manage to fix it and what the issue was. Do you see any errors in the log when you start homebridge on debug mode and try to control it?

**Comment by samwelnella** [comment]
I am also seeing this issue on LG CX tv running 03.21.16. Here is the debug output when trying to turn the screen off from the plug-in

`[2/24/2021, 8:17:16 PM] [webostv] [My LG TV] com.webos.service.tv.power service - turnOffScreen requested. 
[2/24/2021, 8:17:16 PM] [webostv] [My LG TV] Unknown error while requesting turnOffScreen from service com.webos.service.tv.power
`

**Comment by samwelnella** [comment]
I have the same issue on my LG CX TV running 03.12.16. This is the debug output when trying to turn the screen off via the plugin switch.

`[2/24/2021, 8:24:30 PM] [webostv] [My LG TV] com.webos.service.tv.power service - turnOffScreen requested. 
[2/24/2021, 8:24:30 PM] [webostv] [My LG TV] Message from TV 

[2/24/2021, 8:24:30 PM] [webostv] [My LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"error","id":"a4929896000e","error":"404 no such service or method","payload":{}}'
}
[2/24/2021, 8:24:30 PM] [webostv] [My LG TV] Unknown error while requesting turnOffScreen from service com.webos.service.tv.power`

**Comment by merdok** [comment]
It might be that this is somehow dependent on some setting on the tv and you changed that setting which caused it to not work anymore?

**Comment by samwelnella** [comment]
I changed

`const WEBOS_URI_TURN_OFF_SCREEN = 'ssap://com.webos.service.tv.power/turnOffScreen'; // params: standbyMode (active or passive[passive cannot turn screen back on])
const WEBOS_URI_TURN_ON_SCREEN = 'ssap://com.webos.service.tv.power/turnOnScreen'; // params: standbyMode (active or passive[passive cannot turn screen back on])`

To

`const WEBOS_URI_TURN_OFF_SCREEN = 'ssap://com.webos.service.tvpower/power/turnOffScreen'; // params: standbyMode (active or passive[passive cannot turn screen back on])
const WEBOS_URI_TURN_ON_SCREEN = 'ssap://com.webos.service.tvpower/power/turnOnScreen'; // params: standbyMode (active or passive[passive cannot turn screen back on])`

and now the plugin works for turning off the screen.

**Comment by merdok** [comment]
Oh, this is interesting. For my C8 OLED those new commands do not work. 
@samwelnella was the feature for you also working before? Did you recently got an update for you and after that it stopped working? 
It might be that LG is changing that endpoint for newer TVs so i probably need to do a check for the webOS version...

**Comment by samwelnella** [comment]
I tried this plugin for the first time a few days ago so I'm not sure if an update would have affected it. Turning the screen on and off never worked for me.

**Comment by merdok** [comment]
Ok, but you can confirm that with the new endpoints you posted above it works on your LG CX TV? The CX uses webOs 5.0, right?

**Comment by samwelnella** [comment]
Yes with the new endpoints it does work and the CX does use webOS 5.

**Comment by merdok** [comment]
Thanks for the info. I will then adjust the code so that the new endpoints are used for newer TVs. Hopefully i can submit an update tomorrow.

**Comment by merdok** [comment]
Should be fixed in version 2.1.1
