### ISSUE TITLE
It does not work!

### ISSUE THREAD

**Issue by okilic93** [merdok/homebridge-webos-tv#338]
Dear all,
By following all instruction , I did install it. I checked double all related datas. Eveyting is correct. It shows in the interface of HomeBridge. However when I click on features. there is no any function. My TV is LG webos from 2015. On the other hand , there 
 is no 'mobile TV on ' feature on my TV. I could not accept also from TV as there was no any notification on the TV. Where can I find this control acceptance on the TV Menü?

What could be the problem behind it doen not work althought it appears on interface?

Thank you in advance.

**Comment by merdok** [comment]
What it is your TV model and what webOS version does your TV have? It might be that your TV is a webOS1 which has limited support or there might be a different issue.

**Comment by okilic93** [comment]
LG 47LB731V

Web os : 1.4.0-2532


________________________________

**Comment by merdok** [comment]
What does the debug log say? Start homebridge in debug log and then see what is written there when the connection to your tv starts. If it says "connecting to tv" then you did not enter the correct TV ip address or did not confirm the connection on the TV.

**Comment by okilic93** [comment]
Debug log always says “ connecting tv” “ connecting tv” .... there is no any other notification on this screen. I agree with you, the problem might be that did not confirm the connection on TV. However I couldn’t figure out how I can confirm on TV ? On my tv , there is no such thing in the “ settings “ that like explanation. Maybe you can help me for my version .

________________________________

**Comment by merdok** [comment]
When homebridge is trying to connect to the TV then a notification should popup on your TV which you need to accept. The TV needs to be on in that time. If that does not popup then the issue is either in a wrong IP address which you specified or you have some network issues and the TV cannot be reached by homebridge.

**Comment by okilic93** [comment]
Thank you for your swift reply .
Ip is not wrong.  I checked it many times.  As you pointed out, the problem is probably not getting approval  from the TV.  But there is no popup on TV.  Is it related to my TV model?  Or is there any other way to give this approval?
________________________________

**Comment by merdok** [comment]
The plugin only officially supports TVs with webos2 and higher, but i got reports from other people that it was also working on webos1.4 TVs. For this reason i think that there is something that you are doing wrong or simply this is a network issue or configuration issue. Again make sure that the ip address of the TV is reachable from your homebridge device. Make also sure that there is no firewall blocking the request. Recheck that all the relevant settings on your TV are enabled(maybe they are called different on webos1 TVs). Those are the things that i can recommend from you try.

**Comment by okilic93** [comment]
Thank you again for your explanations. I will follow your instructions again. If it will not work again. Nothing to do. :) thanks

________________________________

**Comment by merdok** [comment]
Sure, just me let me know if you were successful :)

**Comment by okilic93** [comment]
Problem is solved.  Thank you again.  I found a way to somehow approve on TV and started working.  The only problem is when the TV is off, when I press the switch on,  the TV won't turn on.  In modem settings, TV IP appears to be off when TV is off.  I think ,For this reason, when I want to open it, I think the system cannot find the IP.  Is it the same for you?

________________________________

**Comment by merdok** [comment]
webos1 TVs unfortunately cannot be turned on remotely so that will not work.
