### ISSUE TITLE
  I can't add TV to Homekit

### ISSUE THREAD

**Issue by svsiznoi** [merdok/homebridge-webos-tv#340]
Good afternoon. I installed the plugin and configured it. TV appeared in Homebridge in the Ok status, after trying to add it to the Homekit app, but the app does not find it. What can be done?
<img width="1373" alt="Снимок экрана 2021-01-12 в 22 17 28" src="https://user-images.githubusercontent.com/77357263/104362116-7086d400-5524-11eb-8f8b-afe0a809a1dd.png">
<img width="1067" alt="Снимок экрана 2021-01-12 в 22 17 14" src="https://user-images.githubusercontent.com/77357263/104362137-754b8800-5524-11eb-8c97-58d20c2cbeeb.png">

**Comment by merdok** [comment]
Did you read the README? 
There are additional steps required in order to make the TV to appear in HomeKit. It does not appear automatically!
https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-the-home-app

**Comment by svsiznoi** [comment]
Yes, I did everything as described in your instructions, but on step 4, the Homekit app does not find my TV. I have a TV with native Homekit, maybe this is the problem?

**Comment by merdok** [comment]
Native HomeKit should not be an issue, both can be used at the same time. 
I think then it might be a network issue on your side, make sure that your firewall does not block the TV or certain ports, you need to be able to ping your TV from your homebridge device. Also it might be an issue with your Home in HomeKit, try to create a new home and check if that fixes your issue.

**Comment by svsiznoi** [comment]
Can you tell me how to check the firewall block? Sorry, I have little experience in this matter

**Comment by svsiznoi** [comment]
And at the same time, the TV appeared in the Homebridge application(this can be seen in the screenshot in my first post) and through it I can control my TV, so I think that everything is fine with the ports. Creating a new home also doesn't solve the problem.

**Comment by merdok** [comment]
The TV might appear locally but it can be blocked in HomeKit due to your firewall. Unfortunately i cannot help you with any network related issues because that depends on your home network setup.
The plugin itself works fine since you can see it in homebridge and control your TV, so your issues are not related to the plugin itself but to something in your local environment... I suspect some network configuration

**Comment by svsiznoi** [comment]
Apparently I will have to use native functions, I did not find a solution to the problem. Other Homebridge plugins work without problems with HomeKit.

**Comment by merdok** [comment]
TVs needs to be added manually to the Home app and if you followed the README and it still does not appear then this strongly indicates an issue with your environment. It might be a homebridge issue (you could try to reinstall it or clear the homebridge cache) or it might be a network issue.

**Comment by 6MH89F3j** [comment]
FWIW, I'm having the same issue. I tried to open up the ports, but Im not sure what Im doing, lol.

It's weird, but I had my TV working just fine in the Home app (I've had the plugin installed for about 7 months). I needed to reinstall stuff for a different issue. After re-installation, I can't get it to add to HomeKit anymore.

I have an Eero network setup, and do have Eero secure enabled. I guess I will try playing with that stuff a little more.

**Comment by svsiznoi** [comment]
Thanks for the answers, I solved my problem. Previously, I already had this plugin installed in conjunction with the old TV, after replacing it with a new one with native HomeKit support, I deleted the plugin, but the old TV remained in the cache of Homebridge itself, I deleted the old TV from the cache and reinstalled the plugin and everything worked.

**Comment by 6MH89F3j** [comment]
If you dont mind me asking, how did you remove it from the cache of homebridge? I'm guessing I have the same problem, since I just did a reinstall of things.

**Comment by svsiznoi** [comment]
But now there is another problem, periodically the visibility of my TV in the ios remote app disappears, while in the Homekit app I see my TV and can control it. If you switch the TV via the original LG remote, it appears in the ios remote app itself. What could be the problem?

**Comment by svsiznoi** [comment]
> If you dont mind me asking, how did you remove it from the cache of homebridge? I'm guessing I have the same problem, since I just did a reinstall of things.

Do you have the Homebridge Config UI X web interface installed?

**Comment by 6MH89F3j** [comment]
I am using Hoobs.

**Comment by svsiznoi** [comment]
Through Hoobs, unfortunately, I will not tell you how to do this. In my Web UI X interface, you need to go to settings-connected bridges and TV and delete the old device from there. Look around maybe you have something similar

**Comment by 6MH89F3j** [comment]
Fair enough. I think I found a way, but it seems nuclear and will make me repair my entire bridge. I’ll keep looking. Thanks for the helping me get farther along on this issue 🙏

**Comment by svsiznoi** [comment]
> Fair enough. I think I found a way, but it seems nuclear and will make me repair my entire bridge. I’ll keep looking. Thanks for the helping me get farther along on this issue 🙏

In my web interface, there are two reset options, the first is when you can reset a separate device(the one you need), and the second option is to reset all Homebridge settings. The main thing here is not to make a mistake. Later I can send screenshots of what it looks like for me.

**Comment by merdok** [comment]
In a other issue someone had a similar issue and the solution there was:

in Homebridge, the TV was still listed under ⁞ Unpair Bridges / Cameras / TVs / External Accessories
removing that solved this issue.

**Comment by 6MH89F3j** [comment]
Yeah, I’m on Hoobs and did a “Reset Connection” and that seemed to clear it up. I was able to reinstall the plug-in and then the TV showed up right away when trying to add the accessory from the home app.

**Comment by svsiznoi** [comment]
> In a other issue someone had a similar issue and the solution there was:
> 
> "
> in Homebridge, the TV was still listed under ⁞ Unpair Bridges / Cameras / TVs / External Accessories
> removing that solved this issue.
> "

But now there is another problem, periodically the visibility of my TV in the ios remote app disappears, while in the Homekit app I see my TV and can control it. If you switch the TV via the original LG remote, it appears in the ios remote app itself. What could be the problem?

**Comment by merdok** [comment]
@svsiznoi sorry but I do not understand what your issue is. Could you explain more detailed?

**Comment by svsiznoi** [comment]
TV regularly disappears from the standard remote control app, the photo shows when the remote sees the TV
![26575403-7DB2-465F-BA5E-A9D126FE4D15](https://user-images.githubusercontent.com/77357263/104699925-7ba85280-5724-11eb-9877-d0ad6a3c23b2.jpeg)
![F23AF4BD-944B-4694-BD06-0241C108BAC3](https://user-images.githubusercontent.com/77357263/104699936-7fd47000-5724-11eb-93b6-87ac29e668ed.jpeg)

**Comment by svsiznoi** [comment]
Very often, when I go to the remote control app, the TV disappears and I can't control it through the remote. But at the same time, I can see it in the Homekit app and manage it. In the photo I show it when I don't see it. 
![D2108ADB-E538-4453-9C26-B36420DD92D9](https://user-images.githubusercontent.com/77357263/104700169-ce820a00-5724-11eb-9eb8-cded9877c555.png)

**Comment by merdok** [comment]
Oh, I guess this has also something to do with homebridge or your environment. You would need to do some investigation in your local setup...

**Comment by svsiznoi** [comment]
It is unlikely that this is a problem in my network, in the Home Kit application my TV is working properly and I can see its status and can always control it. But in the application, the remote control, for some reason it periodically disappears

**Comment by merdok** [comment]
I do not know if this is your network, homebridge or HomeKit, but it is certainly an local issue with your setup. You need to investigate this and find out what is causing this.
