### ISSUE TITLE
Struggle in my TV

### ISSUE THREAD

**Issue by treforparr** [merdok/homebridge-webos-tv#342]
Struggling to connect my TV to hoobs/ HomeBridge 32LM6300PLA, are you experiencing problems with plug-in

**Comment by merdok** [comment]
Would be nice if you could post your config and setup and also what you tried so far so at least that would give us a small idea what is happening...

**Comment by treforparr** [comment]
Of course I will but I’m gonna have to reinstall the plug-in because it kept crashing

**Comment by treforparr** [comment]
I've managed to get it installed using the home Manager app Took a bit of fiddling but I did manage to do it

**Comment by merdok** [comment]
Nice. So it works now?

**Comment by treforparr** [comment]
Yeah but it was a bit of a head fuck to be honest it's took me 4 to 5 hours to get it working

**Comment by merdok** [comment]
Ok, good that works now! Thanks for letting me know! The issue can ble closed i guess.
