### ISSUE TITLE
Voice search

### ISSUE THREAD

**Issue by jfrenzy** [merdok/homebridge-webos-tv#344]
Is there any way to force newer TVs with Google assistant in the remote to voice search with Siri as like a remote button or something?

**Comment by merdok** [comment]
I am pretty sure that this is impossible. You can only use Siri to control your TV.

**Comment by jfrenzy** [comment]
Allow me to elaborate, I mean send a signal to work like a press of the voice search button so that you would be able to use the microphone in the remote from a distance to voice search.

**Comment by merdok** [comment]
Oh, ok. Well, that could maybe be possible, so you can emulate a remote button press, but I am not sure if the voice search button can be emulated. If you check the README on the bottom you will find a list of all possible values, you could try some of them with the cryptic number and see if any of them will work. Also maybe something like VOICE_SEARCH could work but this is just a guess? You could also try to guess the name as I think it might be called similar like the other buttons.
