### ISSUE TITLE
 ‘Connecting to TV’ when adding the TV to HomeKit - no fix

### ISSUE THREAD

**Issue by frogstar** [merdok/homebridge-webos-tv#349]
Hi and thanks for the great work. The PlugIn worked fine for me until i moved the TV into a firewalled IoT Network. 
I am able to reach the TV and can switch channels in the homebridge webinterface, but i am unable to add the TV back into HomeKit. I am seeing the mentioned "Connecting to TV".

My Firewall allows all traffic initiated on the main LAN and i added rules to allow the LG TVs to reach the Homebridge on the suggested ports. Unfortunately that didnt fix the issue for me. Any idea or suggestion where else i could check to see whats going wrong?

**Comment by merdok** [comment]
Hi,
i assume that you did check the https://github.com/merdok/homebridge-webos-tv#fixes-to-known-issues section?
Other then that i can only suggest you to check your network configuration. The  "Connecting to TV" issue is usually related to your local network.

**Comment by frogstar** [comment]
I did look at the "fixes" section before and tested after implementing the suggested changes. However - as you said, it is probably something else in my local network. Might be a caching issue due to the fact that i moved the TV from 'main' to 'IoT' - remember having some trouble witch caching with the unifi gear before. 
Thanks for your reply though!
