### ISSUE TITLE
AirPlay doesn't work anymore

### ISSUE THREAD

**Issue by AndreasHellmiss** [merdok/homebridge-webos-tv#353]
Hi, I'm owning a new LG OLED that support native HomeKit and AirPlay2. I want to use this PlugIn to get e.g. Netflix to my inputs. 
Unfortunately once I use this plugin to integrate my TV into my Home application my TV is shown as an AirPlay device but I can't get it connected. Are there any settings I have to consider?
Additionally there is the "hide native TV service" flag but once I activate this, my TV is not accessible anymore so I disabled it. Is that the setting I have to workaround?

**Comment by merdok** [comment]
This plugin has no effect on your native HomeKit or Airplay2 functionality, all of the run independently to each other.
The "hide native TV service" is only to be used if you use this plugin and have the native TV HomeKit enabled, in that case you will not have 2 TVs appear in your Home app.
