### ISSUE TITLE
Not working for LG 47LW5600

### ISSUE THREAD

**Issue by mrfatboy** [merdok/homebridge-webos-tv#354]
I just found this plugin and wanted to try to install for my 2011 LG 47LW5600 Webos2 tV.  I followed the instructions and added the plugin as well as added the TV to the Home app on my iphone.  Both the ON/OFF & Volume sliders don't control the TV in the Home app.

One part of the instructions I could not complete because I could not find the **Mobile TV setting** on the LG TV.  I looked everywhere.  Is my TV compatible or just too old?

**You also need to enable mobile TV on on your TV for the turn on feature to work correctly.

This is located on your TV under Settings > General > Mobile TV On

On newer TVs LG Connect Apps under the network settings needs to be enabled.**

I just wanted basic ON/OFF control and volume.  All other functions are controlled by my Directv box.  

The LG iphone app does work but I don't want to use it.  Do I need to do something with the pairing key?

thanks

**Comment by merdok** [comment]
Your TV is unfortunately too old and i do not think that it runs webOS.

**Comment by mrfatboy** [comment]
I think you are correct. I could not find the webos version in the settings. There was a SDK 1.05 reference though. Same thing?

BTW, I also could not uninstall the plug in from Homebridge UI. It gave errors. I had to manually uninstall.
