### ISSUE TITLE
Volume up/down as trigger from remote

### ISSUE THREAD

**Issue by rooi** [merdok/homebridge-webos-tv#358]
Hi Merdok!

I've just  update to the new version 2.x.x of your plugin. Great changes!
Is it me, or is the volume up/down trigger not working any longer?
https://github.com/merdok/homebridge-webos-tv/pull/147

When I press up/down on the remote, I can see the following message in homebridge debug:
[TV] Audio status changed. Current volume: 7, Muted: No

Still my automations don't get triggered.

I check to code and noticed the prepareTvSpeakerService() and the following lines:
this.logDebug('Volume change over the remote control (VolumeSelector), pressed: %s', state === Characteristic.VolumeSelector.DECREMENT ? 'Down' : 'Up');

This debug message is not show. Could this be related to the missing up/down tigger or am I doing something wrong?

Thanks!

Roy

**Comment by merdok** [comment]
Oh, you are right! This somehow got lost during the update. Will have a look at it and try to add it back in the next update.

**Comment by rooi** [comment]
Thx!

**Comment by merdok** [comment]
Should be fixed in version 2.1.2

**Comment by rooi** [comment]
That was fast, thanks! Work great!
