### ISSUE TITLE
Hiding TV Service throws 'error' regarding max inputs

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-webos-tv#360]
I assume it is not really something to worry about. I am hiding the TV service as my LG is natively HomeKit compatible and get the following message. For testing purposes I activated the TV service and the message disappeared.

`[01/04/2021, 06:37:27] [homebridge-webos-tv] [LG OLED77CX] Inputs limit (45) reached. Cannot add any more new inputs!`

It is just cosmetic I guess :)

**Comment by merdok** [comment]
Oh, that should not happen of course! I will check it out! Thanks for reporting.

**Comment by merdok** [comment]
Should be fixed in version 2.1.3
