### ISSUE TITLE
Question/feature request: simple switch for on/off status for automations

### ISSUE THREAD

**Issue by CooperCGN** [merdok/homebridge-webos-tv#361]
As the title says I am trying to create some automations with the TVs power status as condition which you can't set in 3rd party apps. Would it be possible to have an optional simple on/off switch as status indicator?

**Comment by merdok** [comment]
Hmm, not sure if a dedicated switch would make sense since there are other ways to do that like a soundOutputButton if you do not switch sound outputs that often. Would that not work for you?

**Comment by CooperCGN** [comment]
Oh I see, yes I can use that as I am only using TV output or arc. As I am planning to use it in a automation converted to shortcut I simply will do to IFs.
