### ISSUE TITLE
Dummy inputs on webOSTV 2.0 

### ISSUE THREAD

**Issue by adrianopery** [merdok/homebridge-webos-tv#363]
Today on my app home the device TV was showing all the inputs on the inputs spinner are "Dummy".
I had to rename manually, but would like to know if is possible to fix it.

**Comment by merdok** [comment]
It actually should not happen, maybe that was caused by some kind of bug by the TV? 
You would need to provide a homebridge debug log of such event so i can at least see what caused the issue in order find out the actual cause and to be able to prevent that. Do you maybe have the homebridge debug log when that happend?

**Comment by adrianopery** [comment]
> It actually should not happen, maybe that was caused by some kind of bug by the TV?
> You would need to provide a homebridge debug log of such event so i can at least see what caused the issue in order find out the actual cause and to be able to prevent that. Do you maybe have the homebridge debug log when that happend?

I'm using Hoobs not homebridge.
Anyway, I'll send to you my log.

07/04/2021 09:45:45 Got SIGINT, shutting down Bridge...
07/04/2021 09:45:56 Initializing HAP-NodeJS v0.9.3...
07/04/2021 09:45:57 Loaded plugin 'homebridge-broadlink-rm-pro'
07/04/2021 09:45:57 [2021-4-7 9:45:57] Registering platform 'homebridge-broadlink-rm-pro.BroadlinkRM'
07/04/2021 09:45:57 Loaded plugin 'homebridge-camera-ffmpeg'
07/04/2021 09:45:57 [2021-4-7 9:45:57] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
07/04/2021 09:45:57 Loaded plugin 'homebridge-magichome-platform'
07/04/2021 09:45:57 [2021-4-7 9:45:57] Registering platform 'homebridge-magichome-platform.MagicHome-Platform'
07/04/2021 09:45:57 Loaded plugin 'homebridge-webos-tv'
07/04/2021 09:45:57 [2021-4-7 9:45:57] Registering platform 'homebridge-webos-tv.webostv'
07/04/2021 09:45:58 Loaded plugin 'homebridge-yamaha-avr'
07/04/2021 09:45:58 [2021-4-7 9:45:58] Registering platform 'homebridge-yamaha-avr.yamaha-avr'
07/04/2021 09:45:58 Loading 5 platforms...
07/04/2021 09:45:58 [webostv] Initializing webostv platform...
07/04/2021 09:45:58 [Camera ffmpeg] Initializing Camera-ffmpeg platform...
07/04/2021 09:45:58 [MagicHome-Platform] Initializing MagicHome-Platform platform...
07/04/2021 09:45:58 Initializing platform accessory 'Led Quarto Didi'...
07/04/2021 09:45:58 Initializing platform accessory 'Led Quarto Didi (Party)'...
07/04/2021 09:45:58 [Yamaha AVR] Initializing yamaha-avr platform...
07/04/2021 09:45:58 [BroadlinkRM] Initializing BroadlinkRM platform...
07/04/2021 09:45:58 [BroadlinkRM] [INFO] Automatic Broadlink RM device discovery has been disabled as the "hosts" option has been set.
07/04/2021 09:45:58 [INFO] Adding RF Support to device A0:43:B0:54:1D:F0 with type 2227
07/04/2021 09:45:58 [BroadlinkRM] [INFO] Running Homebridge Broadlink RM Plugin version 4.4.1-beta.3
07/04/2021 09:45:58 [BroadlinkRM] Persiana Accessory Ready
07/04/2021 09:45:58 [Camera ffmpeg] [Entrada Social] Configuring cached bridged accessory...
07/04/2021 09:45:58 [Camera ffmpeg] [Entrada Externa] Configuring cached bridged accessory...
07/04/2021 09:45:58 [Camera ffmpeg] [Entrada Varanda] Configuring cached bridged accessory...
07/04/2021 09:45:58 [Camera ffmpeg] [Garagem Externa] Configuring cached bridged accessory...
07/04/2021 09:45:58 [webostv] Init - initializing devices
07/04/2021 09:45:58 [webostv] [TV Sala] Init - got TV configuration, initializing device with name: TV Sala
07/04/2021 09:45:58 [webostv] [TV quarto master] Init - got TV configuration, initializing device with name: TV quarto master
07/04/2021 09:45:59 [webostv] [TV quarto da frente] Init - got TV configuration, initializing device with name: TV quarto da frente
07/04/2021 09:45:59 Initializing platform accessory 'Learn IR'...
07/04/2021 09:45:59 Initializing platform accessory 'Learn RF'...
07/04/2021 09:45:59 Initializing platform accessory 'Persiana'...
07/04/2021 09:45:59 Preparing Advertiser for 'TV Sala 0564' using bonjour-hap backend!
07/04/2021 09:45:59 Preparing Advertiser for 'TV quarto master C866' using bonjour-hap backend!
07/04/2021 09:45:59 Preparing Advertiser for 'TV quarto da frente 226B' using bonjour-hap backend!
07/04/2021 09:45:59 Preparing Advertiser for 'HOOBS 208C' using bonjour-hap backend!
07/04/2021 09:45:59 Starting to advertise 'TV Sala 0564' using bonjour-hap backend!
07/04/2021 09:45:59 TV Sala 0564 is running on port 42441.
07/04/2021 09:45:59 Please add [TV Sala 0564] manually in Home app. Setup Code: 031-45-154
07/04/2021 09:45:59 Starting to advertise 'TV quarto master C866' using bonjour-hap backend!
07/04/2021 09:45:59 TV quarto master C866 is running on port 33647.
07/04/2021 09:45:59 Please add [TV quarto master C866] manually in Home app. Setup Code: 031-45-154
07/04/2021 09:45:59 Starting to advertise 'TV quarto da frente 226B' using bonjour-hap backend!
07/04/2021 09:45:59 TV quarto da frente 226B is running on port 35245.
07/04/2021 09:45:59 Please add [TV quarto da frente 226B] manually in Home app. Setup Code: 031-45-154
07/04/2021 09:45:59 Starting to advertise 'HOOBS 208C' using bonjour-hap backend!
07/04/2021 09:45:59 Bridge is running on port 51826.
07/04/2021 09:45:59 [BroadlinkRM] Persiana getCurrentPosition: 0
07/04/2021 09:45:59 [BroadlinkRM] Persiana getPositionState: 2
07/04/2021 09:45:59 [BroadlinkRM] Persiana getTargetPosition: 0
07/04/2021 09:46:00 [webostv] [TV Sala] Connected to TV
07/04/2021 09:46:00 Preparing Advertiser for 'Yamaha AVR 59F3' using bonjour-hap backend!
07/04/2021 09:46:00 Starting to advertise 'Yamaha AVR 59F3' using bonjour-hap backend!
07/04/2021 09:46:00 Yamaha AVR 59F3 is running on port 34283.
07/04/2021 09:46:00 Please add [Yamaha AVR 59F3] manually in Home app. Setup Code: 031-45-154
07/04/2021 09:46:00 [webostv] [TV Sala] Got TV information
07/04/2021 09:46:00 [webostv] [TV Sala] TV webOS version: 2.0
07/04/2021 09:46:00 [webostv] [TV Sala] TV turned on!
07/04/2021 09:46:00 [webostv] [TV Sala] App launched, current appId: com.webos.app.hdmi2
07/04/2021 09:46:00 [webostv] [TV Sala] Sound output changed. Current sound output: tv_speaker
07/04/2021 09:46:00 [webostv] [TV Sala] Subscribed to TV services
07/04/2021 09:46:00 [webostv] [TV Sala] Connected to remote pointer input socket
07/04/2021 09:46:00 [webostv] [TV Sala] Setup finished
07/04/2021 09:46:00 [webostv] [TV Sala] TV setup finished, ready to control tv
07/04/2021 09:46:04 [BroadlinkRM] Persiana getCurrentPosition: 0
07/04/2021 09:46:04 [BroadlinkRM] Persiana getPositionState: 2
07/04/2021 09:46:04 [BroadlinkRM] Persiana getTargetPosition: 0
07/04/2021 09:46:05 [BroadlinkRM] Persiana getCurrentPosition: 0
07/04/2021 09:46:05 [BroadlinkRM] Persiana getPositionState: 2
07/04/2021 09:46:05 [BroadlinkRM] Persiana getTargetPosition: 0
07/04/2021 09:46:05 [Yamaha AVR] Current input: Vivo TV (HDMI1)
07/04/2021 09:46:10 [BroadlinkRM] Persiana getTargetPosition: 0
07/04/2021 09:46:10 [BroadlinkRM] Persiana getCurrentPosition: 0
07/04/2021 09:46:10 [Yamaha AVR] Current input: Vivo TV (HDMI1)
07/04/2021 09:46:14 [Yamaha AVR] Current input: Vivo TV (HDMI1)
07/04/2021 09:46:32 Got SIGINT, shutting down Bridge...

**Comment by merdok** [comment]
The log you provided looks perfectly fine, although this is not a debug log.
And I do not need a start log, you need to provide me the log when the issue happens. 
Does the issue happens all the time or happened only once and never again?

**Comment by adrianopery** [comment]
Yes, all the time.
On app home I can only see "dummy"
![image](https://user-images.githubusercontent.com/49798093/113886158-d3d87900-9796-11eb-86d3-1df412662e13.png)

**Comment by merdok** [comment]
Try to delete the cache file. Should be under .homebridge/.webosTv/
or depending if you set a custom location then it is elsewhere.
You can delete all files there expect the keyFile.

**Comment by miket0429** [comment]
any update on this? mine started doing this last week. The plug-in is up-to-date and I have deleted the cache files and restarted Homebridge.

**Comment by merdok** [comment]
This is a bug with the home app, you need to force kill it and then reopen it, that should fix the issue.

**Comment by adrianopery** [comment]
the strange is that I have 2 tvs exactly same model, date purchase and etc....
One works fine, the other no.

**Comment by merdok** [comment]
This has nothing to do with the TV itself...

**Comment by miket0429** [comment]
> This is a bug with the home app, you need to force kill it and then reopen it, that should fix the issue.

Force killing the Home app doesn't seem to fetch the correct input names. I just manually renamed the dummy inputs in the Home app settings (AV, HDMI1, HDMI2, HDMI3, HDMI4) and they seem to persist so we're good for now.

**Comment by adrianopery** [comment]
I noted that this starts to occurs after web os update a few months ago.

**Comment by luigi-lauro** [comment]
I also ended up with some "dummy" in my LG LCD TV, so I can confirm the bug.

**Comment by merdok** [comment]
It is a cache issue, it is recommended to force close (kill) the home app and reopen it. That should usually get rid of that issue
