### ISSUE TITLE
Turn tv no and off

### ISSUE THREAD

**Issue by danielstorch** [merdok/homebridge-webos-tv#365]
I have homebridge and everything running and configured, but somehow can't find the option for turning my tv on and off? I have the option turn the screen on/off, but can't completely turn the tv off.

What am i missing?

**Comment by merdok** [comment]
This option is on the tv accessory! Maybe you did hide your TVs accessory? 
Also if you are using a third party app for controlling HomeKit like Eve, they have no tv accessory support so you will not see that there.

**Comment by danielstorch** [comment]
Yeah, that was it, thanks. I got the button now. I turned it off first, since it was proposed in the readme.
