### ISSUE TITLE
Problem with two LG TV

### ISSUE THREAD

**Issue by michelebossa** [merdok/homebridge-webos-tv#37]
Hi i have a problem to use these plugin with two LG TV at moment i have configured both but when i use the power button or the volume control in some case the action go to another television configured.
For example power off the TV on kitchen but will go down the TV on the dinner room.
I think there is the owerwrite of configuration during the process on homebridge.

My configuration.

    {
      "accessory": "webos3",
      "name": "TV Salone",
      "ip": "192.168.1.105",
      "mac": "3C:CD:93:78:B7:ED",
      "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
      "pollingEnabled": true
    },
    {
      "accessory": "webos3",
      "name": "TV Cucina",
      "ip": "192.168.1.106",
      "mac": "3C:CD:93:9F:D6:7B",
      "keyFile": "/home/pi/.homebridge/tvcucina/lgtvKeyFile",
      "pollingEnabled": true
    }
There is some action to do to handle these situation?
Thanks.

**Comment by merdok** [comment]
Hi,
thanks for the report. That is a strange problem, i will check if i can fix this issue somehow, but the problem is that i don't have 2 TVs so i am not sure if i will be able too.

**Comment by michelebossa** [comment]
If you want i can do a test for the fix

**Comment by michelebossa** [comment]
Hi merdok thanks for replay i hope you find the fix.

**Comment by merdok** [comment]
Sure, when i need any help then i will let you know.

**Comment by m11rphy** [comment]
Did this ever get fixed? I have bought another TV and don’t want to add it and mess up the other one

**Comment by merdok** [comment]
I am experiencing issues with my RPi since some time now... I first need to stabilize my setup again, after that i will have a look at it.

**Comment by tmcleod3** [comment]
Confirming this error. Can't manage more than one TV.

**Comment by merdok** [comment]
I will see what i can do about it.

**Comment by merdok** [comment]
Sorry, i am still trying to get my Pi back to work with the RPi guys. I upgraded to a 3B+ and since then i have endless issues... As soon as my setup is stable again i will check it out...

**Comment by merdok** [comment]
Should be fixed with latest release, could somebody please try it and let me know? Please note that i renamed the package to `homebridge-webos-tv`, so you need to install this new package and adjust your config.json

**Comment by merdok** [comment]
Yes, you need different keyfiles for each TV. And yes, you can remove the old package after installing this new one.

**Comment by michelebossa** [comment]
Hi Thanks for the new version for me now the problem it is fixed :)

**Comment by michelebossa** [comment]
Hi,
Example of my configuration
{
  "accessory": "webostv",
  "name": "TV Salone",
  "ip": "192.168.1.105",
  "mac": "3C:CD:93:78:B7:ED",
  "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
  "pollingEnabled": true
},
{
  "accessory": "webostv",
  "name": "TV Cucina",
  "ip": "192.168.1.106",
  "mac": "3C:CD:93:9F:D6:7B",
  "keyFile": "/home/pi/.homebridge/tvcucina/lgtvKeyFile",
  "pollingEnabled": true
}
to remove the old package use npm uninstall homebridge-webos3.
Thanks.

**Comment by m11rphy** [comment]
Thanks buddy I’ll install when I get home from work

**Comment by merdok** [comment]
Good to hear that it is fixed now :)
