### ISSUE TITLE
Delay in TV setup after turn on

### ISSUE THREAD

**Issue by luigi-lauro** [merdok/homebridge-webos-tv#370]
It takes about 10-20 seconds from the turn-on command from HomeKit, until when the 'tv setup' as per logs is completed ('TV setup finished, ready to control TV') and the TV is indeed ready to be controlled. Any input given in that time window (e.g. turn off) will not work and the HomeKit status will just revert back. I don't know if it's possible to shorten this delay because as of know it's quite long and it can be cumbersome (e.g. turn on and then change input to launch TV native app). Background polling interval is set to 5 seconds in my case.

**Comment by merdok** [comment]
The tv setup is necessary and assures that when you control the TV all the required information is present and the tv indeed can be controlled. Besides that the TV itself also needs some time to startup and setup all the required endpoints. 

Also please note that most of the actions which you can do (e.g. launch a native app) take that booting time into account. So i am not sure if you are aware of that (this is also documented in the README), you can straight use a `appButton` to launch a native app on your TV even when the TV is off. The tv will then turn itself on and as soon as it is read to be controlled dit will automatically switch to the app which you launched.

**Comment by luigi-lauro** [comment]
Thank you Merdok. I knew physical appbutton work that way from the TV remote but I didn't think to setup appbuttons in plug-in to work around the issue. It's a good suggestion I will use it. Once again I suggest to mention this issue and proposed workarounds in known issues section to avoid further stupid questions like mine :-) thank you once again
