### ISSUE TITLE
RC values: VoiceControl and 2. PowerOn?

### ISSUE THREAD

**Issue by ChrWi** [merdok/homebridge-webos-tv#372]
Hello,
I catched this really nice addon. In terms of remote control values, I am wondering if 
1. the voice button (between Home and Settings) 
2. the 2nd power button on upper right
can be configured as well?
I am using an 8500 nano (2020) with webOS 4.5

**Comment by merdok** [comment]
Hi,

so you can check all the possible RC values here: https://github.com/merdok/homebridge-webos-tv#remote-control-values
I did jailbreak my TV and fetched the values from the TV itself so i do not think that there are any more possible values, unless i missed some files on the TV...

**Comment by ChrWi** [comment]
Hi @merdok. I already checked your list before. But the hint with the official app is a good one: both buttons are not included. A pity, but that‘s life. Thanks for you work!
