### ISSUE TITLE
Feature request- apps as spinner or in inputs spinner

### ISSUE THREAD

**Issue by JackGabbay** [merdok/homebridge-webos-tv#373]
Hi, love the project. Would be great if there was an option to add apps to the spinner for inputs or have a second spinner for apps instead of the toggle buttons.

**Comment by merdok** [comment]
Hi,
thanks for the feedback.
I do not quite understand the issue. The input spinner has already all the inputs and apps from your tv. As default only a few inputs are shown but you can scroll slightly down in that home App view where the spinner is to reveal a list where you can enable which apps or inputs should be visible there.
Did you try that?

**Comment by JackGabbay** [comment]
I only see toggle switches for the apps. Is there a setting I missed?

![image](https://user-images.githubusercontent.com/10299103/119913092-0bf47080-bf2b-11eb-88e9-8008afe43a9b.png)![image](https://user-images.githubusercontent.com/10299103/119913097-0dbe3400-bf2b-11eb-987c-a38bd1ed7768.png)

**Comment by merdok** [comment]
Yes, you need to go inside the the group, there is a button on the bottom saying "Show devices in this group". There you have the correct TV accessory and on that accessory you can configure yourself the input spinner.
