### ISSUE TITLE
Auto-connect Bluetooth Speakers?

### ISSUE THREAD

**Issue by fatmarker** [merdok/homebridge-webos-tv#374]
LG TVs have an [issue](https://lgcommunity.us.com/discussion/5112/speakers-wont-automatically-connect-to-bluetooth/p4) with automatically connecting to Bluetooth speakers.

1. If I first turn on the TV and then the speakers, it identifies the speakers and prompts me to connect.
2. If I first turn on the speakers, wait a second, and then the TV, it connects them automatically.

In either case, the speakers go off automatically when the TV goes off.

Problem: Since the speakers have no smart functionality, I can't automate them to turn on and connect to the TV.

If I turn only the TV on, and connect to the recent speakers in the sound settings, this turns them on and connects them. So the TV has the ability to turn on and connect to the speakers, but I see no way of doing this automatically.

I thought I might be able to achieve this with Homebridge. I'm using your plugin, I've set the soundOutput button to bt_soundbar and it does set Sound Out to Bluetooth when the TV comes on. However, it doesn't connect to the speakers. Any idea?

**Comment by merdok** [comment]
Hi,

as far as I know it is it possible to trigger a connection using the public webos api. You can only change the sound output device.

What might work for you is that after you switch the sound output, you run a remote button sequence which triggers the connection. You would need to first check out what exact sequence is required for that and then try it out.

**Comment by fatmarker** [comment]
Okay, good to know. And thanks for the tip. I'll try that. 🙂
