### ISSUE TITLE
App list

### ISSUE THREAD

**Issue by Stetocasa** [merdok/homebridge-webos-tv#377]
Hello, how can we add the favorite app to launch in the TV list as attached?
I just understand how expose the app button

I'd like to have the favorite app as part of the list

Thanks
Stefano ![image](https://user-images.githubusercontent.com/70729310/125194268-bf51c400-e250-11eb-999e-fc5bec8fc5bc.jpeg)

**Comment by merdok** [comment]
Sorry, i do not quite understand what you mean? The list is populated automatically from the TV, you can go the TV accessory and configure yourself which entries to show there. What else is missing for you?

**Comment by Stetocasa** [comment]
The TV turn off right but no app populated in the list ![image](https://user-images.githubusercontent.com/70729310/125194736-d5f91a80-e252-11eb-8b16-c47064cceeb7.png)

**Comment by merdok** [comment]
You probably disabled all the apps in the list, enable them under the tv accessory.

**Comment by Stetocasa** [comment]
I'm not sure to understand how fix that? Could you please specify how and where?
Thanks

**Comment by merdok** [comment]
Go to the TV accessory, scroll down below the list, there you will have an additional list where you can enable/disable what inputs/apps are shown in the input spinner.

**Comment by Stetocasa** [comment]
Cannot find nothing 😑 https://user-images.githubusercontent.com/70729310/125195126-9af7e680-e254-11eb-9ab8-cff55e3b8113.MOV

**Comment by merdok** [comment]
Then you need to post the debug log. Start homebridge in debug mode and post the output here. Also try to delete the cache.

**Comment by Stetocasa** [comment]
This is my config.


    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "My LG TV",
                    "ip": "192.168.178.87",
                    "mac": "a0:6F:AA:60:xx:xx",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "channelControl": false,
                    "volumeControl": false,
                    "deepDebugLog": true
                }
            ]
        }
    ]
}

**Comment by Stetocasa** [comment]
This is the log


    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "My LG TV",
                    "ip": "192.168.178.87",
                    "mac": "a0:6F:AA:60:57:65",
                    "pollingInterval": 5,
                    "volumeLimit": 100,
                    "channelControl": false,
                    "volumeControl": false,
                    "deepDebugLog": true
                }
            ]
        }
    ]
}

**Comment by Stetocasa** [comment]
Solved!
I removed the LG connect app authorization and connected again. 
Now all definitely works well.
You can close

Thanks

**Comment by merdok** [comment]
ok, good to hear! Thanks for the info!
