### ISSUE TITLE
LG projector with Web OS

### ISSUE THREAD

**Issue by philippvogel** [merdok/homebridge-webos-tv#379]
Does this also work with projectors with installed Web OS?

**Comment by merdok** [comment]
That is actually a very good question. I myself never tried it with a projector neither I know of someone who tried it. But when the projectors run the same or a similar version of webos as the TVs then I do not see any reason why it should not work. Do you have a projector and can try it out?

**Comment by philippvogel** [comment]
Yes. I will have one soon and I will try it out.

**Comment by merdok** [comment]
Perfect, please let me know then if it works, if am also quite interested now😅

**Comment by merdok** [comment]
Oh, nice! Good to hear that it is working. Just out of curiosity what webos version does the projector use?

**Comment by philippvogel** [comment]
webOS 4.5
