### ISSUE TITLE
Remote controls dependent on Magic Remote

### ISSUE THREAD

**Issue by leoravagnani** [merdok/homebridge-webos-tv#380]
Hey!! Just downloaded Homebridge a couple hours ago after being frustrated with the built-in HomeKit support of my TVs and it's great to have way more automation possibilites available (and proper offline state hahaha) - I'm really enjoying it so far!. I've come across a scenario that I think is quite odd, but I don't think there's a way around it, but wanted to confirm if this is known.

Using the Remote from Control Center I'm able to navigate apps such as YouTube and Netflix and control the Internal Speaker volume normally as should be, but when I'm on my Set-Top Box input the nav buttons don't do anything (the same happens when I set sound output to Optical, adjusting the volume shows the volume UI on the TV, but it doesn't relay to my Home Theater).

Now here's the odd part, If I move my Magic Remote around suddenly controls start working as they should (both devices were setup on Device Connector to work with the remote). It seems the TV receives the commands and then relay them to the remote which in turn relay them to the devices, most likely as IR commands. After a few seconds the controls simply stop working again, probably because the Magic Remote enters stand-by to preserve battery.

I tested this with LG's own app and I get the exact same behaviour, it only works after I wake the Magic Remote. Maybe there's a way around it that I'm not aware of. 

Anyways, really great work on this project, thanks for putting the time and effort into this!

**Comment by merdok** [comment]
Oh, never heard of something like that. 
The commands are send straight to the TV using the standard API, the TV does with them afterwards something. At this point i do not have control anymore, so i do not think that there can be done anything...
I suppose the commands cannot control your set top box and it can only be controlled by the remote, but it is intersting that the TV somehow relays those commands through the remote...

**Comment by leoravagnani** [comment]
Yeah, kinda odd isn't it? I tested controlling my Playstation and it works just fine through HDMI-CEC since it's all done on the TV itself.

Pretty sure it's the remote sending IR commands, interesting that they chose to relay from the TV to it tho, maybe they should've included some pre-command to wake it up, that would've been neat.

My current HT is Optical only, I'll get a chance to try another one through ARC to see if it's any different, maybe it talks CEC and it's one less problem haha

**Comment by merdok** [comment]
Ok, you can let me if it work then. I will close this for now!
