### ISSUE TITLE
Make notification button show up as separate from the TV accessory.

### ISSUE THREAD

**Issue by RaffoNin** [merdok/homebridge-webos-tv#383]
I currently have the TV with control for backlight, dark mode, light mode. My problem is whenever I add a notification button is becomes part of the TV accessory and it looks messy. I can make it show up as separate tiles via the home app but the picture profiles and the backlight become separate from the TV accessory as well. 

Since I only use the notification button in automations, I would love to have the notification buttons show up as a separate entity entirely so I can hide in my "Server" room in the home app.

**Comment by merdok** [comment]
Currently it is not possible to do that and i am not sure if it makes sense to add such feature. Quite some code would probably need to be rewritten for that and the advantage would be minor...
I mean i can understand that when you have quite a lot of notification buttons that then the accessory would be quite full. You could also show the accessories as separate tiles and move what you do not want to use that often into a separate room and your most often used tiles add to the favorites?

**Comment by RaffoNin** [comment]
That makes sense. Still appreciate all the effort into the plug-in. Been working well for me. Will close the issue now.
