### ISSUE TITLE
No FilmMaker mode among the picture modes ?

### ISSUE THREAD

**Issue by SebNYD** [merdok/homebridge-webos-tv#384]
Hello,

This project is pretty great, thank you :)

It seems that the FilmMaker picture mode is not available, is it a known limitation ?

Thanks,

**Comment by merdok** [comment]
Hi,

thanks!
It all depends on the tv, it might be that if your tv supports that mode then it exist. You can try and put `filmMaker` or any other variation of that name as the value for the button and see if that works. At the time during my testing i did not have a tv with that mode so i could not test it myself...

**Comment by SebNYD** [comment]
Thanks, I tried a few variation without success.

ill post back if I end up finding something that works ;)
