### ISSUE TITLE
Turn on tv with appid 

### ISSUE THREAD

**Issue by derflerd** [merdok/homebridge-webos-tv#386]
At the beginning when the tv is off  I click on app and he turn on the tv and start immediately the app. Now this stop working.
I don’t know where is the problem, maybe this stop working from the last update of the tv. There is away to fix it?

**Comment by derflerd** [comment]
Ok I find the problem. This works only when Tv connect by WiFi. This not works with lan cable. There is no “wake on lan” support. Only by WLAN

**Comment by merdok** [comment]
Yeah, your tv needs to support wake on lan for lan wake or wake on wifi for wifi wake. You might also check if all the necessary options on your tv are enabled like quick start, mobile wake and depending on your tv also other options.
