### ISSUE TITLE
hideTvService still displays as a TV

### ISSUE THREAD

**Issue by rcarmo** [merdok/homebridge-webos-tv#388]
I have an LG TV with native HomeKit support and am trying to use this plugin solely for managing the audio outputs. 

I've tried setting `hideTvService` to `true` and removing everything from the config but the audio outputs, but I still get a "second TV" on HomeKit with power on/off, a list of video inputs, volume, the works. 

What do I need to do to get rid of those?

**Comment by merdok** [comment]
`hideTvService` should be set to `true` and not `false`

**Comment by rcarmo** [comment]
Sorry, I meant `true`, obviously. Updated to reflect my mistake

**Comment by merdok** [comment]
Setting that to true should do the trick, if not then you should post the whole config so I can have a look.

**Comment by merdok** [comment]
@schweppy  you are using the other plugin (which is a rip off this one) not mine, that is why it is not working for you.

**Comment by schweppy** [comment]
Sorry! How stupid! Haha. 

Have deleted the rubbish one and installed yours! And is now working correctly…….
