### ISSUE TITLE
Renamed HDMI ports on the tv

### ISSUE THREAD

**Issue by rooi** [merdok/homebridge-webos-tv#389]
Hi Merdok,

I searched around the issues but I couldn't find any other mentioning of the following issues on my tv / homebridge configuration.

I just added a new AVR and changed the HDMI connections and names. This change did not get reflected automatically in the Home app. I noticed an issue that mentioned dynamic change of the other app in the input dialer when deleting and installing another app in webos.

How do you suggest the HDMI name changes are reflected in the Home's app input slider?

Thanks,

Roy

**Comment by merdok** [comment]
The names are cached, they are under your config directory. Try to delete the inputs file there and the inputs will sync again completely from the TV.
