### ISSUE TITLE
Accessory stops working after a certain period of time

### ISSUE THREAD

**Issue by LP0101** [merdok/homebridge-webos-tv#39]
Not sure how long it takes, but somewhere a bit over a week, the accessory stops working. It still shows as responding in the Home interface, but when trying to turn the TV on or off, it fails.

Restarting Homebridge temporarily fixes the issue. Soft workaround is making a cronjob to restart homebridge once a week.

I'll try and get logs next time it happens.

**Comment by merdok** [comment]
Maybe your homebridge is running out of memory? Some logs would be good.

**Comment by LP0101** [comment]
Will be sure to gather them next time it happens.

I doubt it's running out of memory, though. Every other accessory continues to work.

**Comment by merdok** [comment]
I need to investigate this issue, but currently my RPi is dead and i am waiting for a replacement so it will take some time :(

**Comment by merdok** [comment]
Could you try with the latest version, if the issue is fixed? Please note that i renamed the package to `homebridge-webos-tv`, so you need to install this new package and adjust your config.json

**Comment by LP0101** [comment]
I'm out of town for a few more days, but I'll disable my cronjob and test this when I get back.

Would you rather I open a new issue or just comment on this one if it isn't fixed?

**Comment by merdok** [comment]
I did closed this issue because i didn't get any response so i assumed it is fixed...
Please reopen this one and we will need to investigate this issue deeper.
