### ISSUE TITLE
Pairing restarts service

### ISSUE THREAD

**Issue by tfraley** [merdok/homebridge-webos-tv#390]
Good day guys, 

I've been trying to get this to work for a little bit now. 
If someone could lend a hand that would be great. 

Hoobs - 4.0.104
Node - 14.18.0
WebOSTV - 2.2.2

It doesn't seem like the key for the TV pairing is saving to the following directory
/var/lib/hoobs/.webosTV/keyfile_LG
/var/lib/hoobs/.webosTV

I've tried giving full permissions to the .webostv folder along with making the folder owner hoobs 
 ( drwxrwxrwx  2 hoobs root  4096 Sep 28 11:17 .webosTV )
Before it was (drwxr-xr-x  4 root  root  4096 Sep 28 11:11 .webosTV)

What am I missing? Is it a bug?

Thanks

**Comment by merdok** [comment]
What is the error which comes up in homebridge?

**Comment by tfraley** [comment]
That's what's strange their is no error @merdok

**Comment by merdok** [comment]
I mean nothing restarts without a reason, there is certainly an error :) You should check the hoobs logs...

**Comment by tfraley** [comment]
Yhea that's what is strange I get prompted on TV for pairing but the file never gets saved in the destination.
and the service starts again with no errors 

Did a fresh uninstall/install here is the logs left it named    ...Bridge 2 at the end

[log.txt](https://github.com/merdok/homebridge-webos-tv/files/7246563/log.txt)

**Comment by merdok** [comment]
You have some errors in your log which are shutting down the bridge. Might be related Also are you running on a Raspberry Pi? What RaspberryPi OS are you using?

**Comment by tfraley** [comment]
I'm using one of Hoobs RaspberryPi's their hardware complete kit had it for at least 6months to a year

**Comment by merdok** [comment]
I guess you should look into the errors which popup in the log which are causing the bridge to shutdown. The issue is somewhere in your environment. Maybe missing packages or outdated software?

**Comment by tfraley** [comment]
Humm.. Not really sure what your point a finger to. 
This plugin restarts as soon as I click accept on the TV, Not sure if I would point at something else 
The ring has been having server-side issues I see errors with that but that's them. Seems like every other week there having issues.

**Comment by merdok** [comment]
This looks to me like an issue with your environment and that is where i am pointing at. You need to debug that issues and find out what is causing it. You were also saying that the files for the key file are not created, this could also strongly hint at wrong permissions either the specified directory or the process running hoobs. You can also try to change the path where the files are saved by specifying a oath where you can be sure that you have access to like your home directory.

**Comment by tfraley** [comment]
Thanks guess I'm not going to get much help.
I've mentioned I opened up permissions to the destination folder and tried changing ownership as well with no luck. 

You also mention the environment but I see no restarting that I am not aware of. Keep in mind I've been testing different things over and over. which is why I pointed to look at the end of the logs. 

This is a certified Hoobs plugin, I would think it would work with the current version of hoobs and I'm even using its hardware.

Also, I pointed out I'm not totally new I've been using hoobs for over 6 months may be more like a year without issue through updates and different addons. This is the only one that has stumped me.

Thank you for the time you did take but that didn't lead me anywhere.
Have a good day.

**Comment by merdok** [comment]
Again you have to realize that the issue which you have is most certainly not with the plugin itself but with some configuration of your setup. I am not a wizard to know what exactly the cause is, but based on the information you provided that is all i can help you. Like i already mentioned you will need to investigate what is causing the issue for you, i cannot do that for you...

**Comment by tfraley** [comment]
@merdok 

Not to beat a dead horse 
I have removed the SD card into my Hoobs pi with a NEW SD with a fresh Hoobs install
I ran through Hoobs update of everything. No other plugins installed nothing else touched other than adding the location.

I installed your plugin and alais it's doing the same thing. 
Here are the current logs from this run through
[log-3.txt](https://github.com/merdok/homebridge-webos-tv/files/7247773/log-3.txt)
h

**Comment by tfraley** [comment]
I revoked all the pariing on my LG tv figured why not just in case.
I will add I use an app on my iphone and it pairs fine with the LG55OLED

**Comment by merdok** [comment]
The log looks exactly the same as before, there are no errors which directly indicate the issue.
That you setup a fresh install does not change anything here, you  need to find a clear indication why homebridge is restarting, maybe try to start it in debug mode which usually provides more log output?

**Comment by tfraley** [comment]
@merdok 

FYI I made a screencast today of a fresh hoobs install and only your plugin to illustrate the problem, Which I have put into Hoobs github here https://github.com/hoobs-org/HOOBS/issues/1553#issuecomment-932494150

The screencast is here if you want to check it out
https://share.descript.com/view/DkUeHxUBMYO

**Comment by merdok** [comment]
This was an issue with a dependency, it should now be fixed in the latest version.

**Comment by tfraley** [comment]
@merdok 
When was the dependency fixed?
I made this video and install 2-3hrs ago

I just went ahead and did the install again. Same results (2:13pm pst)

I'll also note why does your app no only install the bridge during the first install
I have to install it a second time and point it at the bridge for it to finish the install.
Wasn't like that the other day.

Again i'm at a loss as to what to test or do next. I've spent way too much time on this and no one has realy has helped dive in to figure out the problem just assuming what the problem is.

I'm not pointing at you or your add-on as the other WebOS addon is not working right either. Something about this set of addons. My other addons like RING work fine.

**Comment by merdok** [comment]
The issue was fixed with version 2.2.5, previous versions installed the latest dependency of which recently one did break which caused exactly he issue which you descried (bridge restarted during pairing).  Some users at this #392 help me to identify the broken dependency so i could provide a fix. Install version 2.2.5 and make sure that you have the dependency `bufferutil` no higher then at version 4.0.3. If you run the command` npm list -g --depth=4` in the homebridge-webos-tv directory it will show you a list of dependencies with the installed versions.

**Comment by tfraley** [comment]
@merdok 
Ok I have done the install again double-checking that its version 2.2.5

I have gone into the dir "/var/lib/hoobs/webostvbridge "
Then "npm list -g --depth=4 | grep bufferutil" to grep anything with bufferutil
Nothing.

Just in case I did the full list and copied it to a text file then did a search it's not there

Attaching the txt file as proof.

[npm-list.txt](https://github.com/merdok/homebridge-webos-tv/files/7270493/npm-list.txt)
.

I'll go ahead and try another fresh hoobs install this test was done on my exsiting one that has my other bridges runing. (Just wanted to test quickly)

**Comment by tfraley** [comment]
Ok looking at the other thread. 
I looked in the node_modules folder and there is a folder called bufferutil in there though. 
Maybe the module is not installed globally ? 
Looking at the readme in the /var/lib/hoobs/webostvbridge/node_modules/bufferutil
Looks like it's v4.0.4 so prob to high.

Going to try and downgrade it

**Comment by tfraley** [comment]
BOom..

That seemed to do it. 
So I would say your current build is still updating to latest dependecy for some reason. 

From 
    /var/lib/hoobs/webostvbridge/node_modules/
Run
  sudo npm install bufferutil@4.0.3
  
  Did the trick

**Comment by merdok** [comment]
Very good! 
It seems like you have the package installed globally which then takes priority over the one in the plugin directory. So if you have it globally then you need to make sure it is not on the latest version manually! Good that it works now but just be careful during updates...
