### ISSUE TITLE
Turning on cable box

### ISSUE THREAD

**Issue by Stevenlgts** [merdok/homebridge-webos-tv#393]
This plugin works very well when my cable box is already turned on. When the cable box is turned off, I'm required to press the OK button. 
1. Is there a way to automatically press the OK button, so the cable box is always on when turning the TV on with the plugin? 
2. I have tried to add a remote button so that I can press OK (which I assume is coded as ENTER), but I'm unsure what to enter under ACTION. What should add for ACTION?

**Comment by merdok** [comment]
If this is a popup which popus up on the tv and you want to press that one, then it should be possible.

You have to create a remote control button. The `name `is a name which you can freely specify, the action is the `actual `action which you want to simulate from this list: https://github.com/merdok/homebridge-webos-tv#remote-control-values which in your case should indeed be `ENTER`

**Comment by Stevenlgts** [comment]
Thanks for the quick reply. I tried the ENTER and some of the other possible buttons with no luck. I suspect my problem is that ultimately the OK button is a cable remote function and not a tv function.

**Comment by merdok** [comment]
Yes, you are able to only emulate tv remote key presses.
