### ISSUE TITLE
Update plugin issue

### ISSUE THREAD

**Issue by Mikellas** [merdok/homebridge-webos-tv#394]

**Comment by Mikellas** [comment]
I am currently on homebridge-webos-tv v2.2.3

Tried to update the plugin and i get the below error

**Comment by Mikellas** [comment]
Tried to update from 2.2.3 to 2.2.5 this is what  i get

npm ERR! code 1
npm ERR! path C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebridge-webos
-tv\node_modules\utf-8-validate
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.18.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Python39\python.e
xe"
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt       
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer,
 try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 
8
npm ERR! gyp ERR! find VS 
npm ERR! gyp ERR! find VS *************************************************************
*
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio      
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.       
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS *************************************************************
*
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use    
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\Nicolas Server\AppData
\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)   
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules
\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\Nicola
s Server\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\find-visualstud
io.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules
\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules
\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules
\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules
\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:5)       
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1058:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nicolas Ser
ver\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js
" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Nicolas Server\AppData\Roaming\npm\node_modules\homebrid
ge-webos-tv\node_modules\utf-8-validate
npm ERR! gyp ERR! node -v v14.18.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\202
1-10-01T17_05_19_822Z-debug.log

Command failed. Please review log for details.



Keep in mind that all other plugins are working flawlessly

**Comment by merdok** [comment]
This seems like a setup with your npm. There is one dependency which needs to be rebuild after you update it and this rebuild is failing for some reason. You can also skip the dependency update and it should still work.

**Comment by Mikellas** [comment]
Hi and thanks for the info
Noob question how do i skip it?

**Comment by merdok** [comment]
Just ignore the error, then your previously installed version should still be there.
