### ISSUE TITLE
Cannot update to the latest 2.2.5 - strange

### ISSUE THREAD

**Issue by nebosphere19** [merdok/homebridge-webos-tv#395]
Huge list of errors when I try and update to 2.2.5.

USER: bxxxx
DIR: /usr/local
CMD: npm install -g homebridge-webos-tv@latest

npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! CC(target) Release/obj.target/validation/src/validation.o
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.4 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.2 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/utf-8-validate/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/barons/Library/Caches/node-gyp/14.15.4/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/barons/Library/Caches/node-gyp/14.15.4',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/barons/Library/Caches/node-gyp/14.15.4/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/utf-8-validate',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/validation.c:2:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/assert.h:42:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
npm ERR! #error Unsupported architecture
npm ERR!  ^
npm ERR! In file included from ../src/validation.c:3:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:61:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
npm ERR! #error architecture not supported
npm ERR!  ^
npm ERR! In file included from ../src/validation.c:3:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:61:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
npm ERR! typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
npm ERR!         ^
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
npm ERR! typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
npm ERR!         ^
npm ERR! note: '__int128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
npm ERR! typedef __int32_t       __darwin_dev_t;         /* dev_t */
npm ERR!         ^
npm ERR! note: '__int128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
npm ERR! typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
npm ERR!         ^
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
npm ERR! typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
npm ERR!         ^
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
npm ERR! typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
npm ERR!         ^
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
npm ERR! typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
npm ERR!         ^
npm ERR! note: '__int128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
npm ERR! typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
npm ERR!         ^
npm ERR! note: '__int128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! In file included from ../src/validation.c:3:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:61:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
npm ERR! typedef __uint32_t      __darwin_wctype_t;
npm ERR!         ^
npm ERR! note: '__uint128_t' declared here
npm ERR! In file included from ../src/validation.c:3:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:64:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_size_t.h:31:9: error: unknown type name '__darwin_size_t'
npm ERR! typedef __darwin_size_t        size_t;
npm ERR!         ^
npm ERR! In file included from ../src/validation.c:3:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/string.h:141:
npm ERR! In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_rsize_t.h:30:
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
npm ERR! #error architecture not supported
npm ERR!  ^
npm ERR! fatal error: too many errors emitted, stopping now [-ferror-limit=]
npm ERR! 20 errors generated.
npm ERR! make: *** [Release/obj.target/validation/src/validation.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v14.15.4
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

Command failed. Please review log for details.

**Comment by merdok** [comment]
Your npm environment is not set up correctly hence a dependency cannot be updated and build. You would need to make sure that the build process runs through successfully.

**Comment by nebosphere19** [comment]
Strange. It was working fine up until recently. Is there an easy way to fix my npm environment?

**Comment by merdok** [comment]
In general your issue has nothing to do with this plugin but with the sub dependency node-gyp. I guess it was recently updated... 
As far as I understand there is somehow a task which does build that dependency from sources and that is failing for you. I would recommend to open an issue in that  repository or check if somebody else does not have a similar issue there.

**Comment by nebosphere19** [comment]
I’ll give it a shot, thanks. I can’t get the node-gyp rebuild command to work at all.

**Comment by merdok** [comment]
Please let me know if you find out what the issue was.

**Comment by tteuer** [comment]
Same EXACT issue here when trying to update to 2.2.5.

**Comment by merdok** [comment]
I locked the dependencies in the latest update due to a critical issue with a sub dependency. For this reason I suppose that the node-gyp package for some of you might be not up to date, hence it is trying to install the recent one. I know that node-gyp has some building step during installation which quite often fails if something is missing. I guess this is why you are getting the error now with the recent update...

**Comment by nebosphere19** [comment]
Ok - does that mean it should install ok now?

I checked and have the latest version of node-gyp that ships with npm. Are you saying that an even newer version of node-gyp is required? It seems prudent to stick with the version that’s in sync with npm since that’s what most folks using homebridge will have installed. Asking them to maintain a separate global version of node-gyp outside of npm is a lot. 

https://github.com/nodejs/node-gyp/issues/2272

**Comment by merdok** [comment]
Oh, I double checked and node-gyp is actually not even locked to a specific version, so it should have nothing to do with it. You are probably using an older node-gyp version and that update fails.

**Comment by nebosphere19** [comment]
Can you tell me which node-gyp is required to use the latest version of your plugin?

**Comment by merdok** [comment]
Like I said, node-gyp does not matter for my plugin since I do not have a direct dependency to that. Maybe a sub dependency is using that, but that is out of my control unfortunately...

**Comment by nebosphere19** [comment]
Ah, I see. Thanks.

**Comment by GalBrill** [comment]
Same exact issue on my end too :/

**Comment by tteuer** [comment]
I have attempted to update node-gyp manually and it did not seem to make a difference. I updated node and npm to the latest versions as well. 

From what I can tell, it appears the node-gyp dependency is coming from the webos-tv dependency, utf-8-validate.

**Comment by merdok** [comment]
I do not really get it why you get the error... Just tried to run `npm install -g homebridge-webos-tv@latest` to make sure it works, and it works without any issues...

**Comment by tteuer** [comment]
Curious if the other posters are using macOS 10.15 and have their node/npm environments installed through Homebrew?

That’s the same command Homebridge-Config-UI is using to attempt to update. I can perhaps try uninstalling the WebOS-TV plugin and installing fresh to see if it makes a difference.

**Comment by merdok** [comment]
@7RDR7 what nodejs version are you now running on?

**Comment by 7RDR7** [comment]
v14.18.0

**Comment by merdok** [comment]
@7RDR7 Thanks! Good to hear that it works now for you, but seems strange since i am running on v12.22.4 but no issues here...

Anyway, could the other people with the issue also try to update nodejs and see if that helps?

**Comment by 7RDR7** [comment]
I was on v12.x.x before I updated, but can't recall what release, so I could have been on an older release of v12 than you.

**Comment by nebosphere19** [comment]
I updated nodejs and also downgraded command line tools to the latest Catalina-friendly one (I’m on 10.15.7) and it works now - not sure which did it!

**Comment by tteuer** [comment]
Interesting, I'm on Node 16.10.0. Have been on the 16 series for quite some time now. Was on npm 7.24.0, now on 7.24.2 - still having issues. Npm includes node-gyp 7.1.2, but I have manually tried to update to the latest version and still have issues. I reinstalled Xcode CLT 12.4 without any change either... this is so strange!

**Comment by nebosphere19** [comment]
AHHHH - 16 is the problem I think then. I was on 16.10.0 and then I installed “n” to manage node versions, and and ran ’sudo n stable’ and it downgraded node to 14.18.0. Now I don’t have any issues with the install.

**Comment by GalBrill** [comment]
Fixed for me on 2.2.6
