### ISSUE TITLE
Bridge constant starts, fails and restarts on hoobs

### ISSUE THREAD

**Issue by irn-brulad** [merdok/homebridge-webos-tv#397]
As the title said - I installed the plugin via hoobs, entered IP/mac etc for the TV and started the bridge service. 
I acknowledged the remote request on the TV and the HOOBS log shows the bridge connects to the TV then the bridge fails then restarts and repeats, and repeats etc etc

Any ideas what I've probably done wrong?!

**Comment by merdok** [comment]
Probably is related to #392. Please make sure that the bufferutils which you have installed is no higher then 4.0.3, since 4.0.4 broke some binaries which causes that issue.
