### ISSUE TITLE
TV not visible when trying to add to HomeKit but can be controlled with Hoobs 4 UI

### ISSUE THREAD

**Issue by premikkoci** [merdok/homebridge-webos-tv#400]
Hi,

I tried reinstalling, clearing cache, factory reset, etc. to implement lg accessory. All I want is screen control to be able to turn off/on TV screen while listing music.

I am able to add a bridge that is created for your plugin but no accessory is available when added to HomeKit.

My config:
{    
"platform": "webostv",    
"devices": [
        {
            "name": "TV Screen",
            "ip": "192.168.0.xx",
            "mac": "xxxxx",
            "pollingInterval": 5,
           "hideTvService": true,
            "volumeControl": false,
            "screenControl": true
        }
    ]
}

Any ideas?

**Comment by merdok** [comment]
Did you manually add the tv into HomeKit as described in the README? Did you check the troubleshooting section?
