### ISSUE TITLE
HDMI control

### ISSUE THREAD

**Issue by Smitty3007** [merdok/homebridge-webos-tv#401]
When first installed it was showing all 3 hdmi inputs but now it is only showing HDMI2?

**Comment by merdok** [comment]
Sorry i kind of do not understand exactly what are you trying to do... Could you post some screenshots from the issue and from the configuration section of the tv accessory?

**Comment by Smitty3007** [comment]
![image](https://user-images.githubusercontent.com/92412339/137635759-31acdb9d-5829-4c52-8c45-7bddcbac5301.png)

**Comment by Smitty3007** [comment]
![image](https://user-images.githubusercontent.com/92412339/137635771-5fb44c2c-47a4-478e-81d6-144d1f014db9.png)

**Comment by Smitty3007** [comment]
![image](https://user-images.githubusercontent.com/92412339/137635780-1f15cf95-f179-4072-ad1a-f15327628228.png)

**Comment by merdok** [comment]
Not sure why is that, but this is what the TV reports. You can delete the preferences file which is located per default under ~/.webosTv. This should retrigger a fresh fetch of the inputs from the TV.
