### ISSUE TITLE
Voice volume control not working

### ISSUE THREAD

**Issue by noxaeternus** [merdok/homebridge-webos-tv#404]
Hey,
No matter what I tried, renaming commands, using Volume controls, using Remote controls etc nothing works to adjust the volume using voice commands. The buttons in "Home" work perfectly well if used on phone by tapping. 
Any voice commands relating to volume always result in "sorry there was a problem adjusting volume".
Any clues ?
Thanks

**Comment by merdok** [comment]
You cannot use the word "Volume" when trying to set the volume using Siri since this is actually not possible since Apple does not yet for some reason allow that. You need to enable volume control as a "slider" in the config.json, which will allow you to tell Siri to set the TV to x%, and that should work!

**Comment by noxaeternus** [comment]
This is what I changed it to. The slider isn't really doing anything even when used without voice.

                 "pollingInterval": 5,
                    "volumeLimit": 100,
                    "volumeControl": "slider",
                    "channelControl": true,
                    "mediaControl": true,
                    "screenControl": false,
                    "channelButtons": [
                        {
                            "channelNumber": 101,
                            "name": "BBC1 HD"
                        },
                        {
                            "channelNumber": 102,
                            "name": "BBC2"
                        },
                        {
                            "channelNumber": 1,
                            "name": "BBC1"
                        }
                    ],
                    "remoteControlButtons": [
                        {
                            "action": "Mute",
                            "name": "Mute"
                        },
                        {
                            "action": "Mute",
                            "name": "Unmute"
                        },
                        {
                            "action": "ChannelUp",
                            "name": "Next channel on TV"
                        },
                        {
                            "action": "ChannelDown",
                            "name": "Previous channel on TV"
                        }
                    ]
                }
            ],
            "platform": "webostv"
        }

**Comment by merdok** [comment]
Then your issue is not voice commands but something different. If the slider is not working for you then you need to post some debug log and also some information about your TV (model, webOS version).

**Comment by noxaeternus** [comment]
I have just enabled debug logging, where does it write the files to ? Its weird because the slider when moved all the way down, does mute the TV but it does not increase or decrease volume. It does mute and unmute. The volume buttons (not slider) worked absolutely fine. Could it be because I use an external optical amp ? Everything else seems to be working with it seamlessly. It's an LG - 65UJ634V 65" . Running on latest possible WebOS for it. 6.0.15.

**Comment by merdok** [comment]
From the README `the slider volume control is not supported for ARC sound outputs`. Your only option is only to use the buttons or CC remote to control the volume.

**Comment by noxaeternus** [comment]
THanks. So physically pressing them ? No Voice possible ?

**Comment by merdok** [comment]
I mean you can still command Siri to press the volume up or down button but that will just increase/decrease the volume by 1.

**Comment by noxaeternus** [comment]
That's what I tried but its not working, no matter what I assign to those buttons as voice commands, Siri wont do it. I tried both the Buttons / Slider and assigning Remote Control commands.

**Comment by merdok** [comment]
I can assure you that the volume up/down buttons can be controlled by Siri. Since those are switches you have to command Siri to turn on the respective switch...

**Comment by noxaeternus** [comment]
Hmm ok, I will keep trying. Pressing those buttons on Home def works. Its just voice that doesn't Whatever word /name I assign to them Siri says sorry there was a problem adjusting volume.

**Comment by merdok** [comment]
Again you cannot command Siri to "adjust the volume", that will not work since it is not possible using Homekit (expect for homepods)! You have to command Siri to turn on one of the 2 volume switches.

**Comment by noxaeternus** [comment]
Ok, so I get this right. What should I call the switches and how exactly should I then tell Siri to use them ? I am trying giving them different names (not volume) yet its not working.

**Comment by merdok** [comment]
Just say "Turn on [your switch name]"

**Comment by noxaeternus** [comment]
Ahhhhh it works now. I was doing it wrong. Thank you so much.
