### ISSUE TITLE
Sound Sequence

### ISSUE THREAD

**Issue by simon3163** [merdok/homebridge-webos-tv#407]
The sound sequence seems broke.
When adding 3x VOLUMEUP it only saves one occuarnce.

**Comment by merdok** [comment]
It still works as expected here, you should try to add a slight delay between the sequence actions to make sure that the tv has time to process them.

**Comment by simon3163** [comment]
Could you paste your code example by chance?!

**Comment by merdok** [comment]
You have an example in README...
