### ISSUE TITLE
Launch Gallery Mode

### ISSUE THREAD

**Issue by mac8005** [merdok/homebridge-webos-tv#408]
Hi

Love your plugin. It's really great! I'd love to be able to launch the Gallery Mode with an app Button but i have an issues:
 - when i launch the app button the tv starts and opens the gallery app but does not start the gallary mode (it shows the gallary settings)

Are there some params to pass to start the gallary app directly in the gallary mode?

Thank you

**Comment by merdok** [comment]
Not sure about that. There might, you can try to enable deep debug log and check out all the  properties of the app in the terminal log. Sometimes there are some useful information.
