### ISSUE TITLE
Missing YouTube from inputs

### ISSUE THREAD

**Issue by EarmarkedHuman** [merdok/homebridge-webos-tv#409]
Just installed this and noticed that all the apps and inputs from my TV show up in the “Rolodex” view on the home app except for YouTube. I’ve been unable to find a way to manually add it to the list.

**Comment by merdok** [comment]
I would guess that you reached the  limit and no more inputs cannot be added, you can check that out in the homebridge debug log to confirm it. You would need to remove an app from your tv so that YouTube will fit.

**Comment by EarmarkedHuman** [comment]
> I would guess that you reached the  limit and no more inputs cannot be added, you can check that out in the homebridge debug log to confirm it. You would need to remove an app from your tv so that YouTube will fit.

Thanks. Yeah; I had to uninstall a bunch of apps and it now shows up.
