### ISSUE TITLE
Sound output buttons missing “soundbar” from drop down

### ISSUE THREAD

**Issue by EarmarkedHuman** [merdok/homebridge-webos-tv#410]
As I said above, the soundbar option is missing for the drop down and when I try to add it manually via code, it shows up in the visual view as a blank drop down.

**Comment by merdok** [comment]
What is the id of the soundbar sound output?
You should be able to manually add the sound outputs which are missing directly in the config.json, that it is missing afterwards in the ui does not matter, the switch should anyway appear in the home app.

**Comment by EarmarkedHuman** [comment]
> What is the id of the soundbar sound output?
> You should be able to manually add the sound outputs which are missing directly in the config.json, that it is missing afterwards in the ui does not matter, the switch should anyway appear in the home app.
> 

That worked. Thanks. It does show up in the Home app even though it doesn't on the homebridge UI.

**Comment by merdok** [comment]
The id is whatever you typed in the config to make it work. So you can just post the config.json snippet for that sound output.

**Comment by EarmarkedHuman** [comment]
"soundoutputButtons":     [
{
"soundoutput":
"soundbar",
 "name":"Optical"
}
]

According to the logs, webos refers to the optical input as "soundbar"

**Comment by merdok** [comment]
ok thanks for the info, will take on the list!
