### ISSUE TITLE
TV auth keys get reset after container is recreated

### ISSUE THREAD

**Issue by agneevX** [merdok/homebridge-webos-tv#411]
I have found that the default locations, `~/.homebridge/.webosTv/keyFile_xxx` for the key file and `~/.homebridge/.webosTv` do not persist when the Docker container is recreated.

All TVs have to be authorized again.

I have manually specified the locations, this persists and there's no need to reauthorize.

```json
"keyFile": "/homebridge/webos/<TV_NAME>/keyfile",
"prefsDir": "/homebridge/webos/<TV_NAME>"
```

The `oznu/homebridge` uses `/homebridge` as the `WORKDIR`. So `~/` corresponds to `/root`, which does not persist.

```sh
agneev@always-on ~> docker exec -it homebridge sh
/homebridge # cd ~/
~ # echo $PWD
/root
```

**Comment by merdok** [comment]
Yes, that is why you are able to manually specify the paths. Not everyth environemnt is the same so in case there are issues you can overdefine the default key and settings locations.

**Comment by agneevX** [comment]
Ok, since this is not discoverable, can you add this as info to the readme?

**Comment by merdok** [comment]
Both of those configuration fields are already descirbed in the README here: https://github.com/merdok/homebridge-webos-tv#tv-configuration-fields

**Comment by agneevX** [comment]
I get that but a novice user won't know this.

Closing if you think this is how it should be.

**Comment by merdok** [comment]
I mean i do not think that it is needed to go so much into detail, the base information that it is possible to change the default store paths is there and if setting do not presist then that should be the first thing to be changed by the user.

**Comment by Sarcas666** [comment]
Novice user here. This issue made me understand why my TV kept asking for permission every time. I had this problem for several years... In my case, I somehow did not have a .lgtv2 directory so the keyfile was never saved. This issue put me on the right track. Finally. Doh. Fixed it. Got xp and hope to level up ;)
