### ISSUE TITLE
"404 no such service or method" when setting Picture Mode

### ISSUE THREAD

**Issue by embee8** [merdok/homebridge-webos-tv#413]
Hello!

First of all, thanks for creating and maintaining this amazing plugin.

My setup works great so far, but I can't get the picture mode changed. Similar issue to #375 but in my case the setting doesn't even change in first place.

I am running webOS 3 and LG software version 05.60.15.

Debug log says:

```
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] system.notifications service - createAlert requested. Title: lunaSend, Message: lunaSend, Type: confirm, Modal: true
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] Message from TV 

[12/7/2021, 11:05:49 PM] [webostv] [My LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"error","id":"<scrubbed>","error":"404 no such service or method","payload":{}}'
}
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] Unknown error while requesting createAlert from service system.notifications
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] system.notifications service - createAlert requested. Title: lunaSend, Message: lunaSend, Type: confirm, Modal: true
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] Message from TV 

[12/7/2021, 11:05:49 PM] [webostv] [My LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"error","id":"<scrubbed>","error":"404 no such service or method","payload":{}}'
}
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] Unknown error while requesting createAlert from service system.notifications
[12/7/2021, 11:05:49 PM] [webostv] [My LG TV] Remote input socket - sending command: ENTER
```
Any idea what I am dealing with here? Happy to send a PR, but not sure if this is simply a compatibility issue with my TV which was purchased around 2016.

**Comment by merdok** [comment]
Yeah, well it looks to me like webos 3.0 TVs does not support the service required for changing picture modes... I think that it is supported from version 3.5. Unfortunately there is nothing i can do about it.

**Comment by embee8** [comment]
That would be a shame. I'll do some more digging - maybe I'll find a way.

Btw, I don't think it's related to this exact issue, but the settings UI of the plugin doesn't parse the config correctly and ignores the picture mode button entries. Every time I open the UI, it appears as if I were to set up buttons from scratch.

**Comment by embee8** [comment]
Also, I wasn't very precise above. My webOS version is 3.4.0.

**Comment by embee8** [comment]
Some forums suggest that LG likes to keep some settings/APIs closed. I might come back to this and try to install webOS 3.5 on my TV, but there is probably a reason for why they don't push that version to my device.

In the meantime, I was able to work around the issue by using a remote sequence button as described in the docs, which already makes for a much smoother experience.

**Comment by merdok** [comment]
The picture mode and backlight control actually are using hidden APIs which lg never meant to be used publicly, so we even here have a risk that at some point lg will disable those...
So using the remote sequence buttons is the safest way!

As for updating webos on the tv, I do not think that it is possible, lg provides webos updates which bring the version up to 3.4 in your case but 3.5 was reserved for a new model lineup which is a major release for lg. 

It might be that there are some issues with the ui for the picture mode buttons, this comes from the complexity of those objects and limitations of the ui parser. I know I already spent much time trying to figure that out but without success...

**Comment by embee8** [comment]
To be fair, I think the JSON config works great and in some cases is even easier to manage than the UI. 👌

**Comment by merdok** [comment]
Exactly why I always myself only use the config.json and actually never the ui except for testing😅 But some people prefer the ui😊
