### ISSUE TITLE
Visibility of plugin in non-native HomeKit

### ISSUE THREAD

**Issue by PrzemyslawKlys** [merdok/homebridge-webos-tv#415]
Some time ago I've noticed that this plugin is not visible in Eve app. Today I bought another app and again it's not visible at all. Is there a way to make it available? I can see some other homebridge apps works properly such as this one: https://github.com/thoukydides/homebridge-homeconnect

**Comment by PrzemyslawKlys** [comment]
Well, Eve App was just an example to show it's just not one app, and I don't use Eve myself, but I heard it has some great automation features, much more advanced than what HomeKit Native app provides.  

I was specifically thinking on 
- https://apps.apple.com/us/app/home-widget-for-homekit/id1579036143

There is also another one which seems to be doing the same thing

- https://apps.apple.com/us/app/homewidget-for-homekit/id1547029988#?platform=iphone

I was thinking on creating whole screen of "tv channels", kind of remote screen.

**Comment by merdok** [comment]
Yeah, any app that does not support tv accessories will not work. The Eve or other apps will also not display the native lg HomeKit integration in those apps, or am I mistaken here?

**Comment by PrzemyslawKlys** [comment]
I don't see the Sony Homebridge app either. Although I was expecting that "channel" buttons aren't really tv accessories, neither does the sound bulb so I expected them to work.

**Comment by merdok** [comment]
Everything is part of the tv accessory, and if an app does not support the tv accessory then it will not work. 
A couple of years ago this plugin emulated that behavior with a switch accessory, this was before apple implemented the tv accessory. After Apple implemented the tv accessory there was no reason for me to maintain two separate accessories, hence i removed that. It is unfortunately not as simple as replacing the the tv accessory with a switch, a lot of logic need stop be adjusted since those accessories work different. 
It might be that changing the device category would be enough but i honestly do not know that. What you can do is try to change the category here: https://github.com/merdok/homebridge-webos-tv/blob/master/index.js#L258 and then see if the apps will recognize it.

**Comment by PrzemyslawKlys** [comment]
I could always go to the app vendor and see if they can just fix it? It's them doing it wrong right?

**Comment by merdok** [comment]
I mean I do not think Eve will add tv support in their app😅 Why should they?

**Comment by PrzemyslawKlys** [comment]
Because HomeKit natively displays it - so why not them? Eve app allows building scenes and automation and without tv support you can't turn on TV, turn on channel when you come in to Home. 

In native homekit app, you can do it using your plugin. That means the Eve app is inferior to what Apple proposes which makes it bad for their PR 😁same with other apps that tell you, you can build dashboards or widgets - it's pretty bad you can't use the feature I use the most in native app. To me it's their omission and they should fix it.

**Comment by PrzemyslawKlys** [comment]
Right, but again - it's not just about Eve. I would need the apps I mentioned to support it as well. And weirdly enough Home App has limited functionality but more functionality than Even and those 2 apps I mentioned because it actually supports your plugin. 

I guess I could create some shortcuts/automations in Home app, then use them in those apps, but it's just workarounds to workarounds - I'll write them email and ask ;-) Maybe they are just not aware what they are missing out.

**Comment by merdok** [comment]
You could definitely reach out to them and see what they say. You can also let me know what the reply was.

**Comment by PrzemyslawKlys** [comment]
> Dear Przemek,
Thank you for contacting Eve Systems Support.
So far, third parties don't have access to accessories that allow playback like TV-Sets, Apple TVs or the HomePod - Apple only.
If you still have any questions, or if there is anything else we can do to help, don't hesitate to contact us again.
Best regards,
Volker

It seems Apple usual approach to their ecosystem :-) So they can't fix it - only you, if at all it works.

**Comment by merdok** [comment]
Yeah, well there you have it, apparently Apple does not allow access to those accessories hence they are not visible. So i was mistaken, it is not because they do not want to include it, it is because they cannot include it. 
The only way is emulating a switch instead of a tv accessory which i honestly do not want to re implement back since it will be a mess again to manage that.
Not sure if you tried to change the category here: https://github.com/merdok/homebridge-webos-tv/blob/master/index.js#L258 if that would already work then i could figure something out, but you need to test that first.

**Comment by PrzemyslawKlys** [comment]
Change it to what?  what options there are?

**Comment by merdok** [comment]
https://developers.homebridge.io/#/categories
You should try SWITCH

**Comment by PrzemyslawKlys** [comment]
didn't do anything. Seeing as the homeconnect app doesn't seem to have this at all, i don't think it's this setting.

**Comment by merdok** [comment]
Yeah... that would be too easy 😅 Nothing simple can probably be done here, the only way would be to do the emulation with a switch but honestly i do not want to go back to that...

**Comment by PrzemyslawKlys** [comment]
Thank you anyways :-)

**Comment by merdok** [comment]
Just wondering, what would kind of automation would you like to configure using the eve app which you cannot do in home app using the tv?

**Comment by PrzemyslawKlys** [comment]
It's not about Eve App (only example of pretty huge app with lots of users not supporting your plugin). It's about other apps, mainly the dashboard ones:

![image](https://user-images.githubusercontent.com/15063294/146634846-d1cc1a81-b641-4d11-bfbb-abbba2a6d8d7.png)

I would like to create a tv pilot on the 2nd page of my iPhone :)

**Comment by merdok** [comment]
But you can do that using the shortcuts app, or do i miss here something? You can just simply create yourself shortcuts in the shortcuts app and then you can either create icons on the home screen for direct access or create a widget with the actions.

**Comment by PrzemyslawKlys** [comment]
It's 3 clicks to create that in those apps, 50 clicks in Shortcuts app (for 1 action) - at least I can't find an easy way to achieve it. Granted I am not skilled in Shortcuts app because it kills me when I open it up - maybe if I could do it in in VSCode or something, but on iPhone I get distracted after 5 minutes.

**Comment by merdok** [comment]
First world problem 😅 I mean how often do you do it? You will probably just do it once and then ever again (maybe just for changing something), so investing a couple more minutes and clicks is here definitely justified.

**Comment by PrzemyslawKlys** [comment]
I'm pretty lazy - that's true 🤣 I'll survive - counting that Apple will improve homekit in 5 years enough for it to be where people want it to be ;-)

**Comment by merdok** [comment]
Yeah, i also hope that Apple at some point improves the Home app, but till then we have to live with what we have...
