### ISSUE TITLE
Open an app, then send remote commands

### ISSUE THREAD

**Issue by edwilde** [merdok/homebridge-webos-tv#417]
I feel there might already be a way to do this, but perhaps I cannot find it.

I would like to be able to open an app e.g. `com.webos.app.hdmi1` and then send a series of remote commands e.g. `"CLICK"`.

My specific use-case is that when I change to hdmi1 I am asked if I would like to turn on the set top box via webos. I would like to be able to open that app and have the set top box turned on, as I can do with the LG remote by clicking 'OK'.

**Comment by merdok** [comment]
Hi,
this is unfortunately not possible at this moment. 
You can although use only a remote control sequence to archive that. Simply open the HDMI input with the remote control sequence (which should be pretty straight forward) and then press "ok".

**Comment by edwilde** [comment]
Thanks for getting back so quickly @merdok, keep up the good work it is much appreciated by all :)

**Comment by merdok** [comment]
Is your issues solved that way?
