### ISSUE TITLE
Can't install Plugin

### ISSUE THREAD

**Issue by Thommy-de** [merdok/homebridge-webos-tv#418]
Can't install the plugin, failed every time

can someone please help:

USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-webos-tv@latest

npm WARN tarball tarball data for type@https://registry.npmjs.org/type/-/type-1.2.0.tgz (sha512-+5nt5AAniqsCnu2cEQQdpzCAh33kVx8n0VoFidKpB1dVVLAN/F+bgVOqOJqOnEnrhp222clB5p3vUlD+1QAnfg==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for es5-ext@https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.53.tgz (sha512-Xs2Stw6NiNHWypzRTY1MtaG/uJlwCk8kH81920ma8mvN8Xq1gsfhZvpkImLQArw8AHnv8MT2I45J3c0R8slE+Q==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for type@https://registry.npmjs.org/type/-/type-1.2.0.tgz (sha512-+5nt5AAniqsCnu2cEQQdpzCAh33kVx8n0VoFidKpB1dVVLAN/F+bgVOqOJqOnEnrhp222clB5p3vUlD+1QAnfg==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for es5-ext@https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.53.tgz (sha512-Xs2Stw6NiNHWypzRTY1MtaG/uJlwCk8kH81920ma8mvN8Xq1gsfhZvpkImLQArw8AHnv8MT2I45J3c0R8slE+Q==) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /home/pi/.npm/_cacache/content-v2/sha512/fb/99/ede400278aab029eed9c11041da73080877de4571f27d15a0589d2a907575554b00dfc5f9b8153aa389a8e9c49eb869db6d9c941e69def5250fed500277e
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/home/pi/.npm/_cacache/content-v2/sha512/fb/99/ede400278aab029eed9c11041da73080877de4571f27d15a0589d2a907575554b00dfc5f9b8153aa389a8e9c49eb869db6d9c941e69def5250fed500277e'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-12-22T17_21_38_456Z-debug.log

Command failed. Please review log for details.

**Comment by merdok** [comment]
The command should be `sudo npm install -g homebridge-webos-tv`. Not sure what the -E or -n parameters are which you added there. 
Other then that if still does not work, then i guess something is corrupted with your npm installation.

**Comment by Thommy-de** [comment]
Thanks plugin is now running
