### ISSUE TITLE
permission denied to create /root/.lgtv2/

### ISSUE THREAD

**Issue by Xusqui** [merdok/homebridge-webos-tv#419]
Every time I need to reboot my Homebridge instance (Docker over Synology DS718+) it goes to an infinite reboot because Homebridge-webos-tv plugin has no permissions to create /root/.lgtv2/

I've tried chmod'ing /root/ to 777 with the same error

Every time I reboot the Homebridge, I have to manually create that directory:
cd /root
mkdir ./.lgtv2

And then Homebridge starts normally, but if by any chance it reboots (expected or unexpected), the same error occurs.

**Comment by merdok** [comment]
Someone already had this issue. You can have a look here for a possible solution: https://github.com/merdok/homebridge-webos-tv/issues/405#issuecomment-979460393
