### ISSUE TITLE
Dolby Standard picture mode doesn't work.

### ISSUE THREAD

**Issue by RakshithGB** [merdok/homebridge-webos-tv#420]
Hi,

I have an LG OLED CX, which comes with native home kit support. Thanks to your brilliant work in this plugin I can control picture modes with Siri without browsing multiple menus in WebOS. There is one problem though, the standard dolby mode doesn't work. All other modes like dolby vivid, dolby game etc work.

**Comment by merdok** [comment]
Hi,
if it is does not work, then it might be a couple of things... Maybe you mistyped the name? It might also be that the name of this picture mode is different on your TV and it is simply not yet documented, in that case you try to guess some names to find out the correct one. It might also be that the picture mode is not supported on your tv as per README `Not all picture modes might be available for all TVs. `

**Comment by RakshithGB** [comment]
Well I used this:

``` 
"pictureModeButtons": [
                        {
                            "pictureMode": "dolbyHdrGame",
                            "name": "Dolby Game"
                        },
                        {
                            "pictureMode": "dolbyHdrVivid",
                            "name": "Dolby Vivid Mode"
                        },
                        {
                            "pictureMode": "dolbyStandard",
                            "name": "Dolby Standard Mode"
                        },
                        {
                            "pictureMode": "eco",
                            "name": "Eco Mode"
                        },
                        {
                            "pictureMode": "vivid",
                            "name": "Vivid Mode"
                        },
                        {
                            "pictureMode": "normal",
                            "name": "Standard Mode"
                        }
                    ]
```

everything in this list works except for dolby standard, I even tried something like "dolbyNormal" din't get it to work. Anyway to figure out the exact name? Since my TV does have the dolby standard mode I'm guessing we should be able to get it working?

**Comment by RakshithGB** [comment]
Apologies, looking at your source code you seem to support "dolbyHdrStandard" which works. Closing the issue.
