### ISSUE TITLE
No response in home app

### ISSUE THREAD

**Issue by xkyle22x** [merdok/homebridge-webos-tv#423]
As the title indicates I'm getting a no response in HomeKit but when I check the logs and change the input or something in real time it is correctly displaying this in the logs but it just keeps saying no response in home app. 
The plugin has worked without issue for 2 years previously. 
And suggestions?

**Comment by merdok** [comment]
If you are getting a new response then there should be a crash happening and you should see that in the log. If not then I guess it must something not plugin related.

**Comment by xkyle22x** [comment]
It is responding correctly saying exactly what the tv is doing in the logs. No crashes. 
Everything looks fine in the logs

**Comment by merdok** [comment]
Then I can only recommend trying to re add the device to HomeKit. Maybe also try to clear any homebridge caches just to make sure.

**Comment by xkyle22x** [comment]
Removing it and clearing cache worked. 
Thanks
