### ISSUE TITLE
npm ERR! gyp ERR! find Python

### ISSUE THREAD

**Issue by DJay-X** [merdok/homebridge-webos-tv#424]
Trying to update to the latest homebridge-webos-tv plugin I get an error and not able to update. 

Node.js Version v16.13.2
Npm v8.4.1
Python 3.9.10

Any help is much appreciated.
Thanks

pi@raspberrypi-3BPlus:~ $ sudo -E -n npm install -g homebridge-webos-tv@latest
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.2 | linux | arm
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
npm ERR! gyp ERR! find Python checking if "python3" can be used
npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python3"
npm ERR! gyp ERR! find Python - version is "3.5.3"
npm ERR! gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python checking if "python" can be used
npm ERR! gyp ERR! find Python - executable path is "/usr/bin/python"
npm ERR! gyp ERR! find Python - version is "2.7.13"
npm ERR! gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
npm ERR! gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python You need to install the latest version of Python.
npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
npm ERR! gyp ERR! find Python you can try one of the following options:
npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
npm ERR! gyp ERR! find Python For more information consult the documentation at:
npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
npm ERR! gyp ERR! find Python **********************************************************
npm ERR! gyp ERR! find Python 
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:266:16)
npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:297:7)
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:388:7)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Socket.<anonymous> (node:internal/child_process:450:11)
npm ERR! gyp ERR! stack     at Socket.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Pipe.<anonymous> (node:net:687:12)
npm ERR! gyp ERR! System Linux 4.19.66-v7+
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v16.13.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-02-04T11_05_50_223Z-debug-0.log
pi@raspberrypi-3BPlus:~ $ python -V
Python 3.9.10

**Comment by merdok** [comment]
This error has nothing to do with the plugin but with your local environment. You could try to update your nodejs, from my experience that should fix it.

**Comment by DJay-X** [comment]
Hmm. Strange. Thx.
Only noticing it when trying to update this plugin.

However, Node is on the latest Version.
Sorry.. not so familiar how to "update your nodejs"
I update regularly with just using sudo hb-service update-node

Do you have any advice on how to fix it the best way?

Thanks in advance.

**Comment by merdok** [comment]
I mean like already mentioned this is something related to your local environment. You should try to google for that error and I am certain that you will get some hits. 
I suppose you are getting this error because of a dependency of the plugin also got updated so node-gyp requires a rebuild. My plugin has no direct dependency to node-gyp so it must be coming from another dependency...

**Comment by tomrush** [comment]
Just had this issue thought this might help out other people. 

As said by @merdok its an issue with the environment issue. My version of Raspberry Pi OS only went to Python version 3.5 and as the error log says node-gyp needs version 3.6 or greater. 

I installed the latest version of Python and then used the `npm config set python [PATH_TO_NEW_PYTHON]` to tell npm to use the new version of python. If you use python for other things you might need to do something different.

**Comment by DJay-X** [comment]
I also was able to fix the problem getting not installed the updated homebridge-webos-tv plugin.

I used the instruction on this website to install Python 3.9.10
https://itheo.tech/install-python-39-on-raspberry-pi
Then pointing to `npm config set python /usr/bin/python3.9`
