### ISSUE TITLE
LG OLED Will No Longer Power On Using Home App

### ISSUE THREAD

**Issue by chrisdudek** [merdok/homebridge-webos-tv#425]
For whatever reason, the Home App is unable to power the tv on. Once the tv is on by using a remote, then the Home app can switch inputs and turn the tv off. Not sure why the Power On isn't working but it would be great if it did.

LG OLED C7
Plugin Version 2.2.7

Note - Mobile TV Settings are flipped to On for both the Wifi and Bluetooth
Note #2 - The TV is on a different VLAN (IoT) than the Homebridge (Main). Is this a known issue? Again - once the TV is on, everything works....but maybe in order to start the connection when the TV is off it needs to be on the same VLAN?

**Comment by chrisdudek** [comment]
Read old issues. Will try same vlan or look at firewall settings.

**Comment by vordenken** [comment]
I have the same problem with my LG 65UN74007LB. 
I only have one network so its no networking issue. Also the native HomeKit integration this TV provides doesn't have this problem, worked for months. Only the homebridge-plugin integration has this problem (at least for me). Once the TV is on, I can use all features without a problem.

My main use for this plugin would be to control the TVs apps (e.g. "Hey Siri open Youtube on my TV". This is not possible with the native integration. 

Would it be possible to use the native HomeKit for turning on/off the TV and this plugin for app-lists etc.?

**Comment by merdok** [comment]
@vordenken no that will not be possible this way. It is certainly a kind of a network issue on your side also. You need to make sure that magic packets (wake up packets) reach your tv from your homebridge device.

**Comment by vordenken** [comment]
Yes you're probably right and it is kind of a networking issue on my end. I run homebridge on my raspberry pi as a docker container - maybe this feature doesn't work then? 
At first I thought it had to be a different problem because HomeKit native can wake up the TV. Are they using WOL as well?

**Comment by merdok** [comment]
Yes, LG is also using WOL.
The docker container can be very probably the issues depending on how you configured your network there.

**Comment by wttw** [comment]
For future folks diagnosing wake on lan issues...

`/usr/lib/node_modules/homebridge-webos-tv/node_modules/wake_on_lan/wake` is a script that lets you use the same wake on lan code as the plugin does.

Run it with the mac address of your tv - `./wake yo:ur:ma:ca:dd:rs` while the TV is turned off.

I needed to set a broadcast address explicitly with `./wake -a 192.168.1.255 yo:ur:ma:ca:dd:rs` for it to work, as the default 255.255.255.255 broadcast address wasn't working (for network reasons I've not entirely diagnosed yet). Once that worked, setting `"broadcastAdr": "192.168.1.255",` in the configuration for this plugin made it work there too.
