### ISSUE TITLE
Input selection does not work in an automation

### ISSUE THREAD

**Issue by MikeDeltaHH** [merdok/homebridge-webos-tv#426]
Hello!

I have a problem with the plugin in conjunction with my LG OLED65G19LA (WebOS 6) with an automation! I have created two app buttons for HDMI 1 and HDMI 2! For example, if I turn on HDMI1 via the button and on the TV was previously HDMI 2 active then HDMI 2 is first displayed and after a few seconds the TV switches to HDMI 1 and vice versa, so the manual turn on works! I have then created two scenes in each of which an HDMI input is switched on and an automation linked to each scene so that depending on which device (media player or set-top box) then the correct HDMI input is displayed - unfortunately this does not work, if previously another input was active on the TV is not switched to the HDMI input configured in the scene with the automation! Since this works manually yes, I can only assume that this is because it takes several seconds in manual switching until the correct HDMI input is activated and this takes too long in the automation ...
Furthermore, I noticed two things:

- In the Apple Home app, the TV is displayed as a lamp and not as TV
- If I activate in the Apple Home app "show as separate fields" are then only the two app buttons displayed but no longer the TV itself so that I can no longer turn it off via the Apple Home app

Do you have any ideas here?

Here is my config:

{
            "devices": [
                {
                    "name": "My LG TV",
                    "ip": "192.168.2.17",
                    "mac": "b0:37:95:06:7e:e6",
                    "pollingInterval": 5,
                    "hideTvService": true,
                    "volumeLimit": 100,
                    "volumeControl": "both",
                    "channelControl": false,
                    "appButtons": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "HDMI 1"
                        },
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "HDMI 2"
                        }
                    ]
                }

Kind Regards!
Mike

**Comment by merdok** [comment]
As for your two notes, i see that you have the `hideTvService` property set to true, this means that you are hiding the plugins tv accessory and use the native accessory provided by LG. Not sure if this is your desired setup. Anyway the lamp which you are talking about is probably the volume control since i see that you have `volumeControl` set to `"both"`.
If you are still using the TV's native homekit accessory then i would recommend you to remove it and remove the  `hideTvService` line from your config.

About your automation issue, i am not quite sure what your workflow there is. As soon as you switch to another input it will indeed take a little bit till everything updates, but then you should make your automation react to the input switch becoming enabled instead of depending on the switch being already active during the execution of your automation. I mean anything can happen during input switching, it might be a lag or network issue and suddenly the switch reacts with even more delay...

**Comment by MikeDeltaHH** [comment]
Hello!

Thank you, I set "HideTvService" to false and "VolumeControl" to "slider" - HomeKit I have turned off in the LG since this function is a bad joke and does not even work cleanly! In addition, I had another LG TV plugin active that I had first tested and since I had the same problems there I have installed this here - I had read where that Apple supports only one TV in HomeKit what I just remembered and now uninstalled the other plugin and now the LG is also correctly displayed as a TV and the tile no longer disappears with the setting "show as separate fields" in the Home App!

I have a Logitech Harmony Elite and there with the LG TV, a DENON A/V receiver and a DUNE media player created an automation that all three devices are turned on, the corresponding HDMI input of the A/V receiver and also the corresponding HDMI input of the LG TV are activated. I integrated this automation into HomeKit using a Harmony Homebridge plugin. Before the LG TV I had a Panasonic and there everything worked but since I have the LG TV the automation in the LG no longer switches to the HDMI input - so I was looking for an alternative and created by means of this plugin here a scene "Activate HDMI 1" and an automation with the trigger that when the automation is executed by means of the Harmony, so all three devices are turned on this scene is executed and that just does not happen...

I do not know how I can realize this differently because there is a Homebridge plugin for the DENON A/V receiver but nothing for the DUNE media player so that I can not map this without the Harmony... 

Kind Regards!
Mike

**Comment by MikeDeltaHH** [comment]
Yes exactly - if the automation that is present as a tile in HomeKit goes to active then the scene should be performed - the scene itself is fine, if I test it manually then it also works only with an automation as a trigger nothing happens....

**Comment by merdok** [comment]
Maybe you have a condition set for the trigger?

**Comment by MikeDeltaHH** [comment]
No, no condition - a pure reaction to a device condition! But since the manual triggering by the plugin works I think that the problem is somewhere else to look for, maybe the scene is already triggered before the TV is completely switched on - I'll try to change the automation to TV goes on with the condition that the A/V receiver must also be active and then the scene with the right HDMI input is switched ... maybe that works better ...

Thanks in any case for your support and also the work on the plugin!

**Comment by MikeDeltaHH** [comment]
The new automation works perfect, great!
