### ISSUE TITLE
App specific remote buttons

### ISSUE THREAD

**Issue by CalvinGra** [merdok/homebridge-webos-tv#427]
Is it possible to give the remote buttons in the control center different functions in different apps?

For example i want to use the up and down buttons while watching tv to change channels.
In other apps and the menu just up and down.

**Comment by merdok** [comment]
Yes, it is! Please check the README, the ccRemoteRemap property is what you are looking for.

**Comment by CalvinGra** [comment]
I can only change it for all apps right? What i would like is when I am in com.webos.app.livetv I want

             "arrowup": "CHANNELUP",
            "arrowdown": "CHANNELDOWN",

and when I am using Netflix or the menu or any other app i want it to be:

             "arrowup": "UP",
            "arrowdown": "DOWN",

**Comment by merdok** [comment]
Oh, you want it to have per app?

That is not possible currently. It would be possible to add such possibility but not sure if that would not be confusing to have multiple configurations for that

**Comment by CalvinGra** [comment]
Yes, alright maybe it is possible to add this in the future as an optional function?

**Comment by merdok** [comment]
This is now included in version 2.3.0
