### ISSUE TITLE
[Help] "No TV service" makes TV act as bulb, need for deeper configuration

### ISSUE THREAD

**Issue by jvacek** [merdok/homebridge-webos-tv#430]
My LG TV already has HomeKit exposed directly so I switched off the "TV Service"; the only thing I really need is the volume slider and the Screen on/off.

This ends me up with a "bulb", where the on/off simple press effectively works as a mute button. In the advanced view, there is a brightness slider which controls the volume, and a toggle switch for the screen on/off state.

Would it be possible to configure this in such a way that the simple press toggle would control the screen on/off, and have a volume slider instead of a brightness slider?

**Comment by merdok** [comment]
Not possible! There is no slider control in the home app. The only possible way is to show volume control as a light bulb.
