### ISSUE TITLE
Netflix as button does not switch the input to Netflix

### ISSUE THREAD

**Issue by nmagati** [merdok/homebridge-webos-tv#431]
I have an LG TV with model number 65UJ6300-UA. I have followed the instructions to install the plugin. I have added a button for Netflix to be able to operate via Siri. In general, the plugin seems to be working for power and switching the input from the selection slider. 
But, I see three issues with the Netflix button
1) When the Netflix button is pressed, only the first time after HomeBridge is restarted works and switches the input to Netflix. But does not work subsequent button presses.
2) I am unable to switch the input via "Siri" voice commands (I tried a couple of variations: "Hey Siri, switch the input to Netflix.", "Hey Siri, turn ON Netflix") for both cases, Siri keeps saying some to the effect of "this functionality is not available".
3) I also have not figured out how to increase or decrease the volume via voice commands

Plugin version: homebridge-lgwebos-tv v1.11.3

Here is the system information:

HomeBrudge version: 1.4.0
OS	Raspbian GNU/Linux Bullseye (11)
Hostname	homebridge
IPv4 (wlan0)	xx.xx.xx.xx
IPv6 (wlan0)	xx.xx.xx.xx.xx.xx.xx
Node.js Version	[v16.13.2](https://git.io/JTKEF)
Npm Version	v8.3.1
User	pi
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Service Mode	Yes

Here is the configuration:

"devices": [
        {
            "name": "Living Room TV",
            "host": "192.168.86.26",
            "mac": "38.8c.50.56.66.2c",
            "disableLogInfo": false,
            "disableLogDeviceInfo": false,
            "enableDebugMode": true,
            "turnScreenOnOff": false,
            "volumeControl": 2,
            "infoButtonCommand": "MENU",
            "getInputsFromDevice": false,
            "filterSystemApps": true,
            "inputs": [
                {
                    "name": "Netflix    ",
                    "reference": "netflix",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "Prime.     ",
                    "reference": "amazon",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "Hulu.      ",
                    "reference": "hulu",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "YouTube.   ",
                    "reference": "youtube.leanback.v4",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "YouTube TV ",
                    "reference": "youtube.leanback.ytv.v1",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "Ggle Play  ",
                    "reference": "googleplaymovieswebos",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "Peacock.   ",
                    "reference": "com.peacock.tv",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "Disney+.   ",
                    "reference": "com.disney.disneyplus-prod",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "Music.     ",
                    "reference": "com.webos.app.music",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "FandangoNOW ",
                    "reference": "com.mgo.mgowebos",
                    "type": "APPLICATION",
                    "mode": 0
                }
            ],
            "buttons": [
                {
                    "name": "Netflix",
                    "mode": 0,
                    "reference": "netflix",
                    "command": "CLICK",
                    "displayType": 0
                }
            ],
            "enableMqtt": false,
            "mqttAuth": false,
            "mqttDebug": false,
            "pictureModeControl": false,
            "brightnessControl": false,
            "backlightControl": false,
            "contrastControl": false,
            "colorControl": false
        }
    ],
    "platform": "LgWebOsTv"
}

Please let me know if you need any more info.

**Comment by merdok** [comment]
You are not using the correct plugin. You have installed the ripoff plugin. Either open an issue in that plugins github or install this plugin which is superiorer to the other one.
