### ISSUE TITLE
api way to know if "TV on with Mobile" is set to true

### ISSUE THREAD

**Issue by Ganime422** [merdok/homebridge-webos-tv#433]
Hi there

is there an API way to validate (and also set the value) of "TV on with Mobile" switch?
it is used for wake-on-lan to turn the tv on through the app
but I have to set this value to "true" manually first on the tv in the network settings >> mobile connection management >> TV on with Mobile >> Turn on via Wifi

so can I see the value of this parameter through an api call, and set it to true through an api call?

thanks

**Comment by merdok** [comment]
That is unfortunately not possible as far as I know. There is no public api for that.
I mean why you would want to know that anyway? You should once go in your tv settings enable that and then you do not need to do it ever again.
