### ISSUE TITLE
Problem with input changed unexpectedly

### ISSUE THREAD

**Issue by dvd2000k** [merdok/homebridge-webos-tv#436]
I have installed this plugin because the original homekit integration of my tv is limited (webos6 oled 2021).
But when i change the input to HDMI (i turn on the Apple TV and input automatically switch on hdmi) and i watch a movie, after about 15min it reverts to liveTV without doing anything.
Disabling the plugin the problem disappear…
Never had this problem with the embedded homekit integration of the tv, i don’t know why whit this plugin the tv revert on liveTV evert 15minutes.

**Comment by merdok** [comment]
It is certainly not the plugin which is doing this. Either something else is controlling the TV or you have some kind of automation set up or maybe it is your Apple TV. I can assure that the plugin does not change or set anything by itself.

**Comment by dvd2000k** [comment]
No automation made. I have enabled the embedded homekit in my tv and this thing doesn’t appen. So maybe tv software related…
And exactly every 15minutes.

**Comment by merdok** [comment]
It has nothing to do with your tv software, neither the plugin. I will unfortunately will not be able to help you out here since i have no idea how your local setup looks like and what kind of servers and software you are running across your network. I can only advice you to do some investigation by for example turning off device one by one. Maybe start with the Apple tv ?

**Comment by dvd2000k** [comment]
Don’t know why is happening only with the plugin. I have a raspberry pi with Homebridge 1.4.0. I don’t think it’s an Apple TV problem because I don’t get the “no signal screen” but simply the tv change the input by itself to “liveTV”. 
will try tomorrow to restore everything.

**Comment by merdok** [comment]
Probably there is no access to Live Tv with the native LG homekit integration, so i suppose nothing happens there when the change request from somewhere comes.

**Comment by dvd2000k** [comment]
There is tvlive in native homekit integration. I’ve installed the plugin for screen off and channel up/down.
It’s a very strange thing.
