### ISSUE TITLE
dolbyHdrDarkAmazon

### ISSUE THREAD

**Issue by scottleestrange** [merdok/homebridge-webos-tv#437]
I added picture mode dolbyHdrDarkAmazon

From that point the bride errors out.  It errors at such a rate and apparently looping so rapidly that HOOBS cannot respond

To recover I must refresh HOOBS and restore to a point where that setting was not set

If this causes an exception it should not bring down the service,

**Comment by merdok** [comment]
Where did you add this picture mode?
Please post the homebridge debug log so at least i have an idea about exception you speak. I need some more info from you in order to identify and fix the issue...
