### ISSUE TITLE
Volume Slider seen by HomeKit as a light

### ISSUE THREAD

**Issue by phydeauxfilms** [merdok/homebridge-webos-tv#438]
When I set up the plugin, HomeKit sees the volume slider as a light.  This becomes a problem when I ask Siri to turn off the lights when I'm watching the TV and she mutes the TV.  There is no way to change it in HomeKit settings and the only option I see in the plugin settings is to just ignore the slider entirely.  Is there a way to make HomeKit see it as a volume slider instead of a light dimmer?

**Comment by merdok** [comment]
Unfortunately that is not possible, plugins for homebridge are not able to to use the homekit volume slider. For this reason as a workaround the the volume is represented as a light bulb.

**Comment by phydeauxfilms** [comment]
> Unfortunately that is not possible, plugins for homebridge are not able to to use the homekit volume slider. For this reason as a workaround the the volume is represented as a light bulb.

Thanks for the quick reply.  Hopefully this will be fixed in a future update.  Nice plugin.  Otherwise it works great.

**Comment by RealNd** [comment]
mb as Fan?

**Comment by merdok** [comment]
As fan would be possible but i have no plans currently to add that as it would introduce complexity

**Comment by RealNd** [comment]
I change the code to the fan every time after the update) so I would really like to add this function. Thanks for the plugin

**Comment by merdok** [comment]
Will see what I can do👍

**Comment by anthonyvallone** [comment]
> I change the code to the fan every time after the update) so I would really like to add this function. Thanks for the plugin

Could you share the code please? Does it work with siri as the light bulb doesnt seem to.
