### ISSUE TITLE
Siri voice control for apps

### ISSUE THREAD

**Issue by lorenzomorandini** [merdok/homebridge-webos-tv#440]
Hi, thank you for the incredible plugin. I have set up a few apps using the app buttons and they all work fine, even turning the tv on if it’s off before starting the app. I am just not sure how to use siri voice commands to start them. It always complains that it can not find a suitable tv near by. What am I doing wrong?

**Comment by merdok** [comment]
The command should usually look like this: "turn on/off [button_name]". Do not use the word "tv" in any case since this is not possible for Siri to do, due to Siri limitations.

**Comment by lorenzomorandini** [comment]
I already tried but it doesn’t work. Does it make a difference if the button is together with the tv accessory or divided?

**Comment by merdok** [comment]
That does not matter. "Turn on/off (button name)" should certainly work.
