### ISSUE TITLE
TV "active" state does not work when used with conditionals in Shortcuts

### ISSUE THREAD

**Issue by renfeisong** [merdok/homebridge-webos-tv#445]
Hello! I have a LG C1 and I am trying to use the TV's on/off state as conditions in automations. I am using the `Active` state, but for some reason the actions in the `if` block is never triggered. I am using the stock Home app and have verified the value is `"On"` when the TV is on and `"Off"` when the TV is off with the Shortcut app (second screenshot). The plugin works great otherwise. Any idea what am I missing? Thanks.

[Screenshot 1: Home app shortcut setup](https://user-images.githubusercontent.com/4545784/180719240-a50074c7-79d7-46b2-8d00-f80cf47a95ee.PNG)

[Screenshot 2: Shortcut app verifying that the value is as expected](https://user-images.githubusercontent.com/4545784/180719262-614d9207-bd73-49b6-8699-e7d5f7f90be7.PNG)

Config (IP and MAC address redacted):

```
{
    "devices": [
        {
            "name": "LG C1",
            "ip": "xxx.xxx.x.xx",
            "mac": "xx:xx:xx:xx:xx:xx",
            "pollingInterval": 5,
            "volumeLimit": 100,
            "volumeControl": "none",
            "channelControl": false,
            "colorControl": false
        }
    ],
    "platform": "webostv"
}
```

**Comment by merdok** [comment]
Hi,
I am not familiar that much with shortcuts, but i think it might be the check "if active is off" check. The characteristic "Active" reports a Boolean value (true or false) so not sure if checking against an "Off" value is the correct way.

**Comment by renfeisong** [comment]
Thanks for the reply! The Home app only provides "On"/"Off" selections but does indicate that the type is "number" [(Screenshot)](https://user-images.githubusercontent.com/4545784/180877175-2158a806-a593-4cc4-b782-7ea566f911d6.PNG), my guess is that Apple is dumbing down the UI and hiding the fact that it is a Boolean.

I played with it more and I think it's very likely a bug in the Home app. Previously I had a condition structured as:

```
if Switch is On:
  if TV Active is Off:
    Set Light On
  endif
endif
```

And the light would not turn on despite both conditions are true. However, if I swap the two `if` conditions:

```
if TV Active is Off:
  if Switch is On:
    Set Light On
  endif
endif
```

Then it would work every time. Very strange...

**Comment by merdok** [comment]
Oh, that is really strange that after you swap the conditions it will work... I would then guess that indeed that must be a bug either in the home app or at processing the script.
The active state of the tv is mirrored in the home app as the tv accessory, so whenever you set the tv accessory switch being on then the active state must be on.

**Comment by renfeisong** [comment]
Good to know. Thanks for the support, Marcin!
