### ISSUE TITLE
Unable to update to the latest version

### ISSUE THREAD

**Issue by smarbitbe** [merdok/homebridge-webos-tv#447]
Timezone	GMT+0200
OS	Raspbian GNU/Linux Buster (10)
Hostname	homebridge
Node.js Version	[v16.16.0](https://homebridge.io/w/JTKEF)
User	homebridge
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/

`307 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ext Completed in 3447ms
308 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/type Completed in 3560ms
309 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ext/node_modules/type Completed in 3591ms
310 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/es5-ext Completed in 3944ms
311 timing reify:unpack Completed in 3958ms
312 timing reify:unretire Completed in 1ms
313 timing build:queue Completed in 9ms
314 timing build:link:node_modules/homebridge-webos-tv Completed in 4ms
315 timing build:link:node_modules/homebridge-webos-tv/node_modules/mkdirp Completed in 8ms
316 timing build:link:node_modules/homebridge-webos-tv/node_modules/node-gyp-build Completed in 8ms
317 timing build:link:node_modules/homebridge-webos-tv/node_modules/wake_on_lan Completed in 7ms
318 timing build:link Completed in 10ms
319 info run bufferutil@4.0.6 install node_modules/homebridge-webos-tv/node_modules/bufferutil node-gyp-build
320 info run bufferutil@4.0.6 install { code: 1, signal: null }
321 timing reify:rollback:createSparse Completed in 1171ms
322 timing reify:rollback:retireShallow Completed in 5ms
323 timing command:install Completed in 9902ms
324 verbose stack Error: command failed
324 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
324 verbose stack     at ChildProcess.emit (node:events:527:28)
324 verbose stack     at maybeClose (node:internal/child_process:1092:16)
324 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
325 verbose pkgid bufferutil@4.0.6
326 verbose cwd /usr
327 verbose Linux 5.10.103-v7l+
328 verbose node v16.16.0
329 verbose npm  v8.11.0
330 error code 1
331 error path /usr/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
332 error command failed
333 error command sh -c node-gyp-build
334 verbose exit 1
335 timing npm Completed in 10237ms
336 verbose unfinished npm timer reify 1660028121850
337 verbose unfinished npm timer reify:build 1660028129509
338 verbose unfinished npm timer build 1660028129510
339 verbose unfinished npm timer build:deps 1660028129511
340 verbose unfinished npm timer build:run:install 1660028129530
341 verbose unfinished npm timer build:run:install:node_modules/homebridge-webos-tv/node_modules/bufferutil 1660028129531
342 verbose code 1
343 error A complete log of this run can be found in:
343 error     /home/homebridge/.npm/_logs/2022-08-09T06_55_21_521Z-debug-0.log
`

**Comment by merdok** [comment]
Looks like a npm issue to me

**Comment by smarbitbe** [comment]
Upgraded npm to the latest version and now it works. Thanks for the tip.
