### ISSUE TITLE
5 toggles

### ISSUE THREAD

**Issue by mkstretch** [merdok/homebridge-webos-tv#449]
I have 5 toggles in home kit that say TV. I know they are for volume and channel, but how do I rename them? Thanks

**Comment by merdok** [comment]
Every switch has a unique name, if you want to change the name then you can go on the switch details and rename it there.

**Comment by jricey** [comment]
Changing the name of one doesn’t work as you think. 

Changing one changes them ALL to the new name… that doesn’t solve the issue.
