### ISSUE TITLE
Cannot set volumeLimit

### ISSUE THREAD

**Issue by vipersonic** [merdok/homebridge-webos-tv#45]
For some reason setting a volumeLimit doesn’t limit the volume limit. I still can go beyond the set volume limit with the Home controls.

**Comment by merdok** [comment]
The only thing what i can think of is that you setting the volumeLimit as a string with qutoas instead of a number. It should be without quotas.

Example: 
`"volumeLimit ": 40`

**Comment by vipersonic** [comment]
Yup I did that but it still doesn’t work. Here’s my config:

>     "accessories": [
        {
            "accessory": "webos3",
      		"name": "LG TV",
      		"ip": "192.168.1.44",
      		"mac": "78:5D:C8:80:0D:A9",
      		"keyFile": "/users/livingroom/.homebridge/lgtvKeyFile",
      		"pollingEnabled": true,
      		"volumeControl": true,
      		"volumeLimit": 35,
      		"appSwitch":[
      			"com.webos.app.hdmi1",
      			"com.webos.app.hdmi2",
         		"youtube.leanback.v4",
         		"amazon",
         		"netflix",
         		"spotify-beehive"
         	]
         	
        }
    ],

**Comment by merdok** [comment]
You are still using the old version of the plugin, this plugin has been renamed to `homebridge-webos-tv`
Please read the README, you need to adjust your config to use the new plugin with the volumeLimit functionality.

**Comment by vipersonic** [comment]
Ah OK, it works now. Thanks a lot!
