### ISSUE TITLE
Volume as a Fan is on at 0% when te TV is off

### ISSUE THREAD

**Issue by carlosgamezvillegas** [merdok/homebridge-webos-tv#451]
Hello Webos Tv team,

I have an issue with the new “Volume as Fan” option, the control in HomeKit shows a on when the Tv is off and the volume is at 0%, I expect this behavior when the Tv is on and on mute but not when the Tv is off.

kind regards,

**Comment by merdok** [comment]
Yeah, you are completely right, this is a bug. Should now be fixed in version 2.3.2
