### ISSUE TITLE
Plug-in completely broken since latest update. 

### ISSUE THREAD

**Issue by jricey** [merdok/homebridge-webos-tv#453]
TV became unresponsive in HomeKit after update. I removed to try and re-add the device and now I cannot get it back into HomeKit. 

After adding the bridge to HomeKit the tv doesn’t show up even after it has been set up in configuration… very frustrating. 

Please help!

**Comment by merdok** [comment]
Did you manually add the tv in the home app? What errors do you get? Please post a debug log.

**Comment by PetersenLars** [comment]
I'm having similar issues. Although I didn't try to re-add the device, it seems something broke after the iOS16 update. If I turn it on or off the plugin doesn't seem to register anything.

**Comment by BunpGhost** [comment]
I had the same issue and then I came here and found this and got it working.
So it wasn't clear to me but.. 
You have to mannually add the TV and not the Bridge.
