### ISSUE TITLE
IOS16 "Hey Siri, Turn the XBOX on."

### ISSUE THREAD

**Issue by deviann877** [merdok/homebridge-webos-tv#455]
Asking Siri to turn a specific app launches all apps that are configured. If I say "Hey siri, turn on hdmi 3, it will still cycle quickly through all apps. I have checked all appid's.

This is a new issue and hasn't done this before IOS16. ![image](https://user-images.githubusercontent.com/76647355/190900710-9c76d8fa-f989-4028-a5d8-244fa0cf3ed6.jpeg)

**Comment by deviann877** [comment]
Also, upon upgrading to ios16, all buttons were renamed to "LG TV".

**Comment by merdok** [comment]
Not a bug with the plugin, but has something to do with a change in iOS16. As far as i know there is nothing at this point that i can do...
More info https://github.com/homebridge/homebridge/issues/3210#issuecomment-1217735865
A temporary solution: https://github.com/merdok/homebridge-xiaomi-fan/issues/123#issuecomment-1239074853
