### ISSUE TITLE
All accessories have the same name

### ISSUE THREAD

**Issue by MED1975** [merdok/homebridge-webos-tv#456]
Hi - I'm not sure if this has been the case since iOS 16 (I'm sure it has been correct since) but I noticed last night that all the accessories now have the same name, everything is called the name of the TV (in my case I called it LG TV) - so when you look at the channel up/down button, volume up/down etc they all say LG TV and not the correct name so cant be identified. Any ideas?

**Comment by merdok** [comment]
Hi,
please have a look at my comment here #455
This is an issue in ios16 and there is nothing that can be done. There is although a workaround.
