### ISSUE TITLE
Random and double "TV turned off" events

### ISSUE THREAD

**Issue by satrik** [merdok/homebridge-webos-tv#458]
Hi,

since the last update, the plugin generates wrong log messages for my TV. About once per hour it logs this message while the TV is still running.

```
...
[27.9.2022, 14:34:48] [homebridge-webos-tv] [LG TV] TV turned off!
[27.9.2022, 14:34:55] [homebridge-webos-tv] [LG TV] Disconnected from TV
[27.9.2022, 14:34:58] [homebridge-webos-tv] [LG TV] Connected to TV
[27.9.2022, 14:34:59] [homebridge-webos-tv] [LG TV] Got TV information
[27.9.2022, 14:34:59] [homebridge-webos-tv] [LG TV] TV webOS version: 6.0
[27.9.2022, 14:34:59] [homebridge-webos-tv] [LG TV] TV turned on!
...
```

And another strange thing is, that turning the TV off "in real" generates always 2 events since the last update. 

```
...
[27.9.2022, 14:39:01] [homebridge-webos-tv] [LG TV] TV turned off!
[27.9.2022, 14:39:02] [homebridge-webos-tv] [LG TV] TV turned off!
[27.9.2022, 14:39:17] [homebridge-webos-tv] [LG TV] Disconnected from TV
[27.9.2022, 14:39:22] [homebridge-webos-tv] [LG TV] Starting TV alive polling
...
```

I have already completely removed the TV from homebridge/kit and re-added it. I restarted all my network devices (routers, switches), the raspberry pi, reconfigured the network on the TV, nothing fixed it so far. 
I also had tested ping from the raspberry to the LG while this message was logged and there was no packet drop - so I think we can exclude a network issue.

Any idea what could cause this problems?
It was running for month now without any issues and I didn't changed anything apart from updating the plugin. It's really annoying for me because "TV off" triggers an automation in my home -.-

TV is a OLED C1, Homebridge Version 1.5.0 and Plugin 2.3.3

**Comment by merdok** [comment]
Hi,
nothing changed about that behavior in the last update, in fact in the last couple of updates nothing about that was changed, so my assumption is that something with the tv changed? This log indicated that in fact something with the tv status changed.

**Comment by satrik** [comment]
My TV is rooted and the last change/update was in January..

**Comment by merdok** [comment]
If your TV is rooted or not does not change anything. The log appears because in fact the TV reported that status. You can enable debug log or even deepDebugLog and we should be able to see what the TV sends.

**Comment by satrik** [comment]
@merdok I've activated both, homebridge debug and deepDebugLog. Here is the [homebridge log] (https://gist.github.com/satrik/7351e83cf35e61b8b6777cd7c8df84a9) - the "double off" issue is logged in the lines 9036/9062

**Comment by merdok** [comment]
Thanks! 
The logic for that did not change since a long time. The tv sends a message which is being picked up by the plugin.
I suspect something might have changed on the tv, since the message is now being sent...

**Comment by satrik** [comment]
hmm, "Prepare Suspend" is missing [here](https://github.com/merdok/homebridge-webos-tv/blob/aa6b69cf2967640d10956008ed6875935b94ace6/lib/LgTvController.js#L1335), could this lead to the double off behavior?

**Comment by merdok** [comment]
Prepare Suspend is an intermediate status and is not handled on purpose.
The thing is that this was certainly not I theodicies in the last update or the update before or even before that. The code did not change since a long time anymore. Also that the log message appears twice in the log, that should not change anything, the status of the accessory can only be set once to a opposite state, so if the status is already off, subsequent off setting should not have any effect or trigger any automation.

**Comment by satrik** [comment]
yeah you're right, double off shouldn't trigger the automation twice. 
I will let the debug option on and check today evening if the random disconnect<>connect comes again

**Comment by merdok** [comment]
I more or less have to be graceful here with the status changes since I know that changed already a couple of times between webos versions and also it is different between OLED and LCD TVs.

**Comment by satrik** [comment]
well classic demonstration effect. there wasn't a single "power off>disconnect>connect" issue since I activated debug logging yesterday. I will check it later again and if there is still no issue, I will close the issue :)

**Comment by merdok** [comment]
Ok, thanks for the update!

**Comment by satrik** [comment]
@merdok, 2 days without any unwanted disconnect... so this problem is fixed by magic 😄

Btw, I fixed the "double tv off", the issue was that both "Request Suspend" and "Suspend" are setting the tvPowerState to "Off" which triggers twice the off event. adding another state which isn't depending on the connection state of the event listener fixed it for me. works exactly like expected since 2 days. I could make a PR if you are open for it.
https://github.com/satrik/homebridge-webos-tv/commit/33320fa9434ddf381beadc6ede4903929d302896

**Comment by merdok** [comment]
Good to hear that the initial issue is solved! Thanks for the info!

I am very cautious by such changes since it might work for you but for others it might break. Also introducing another flag adds some complexity to the logic.
And in the scenario from pixel refresher to off state the event will now never trigger😅

**Comment by satrik** [comment]
> And in the scenario from pixel refresher to off state the event will now never trigger

is the pixel refresher always starting before "Request Suspend" and "Suspend"? I've deleted all logs and can't check currently in which order they are coming from the TV 😅

**Comment by satrik** [comment]
then it doesn't make sense to set the state in the pixel refresher case 😄

 as you don't like to add the additional flag/state I will just change it locally for me. 

thanks for your help!
