### ISSUE TITLE
App Button Names

### ISSUE THREAD

**Issue by elorand** [merdok/homebridge-webos-tv#459]
Hello,

since iOS16 some AppButtons and NotificationButtons appear under the same name of the TV itself, instead of their given names in the config. On my iPad running iPadOS15 are shown the given names, like on my iPhone used to be (on iOS15).

Screenshot iPad:
![CE899761-DF4C-49B6-80F3-1B5FF6712C2F](https://user-images.githubusercontent.com/98426071/194144308-0d5b8945-ef2a-4c7a-a08e-00fe47ae4cdc.jpeg)

Screenshot iPhone:
![F8862777-0169-4A0B-87E1-4A3939771EFB](https://user-images.githubusercontent.com/98426071/194144510-fc0e2de7-5160-47db-8d80-660a66b4f07d.png)

**Comment by merdok** [comment]
Hi,
please have a look at my comment here #455
This is an issue in ios16 and there is nothing that can be done. There is although a workaround.
