### ISSUE TITLE
Possible to turn off the Volume Switch services?

### ISSUE THREAD

**Issue by vipersonic** [merdok/homebridge-webos-tv#46]
I'd rather just have the Volume as a lightbulb, rather than 2 volume switches. Is it possible to turn it off in the config?

**Comment by merdok** [comment]
You can easily remove them from your room if you don't need them.

**Comment by vipersonic** [comment]
I’m afraid that I only found options to remove the entire homebridge, but not individual accessories/buttons like the volume up/volume down ones. 

Kenneth

**Comment by merdok** [comment]
You can create a new room which you call "unused" and move all switches there which you don't want to have. I decided against adding a property in the config to disable the volume switches because this can easily be done in every HomeKit app.

**Comment by vipersonic** [comment]
Moving a single switch to another room moves all the other TV switches as well. 

Kenneth

**Comment by merdok** [comment]
True... Currently it is not possible then. Maybe in a future update i will add that...

**Comment by vipersonic** [comment]
Thanks!

Kenneth
