### ISSUE TITLE
Plugin stops working overnight

### ISSUE THREAD

**Issue by bbrantley** [merdok/homebridge-webos-tv#460]
Three days ago, the plugin has started... not working... overnight.  Each morning it doesn't work, and I don't see anything in the logs.  Cycling homebridge brings things right back to working again.  

Everything was stable for the previous six+ months, and I can't fathom what might have changed.  Any ideas?

**Comment by merdok** [comment]
Hmm, did not notice anything about such an issue. 
You would need to provide a homebridge debug or crash log so i can have a look and check for potential issues...

**Comment by bbrantley** [comment]
Thanks, it's now stable again, seemingly.  I've turned up logging so that I can report more here, if it happens again.
