### ISSUE TITLE
How to find picture mode names?

### ISSUE THREAD

**Issue by Keagel** [merdok/homebridge-webos-tv#461]
Hey!

I'm trying to use the picture mode button but only some of the HDR modes work for me. I'm mainly trying to change to two modes named "Standard (User)" and "Cinema Home (User)". I've tried a variety of names in the JSON config but I can't get them to work. The TV model is OLED55C1. It's on WebOS 6.0.

How can I figure out how the modes are named internally?

Thanks!

**Comment by merdok** [comment]
Unfortunately there is no other way currently then try to guess. Some were easy to guess but others might be hard...

**Comment by Keagel** [comment]
I forked your repository and added a CLI command to change picture settings so I could try and find the correct names without having to edit the configuration and restart Homebridge every time. I ended up figuring out that the modes are simply named hdrStandard and hdrCinemaBright - which are already listed. Not sure why it didn't work before but it does now.

**Comment by merdok** [comment]
If you want, you can submit a PR with the added CLI command as it could be helpful for others.

**Comment by merdok** [comment]
Thanks!
