### ISSUE TITLE
notificationButtons: wrong (parent) name displayed

### ISSUE THREAD

**Issue by shanemcw** [merdok/homebridge-webos-tv#464]
When using notificationButtons, the name that is displayed in Home for the notification button (mapped to a switch) is the "devices" "name," e.g. "LG TV" and not that "notificationButtons" "name" e.g. "My Notification Button"

**Comment by merdok** [comment]
What you probably mean is not an issue with the plugin, but something that changed in ios16 for some reason. More info here: https://github.com/merdok/homebridge-webos-tv/issues/455#issuecomment-1250263091
