### ISSUE TITLE
requires a Homebridge version of >=1.4.0 which does not satisfy the current Homebridge version of 1.3.4.

### ISSUE THREAD

**Issue by tfraley** [merdok/homebridge-webos-tv#465]
11/8/2022, 8:29:20 AMLG100 starting
11/8/2022, 8:29:30 AMLG100ERROR[31mThe plugin "homebridge-webos-tv" requires a Homebridge version of >=1.4.0 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
11/8/2022, 8:29:31 AMLG100ERRORError loading plugin "homebridge-webos-tv"
11/8/2022, 8:29:31 AMLG100WARNINGNo plugins installed.
11/8/2022, 8:29:31 AMLG100Loading 1 platforms...
11/8/2022, 8:29:31 AMLG100Bridge is running on port 51836.

**Comment by merdok** [comment]
What is the issue you are facing? The plugin requires homebridge version 1.4.0, and you have 1.3.4. You need to update your homebridge.

**Comment by tfraley** [comment]
Sorry I should of noted. 
I am using Hoobs and your plugin has stopped working. 
Being that it's certified hoobs plugin I thought it would be strange to see this error. 

My assumption is Hoobs has not updated to Homebride version 1.4.0 or better but yet you plugin is requiring it. Again strange because it's hoobs certified.

I'm not new and have had it working and using it for a good maybe year now. But this week it's stoped working and that is whats in the log.

**Comment by tfraley** [comment]
Also why has the thread been marked closed after a question is 5min ago and I responded 1min after yours

**Comment by merdok** [comment]
I did not change the version of homebridge which HOOBS is running on. I suppose that should not change. I think this is not an issue with the plugin but more with your local setup.
As for why I closed the issue, you posted a log snippet without any context, there is no way for me to know what your issue is from that...

**Comment by tfraley** [comment]
@merdok Understood. 
Nothing has changed with my local setup, But I have a backup from a few months ago. 
Perhaps I will restore and systematically update it to see where it breaks. But that log entry raised a flag to me like the plugin updated to a version of homebridge that Hoobs is not on yet for some reason.

Perhaps I will try and roll back to your older plugin version to see if it does anything. 


But what your saying your latest version of your plugin should work with the latest version of Hoobs?

**Comment by merdok** [comment]
The requirement for homebridge 1.4.0 is already included in the plugins since july this year, so it is nothing recent. 

I do not use hoobs myself, but hoobs is nothing else then a wrapped homebridge so it should work.
