### ISSUE TITLE
Possible to hide all IoT devices?

### ISSUE THREAD

**Issue by tetanus** [merdok/homebridge-webos-tv#466]
I have IoT devices exposed to my LG TV's Home Dashboard for the convenience of controlling them while the TV is on. These devices all appear in the TV's Accessory Details view in HomeKit. Would it be possible to prevent them from showing at all so that the accessory details view is cleaner and less cluttered?

**Comment by merdok** [comment]
I do not quite understand what you mean, but I guess you could use the configuration to disable the stuff which you do not want to appear.
