### ISSUE TITLE
Multiple Inputs that have not been added

### ISSUE THREAD

**Issue by sahotanick** [merdok/homebridge-webos-tv#467]
Hi, 

I see multiple inputs in the settings however I haven’t added these in and also they shouldn’t be automatically fetched like this. Please see screenshots below:

![9CABE10B-F2F6-4E45-BA11-578BA176931B](https://user-images.githubusercontent.com/25302199/203401037-eb2ceb90-4d85-4f00-a24a-96dc18deac20.png)
![4F665C2B-0082-4174-B3A0-DC4C19DF4C4B](https://user-images.githubusercontent.com/25302199/203401045-a0dea985-cf15-4a60-8601-155993897069.png)
![FC66F578-8E5A-4759-8110-1502A5128BF6](https://user-images.githubusercontent.com/25302199/203401050-d12f80b7-e664-4c61-ab59-89280d576f0e.png)

**Comment by merdok** [comment]
Oh, that is quite weird. You might want to try to clear the inputs cache under the plugin prefs directory and see if that helps

**Comment by sahotanick** [comment]
Thanks @merdok, I’m guessing that means SSH on and then navigate to that directory for the web-os plugin? Do you have a direct path you can paste here to make it a bit easier for me to find?

**Comment by merdok** [comment]
Yes, exactly. If you did not change the default directory then it should be: ~/.homebridge/.webosTv
