### ISSUE TITLE
Feature request - Add Energy Saving to functions

### ISSUE THREAD

**Issue by Robmanzzz** [merdok/homebridge-webos-tv#468]
Hi!

Thank you for all your work on this plugin, I do however have a feature request :)

Is it possible to expose the 6 different Energy Saving options (Auto, Off, Minimum, Medium, Maximum, Screen Off) as a button or switch to Homekit? I use the Energy Saving function to dim the (OLED) backlight to accommodate the ambient light in the living room. I rather use this option rather than dimming the backlight manually for a couple of reasons: 

1. I've calibrated the TV and I would love to just turn Energy Saving off and get back to the fully calibrated brightness with one button. 
2. When enabled, Energy Saving dims all of the picture modes (SDR, HDR, DV) as opposed to dimming the backlight which only changes the value of the current picture mode.

I currently use a Logitec Harmony with macros to enable/disable Energy Saving, but I would rather user a direct Homekit solution.

Thanks for reading, I do hope it's possible!

Rob

https://user-images.githubusercontent.com/8589665/204784594-60a5cf26-11c6-4e75-88c0-7a8692b34d10.mov

**Comment by merdok** [comment]
Hi,
unfortunately as far as i know it is not possible to control the Energy Saving options, at least i am not aware of any API endpoints on the TV which control that.
But i think you could use the `remoteSequenceButtons` to achieve that, you would just need to enter the sequence of remote buttons which needs to be execute to accomplish that.
