### ISSUE TITLE
Updated now getting error: webOS - Error: connect ETIMEDOUT 192.168.1.23:3000

### ISSUE THREAD

**Issue by m11rphy** [merdok/homebridge-webos-tv#47]
Hi Just did the update and now getting the following error;

webOS - Error: connect ETIMEDOUT 192.168.1.23:3000

**Comment by merdok** [comment]
Probably the TV is not reachable, check if the ip is correct and the TV is in the network.

**Comment by m11rphy** [comment]
if the TV is on it works fine, but I can turn the TV on with HomeKit

**Comment by merdok** [comment]
That means that your TV is going into deep sleep mode, maybe you disabled mobile tv on.

**Comment by m11rphy** [comment]
You are right somehow I turned it off, all working brilliantly. Thank you so much for all th work you do on this plugin it really is the best one I use

**Comment by merdok** [comment]
Good to hear :)
