### ISSUE TITLE
Add Button For “Reduce Blue Light” Toggle (C1)

### ISSUE THREAD

**Issue by iSteve-O** [merdok/homebridge-webos-tv#470]
I tried to do this with a button sequence but the I can’t get it to work reliably every time. It would be so great if you could add a toggle for the “reduce blue light” option so I can toggle it on and off easily with automation. 

The toggle I speak of is located in the advanced section of the picture menu on my LG C1 tv. 

I really appreciate your consideration.

**Comment by merdok** [comment]
Unfortunately this is not possible directly as there is no API (at least public or documented) to do that. You would need to stick with a sequence. Maybe you can add some delay between the actions to make it work more reliably.

**Comment by iSteve-O** [comment]
I see. thank you for your reply. 

I'm wondering if you can help me with the sequence? 

Is there a way to have different intervals for different commands? I assume the interval set in my sequence below applies to each command. I tried a standard interval up to 2500 but it still wasn't enough. I need a longer interval at least after the first `enter` (that's as far as it gets before getting off track so I may need more longer ones after). Maybe I'll keep trying to increase that single interval, but I'd love to set an interval-per-command, if possible in the plugin.

Here is my current sequence config
```
                    ],
                    "remoteSequenceButtons": [
                        {
                            "sequence": [
                                "MENU",
                                "UP",
                                "UP",
                                "ENTER",
                                "RIGHT",
                                "DOWN",
                                "DOWN",
                                "ENTER",
                                "DOWN",
                                "DOWN",
                                "DOWN",
                                "DOWN",
                                "DOWN",
                                "DOWN",
                                "ENTER",
                                "EXIT"
                            ],
                            "name": "Reduce Blue",
                            "interval": 2500
                        }
                    ],
```

I really appreciate your help, but no obligation to do so.

**Comment by merdok** [comment]
Glad you got it work with the sequence buttons. Yeah the config of that could be improved...
