### ISSUE TITLE
Plugin won’t install after pressing install…

### ISSUE THREAD

**Issue by jricey** [merdok/homebridge-webos-tv#475]
Can anyone please help with the above?
After searching for and clicking install on the WebOS Tv plug-in, nothing actually installs...
I select to create a new bridge then just takes me back to the install page with no option to configure.
Same thing happens again if I click install...
Am I missing something?

**Comment by merdok** [comment]
I do not think that the issue is related to this plugin... I guess it has something to do with your homebridge installation
