### ISSUE TITLE
How can I find out the name to specify for additional picture modes?

### ISSUE THREAD

**Issue by ledhed2222** [merdok/homebridge-webos-tv#476]
I'm using a projector (HU 810PW) which has some additional picture modes you don't have. How would I go about determining what the specific string is to use for the appropriate picture mode value?

**Comment by merdok** [comment]
Well, those are nowhere documented  so the best way for you here would be just try to guess them. Usually they have a very similar name as those which you see on the device, but they also can have completely different ones which makes them hard to guess.

**Comment by merdok** [comment]
Yes, you can definitely submit a PR if you find any new ones.
