### ISSUE TITLE
Asking Siri to go to Netflix

### ISSUE THREAD

**Issue by LazaroFilm** [merdok/homebridge-webos-tv#478]
I'm trying to ask my HomePod to go to Netflix app on my LG tv but it says it can't find any TV with Netflix on. But I can switch the TV to Netflix in the home app. 

The only temporary fix I found is creating a scene called Netflix with the TV on the Netflix channel. 

I'm using Netflix but that issue goes for all the Tv apps.

**Comment by merdok** [comment]
This has nothing to do with the plugin but with Siri itself. Sometimes Siri does not understand which switch you mean do you need to rename it to a name that she understands.
