### ISSUE TITLE
TVs won't turn off after HomeKit infrastructure upgrade

### ISSUE THREAD

**Issue by thellamie** [merdok/homebridge-webos-tv#479]
After updating to the new HomeKit infrastructure with iOS 16 I can no longer turn TVs off. They'll turn on OK but nothing happens issuing commands to turn them off.

Basics:
7 original HomePods
3 HomePod Minis
All running HomePod OS 16.3.1 (but has been doing this since 16 first introduced new infrastructure upgrade

Have attempted to remove all of the TVs (6 in total)
Have attempted to remove cached items
Have attempted older versions (going back to 2.3.0)
Nothing shows up in logs when I attempt to turn them off. I've put HomeBridge in Debug mode 

The only thing I can see in the logs is after turning on a TV (via voice, Assessors HomeBridge Function, or Home App) that TV will continually show up as "[TV Name] Connecting to TV". Not sure if it did this before though as I wasn't running in debug mode.

**Comment by merdok** [comment]
This has nothing to do with the architecture update. I myself also did the architecture update and there are no issues. Please make sure that the tv is reachable within your network.

**Comment by thellamie** [comment]
I can turn them on over network successfully. Just can't turn them off. I'll concede likely not related to the upgrade but the timing started at the same time

**Comment by merdok** [comment]
Something also changed with your tv then, maybe the ip changed or the pairing got lost and you need to re-pair them?
As already mentioned the architecture update has nothing to do with your issue.

**Comment by thellamie** [comment]
Unlikely to happen to all six at the same time: 

"Have attempted to remove all of the TVs (6 in total)
Have attempted to remove cached items
Have attempted older versions (going back to 2.3.0)"



Also just removed and re-added all of them again just minutes ago and the same thing occurs. I can turn them all on just fine but not off.

**Comment by merdok** [comment]
The fact that you see "connecting to tv" in your log strongly indicates that the plugin cannot connect to your tv.
Your issue is a local infrastructure problem. A tv can be turned on without a connection to the tv as it is using a magic packet sent over the network, but to turn off the tv a connection has to be established to the tv.

**Comment by thellamie** [comment]
Thanks @merdok for the hints. I found it and will close the issue. In this case someone had turned WiFi on for *ONE* of the TVs. The listener on the TV used this MAC address but was still connected to ethernet which was getting the magic packet. 

Odd thing is ALL of the six TVs stopped responding when this happened. I can replicate it by simply changing the MAC address of any one of them... As soon as I do all of them stop responding. Not sure I'd call it a bug necessarily but weird the plugin is impacted by this.
