### ISSUE TITLE
TV Power remains on

### ISSUE THREAD

**Issue by Be2daErtin** [merdok/homebridge-webos-tv#48]
Hi, 
Since upgrading the plugin from webos3 I've discovered that when polling is true. The TV Power always stays on after briefly turning off. Thus, Siri cannot turn the tv back on

**Comment by Be2daErtin** [comment]
Ok. Something interesting happened. 

I was testing this on HDMI 1. My mac is connected to HDMI1 whilst my Apple TV connected to HDMI2.

Turing the TV on and off kept showing the TV as on when polling finished. After a while my Apple TV turned of due to sleep mode. I heard a clicking noise from the TV and suddenly the tv is shown as off.

Now suddenly it is all working again. So I assume the TV Power is affected by some HDMI keep alive value.

**Comment by Be2daErtin** [comment]
Yes I do

**Comment by merdok** [comment]
Even if you turn off an OLED, it stays on for around 15 minutes (the screen just gets black but the TV is still on), and in that time a pixel refresh is run to keep the picture quality good. At that time the TV will still be reported as on, and i can't really know if it is really on or the pixel refresher is running. 
So i suspect that this is what is happening in your case too...
