### ISSUE TITLE
Channel Switch not turning on when tuning in to channel via the remote

### ISSUE THREAD

**Issue by Terabyte1385** [merdok/homebridge-webos-tv#480]
I have a switch created for channel 2 of my TV. I use it to change the backlight lightstrip to green. The automation runs when I manually turn on the switch. However, when I change to channel 2 via the tv remote, the switch doesn't adapt, stays off and the automation doesn't run.

I'll make sure to send you some Homebridge logs once I get the chance to.

**Comment by merdok** [comment]
Yeah you would need to post some debug logs, specially for the time when you switch the channel so we can have a look if the event gets triggered. Also you would need to post your switch config

**Comment by Terabyte1385** [comment]
```
[3/13/2023, 4:31:40 PM] [webostv] [Living Room TV] Connected to TV
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] Got TV information
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] TV webOS version: 4.5
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] TV turned on!
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] App launched, current appId: com.webos.app.livetv
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] Sound output changed. Current sound output: external_arc
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] Channel changed. Current channel: 5, DIGI3 HD, channelId: 3_13_5_5_213_171_1
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] Subscribed to TV services
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] Connected to remote pointer input socket
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] Setup finished
[3/13/2023, 4:31:41 PM] [webostv] [Living Room TV] TV setup finished, ready to control tv
```

```
"devices": [
                {
                    "name": "Living Room TV",
                    "ip": "192.168.0.18",
                    "mac": "[MAC goes here]",
                    "pollingInterval": 5,
                    "hideTvService": false,
                    "volumeLimit": 100,
                    "volumeControl": "none",
                    "channelControl": false,
                    "mediaControl": false,
                    "screenControl": false,
                    "appButtons": [
                        {
                            "appId": "netflix",
                            "name": "Open Netflix"
                        },
                        {
                            "appId": "youtube.leanback.v4",
                            "name": "Open YouTube"
                        },
                        {
                            "appId": "com.disney.disneyplus-prod",
                            "name": "Open Disney+"
                        }
                    ],
                    "channelButtons": [
                        {
                            "channelNumber": 2,
                            "name": "DIGI2"
                        },
                        {
                            "channelNumber": 3,
                            "name": "DIGI2 HD"
                        },
                        {
                            "channelNumber": 5,
                            "name": "DIGI3 HD"
                        },
                        {
                            "channelNumber": 7,
                            "name": "DIGI4 HD"
                        }
                    ]
                }
            ]
```

**Comment by merdok** [comment]
I do not see anything wrong with your log or the config.
It should actually work! What webos version does your tv has? Did you try to restart homebridge or maybe force Jill the home app and reopen it?

**Comment by Terabyte1385** [comment]
webOA 4.5 (2.3.5), firmware 5.30.25

Just as I was looking for the version I noticed it started working again. It's strange because just as I was collecting the logs it didn't work, so it's a bit spotty. I'll keep trying and update you if it messes up again.

**Comment by Terabyte1385** [comment]
Update: issue still occurs. The "Channel changed" log no longer appears in the Homebridge logs, and the switches don't change states as they should.

**Comment by merdok** [comment]
I guess then something is wrong with the reporting of channel changes from your tv then.
If the log does not appear then your tv does not sent channel change events. You can also try to use the channel id instead of the channel number.

**Comment by Terabyte1385** [comment]
Will try and update you further on the situation. Thanks!

**Comment by Terabyte1385** [comment]
Yep, still happening.

**Comment by merdok** [comment]
Well if the channel change log still does not appear then something is odd with the tv reporting the changes...

**Comment by Terabyte1385** [comment]
What can be done about this? Is there anything else you recommend trying? 

**UPDATE:** It seems like restarting the TV solves the issue temporarily. Just turning off the TV from the remote is not enough, an unplug is required.

**Comment by merdok** [comment]
I unfortunately have no idea what else could be done to fix the issue. I never heard of anyone else experiencing something similar before...

**Comment by merdok** [comment]
You mean when live tv is not the default app during startup?

**Comment by Terabyte1385** [comment]
That's correct, when the TV opens on HDMI input or something else

**Comment by merdok** [comment]
Hmmm, there is a logic which should take care of that. Are you able to modify some code by adding a log output at a line to check whether it is called? If yes please add a log point at line 419 in LgTvController.js and check whether it is being called.

**Comment by merdok** [comment]
You just have to navigate to your node_modules directory find the plugin directory and replace it there, then restart homebridge.

**Comment by merdok** [comment]
Should be fixed in version 2.4.0

**Comment by Terabyte1385** [comment]
Hello, sorry for the inactivity. W/ v2.4.0 this is unfortunately not fixed for me. I wasn't able to get the edited version w/ the log point to work in my Homebridge unfortunately.

**Comment by merdok** [comment]
Then you need to post what the error is so I can understand what is going wrong.

**Comment by merdok** [comment]
If it fails then there certainly has to be an error log mentioning that a subscription to a service failed. That is what you have to look in the log for.

**Comment by Terabyte1385** [comment]
Hi there, I don't see any error for subscription. But I do see this at subscription time:
`Channel changed. Current channel: undefined, undefined, channelId: undefined`

Will update to v2.4.1 and let you know if it's fixed.

**Comment by Terabyte1385** [comment]
Great news! Seems like it's working w/ v2.4.1.

I'm going to play around with it and update you if anything goes wrong again.

**Comment by merdok** [comment]
That sounds good! Thanks for letting me know
