### ISSUE TITLE
Service menu support.

### ISSUE THREAD

**Issue by mycop5** [merdok/homebridge-webos-tv#481]
Please add option to enter to service menu. (Ez-adj, instart,instop)
It is hard to find IrDa sometime.

**Comment by merdok** [comment]
As far as I know this is not possible. If there is a way to do that over the websocket then it would be great if someone could point me to that so I can implement it.

**Comment by mycop5** [comment]
> As far as I know this is not possible. If there is a way to do that over the websocket then it would be great if someone could point me to that so I can implement it.

If you enter this sites in TV browser, then you can enter toservice menu.
webosapp.club/instart
webosapp.club/ezadjust

I even use part of code and enter it in browser manualy, offline. 
It work.
I dont know specific of your code...but...
Maybe you can implement in your projet.

**Comment by merdok** [comment]
Hmm, interesting. Will check it out!

**Comment by merdok** [comment]
Added in version 2.4.0
