### ISSUE TITLE
Can't switch to App 

### ISSUE THREAD

**Issue by Zi0u** [merdok/homebridge-webos-tv#484]
Dear team

I've updated the plugin today and now I'm not able to switch to some appButtons for exemple my config below : 

> "appButtons": [
>                         {
>                             "appId": "com.webos.app.livetv",
>                             "name": "Live"
>                         },
>                         {
>                             "appId": "com.webos.app.hdmi3",
>                             "name": "PS4"
>                         }
>                     ],

Hereunder the logs retrieved with the debugMode : 

> [28/03/2023, 22:34:13] [homebridge-webos-tv] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside write handler for characteristic: newNotificationButtonDef is not defined. See https://homebridge.io/w/JtMGR for more info.
> [28/03/2023, 22:29:40] [homebridge-webos-tv] ReferenceError: newNotificationButtonDef is not defined
>     at webosTvDevice.<anonymous> (file:///usr/local/lib/node_modules/homebridge-webos-tv/index.js:762:50)
>     at On.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2547:42)
>     at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)
>     at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:174:57)
>     at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:167:75
>     at new Promise (<anonymous>)
>     at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:163:16)
>     at On.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:871:24)
>     at Accessory.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1889:29)
>     at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:193:27)

I'm on WebOS 4.0. The other options like volume or channel switch works fine. 
Working fine before the update. 

Thanks in advance for your help.

**Comment by merdok** [comment]
Oh, you are right...
Should be fixed in version 2.4.1 now!
Thanks for reporting!
