### ISSUE TITLE
Volume set up

### ISSUE THREAD

**Issue by ckangnz** [merdok/homebridge-webos-tv#485]
I tried using the _light switch_ for my volume, but sliding it didn't work for my C1.

Is there any way to set an automation on :
"When input mode is Disney Plus, set volume to 20"
"When input mode is Netflix, set volume to 18" etc.?

The soundbar speakers I have is too loud on Youtube, and too quiet on Netflix and Disney Plus so I want to adjust the volume depending on my input

**Comment by merdok** [comment]
If you have a look at the README for the description of the volume control, there is the following note:

The slider (lightbulb and fan) volume control is not supported for ARC sound outputs

Might it be that you do not use the tv speaker but external?

**Comment by merdok** [comment]
It has nothing to do with the plugin, the issue is that the webos api does not allow that, so lg would need to adjust that...

**Comment by ckangnz** [comment]
oh well...

at least this plugin offers more input options than the default HDMIs.. i'm happy with how it is for now 🙂...

Thank you though!

**Comment by merdok** [comment]
I mean in theory you could create a shortcut which triggers the volume up or down buttons multiple times until the desired volume is reached, just not sure if a shortcut can be triggered by an automation...

**Comment by ckangnz** [comment]
I couldn't find a way to trigger a shortcut via automation. 

Oh well.. if it's not supported it's what it is 😅
