### ISSUE TITLE
TV asks constantly to accept connection

### ISSUE THREAD

**Issue by Vicelow** [merdok/homebridge-webos-tv#486]
Hi there,

since a few days my LG (with webos 03.34.65) asks every few minutes to accept the remote connection
"If you accept this connect, LG Remote App will be able to access and store information about your TV“. I’ve clicked „yes“ uncountable times but it still would bring up the notification. Also reinstalled the Homebridge plugin, the HomeKit TV device and unpaired the TV in homebridge. No success though. Is this a TV bug or with the plugin / homebridge? Any idea?

many thanks
Vicelow

**Comment by merdok** [comment]
You have to make sure that homebridge can write files to the settings directory for the plugin. I suspect the permissions changed and the plugin cannot write the key anymore, hence it will ask in every restart.

**Comment by Vicelow** [comment]
Many thanks for the quick answer - that sounds plausible. Probably because I have recently moved Homebridge on my Synology NAS from docker to native app. Would you know by chance how to set the permission? For now navigated to the folder "Homebridge" and set the permission for user "homebridge" to all folders and subfolders. (apologies for screenshot in German)
<img width="1174" alt="Bildschirmfoto 2023-04-09 um 10 33 19" src="https://user-images.githubusercontent.com/107150273/230762827-653d384d-1e54-4d17-b239-869fdd046cc7.png">

**Comment by merdok** [comment]
You would need to figure out that by yourself. I do not use a NAS so I am not sure how to do it. As an alternative you can specify the key file location in your config and choose a directory where you have write permissions.

**Comment by Vicelow** [comment]
Alright, for now there was no further notification. I'll check and observe - thanks again for the support
