### ISSUE TITLE
Feature Request - a_Volume Slider 0% without mute b_Seperate additional tiles beyond volume slider

### ISSUE THREAD

**Issue by HawaiiBoi32** [merdok/homebridge-webos-tv#489]
Title says it all basically. 
A - I'm trying to set up a scene so that I can turn on the tv, switch to my xbox and set the volume to 0. This is different than muting but the way scenes work if you set the % to 0 it turns off. I'm guessing you could set up a specific type of slider that would just send a 0% volume input instead of a mute input to the tv.
B - It would be very nice if I could have the volume slider with the TV inputs, but then any additional buttons to be separate tiles. Unless this is already a feature but I missed it.

**Comment by merdok** [comment]
Hi,

both your requests are more or less homekit limitations. 
I can only use a fan or lightbulb to imitate a slider functionality in homekit, and they automatically turn off when they reach 0%.
The same goes for the other issue, i cannot place a slider in tv inputs area as Apple did not design that way unfortunately... 
Maybe the TV support will be improved by Apple at some point but until then we have to work with tricks which are not always optimal...

**Comment by HawaiiBoi32** [comment]
Thanks for the quick response, unfortunate as it is lolBrandon Gadow(732) 421-4558On Apr 23, 2023, at 3:08 AM, Marcin ***@***.***> wrote:﻿
Hi,
both your requests are more or less homekit limitations.
I can only use a fan or lightbulb to imitate a slider functionality in homekit, and they automatically turn off when they reach 0%.
The same goes for the other issue, i cannot place a slider in tv inputs area as Apple did not design that way unfortunately...
Maybe the TV support will be improved by Apple at some point but until then we have to work with tricks which are not always optimal...
