### ISSUE TITLE
Config with Multiple TVs not working

### ISSUE THREAD

**Issue by erickkrauss** [merdok/homebridge-webos-tv#49]
I've tried to make the plugin working with multiple TV at the same time but it seems it only works with the first TV acessed by homebridge/plugin. I created diferent "keyfile" directories for each TV as config.json bellow : 

{
  "bridge":{
    "name":"Homebridge",
    "username":"CD:22:3D:E3:CE:30",
    "port":51826,
    "pin":"031-45-154"
  },
 "description":"Homebridge",
 "accessories":[
     {
        "accessory": "webos3",
        "name": "TV 1",
        "ip": "192.168.1.205",
        "mac": "c8:08:e9:97:68:B9",
        "keyfile": "/home/pi/.homebridge/1/lgtvKeyFile",
        "pollingEnabled": true,
        "appSwitch":[
            "com.webos.app.livetv",
            "netflix",
            "youtube.leanback.v4"
        ]
     },
     {
        "accessory": "webos3",
        "name": "TV 2",
        "ip": "192.168.1.206",
        "mac": "e0:51:63:74:82:76",
        "keyfile": "/home/pi/.homebridge/2/lgtvKeyFile",
        "pollingEnabled": true,
        "appSwitch":[
            "com.webos.app.livetv",
            "netflix",
            "youtube.leanback.v4"
        ]
     },
     {
        "accessory": "webos3",
        "name": "TV 3",
        "ip": "192.168.1.207",
        "mac": "5c:dc:96:2f:00:2c",
        "keyfile": "/home/pi/.homebridge/3/lgtvKeyFile",
        "pollingEnabled": true,
        "appSwitch":[
            "youtube.leanback.v4",
            "com.webos.app.livetv"
        ]
     }
 ]
}

**Comment by merdok** [comment]
You are still using the old version of the plugin. Please read the README. This plugin has been renamed to `webostv`
