### ISSUE TITLE
Can you move app buttons into HDMI/inputs list please ?

### ISSUE THREAD

**Issue by mkizzle2906** [merdok/homebridge-webos-tv#490]
As the tittle, can you make it happen or there is anyway to configure config to move app buttons into HDMI/input list in Home app ?

**Comment by merdok** [comment]
The source picker in the home app should already be filled with all the applications from your tv. The app buttons are just additionally there to allow you to use them for automations.

**Comment by mkizzle2906** [comment]
> The source picker in the home app should already be filled with all the applications from your tv. The app buttons are just additionally there to allow you to use them for automations.

![IMG_395F65166972-1](https://user-images.githubusercontent.com/32402155/236466154-0ba12ea9-816f-469f-845e-24a738faa240.jpeg)
I don't have any apps in the source picker
