### ISSUE TITLE
Can’t find working name for settings menu/gear button 

### ISSUE THREAD

**Issue by candybars2001** [merdok/homebridge-webos-tv#491]
In order to create a sequence that will generate a 30 minute sleep timer, I have to begin with pressing The settings Or gear button, Which brings up the quick settings options that can then be expanded.  I tried SETTINGNS, QSETTINGS, MENU, QMENU among others, but non seem to work. Everything works perfectly and explained in detail in a way that’s very easy to understand, except for this probably obvious thing I’m missing. Would appreciate any advice. Thanks

**Comment by merdok** [comment]
If it is not present on the known commands list then i guess nobody yet found out what command it is. Maybe there is a different way which leads you to the same result without the need of that menu?
