### ISSUE TITLE
Input spinner

### ISSUE THREAD

**Issue by beliy82** [merdok/homebridge-webos-tv#492]
i got some app that says "dummy" instead youtube or netflix, and i dont have any HDMI1 inputs in a spinner

**Comment by merdok** [comment]
This is a cache issues. Try to force kill the home app or clear the input cache in the webostv preferences directory.

**Comment by beliy82** [comment]
force kill didnt help, webostv preferences directory - where is it?

**Comment by merdok** [comment]
If you did not change it manually, then the default one is listend in the documentation https://github.com/merdok/homebridge-webos-tv#tv-configuration-fields
look for `prefsDir`

**Comment by merdok** [comment]
If you did not change your directory then it is located under  `~/.homebridge/.webosTv`

**Comment by tobihoby** [comment]
ok, found the directory. Which file should be deleted? I have connected two TVs. There is only one problem.

![image](https://github.com/merdok/homebridge-webos-tv/assets/60090762/4d46bb67-2dba-467c-8375-f8d80eb6556e)

**Comment by beliy82** [comment]
> ok, found the directory. Which file should be deleted? I have connected two TVs. There is only one problem.
> 
> ![image](https://user-images.githubusercontent.com/60090762/252435620-4d46bb67-2dba-467c-8375-f8d80eb6556e.png)

where is the directory location?

**Comment by tobihoby** [comment]
> > ok, found the directory. Which file should be deleted? I have connected two TVs. There is only one problem.
> > ![image](https://user-images.githubusercontent.com/60090762/252435620-4d46bb67-2dba-467c-8375-f8d80eb6556e.png)
> 
> where is the directory location?

/var/lib/homebridge/.webosTv

**Comment by tobihoby** [comment]
> The inputs file for the TV which you want to clear

inputsAvailable or inputsConfg delete?

**Comment by merdok** [comment]
First inputsAvailale

**Comment by beliy82** [comment]
![image](https://github.com/merdok/homebridge-webos-tv/assets/71979517/cd154929-c5c3-4b47-8c30-b1873d85362e)

i dont have any inputs...

**Comment by tobihoby** [comment]
I deleted the inputsAvailale, stopped the childbridge beforehand and then started it again. Unfortunately, the wrong names are still displayed. :(

**Comment by merdok** [comment]
You have to force close the home app and also try to delete the other file.

**Comment by beliy82** [comment]
> @beliy82 you do not use this plugin but the copy. If you have issues then you should go to the other plugin's github.

![image](https://github.com/merdok/homebridge-webos-tv/assets/71979517/8d4121d9-eb29-4867-9d8a-e43731180021)

No, im using this plugin

**Comment by ggroel** [comment]
A while ago I have it installed, but I remember that when I added to the home app I let you select that inputs wanted to appear (I do not find it now that I have it installed). Didn't you appear when you added it?

**Comment by merdok** [comment]
@beliy82 then you are looking in the wrong directory.

**Comment by tobihoby** [comment]
> You have to force close the home app and also try to delete the other file.

that works, thank you
