### ISSUE TITLE
how to config arcsound default 

### ISSUE THREAD

**Issue by derflerd** [merdok/homebridge-webos-tv#493]
i want to write in the config file
that the default sound source will be external_arc - hdmi arc

how to write this line?

i have a problem that the tv turn the tv don’t comment to the soundbar arc that connect.

**Comment by merdok** [comment]
Do you want to automatically switch to a certain sound output when the TV turns on? 
You would need to create yourself a switch for the desired sound output and create and automation for that.

**Comment by derflerd** [comment]
ok, so what is the comment for making a switch for change the sound output?

**Comment by merdok** [comment]
You can check that out in the README

**Comment by derflerd** [comment]
i don’t know how to write it on the configuration file.
can you help me?

**Comment by merdok** [comment]
Just have a look at the README, you even have an example there which covers your particular case…
