### ISSUE TITLE
"Eye Comfort Mode" setting not available

### ISSUE THREAD

**Issue by sunnyd24** [merdok/homebridge-webos-tv#494]
@merdok Thanks for this plugin, really good work and super useful.

Just one issue I have with this is that there is no control of the "Eye Comfort Mode" as can be found on my LG OLED65W9PLA.
This option would be really great as it can be enabled when required, especially in evenings to minimise blue light from TV.

**Any chance this could be added to the next release?**

**Comment by merdok** [comment]
I have never seen any references to that mode in the official api so I am not sure, maybe it would require some access of undocumented stuff but that would first require to find out if that is even possible. Is the eye comfort mode a part of the picture settings or where exactly is it located?

**Comment by sunnyd24** [comment]
@merdok

Interesting that you haven't come across it yet, I thought it would be a standard setting on most LG TV's by now, my TV is from 2019 in the signature range.

The "Eye Comfort Mode" is located in "Settings" -> "Picture settings" -> "Additional Settings" -> "Eye Comfort Mode" toggle switch. 
See images below:

<a href="https://ibb.co/NYnrnZR"><img src="https://i.ibb.co/VBpxp26/20230724-213918.jpg" alt="20230724-213918" border="0"></a>

<a href="https://ibb.co/kQ86pgP"><img src="https://i.ibb.co/pJzrgvk/20230724-213927.jpg" alt="20230724-213927" border="0"></a>

**Comment by merdok** [comment]
Oh, it is not directly a picture mode i guess, in that case that will be a guessing game to find that out as this is nor part of the official API. The best approach would be the add a cli command which allows to set the picture settings and then more or less it would be a try and error. I guess something in the direction like in the list here: https://github.com/merdok/homebridge-webos-tv/blob/master/lib/LgTvController.js#L1220

**Comment by mrbillpapas** [comment]
Would it be possible to implement    "colorTemperature": control? This on the TV there is a slider that allows color temp adjustments. Would be awesome! Also related to eye care (as far as I can tell it just adjusts the temperature to max warmth)
I saw it in the link above.

**Comment by merdok** [comment]
I guess that would be possible, but I am not sure if that indeed would be the same as the eye comfort mode.
