### ISSUE TITLE
Picture Mode switches are non-functional on LG C1

### ISSUE THREAD

**Issue by blimeylimey** [merdok/homebridge-webos-tv#497]
Running latest firmware on the C1, and the audio mode and audio output switches work perfect but the Picture Mode switches don’t work. Have tried creating a switch for every single one in the drop-down to see if any would appear during playback, but none worked. Are there any known limitations to this feature?

**Comment by merdok** [comment]
I did not test it with the latest firmware but last time I checked it was working fine on my C1. I cannot validate it right now as i do not have access to the tv. You would need to check if there are any errors appearing in the debug log when you try to use the switches and let me know if that is the case.

**Comment by blimeylimey** [comment]
I did some more testing and can clarify that they are working, though there’s no visual indication in HomeKit. By that, the issues are
- Enabling a picture mode switch in HomeKit triggers the change on the TV, but the HomeKit switch does not remain persistent like the Audio Mode switches do.
- Homekit doesn’t automatically replicate the current picture mode switches to ‘On’ as it does with Audio Modes. For example, I have Audio Mode Switches for Music and Cinematic. If I manually change these via my TV while Homekit is open, I can see the switches automatically turn themselves on/off as the modes change. Picture Modes don’t do this.
- I’ve enabled detailed logging and no log items appear when using the Picture Mode Switches

**Comment by merdok** [comment]
This is actually the expected behavior. Unfortunately there is no feedback from the tv about the current active picture mode hence those switches are stateless. They can switch to the desired picture mode but there is currently no way that they show which picture mode is active.

**Comment by blimeylimey** [comment]
Oh, that’s good to know. Apologies if that was anywhere in the documentation and I missed it.On 17 Sep 2023, at 16:11, Marcin ***@***.***> wrote:﻿
This is actually the expected behavior. Unfortunately there is no feedback from the tv about the current active picture mode hence those switches are stateless. They can switch to the desired picture mode but there is currently no way that they show which picture mode is active.
