### ISSUE TITLE
Don't see webos log in homebridge of channels

### ISSUE THREAD

**Issue by MartinVanVan** [merdok/homebridge-webos-tv#500]
I wanted to reconfigure my channel buttons. 
In the past a went through all the channels and could see the "channel changed" log and the corresponding id: 
`[08/10/2023, 18:05:03] [homebridge-webos-tv] [LG] Channel changed. Current channel: 7, ProSieben, channelId: 3_4_7_0_10008_53621_6`

Now i don't see any logs of apps or outputs being changed. Worked before and some old app buttons still work. 
Log is enabled.
"deepDebugLog": true,
            "silentLog": true

**Comment by merdok** [comment]
As you probably already noticed the silentLog property hides that log

**Comment by MartinVanVan** [comment]
Yeah sry 🙈
