### ISSUE TITLE
Feature request on more triggers

### ISSUE THREAD

**Issue by remlio** [merdok/homebridge-webos-tv#501]
It would be great if there were more triggers, I mean trigger of the active app, i.e. Youtube, TV etc. So we could see 2 triggers at once like "playing" and "youtube" instead of only one "playing (something from nowhere)"

**Comment by merdok** [comment]
For active app you can already use the `appButtons` the app button for the specified app will turn on when it becomes active, meaning you can do automations based on that. In general this also could be added to `triggers` but it would just be a duplication of an already existing functionallity.

**Comment by remlio** [comment]
thank you, I’ll try it
