### ISSUE TITLE
Channels as input

### ISSUE THREAD

**Issue by brun0san** [merdok/homebridge-webos-tv#504]
I have a custom setup with home assistant where I am able to customise the inputs to add tv channels to the spinner. This is used not only to switch channels without buttons, but also provides a way to show the active tv channel in the tv button, rather than just displaying “Live TV”.

Is there any way to do this?

**Comment by merdok** [comment]
You probably should have a look at `channelButtons`, which allow you to add switches for desired channels. Adding channels to the input spinner is not possible and does not even make sense, as when the Live Tv input is selected and you have a channel added there, which input do you select from the list? You cannot select two elements in the list at the same time.

**Comment by brun0san** [comment]
Thanks for your prompt reply, but as I said I do have this working with Home Assistant and was wondering whether this was possible with your implementation. I did play with the buttons, but configuring a bunch of buttons to control the channels is not what I was looking for, as a workaround I’ve configured the remote control to switch channels up/down which gives me the ability to change channels.

As mentioned in the initial post, it’d be nice to have the channels as an input as you could give you a quick indication of which channel the tv is switched on all from a single button, but if that is not possible and can’t be changed that’s ok.

Great job with the implementation, works very well and it’s very reliable.
