### ISSUE TITLE
Question: Is there a way to remove the following messages from the log?

### ISSUE THREAD

**Issue by Marco-Erlangen** [merdok/homebridge-webos-tv#508]
In this case, the following messages are displayed in the log:

[8.12.2023, 10:04:26] [webostv] [TV Schlafzimmer] TV setup finished, ready to control tv
[8.12.2023, 10:41:16] [webostv] [Fernseher] TV setup finished, ready to control tv

Is it possible to hide these messages? These are displayed even when silent log is enabled.

**Comment by merdok** [comment]
No it is not possible, why would you want to remove them? Those only popup once during startup and never ever again...

**Comment by Marco-Erlangen** [comment]
Ok, thanks for the feedback. I only turn on the logs if there is a problem, that was the background.

**Comment by merdok** [comment]
That log should not hurt as like already mentioned it only appears once during startup, also it lets you know that the plugin is ready and working correctly, so i guess it is good to have it all the time.
