### ISSUE TITLE
In the UI of the devices, the volume and mute are displayed, although not specified.

### ISSUE THREAD

**Issue by Marco-Erlangen** [merdok/homebridge-webos-tv#509]
I have added two TVs to my TV: "TV Schlafzimmer" and "Fernseher".
When I go into the UI in the devices, it shows me the mute for one TV and the volume for the other.
I didn't specify this in the configuration. Does anyone have any idea how I can get these devices removed from view?

"devices": [
                {
                    "name": "TV",
                    "ip": "192.168.2.120",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "silentLog": true,
                    "hideTvService": false,
                    volumeLimit: 15,
                    "volumeControl": "none",
                    "channelControl": false
                },
                {
                    "name": "TV bedroom",
                    "ip": "192.168.2.122",
                    "mac": "xx:xx:xx:xx:xx:xx",
                    "pollingInterval": 5,
                    "silentLog": true,
                    "hideTvService": false,
                    volumeLimit: 15,
                    "volumeControl": "none",
                    "channelControl": false
                }

![Unbenannt](https://github.com/merdok/homebridge-webos-tv/assets/108013443/b0d91e2b-a300-449f-ba68-7f11b1682d63)

**Comment by Marco-Erlangen** [comment]
Correctly, all devices in the Homebridge that are present via the plugins are displayed here. When I reinstalled the plugin, these two were not there. But only the two TV sets. I tried to adjust the configuration in the WebOS plugin in the settings. The settings then also appeared on the devices. But there is no way to get rid of them anymore.

**Comment by merdok** [comment]
The homebridge ui shows you additional accessories which HomeKit does not show or support. In that case you see the volume control accessory of the tv, which HomeKit does not support. On iOS devices on the other hand you can you use the volume up/down button when the remote control is open to control the volume, that obviously does not work in homebridge hence they show the volume accessory so that you are still able to control the volume of your tv through homebridge ui.

**Comment by Marco-Erlangen** [comment]
When I reinstalled the plugin, only the TVs were present on the devices in the Homebridge.
The strange thing is that the volume is displayed for one TV and only the mute switch for the other. If so, the same options should be displayed for all devices, right?
In general, when I installed the plugin and added the TVs, only the two TVs were available in the Homebridge itself and no other devices. You can set the other options in the advanced settings of the web plugin. I tried this once and since then I can no longer remove the devices from the Homebridge view.
