### ISSUE TITLE
Feature Request: Extend homebridge-webos-tv to support new mute and power buttons on command centre remote interface

### ISSUE THREAD

**Issue by karter16** [merdok/homebridge-webos-tv#513]
In the latest version of iOS the remote in Command Centre presents two additional, buttons in the top left (mute) and top right (power).

Is it possible to have homebridge-webos-tv extended so that these buttons can be used/mapped?

![IMG_8102](https://github.com/merdok/homebridge-webos-tv/assets/4284373/c6be5917-0043-452b-ba5c-6c214492b0f3)

**Comment by merdok** [comment]
Hmmm that is quite interesting, did not notice that... I will investigate if it is possible to hook up actions to those buttons.

**Comment by merdok** [comment]
Hi, did some investigations and as it currently seems, there is no way to map actions to those buttons yet...

**Comment by karter16** [comment]
Wow that was quick - thanks very much for checking! would you like me to close this out now given it can't be actioned?

**Comment by merdok** [comment]
Sure, I think that we can close it for now! I will keep my eye on that!
