### ISSUE TITLE
Cannot update the plugin anymore

### ISSUE THREAD

**Issue by luigi-lauro** [merdok/homebridge-webos-tv#517]
I tried update raspbian, npm and node (both 20 and 18.x) to no avail. Any support is appreciated!

Luigi

pi@homebridge:~ $ cat /home/pi/.npm/_logs/2024-01-19T08_00_41_780Z-debug-0.log 
0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.2.3
2 info using node@v18.19.0
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 6ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 6ms
6 timing config:load:builtin Completed in 6ms
7 timing config:load:cli Completed in 8ms
8 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
9 timing config:load:env Completed in 2ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/pi/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 3ms
16 timing config:load Completed in 31ms
17 timing npm:load:configload Completed in 31ms
18 timing config:load:flatten Completed in 9ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install homebridge-webos-tv@2.4.3
22 verbose argv "install" "--global" "homebridge-webos-tv@2.4.3"
23 timing npm:load:setTitle Completed in 3ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/pi/.npm/_logs/2024-01-19T08_00_41_780Z-
26 verbose logfile /home/pi/.npm/_logs/2024-01-19T08_00_41_780Z-debug-0.log
27 timing npm:load:logFile Completed in 27ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 120ms
31 timing config:load:flatten Completed in 3ms
32 timing arborist:ctor Completed in 3ms
33 silly logfile start cleaning logs, removing 3 files
34 timing idealTree:init Completed in 18ms
35 timing idealTree:userRequests Completed in 11ms
36 silly idealTree buildDeps
37 silly fetch manifest homebridge-webos-tv@2.4.3
38 silly logfile done cleaning log files
39 http fetch GET 200 https://registry.npmjs.org/homebridge-webos-tv 339ms (cache revalidated)
40 silly placeDep ROOT homebridge-webos-tv@2.4.3 OK for:  want: 2.4.3
41 silly fetch manifest persist-path@^1.0.2
42 silly fetch manifest websocket@^1.0.32
43 silly fetch manifest mkdirp@^1.0.4
44 silly fetch manifest tcp-ping@^0.1.1
45 silly fetch manifest wake_on_lan@^1.0.0
46 silly fetch manifest chalk@^5.0.1
47 silly fetch manifest yargs@^17.6.0
48 silly fetch manifest env-paths@^3.0.0
49 http fetch GET 200 https://registry.npmjs.org/mkdirp 135ms (cache revalidated)
50 http fetch GET 200 https://registry.npmjs.org/env-paths 209ms (cache revalidated)
51 http fetch GET 200 https://registry.npmjs.org/websocket 239ms (cache revalidated)
52 http fetch GET 200 https://registry.npmjs.org/wake_on_lan 243ms (cache revalidated)
53 http fetch GET 200 https://registry.npmjs.org/chalk 246ms (cache revalidated)
54 http fetch GET 200 https://registry.npmjs.org/yargs 263ms (cache revalidated)
55 http fetch GET 200 https://registry.npmjs.org/tcp-ping 284ms (cache revalidated)
56 http fetch GET 200 https://registry.npmjs.org/persist-path 395ms (cache revalidated)
57 timing idealTree:#root Completed in 774ms
58 silly placeDep node_modules/homebridge-webos-tv chalk@5.3.0 OK for: homebridge-webos-tv@2.4.3 want: ^5.0.1
59 silly placeDep node_modules/homebridge-webos-tv env-paths@3.0.0 OK for: homebridge-webos-tv@2.4.3 want: ^3.0.0
60 silly placeDep node_modules/homebridge-webos-tv mkdirp@1.0.4 OK for: homebridge-webos-tv@2.4.3 want: ^1.0.4
61 silly placeDep node_modules/homebridge-webos-tv persist-path@1.0.2 OK for: homebridge-webos-tv@2.4.3 want: ^1.0.2
62 silly placeDep node_modules/homebridge-webos-tv tcp-ping@0.1.1 OK for: homebridge-webos-tv@2.4.3 want: ^0.1.1
63 silly placeDep node_modules/homebridge-webos-tv wake_on_lan@1.0.0 OK for: homebridge-webos-tv@2.4.3 want: ^1.0.0
64 silly fetch manifest minimist@^1.2.0
65 silly placeDep node_modules/homebridge-webos-tv websocket@1.0.34 OK for: homebridge-webos-tv@2.4.3 want: ^1.0.32
66 silly fetch manifest bufferutil@^4.0.1
67 silly fetch manifest debug@^2.2.0
68 silly fetch manifest es5-ext@^0.10.50
69 silly fetch manifest typedarray-to-buffer@^3.1.5
70 silly fetch manifest utf-8-validate@^5.0.2
71 silly fetch manifest yaeti@^0.0.6
72 silly placeDep node_modules/homebridge-webos-tv yargs@17.7.2 OK for: homebridge-webos-tv@2.4.3 want: ^17.6.0
73 silly fetch manifest cliui@^8.0.1
74 silly fetch manifest escalade@^3.1.1
75 silly fetch manifest get-caller-file@^2.0.5
76 silly fetch manifest require-directory@^2.1.1
77 silly fetch manifest string-width@^4.2.3
78 silly fetch manifest y18n@^5.0.5
79 silly fetch manifest yargs-parser@^21.1.1
80 http fetch GET 200 https://registry.npmjs.org/minimist 273ms (cache revalidated)
81 http fetch GET 200 https://registry.npmjs.org/typedarray-to-buffer 263ms (cache revalidated)
82 http fetch GET 200 https://registry.npmjs.org/es5-ext 269ms (cache revalidated)
83 http fetch GET 200 https://registry.npmjs.org/bufferutil 278ms (cache revalidated)
84 http fetch GET 200 https://registry.npmjs.org/utf-8-validate 271ms (cache revalidated)
85 http fetch GET 200 https://registry.npmjs.org/debug 287ms (cache revalidated)
86 http fetch GET 200 https://registry.npmjs.org/escalade 345ms (cache revalidated)
87 http fetch GET 200 https://registry.npmjs.org/yargs-parser 360ms (cache revalidated)
88 http fetch GET 200 https://registry.npmjs.org/require-directory 388ms (cache revalidated)
89 http fetch GET 200 https://registry.npmjs.org/cliui 396ms (cache revalidated)
90 http fetch GET 200 https://registry.npmjs.org/y18n 391ms (cache revalidated)
91 http fetch GET 200 https://registry.npmjs.org/get-caller-file 399ms (cache revalidated)
92 http fetch GET 200 https://registry.npmjs.org/string-width 410ms (cache revalidated)
93 http fetch GET 200 https://registry.npmjs.org/yaeti 1084ms (cache revalidated)
94 timing idealTree:node_modules/homebridge-webos-tv Completed in 1152ms
95 timing idealTree:node_modules/homebridge-webos-tv/node_modules/chalk Completed in 1ms
96 timing idealTree:node_modules/homebridge-webos-tv/node_modules/env-paths Completed in 0ms
97 timing idealTree:node_modules/homebridge-webos-tv/node_modules/mkdirp Completed in 0ms
98 timing idealTree:node_modules/homebridge-webos-tv/node_modules/persist-path Completed in 0ms
99 timing idealTree:node_modules/homebridge-webos-tv/node_modules/tcp-ping Completed in 0ms
100 silly placeDep node_modules/homebridge-webos-tv minimist@1.2.8 OK for: wake_on_lan@1.0.0 want: ^1.2.0
101 timing idealTree:node_modules/homebridge-webos-tv/node_modules/wake_on_lan Completed in 12ms
102 timing idealTree:node_modules/homebridge-webos-tv/node_modules/minimist Completed in 0ms
103 silly placeDep node_modules/homebridge-webos-tv bufferutil@4.0.8 OK for: websocket@1.0.34 want: ^4.0.1
104 silly fetch manifest node-gyp-build@^4.3.0
105 silly placeDep node_modules/homebridge-webos-tv debug@2.6.9 OK for: websocket@1.0.34 want: ^2.2.0
106 silly fetch manifest ms@2.0.0
107 silly placeDep node_modules/homebridge-webos-tv es5-ext@0.10.62 OK for: websocket@1.0.34 want: ^0.10.50
108 silly fetch manifest es6-iterator@^2.0.3
109 silly fetch manifest es6-symbol@^3.1.3
110 silly fetch manifest next-tick@^1.1.0
111 silly placeDep node_modules/homebridge-webos-tv typedarray-to-buffer@3.1.5 OK for: websocket@1.0.34 want: ^3.1.5
112 silly fetch manifest is-typedarray@^1.0.0
113 silly placeDep node_modules/homebridge-webos-tv utf-8-validate@5.0.10 OK for: websocket@1.0.34 want: ^5.0.2
114 silly placeDep node_modules/homebridge-webos-tv yaeti@0.0.6 OK for: websocket@1.0.34 want: ^0.0.6
115 http fetch GET 200 https://registry.npmjs.org/ms 128ms (cache revalidated)
116 http fetch GET 200 https://registry.npmjs.org/es6-symbol 116ms (cache revalidated)
117 http fetch GET 200 https://registry.npmjs.org/next-tick 120ms (cache revalidated)
118 http fetch GET 200 https://registry.npmjs.org/is-typedarray 109ms (cache revalidated)
119 http fetch GET 200 https://registry.npmjs.org/es6-iterator 146ms (cache revalidated)
120 http fetch GET 200 https://registry.npmjs.org/node-gyp-build 326ms (cache revalidated)
121 timing idealTree:node_modules/homebridge-webos-tv/node_modules/websocket Completed in 362ms
122 silly placeDep node_modules/homebridge-webos-tv node-gyp-build@4.8.0 OK for: bufferutil@4.0.8 want: ^4.3.0
123 timing idealTree:node_modules/homebridge-webos-tv/node_modules/bufferutil Completed in 7ms
124 silly placeDep node_modules/homebridge-webos-tv ms@2.0.0 OK for: debug@2.6.9 want: 2.0.0
125 timing idealTree:node_modules/homebridge-webos-tv/node_modules/debug Completed in 4ms
126 silly placeDep node_modules/homebridge-webos-tv es6-iterator@2.0.3 OK for: es5-ext@0.10.62 want: ^2.0.3
127 silly fetch manifest d@1
128 silly fetch manifest es6-symbol@^3.1.1
129 silly placeDep node_modules/homebridge-webos-tv es6-symbol@3.1.3 OK for: es5-ext@0.10.62 want: ^3.1.3
130 silly fetch manifest d@^1.0.1
131 silly fetch manifest ext@^1.1.2
132 silly placeDep node_modules/homebridge-webos-tv next-tick@1.1.0 OK for: es5-ext@0.10.62 want: ^1.1.0
133 http fetch GET 200 https://registry.npmjs.org/ext 96ms (cache revalidated)
134 http fetch GET 200 https://registry.npmjs.org/d 804ms (cache revalidated)
135 http fetch GET 200 https://registry.npmjs.org/d 816ms (cache revalidated)
136 timing idealTree:node_modules/homebridge-webos-tv/node_modules/es5-ext Completed in 830ms
137 silly placeDep node_modules/homebridge-webos-tv d@1.0.1 OK for: es6-iterator@2.0.3 want: 1
138 silly fetch manifest type@^1.0.1
139 http fetch GET 200 https://registry.npmjs.org/type 62ms (cache revalidated)
140 timing idealTree:node_modules/homebridge-webos-tv/node_modules/es6-iterator Completed in 82ms
141 silly placeDep node_modules/homebridge-webos-tv type@1.2.0 OK for: d@1.0.1 want: ^1.0.1
142 timing idealTree:node_modules/homebridge-webos-tv/node_modules/d Completed in 10ms
143 silly placeDep node_modules/homebridge-webos-tv ext@1.7.0 OK for: es6-symbol@3.1.3 want: ^1.1.2
144 silly fetch manifest type@^2.7.2
145 timing idealTree:node_modules/homebridge-webos-tv/node_modules/es6-symbol Completed in 14ms
146 silly placeDep node_modules/homebridge-webos-tv/node_modules/ext type@2.7.2 OK for: ext@1.7.0 want: ^2.7.2
147 timing idealTree:node_modules/homebridge-webos-tv/node_modules/ext Completed in 11ms
148 timing idealTree:node_modules/homebridge-webos-tv/node_modules/ms Completed in 0ms
149 timing idealTree:node_modules/homebridge-webos-tv/node_modules/next-tick Completed in 0ms
150 timing idealTree:node_modules/homebridge-webos-tv/node_modules/node-gyp-build Completed in 0ms
151 timing idealTree:node_modules/homebridge-webos-tv/node_modules/type Completed in 0ms
152 silly placeDep node_modules/homebridge-webos-tv is-typedarray@1.0.0 OK for: typedarray-to-buffer@3.1.5 want: ^1.0.0
153 timing idealTree:node_modules/homebridge-webos-tv/node_modules/typedarray-to-buffer Completed in 6ms
154 timing idealTree:node_modules/homebridge-webos-tv/node_modules/is-typedarray Completed in 0ms
155 timing idealTree:node_modules/homebridge-webos-tv/node_modules/utf-8-validate Completed in 0ms
156 timing idealTree:node_modules/homebridge-webos-tv/node_modules/yaeti Completed in 0ms
157 silly placeDep node_modules/homebridge-webos-tv cliui@8.0.1 OK for: yargs@17.7.2 want: ^8.0.1
158 silly fetch manifest string-width@^4.2.0
159 silly fetch manifest strip-ansi@^6.0.1
160 silly fetch manifest wrap-ansi@^7.0.0
161 silly placeDep node_modules/homebridge-webos-tv escalade@3.1.1 OK for: yargs@17.7.2 want: ^3.1.1
162 silly placeDep node_modules/homebridge-webos-tv get-caller-file@2.0.5 OK for: yargs@17.7.2 want: ^2.0.5
163 silly placeDep node_modules/homebridge-webos-tv require-directory@2.1.1 OK for: yargs@17.7.2 want: ^2.1.1
164 silly placeDep node_modules/homebridge-webos-tv string-width@4.2.3 OK for: yargs@17.7.2 want: ^4.2.3
165 silly fetch manifest emoji-regex@^8.0.0
166 silly fetch manifest is-fullwidth-code-point@^3.0.0
167 silly placeDep node_modules/homebridge-webos-tv y18n@5.0.8 OK for: yargs@17.7.2 want: ^5.0.5
168 silly placeDep node_modules/homebridge-webos-tv yargs-parser@21.1.1 OK for: yargs@17.7.2 want: ^21.1.1
169 http fetch GET 200 https://registry.npmjs.org/strip-ansi 125ms (cache revalidated)
170 http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point 99ms (cache revalidated)
171 http fetch GET 200 https://registry.npmjs.org/wrap-ansi 127ms (cache revalidated)
172 http fetch GET 200 https://registry.npmjs.org/emoji-regex 110ms (cache revalidated)
173 timing idealTree:node_modules/homebridge-webos-tv/node_modules/yargs Completed in 161ms
174 silly placeDep node_modules/homebridge-webos-tv strip-ansi@6.0.1 OK for: cliui@8.0.1 want: ^6.0.1
175 silly fetch manifest ansi-regex@^5.0.1
176 silly placeDep node_modules/homebridge-webos-tv wrap-ansi@7.0.0 OK for: cliui@8.0.1 want: ^7.0.0
177 silly fetch manifest ansi-styles@^4.0.0
178 http fetch GET 200 https://registry.npmjs.org/ansi-regex 75ms (cache revalidated)
179 http fetch GET 200 https://registry.npmjs.org/ansi-styles 70ms (cache revalidated)
180 timing idealTree:node_modules/homebridge-webos-tv/node_modules/cliui Completed in 94ms
181 timing idealTree:node_modules/homebridge-webos-tv/node_modules/escalade Completed in 0ms
182 timing idealTree:node_modules/homebridge-webos-tv/node_modules/get-caller-file Completed in 0ms
183 timing idealTree:node_modules/homebridge-webos-tv/node_modules/require-directory Completed in 0ms
184 silly placeDep node_modules/homebridge-webos-tv emoji-regex@8.0.0 OK for: string-width@4.2.3 want: ^8.0.0
185 silly placeDep node_modules/homebridge-webos-tv is-fullwidth-code-point@3.0.0 OK for: string-width@4.2.3 want: ^3.0.0
186 timing idealTree:node_modules/homebridge-webos-tv/node_modules/string-width Completed in 11ms
187 timing idealTree:node_modules/homebridge-webos-tv/node_modules/emoji-regex Completed in 0ms
188 timing idealTree:node_modules/homebridge-webos-tv/node_modules/is-fullwidth-code-point Completed in 0ms
189 silly placeDep node_modules/homebridge-webos-tv ansi-regex@5.0.1 OK for: strip-ansi@6.0.1 want: ^5.0.1
190 timing idealTree:node_modules/homebridge-webos-tv/node_modules/strip-ansi Completed in 5ms
191 timing idealTree:node_modules/homebridge-webos-tv/node_modules/ansi-regex Completed in 0ms
192 silly placeDep node_modules/homebridge-webos-tv ansi-styles@4.3.0 OK for: wrap-ansi@7.0.0 want: ^4.0.0
193 silly fetch manifest color-convert@^2.0.1
194 http fetch GET 200 https://registry.npmjs.org/color-convert 170ms (cache revalidated)
195 timing idealTree:node_modules/homebridge-webos-tv/node_modules/wrap-ansi Completed in 181ms
196 silly placeDep node_modules/homebridge-webos-tv color-convert@2.0.1 OK for: ansi-styles@4.3.0 want: ^2.0.1
197 silly fetch manifest color-name@~1.1.4
198 http fetch GET 200 https://registry.npmjs.org/color-name 62ms (cache revalidated)
199 timing idealTree:node_modules/homebridge-webos-tv/node_modules/ansi-styles Completed in 72ms
200 silly placeDep node_modules/homebridge-webos-tv color-name@1.1.4 OK for: color-convert@2.0.1 want: ~1.1.4
201 timing idealTree:node_modules/homebridge-webos-tv/node_modules/color-convert Completed in 5ms
202 timing idealTree:node_modules/homebridge-webos-tv/node_modules/color-name Completed in 0ms
203 timing idealTree:node_modules/homebridge-webos-tv/node_modules/y18n Completed in 1ms
204 timing idealTree:node_modules/homebridge-webos-tv/node_modules/yargs-parser Completed in 0ms
205 timing idealTree:node_modules/homebridge-webos-tv/node_modules/ext/node_modules/type Completed in 0ms
206 timing idealTree:buildDeps Completed in 3810ms
207 timing idealTree:fixDepFlags Completed in 4ms
208 timing idealTree Completed in 3849ms
209 timing reify:loadTrees Completed in 3943ms
210 timing reify:diffTrees Completed in 15ms
211 silly reify mark retired [ '/usr/lib/node_modules/homebridge-webos-tv', '/usr/bin/webostv' ]
212 silly reify moves {
212 silly reify   '/usr/lib/node_modules/homebridge-webos-tv': '/usr/lib/node_modules/.homebridge-webos-tv-DqpOBIqe',
212 silly reify   '/usr/bin/webostv': '/usr/bin/.webostv-oGxW2OFU'
212 silly reify }
213 timing reify:retireShallow Completed in 9ms
214 timing reify:createSparse Completed in 15ms
215 timing reify:loadBundles Completed in 0ms
216 http fetch GET 200 https://registry.npmjs.org/type/-/type-1.2.0.tgz 832ms (cache revalidated)
217 http fetch GET 200 https://registry.npmjs.org/homebridge-webos-tv/-/homebridge-webos-tv-2.4.3.tgz 862ms (cache revalidated)
218 http fetch GET 200 https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz 837ms (cache revalidated)
219 http fetch GET 200 https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz 833ms (cache revalidated)
220 http fetch GET 200 https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz 844ms (cache revalidated)
221 http fetch GET 200 https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz 852ms (cache revalidated)
222 http fetch GET 200 https://registry.npmjs.org/websocket/-/websocket-1.0.34.tgz 846ms (cache revalidated)
223 http fetch GET 200 https://registry.npmjs.org/next-tick/-/next-tick-1.1.0.tgz 854ms (cache revalidated)
224 http fetch GET 200 https://registry.npmjs.org/tcp-ping/-/tcp-ping-0.1.1.tgz 843ms (cache revalidated)
225 http fetch GET 200 https://registry.npmjs.org/wake_on_lan/-/wake_on_lan-1.0.0.tgz 855ms (cache revalidated)
226 http fetch GET 200 https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz 862ms (cache revalidated)
227 http fetch GET 200 https://registry.npmjs.org/utf-8-validate/-/utf-8-validate-5.0.10.tgz 884ms (cache revalidated)
228 http fetch GET 200 https://registry.npmjs.org/typedarray-to-buffer/-/typedarray-to-buffer-3.1.5.tgz 883ms (cache revalidated)
229 http fetch GET 200 https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz 915ms (cache revalidated)
230 http fetch GET 200 https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz 878ms (cache revalidated)
231 http fetch GET 200 https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.8.tgz 884ms (cache revalidated)
232 http fetch GET 200 https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz 889ms (cache revalidated)
233 http fetch GET 200 https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz 1019ms (cache revalidated)
234 http fetch GET 200 https://registry.npmjs.org/persist-path/-/persist-path-1.0.2.tgz 1013ms (cache revalidated)
235 http fetch GET 200 https://registry.npmjs.org/ext/-/ext-1.7.0.tgz 1025ms (cache revalidated)
236 http fetch GET 200 https://registry.npmjs.org/yargs/-/yargs-17.7.2.tgz 1095ms (cache revalidated)
237 http fetch GET 200 https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.8.0.tgz 1033ms (cache revalidated)
238 http fetch GET 200 https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.62.tgz 1069ms (cache revalidated)
239 http fetch GET 200 https://registry.npmjs.org/mkdirp/-/mkdirp-1.0.4.tgz 1080ms (cache revalidated)
240 http fetch GET 200 https://registry.npmjs.org/cliui/-/cliui-8.0.1.tgz 1063ms (cache revalidated)
241 http fetch GET 200 https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.3.tgz 1084ms (cache revalidated)
242 http fetch GET 200 https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz 1083ms (cache revalidated)
243 http fetch GET 200 https://registry.npmjs.org/type/-/type-2.7.2.tgz 1155ms (cache revalidated)
244 http fetch GET 200 https://registry.npmjs.org/env-paths/-/env-paths-3.0.0.tgz 1173ms (cache revalidated)
245 http fetch GET 200 https://registry.npmjs.org/debug/-/debug-2.6.9.tgz 1158ms (cache revalidated)
246 http fetch GET 200 https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz 1218ms (cache revalidated)
247 http fetch GET 200 https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz 1297ms (cache revalidated)
248 http fetch GET 200 https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz 1189ms (cache revalidated)
249 http fetch GET 200 https://registry.npmjs.org/ms/-/ms-2.0.0.tgz 1223ms (cache revalidated)
250 http fetch GET 200 https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.3.tgz 1246ms (cache revalidated)
251 http fetch GET 200 https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.1.1.tgz 1315ms (cache revalidated)
252 http fetch GET 200 https://registry.npmjs.org/yaeti/-/yaeti-0.0.6.tgz 1308ms (cache revalidated)
253 http fetch GET 200 https://registry.npmjs.org/chalk/-/chalk-5.3.0.tgz 1239ms (cache revalidated)
254 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/tcp-ping Completed in 1456ms
255 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/wrap-ansi Completed in 1472ms
256 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/strip-ansi Completed in 1474ms
257 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/string-width Completed in 1474ms
258 http fetch GET 200 https://registry.npmjs.org/d/-/d-1.0.1.tgz 1269ms (cache revalidated)
259 http fetch GET 200 https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz 1273ms (cache revalidated)
260 http fetch GET 200 https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz 1269ms (cache revalidated)
261 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/get-caller-file Completed in 1509ms
262 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/wake_on_lan Completed in 1512ms
263 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/require-directory Completed in 1539ms
264 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ansi-regex Completed in 1534ms
265 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/is-typedarray Completed in 1538ms
266 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/typedarray-to-buffer Completed in 1548ms
267 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/is-fullwidth-code-point Completed in 1554ms
268 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/persist-path Completed in 1570ms
269 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ms Completed in 1574ms
270 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/env-paths Completed in 1583ms
271 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/next-tick Completed in 1595ms
272 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/node-gyp-build Completed in 1594ms
273 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ansi-styles Completed in 1593ms
274 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/color-name Completed in 1598ms
275 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/escalade Completed in 1647ms
276 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/emoji-regex Completed in 1647ms
277 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/color-convert Completed in 1651ms
278 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/cliui Completed in 1654ms
279 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/mkdirp Completed in 1662ms
280 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/yaeti Completed in 1673ms
281 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/y18n Completed in 1679ms
282 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/d Completed in 1696ms
283 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/debug Completed in 1724ms
284 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/yargs-parser Completed in 1753ms
285 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/chalk Completed in 1746ms
286 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/minimist Completed in 1755ms
287 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/es6-iterator Completed in 1784ms
288 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/es6-symbol Completed in 1796ms
289 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/websocket Completed in 1806ms
290 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/utf-8-validate Completed in 1831ms
291 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/bufferutil Completed in 1833ms
292 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ext Completed in 1913ms
293 timing reifyNode:node_modules/homebridge-webos-tv Completed in 1922ms
294 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/yargs Completed in 1980ms
295 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/type Completed in 2094ms
296 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/ext/node_modules/type Completed in 2118ms
297 timing reifyNode:node_modules/homebridge-webos-tv/node_modules/es5-ext Completed in 2396ms
298 timing reify:unpack Completed in 2405ms
299 timing reify:unretire Completed in 1ms
300 timing build:queue Completed in 8ms
301 timing build:link:node_modules/homebridge-webos-tv/node_modules/mkdirp Completed in 7ms
302 timing build:link:node_modules/homebridge-webos-tv Completed in 10ms
303 timing build:link:node_modules/homebridge-webos-tv/node_modules/node-gyp-build Completed in 8ms
304 timing build:link:node_modules/homebridge-webos-tv/node_modules/wake_on_lan Completed in 7ms
305 timing build:link Completed in 10ms
306 info run bufferutil@4.0.8 install node_modules/homebridge-webos-tv/node_modules/bufferutil node-gyp-build
307 info run bufferutil@4.0.8 install { code: 1, signal: null }
308 timing reify:rollback:createSparse Completed in 314ms
309 timing reify:rollback:retireShallow Completed in 1ms
310 timing command:install Completed in 10161ms
311 verbose stack Error: command failed
311 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
311 verbose stack     at ChildProcess.emit (node:events:517:28)
311 verbose stack     at maybeClose (node:internal/child_process:1098:16)
311 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
312 verbose pkgid bufferutil@4.0.8
313 verbose cwd /usr
314 verbose Linux 6.1.0-rpi7-rpi-v7l
315 verbose node v18.19.0
316 verbose npm  v10.2.3
317 error code 1
318 error path /usr/lib/node_modules/homebridge-webos-tv/node_modules/bufferutil
319 error command failed
320 error command sh -c node-gyp-build
321 verbose exit 1
322 timing npm Completed in 11224ms
323 verbose unfinished npm timer reify 1705651242842
324 verbose unfinished npm timer reify:build 1705651249251
325 verbose unfinished npm timer build 1705651249252
326 verbose unfinished npm timer build:deps 1705651249252
327 verbose unfinished npm timer build:run:install 1705651249272
328 verbose unfinished npm timer build:run:install:node_modules/homebridge-webos-tv/node_modules/bufferutil 1705651249273
329 verbose code 1
330 error A complete log of this run can be found in: /home/pi/.npm/_logs/2024-01-19T08_00_41_780Z-debug-0.log

**Comment by merdok** [comment]
Seems you might have the same issues as here, please check the solution there

https://github.com/merdok/homebridge-webos-tv/issues/512#issuecomment-1899898042

**Comment by luigi-lauro** [comment]
Confirmed, thank you very much, it was that!
