### ISSUE TITLE
Turn TV on to a specific input?

### ISSUE THREAD

**Issue by DataFran** [merdok/homebridge-webos-tv#519]
I’m trying to set up an automation that turns the TV on and selects the AppleTV input whenever I airplay something to the AppleTV, I have it working now where it turns the TV on, waits 20 seconds, then changes the input (I couldn’t get it to work with any shorter window), is there a way to have the TV turn on and select a specific input in the same command?

**Comment by merdok** [comment]
You can do an appButton for your specific input. When you turn on the created switch and the tv is off, it will automatically turn on and switch to the specified app or in your case input (an input is also just app). I guess that is what you are looking for.

**Comment by DataFran** [comment]
This absolutely did the trick, don't know why I couldn't get this yesterday, but I'll chalk it up to a day full of learning.

**Comment by merdok** [comment]
Good to hear that it works👍
