### ISSUE TITLE
How to trigger automation when input changes

### ISSUE THREAD

**Issue by czbird77** [merdok/homebridge-webos-tv#520]
Hi, this is more of a question than a bug, I guess.
I'm unable to trigger new automation with additional switches I've added for inputs, channels, etc.
The only accessory that I'm offered in Home app when creating new automation is TV on / TV off.
Is there a way to trigger automation based on the additional switches the plugin provides?
All the switches work, they just are not offered to trigger automation.
Am I doing something wrong or is it supposed to be like this?
Thanks!

**Comment by merdok** [comment]
You have to create an appButton for every input which you need and then you can create some automations based on whether the switch is on or off.

**Comment by czbird77** [comment]
Yeah, got it. It now allows me to start automations with the appButtons. 
Don't know why they were not offered in the Home app yesterday,
Thanks!
