### ISSUE TITLE
Hide TV service

### ISSUE THREAD

**Issue by MrAnnoymous** [merdok/homebridge-webos-tv#522]
hi if my tv already already supports native HomeKit integration, if i turn on hide tv service will it solve the none respond issue ?

**Comment by merdok** [comment]
It will just hide the tv accessory created by this plugin, you are still required to provide all required info for the plugin to function properly.

**Comment by MrAnnoymous** [comment]
> It will just hide the tv accessory created by this plugin, you are still required to provide all required info for the plugin to function properly.

i just tried and my tv homekit still showing none respond, i think will just stick with your plug in, because the tv homekit will sync and update my hdmi device name

**Comment by merdok** [comment]
Yeah, my plugin is superior over the native tv HomeKit integration so you can use that instead.
