### ISSUE TITLE
Q: Long delays before websocket is open

### ISSUE THREAD

**Issue by aboulfad** [merdok/homebridge-webos-tv#53]
Hi, I don't think this is a bug per say related to this project but curious if anyone is observing very long delays before the LG TV websocket is available for connection?

I have done many tests without using this framework to characterize timing and this is roughly what I found out, issuing *nix commands from my old rpi (which will run homebridge). Ive also done the equivalent using the core LGTV2 project that this homebridge extension uses, and it connects roughly after that long delay.

1. Issue wakeonlan command, T=0, issue a periodic netcat cmd to TV_IP:3000
2. TV powers T=2-3 s after wake command (you hear the relay switch click)
3. TV displays picture (livetv) at T=5-6s
4. Netcat connects to [TV_IP:3000] at T=14-15s 

LG TV: OLED65E7/801.11ac connection, rpi/Enet

Thanks for an insight/info !

**Comment by merdok** [comment]
Hi,

LG has pretty slow channel changing times, somehow they never improved that over the years, for this reason i think there is a big delay between turning on the tv till the picture is there. Even on my 2018 OLED TV this is still slow.

As of the powering on, my TV powers on (click sound from TV) instantly after i press the Homekit power on button. There is no noticeable delay, so maybe this delay is related somehow to your network?

**Comment by aboulfad** [comment]
I think it’s the combination of the old rpi I am using and maybe the network, but my observation was regarding how soon can the LG accept a **web socket connection and a request** after it’s ON or pic is displayed. (If I use wakeonlan from my iMac, the TV powers on very quickly)

If you don’t mind, can you try with your plugin the following:
- power on the LG, then 
- switch to another input, and check the delay!

What I am trying to do, is to create a plugin that will mimic the Harmony One activity concept (turn on TV, choose input, turn on AVR, turn on player,...). Thank you.

**Comment by merdok** [comment]
This all depends on the environment (network, hardware and also some randomness is involved).  So you cannot say that for each TV it takes 10 seconds. It will vary from user to user.

**Comment by aboulfad** [comment]
I never said that for each TV it takes long, I was asking for additional input so I can better understand the variables. 

I will close this request for info and maybe follow up in the base lgtv2 project that your plugin uses.
