### ISSUE TITLE
Are these features meant to work via Siri / Homepod 

### ISSUE THREAD

**Issue by noxaeternus666** [merdok/homebridge-webos-tv#531]
Quick question as I can't find anything concrete on this. I have installed this and all is working on both of my LG TVs. I can turn the devices on & off. 
Homebridge can see volume controls and channel up / down, mute etc. But I can't seem to tell Siri to apply these settings via voice. Like I want to be able to "Pause Living Room TV" or "Next Channel or Channel Up on Living Room TV". Doesn't seem to work. 
Can someone point me int he right direction on how to get this fixed if it is indeed possible. 
Thanks

**Comment by merdok** [comment]
You have to create the switches for those features (with configuration) and tell Siri to turn them on by the switch name. As far as i am aware Siri is not able to control a TV they way you would expect it to.

**Comment by noxaeternus666** [comment]
Thanks for the reply. Yes, "Channel Up On" seems to work, just doesn't feel natural. I wonder if there is a way to change it.

**Comment by merdok** [comment]
Unfortunately not and the reason is as I already mentioned because Siri cannot control TV's officially.
