### ISSUE TITLE
TV Volume Slider Doesn't Work

### ISSUE THREAD

**Issue by jmasarweh** [merdok/homebridge-webos-tv#535]
The Volume slidebar doesn't work (no effect on actual volume). It only reports the TV volume when using the volume up or down switches in homekit. But when using the physical LG TV remote, it doesn't update. There is also no 0% state, after 1% the slider goes to 100%.

Reproduction 1:
-Slide volume slidebar up or down in Apple Home.
-No volume changes on TV.
Expected behaviour:  Volume changes on TV accordingly.

Reproduction 2:
-Change TV volume using TV remote.
-No volume percentage changes in Apple Home Volume slidebar.
Expected behaviour:  Volume slidebar % changes in AH accordingly.

Reproduction 3:
-Change TV volume using Apple Home Volume Down button all the way to 1%.
-Press Volume Down one more time.
-Volume slidebar goes to 100%.
(However, sliding the slidebar to 0% mute the TV as expected).
Expected behaviour:  Volume slidebar should state off or 0% .

Plugin: v 2.4.4
Homebridge: v 1.8.2
Node.js: v 20.14.0
OS: Linux: Debian GNU/Linux Bookworm (12)
TV: LG G3

Config:

`{
    "devices": [
        {
            "name": "My LG TV",
            "ip": "192.168.50.55",
            "mac": "AD:B9:88:2B:ED:D1",
            "pollingInterval": 5,
            "silentLog": true,
            "volumeLimit": 100,
            "volumeControl": "both",
            "channelControl": false,
            "screenControl": true,
            "screenSaverControl": true,
            "backlightControl": true,
            "contrastControl": true,
            "notificationButtons": [
                {
                    "message": "🚨 Outdoor Motion Detected!",
                    "name": "TV Message"
                }
            ],
            "pictureModeButtons": [
                {
                    "pictureMode": "vivid",
                    "name": "  Vivid Mode"
                },
                {
                    "pictureMode": "filmMaker",
                    "name": "Filmmaker Mode"
                }
            ]
        }
    ],
    "platform": "webostv"
}`

**Comment by merdok** [comment]
Can it be that you have an external
Audio receiver which you use, possibly using ARC? If that is the case, then it is a limitation of the official LG api.

**Comment by jmasarweh** [comment]
Hi - you're right, and I missed the note you also had in the config. Thanks!
