### ISSUE TITLE
OLED turning on/off

### ISSUE THREAD

**Issue by DanielWeeber** [merdok/homebridge-webos-tv#54]
Like mentioned in #50:

If you turn off the OLED tv it does not get offline (layer 3 still available, therefore script still connected) right away from time to time. One should be able to turn on and off the TV at all times.

My guess is, currently untested, that we are safe to remove the connected check for turning on the TV. WoL is Layer 2 based - it does not depend on a disconnected/connected state to the API. Even when you turn on the TV while it is turned on it should not change anything.

**Comment by merdok** [comment]
Thanks! 
The TV status should be keep track of, so the connected state is important. The issue lies probably how the connected state is tracked. I have some ideas how to improve it but it is hard to debug since this is only an issue when the refresh is running on the TV, which only happens every 4 hours for about 10 minutes...

**Comment by DanielWeeber** [comment]
I just tried everything again:

#50 is not solved for me. I turned the TV off via Siri. Turned it off again. "Some devices are not responding".
(Ping went offline and in the logs the module said it is disconnected)
After that I tried to "Hey Siri turn the TV in the living room on". It said "Okay" but the TV did not turn on and the Icon in the Home App changed to "Not Responding" with the exclamation mark in the upper right corner.

**Comment by merdok** [comment]
If #50 is not fixed for you, then i would assume this is network or environment related issue.

**Comment by DanielWeeber** [comment]
wow. 
You can close this issue. Will solve it myself.

**Comment by merdok** [comment]
Okay, thanks!
