### ISSUE TITLE
Remap remote buttons, eg. use color buttons for media controls

### ISSUE THREAD

**Issue by KoCMoHaBTa** [merdok/homebridge-webos-tv#541]
Hi, this is really great plug.

The magic remote lacks media buttons, more specifically media buttons like play/pause.
I would be great if we could remap the colored buttons (red, green, yellow, blue) in a way that they can perform specific actions.

The problem with the wheel click is that it does not perform the same action in every context/app/input, for example
- on AppleTV+ - it toggles play/pause
- on YouTube - it shows the app's media controls
- on my TV service provider's app (EON) - it shows the media controls

I would really like to have single click play/pause, instead of 2+ clicks like on YouTube and EON

What i've tried so far:
1. `ccRemoteRemap` - lacks the color buttons and also i'm not sure how this is supposed to work

For example - none of these does nothing.
```
"ccRemoteRemap": {
    "playpause": "YELLOW"
}

"ccRemoteRemap": {
    "information": "PAUSE"
}
```

2. Using `remoteControlButtons` as triggers via automations

When defining any remote control button, eg.

```
"remoteControlButtons": [
    "RED",
    "GREEN",
    "YELLOW",
    "BLUE",
    "PLAY",
    "PAUSE"
]
```

The buttons appear in the Home app, tapping on them from the Home app works, however clicking the button on the remote - does not toggle the state of the Home app.

My idea here was to write automation in the Home app, for example where the yellow button is on - to pause.
But it appears that these are one way controls - from Home App to the TV and can't be used as event triggers.

Is there some other way to achieve my goal or this is something that currently does not exist as plugin feature?

**Comment by merdok** [comment]
Hi, thanks for the suggestion, but unfortunately from what i understand is that what you are requesting is not possible. So there is no feedback from tv which remote control button was pressed and it is not possible react to those or even remap the functionality of those.

**Comment by KoCMoHaBTa** [comment]
Ok, thanks for the info. Hopefully, someday, this could be possible.
