### ISSUE TITLE
How to update/re-fetch Input names?

### ISSUE THREAD

**Issue by SawkeeReemo** [merdok/homebridge-webos-tv#543]
Is there a way to re-fetch the updated Input names from my TV? For some reason, even though I changed the input names a while ago, they are still showing the old names in input spinner. I was going to manually update the JSON config, but figured I’d ask here first.

**Comment by merdok** [comment]
There is a json file in the prefsDir where the input names are cached, you can delete that file and that will re-fetch them from the tv.

**Comment by SawkeeReemo** [comment]
Ok cool. Thanks! But also, any idea where to find that? The only thing related to webosTv I see is this:
![IMG_9747](https://github.com/user-attachments/assets/2d145d29-bf5c-4793-ab06-916b43e5caf4)

**Comment by SawkeeReemo** [comment]
Oh I also found this:
![IMG_9748](https://github.com/user-attachments/assets/67e86da0-d200-4044-aeba-6312ba86f0a6)

**Comment by merdok** [comment]
inputsAvailablexxxxx and inputsConfigxxx are the files that you should delete

**Comment by SawkeeReemo** [comment]
Cool. Thanks! I’ll back them up first just in case. HomeKit automations are intense. 😅

**Comment by SawkeeReemo** [comment]
Thank you! That worked perfectly. Appreciate the help!
