### ISSUE TITLE
QUESTION: Notifications file? Image? Or…?

### ISSUE THREAD

**Issue by SawkeeReemo** [merdok/homebridge-webos-tv#545]
First of all, I love this plugin! Thanks for making it. 

I’m just now discovering the notifications option. But I’m not sure what type of file it takes. I tried to use a png file hoping I could see a nice icon instead of their generic speech bubble, but it really did not like that. Haha

is there a way to use your own icon/image? If not, what does the file option take?

thanks!

**Comment by merdok** [comment]
Instead of a notification message, you can specify a file which is located on the host machine. The message for the notification to show will be read from that file. This is useful to show dynamic content in the notification, like lets say the current temperature outside.

**Comment by SawkeeReemo** [comment]
That’s very cool. But what type of file? Just a text file? Or does it need something specific? And I’m assuming no way to get a different icon?

**Comment by merdok** [comment]
Yeah, just a text file, as mentioned the content of that file will be used for the notification message.
There is no way to change the icon currently.

**Comment by SawkeeReemo** [comment]
Ok, cool. Thanks for the response!
