### ISSUE TITLE
Inputs as tiles

### ISSUE THREAD

**Issue by toolman11** [merdok/homebridge-webos-tv#548]
Hi sorry for the newb question here but I was able to get this working through Homebridge on my Synology NAS just great. I have a "My LG TV" tile in my Home app, and when I tap it I can successfully turn on and off my TV or change input using the spinner below the button.

I'd like to have each input on a separate tile, or more importantly, have the ability to just say "Siri switch to HDMI1" or tie it in with an Apple Shortcut to switch inputs. Is this possible with this plugin?

**Comment by merdok** [comment]
Please check README in the configuration section https://github.com/merdok/homebridge-webos-tv?tab=readme-ov-file#tv-configuration-fields
The property which you are looking for is `appButtons`

**Comment by toolman11** [comment]
Thanks, I figured it out.
