### ISSUE TITLE
Not compatible with Node.js v22

### ISSUE THREAD

**Issue by kueblero** [merdok/homebridge-webos-tv#549]
I recently updated to Node.js v22 and now I get the error message:
The plugin "homebridge-webos-tv" requires Node.js version of ^18.20.4 || ^20.15.1 which does not satisfy the current Node.js version of v22.11.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF

**Comment by merdok** [comment]
Thanks for the info! I will validate if everything works fine with v22 and enable it!

**Comment by merdok** [comment]
Node.js v22 should now work with version 2.4.6
