### ISSUE TITLE
TV turned on when homebridge starts / reconnects to TV

### ISSUE THREAD

**Issue by quacktacular** [merdok/homebridge-webos-tv#55]
Hey! I've noticed an issue for a while, but its been getting a bit worse lately. When homebridge starts and connects to the TV it frequently turns the TV on when it was previously off. This can be especially surprising at night since the TV is quite bright.

Also seems to happen when the connection is lost (host not found or timeout etc), and later reconnects. 

Any recommendations for how I can troubleshoot this? Not necessarily an issue with the plugin itself, but I haven't been able to sort it out yet.

**Comment by merdok** [comment]
I have never experienced this before and i restart my homebridge a lot, especially when i work on updates for this plugin.
The wake on lan signal is only send to the TV when you press the on/off button (or start an app and the TV is off). Maybe somehow your on/off button is stuck and it fires all the time in the background? Maybe something else is sending the wake on lan signal to the tv or on the whole network?

**Comment by quacktacular** [comment]
Alright so this has nothing to do with homebridge-webos-tv! Sorry about that haha.

Took a look with wireshark and figured out a different plugin (homebridge-dacp) was waking up the Apple TV, which was then turning the TV on over HDMI-CEC.
