### ISSUE TITLE
Filtering EHOSTDOWN, ETIMEDOUT and ECONNREFUSED. at least EHOSTDOWN.

### ISSUE THREAD

**Issue by thesquaremedia** [merdok/homebridge-webos-tv#56]
I saw the previews issue I would suggest doing something like this below on line 110. Seems like all of this are related to the tv being of. I could create a pr if you let me know which option you prefer.

```
    this.lgtv.on('error', (error) => {
        if( ! error.contains( 'EHOSTDOWN' ) && ! error.contains( 'ETIMEDOUT' ) && ! error.contains( 'EHOSTDOWN' ) ){
                this.log.error('webOS - %s', error);
        }
    });
```
or
```
    this.lgtv.on('error', (error) => {
        if( string.indexOf( 'EHOSTDOWN' ) === -1 && string.indexOf( 'ETIMEDOUT' ) === -1 && string.indexOf( 'ECONNREFUSED' ) === -1 ){
                this.log.error('webOS - %s', error);
        }
    });
```

**Comment by merdok** [comment]
I still don't understand why is the error coming so often for some people. In my case it appears very rare, so i am not exactly sure why it is like that. I think this error is related to a network issue and maybe if we filter out this error it might confuse some people who are searching for a reason why the plugin is not working?

**Comment by thesquaremedia** [comment]
That makes sense I’ll try to see if I can debug it a bit more. When the lgtv turns off and it retira to search for it the message just keeps popping up until tv connects again.

**Comment by merdok** [comment]
Okay, let me know what you find. I will also try to improve this a little bit.

**Comment by thesquaremedia** [comment]
@merdok I believe I know why this happens. It has to do with wifi routers using the same SSID for the 2.4 and 5 GHz frequencies. It seems like the tv will randomly disconnect from the network due to this. Giving the 2.4 frequency a different name solves the issue. in fact it makes the plugin work more efficiently. Some wifi routers like att new ones use band steering but as we can see it isn't always effective. Since I made this change I haven't seen the errors show up.

**Comment by merdok** [comment]
Ok, thanks for the info. So it has something to do with the TV itself. I will try to find maybe a workaround for this but i am not if anything will work since it is clearly a network issue.
I leave this issue open till i investigate this.

**Comment by kapps7** [comment]
I am seeing this exact issue. Both my TV and home bridge are running on LAN

**Comment by defmech** [comment]
I'm getting the error `[TV] webOS - Error: connect EHOSTDOWN` multiple times a minute. Homebridge server and TV are on wired LAN connections.

**Comment by merdok** [comment]
That should be fine as long as there are no issues with the plugin.
