### ISSUE TITLE
Pop-up Notifications in screen

### ISSUE THREAD

**Issue by jesusmarcos** [merdok/homebridge-webos-tv#57]
Hi.

Would be great if the plugin allows us to generate buttons to send pre-defined messages to the TV.

So if I'm watching the TV and someone opens the door, I can be informed directly in the TV.

I don't know if this is possible or not, but could be a good option (I saw it for Home Assistant but not for Homebridge).

Many thanks in advance.

**Comment by merdok** [comment]
Yes, showing a notification on the TV is certainly possible. 
But the questions is, how would you connect that to other devices or actions with a custom message?

**Comment by jesusmarcos** [comment]
Hi merdok.

As it will not be possible to generate custom messages "on the fly", one option can be something similar to what you are doing with the appSwitch.

Let's supose that we define a property called textMessages where we can inform an ID and a text message. The ID will be there to be able to identify the option even if we change the text.

"textMessages": [
  {
    "id": "BackDoorOpen",
   "text": "The back door is open"
  },
  {
    "id": "MovementOutside",
    "text": "Movement detected in the backyard"
  }
]

You can create two accessories (switches) to activate the message in the TV everytime the switch is activated (and will be deactivated inmediatly after the activation).

So we can automated the event coming from another accessory (body sensor, contact sensor, ring bell button,...) to generate the messages.

Of course, the messages will be shown only if the TV is on (it's not needed to wake up the tv).

Could I explain you my idea about that?

I hope this helps and it's not something stupid. :-)

Many thanks in advance.

**Comment by merdok** [comment]
I wanted to prevent extending the configuration to not overwhelm users with a lot of options to configure and confuse them.
I think i saw a homebridge plugin where a switch was reading the name that the user associated it with in the Home app, maybe this could be used as a custom message for the notification.

I know that the Home app can send notifications when something happens, can this somehow be used by Hmebridge? I think that would be ideal for it.

I find the idea good and useful but i would need to think about it how would be the best way to implement this feature.

**Comment by jesusmarcos** [comment]
Great !!!   Of course this was only an idea and I'm sure that you will find better ways to implement it.

I'm happy that you are going to consider it.

Many thanks for that and for the great job done with this useful plugin.

**Comment by jesusmarcos** [comment]
Did you find a way to solve it?

Maybe some easy solution is to implement it as you did with appSwitch (just a set of strings that can be used to create the "buttons"). ;-)

**Comment by merdok** [comment]
Sorry i did not have time yet to have a look into it. Hopefully i can do that soon...

**Comment by merdok** [comment]
@jesusmarcos i think i now have a good solution how to solve it, i will be trying that out in the next days and if everything will be fine then i will commit it.
Basically for each notification i will create a switch which you can then use for automation, turning on the switch will display the notification and the switch will instantly be disable again (will emulate a button).

**Comment by merdok** [comment]
@jesusmarcos notifications are now included in the latest update (1.3.0), please try it out and let me know if it works as expected.

**Comment by palasinio** [comment]
Nice! 👍 
Works!

**Comment by jesusmarcos** [comment]
Hi merdok.

I could do a quick test right now (send a message to the TV when the backdoor is open) and it works perfectly. :-)

Thanks a lot. This opens new opportunities of communication at home.

Great job. 👍

**Comment by DJay-X** [comment]
Just want to say a big thank you @merdok . Everything works so smooth and without any problem here on my LG 55EG9209 OLED with webOS 2. Unfortunately there is no Update on this 3 Year old LG for webOS 3>

Anyways, all what I would expected works perfekt with your plugin. Notifications are also a great feature and switching to my favourite App on the LG, just by asking Siri now. 

Thanks for the time you are investing, your great work and sharing it with us. 👍🏻

**Comment by merdok** [comment]
@palasinio @jesusmarcos 
Thanks for the info! Glad that everything works fine now 👍 
@DJay-X 
Thanks! I try to make it as best as possible :)

**Comment by Hussamfhaily** [comment]
Big thanks for the update. it would be great if we can change the icon of the notification

**Comment by merdok** [comment]
Unfortunately as far as i know this is not possible.
