### ISSUE TITLE
EACCES: permission denied, open '/home/pi/Desktop/lgtvKeyFile'

### ISSUE THREAD

**Issue by Kuglikrug** [merdok/homebridge-webos-tv#58]
Hey everybody,

first of all thank you @merdok for this awesome homebridge plugin!

I managed to install the plugin and get it to run but i get the following message:

EACCES: permission denied, open '/home/pi/Desktop/lgtvKeyFile'

I created an empty file at the exact location but it still gives me the error.
I am really no expert on this and it's probably a stupid mistake i'm making but can someone tell me what i'm missing?

I'm running Homebridge as systemd on a zero w

Greetings
Leo

**Comment by merdok** [comment]
Hi,

don't create the file. The file will be created automatically for you. I suspect that since you created the file by yourself homebridge can't access the file now.

**Comment by Kuglikrug** [comment]
Hey,

I tried it first without creating the file just as you said, but i got the same message.
Went ahead and deleted the self-made-file and restarted homebridge but i still get the error.

Is there a way to give homebridge all the rights it needs to create/access the file?

**Comment by merdok** [comment]
I am not sure about that, but this is clearly a permissions issue. You can also try to delete this property from your config, then the key file will be automatically created for you.

**Comment by elkorleone** [comment]
I have the same problem, the plugin cannot create the file
to be mentioned, I'm using Hombridge in a docker (OZNU) maybe the path is wrong

**Comment by merdok** [comment]
You can try to change path, using the "keyFile" property.

**Comment by elkorleone** [comment]
The plugin dont create the file, i tried several paths

**Comment by merdok** [comment]
Then I guess that it is a homebridge permission issue. Try to correct your permission so that homebridge can write to the specified location.

**Comment by merdok** [comment]
Thanks for the info!

**Comment by merdok** [comment]
Unfortunately that is not possible.
