### ISSUE TITLE
Will Not Turn On TV

### ISSUE THREAD

**Issue by jlhunter2008** [merdok/homebridge-webos-tv#59]
When my TV is off the home app shows no response message for the TV Power switch. Also in homebridge it is throwing out the error “webOS - Error: connect ETIMEDOUT 192.168.1.166:3000” when it is turned off. Obviously when the TV is on the message goes away along with the no response message in the Home app. Any way to fix this? My LG is correctly connected via Wi-Fi.

**Comment by merdok** [comment]
Is this issue fixed?
