### ISSUE TITLE
[RTV] webOS - Error: connect ECONNREFUSED 10.0.0.7:3000

### ISSUE THREAD

**Issue by BrianR69** [merdok/homebridge-webos-tv#61]
It doesn't work for me, I used the LGTv2 plugin and it can turn on and monitor the state of my tv but it does not turn it off, but when I use this plugin it shows that error and many accesories appear on my home app, but none of them work, doesn't show if my tv is on or off and neither let me turn it on or off.
![44496406-4073c900-a629-11e8-86c3-1efef843f268](https://user-images.githubusercontent.com/42625969/44496944-ab260400-a62b-11e8-9b9e-ba2116f26848.png)

![image](https://user-images.githubusercontent.com/42625969/44497037-f6d8ad80-a62b-11e8-8610-26d360a09ac5.png)

![image](https://user-images.githubusercontent.com/42625969/44496464-83ce3780-a629-11e8-98b6-464bde06d420.png)
I have an arduino with an IR emitter as a server, and with the plugin http-ir-blaster I can use my iPhone to turn it on/off with Siri or via the server and control the inputs but it doesnt tell me if my tv is on, but I have set a few automations to turn the tv off, but sometimes my tv is already off so it turns on, and in other times i tell it to turn on but if is already on it turns off

**Comment by merdok** [comment]
You have to give permissions to the TV to accept connections. Make sure that all the toggles specified in the README are enabled and that you confrim the popup which pops on your TV.

**Comment by BrianR69** [comment]
I have activated the mobile tv, but no pop on appeard, do you think that is the problem?

**Comment by merdok** [comment]
Maybe you put in a wrong path to the keyFile or you do not have enough permissions to create that file. It can also be that your firewall is blocking the connection...

**Comment by BrianR69** [comment]
By the way, I used the same path you have specified on the Readme file

**Comment by BrianR69** [comment]
I turned off the tv and then tried to turn it on, and indeed worked, it doesn't tell me if the tv is on and this appeard(I renamed it as Tv)
![image](https://user-images.githubusercontent.com/42625969/44640901-3c251400-a979-11e8-98fe-5f8d74a2c781.png)
That appear when I turned the tv on with my iPhone

**Comment by merdok** [comment]
Only use the same path as i specified in the README if you have the directories and your homebridge user has permissions to write in it. If you do not know that then just delete this line from the config.

**Comment by BrianR69** [comment]
I’ve tried with and without it and nothing has changed

**Comment by merdok** [comment]
Then it must be a network issue, maybe wrong IP adress or mac adress. Or like i already mentioned before, your fireweall might block the connections.

What TV do you have? What webOS version?

**Comment by BrianR69** [comment]
The ip and the mac address are ok as I can turn it on, I have an LG LH550b, I think is a WebOS 2, the only option available is mobile tv, i have changed a few firewall settings and nothing happened

**Comment by merdok** [comment]
I am out of ideas here. I suppose this is a configuration problem... Maybe your TV is not on the latest software?
Can you try to ping your tv from the terminal and see if you get a response?

**Comment by BrianR69** [comment]
Its on its latest, version 4.something, the ping does work
![image](https://user-images.githubusercontent.com/42625969/44687712-c2d40280-aa06-11e8-881f-cc9cd715257c.png)

**Comment by merdok** [comment]
Yes, well then probably some configuration problems. I would recommend that you recheck your settings and make sure that everything is ok.

**Comment by BrianR69** [comment]
![image](https://user-images.githubusercontent.com/42625969/44821581-6cec8f80-abab-11e8-90de-3d1f003d70c2.png)
![image](https://user-images.githubusercontent.com/42625969/44821585-737b0700-abab-11e8-95c0-f45275d1d96d.png)
![image](https://user-images.githubusercontent.com/42625969/44821592-78d85180-abab-11e8-8812-11e126b480a1.png)
![image](https://user-images.githubusercontent.com/42625969/44821597-82fa5000-abab-11e8-9a2b-e82e21c42e89.png)
![image](https://user-images.githubusercontent.com/42625969/44821599-87bf0400-abab-11e8-8554-c45ccb9b5b36.png)
As you see here, everything is up to date, if I use the plugin LGTv2 it appears if its on(RTV),  but if I use your plugin it just says connection error, what i think it may be is the dns, i'll try to change it and tell you if something happens, I can also show you my config.json

**Comment by merdok** [comment]
This must be a permission error then. It can be that using LGTv2 and my plugin will cause some sort of conflict. Maybe you didn't give the permissions for my plugin so the tv blocks all requests.

**Comment by BrianR69** [comment]
How do I give permission to your plugin? I'll try to delete LGTv2, and see if something happens

**Comment by BrianR69** [comment]
![image](https://user-images.githubusercontent.com/42625969/44886334-89a3c880-ac7a-11e8-92f2-36a88f877546.png)
I tried to remove both and then just install yours, it says something about permission denied

**Comment by BrianR69** [comment]
Tried installing with this command "sudo npm install -g --unsafe-perm  homebridge-webos-tv" and the Permission denied error disappeared but didn't work either

**Comment by merdok** [comment]
Can you post your config.json?

**Comment by BrianR69** [comment]
![image](https://user-images.githubusercontent.com/42625969/44950194-82a1c500-adf6-11e8-88f2-b357ced59539.png)
![image](https://user-images.githubusercontent.com/42625969/44950209-cac0e780-adf6-11e8-9a8d-139398747695.png)
Sorry for the delay of posting it, and thank you for your quick response

**Comment by merdok** [comment]
The config looks good. Like i said you do not need the keyFile path. 
Also make sure that the TV is turned ON when you start your homebridge, and a popup should appear on your TV if your IP and MAC are correct. you need to confirm the popup and the plugin should work.

**Comment by BrianR69** [comment]
There is no pop up when I start homebridge even if the tv is on, but I can turn it on with Siri

**Comment by merdok** [comment]
Sorry, unfortunately i am out of ideas here. It must be some environment issue which i am not aware off.

**Comment by BrianR69** [comment]
I keep trying but I don't know what might be the problem, I copied the mac from the router, so the mac and the IP are ok, now I deleted again the keyFile path and nothing happened, it only says conection refused ip:3000
The raspberry is conected via Ethernet, you think that may be a problem?

**Comment by BrianR69** [comment]
As Right now I'm going to install homebridge on another pi that I have so i can try it with that one

**Comment by merdok** [comment]
Ethernet should not be the problem. 
Yes, please try on another Pi and let me know what happens.

**Comment by BrianR69** [comment]
Same problem even with a different Pi, and different sd card (I've tried with a RPi and a RPi Zero W)

**Comment by merdok** [comment]
Sorry, i do not know what else the problem could be.
