### ISSUE TITLE
Energy Saving (screen off) Feature

### ISSUE THREAD

**Issue by yepecece** [merdok/homebridge-webos-tv#62]
Hi, First of all, thanks for this plugin which works flawlessly.

I often use my LG TV to listen to music and it would be nice if the possibility to switch the screen off could be implemented.

The option can be found in the Picture Menu/Energy Savings settings menu:
https://www.lg.com/us/support/product-help/CT10000018-1425323388087-menu-settings

Let me know if you think this is feasible.

Thanks again

**Comment by merdok** [comment]
Hi,

thanks for the feedback.
Unfortunately, right now i am not aware of an possibility to access the picture menu...
But i will anyway have a look if this can be done.

**Comment by yepecece** [comment]
Hi, 

Thanks for your answer.
Maybe it could be done with the brightness setting?

I'm not sure this is the correct resource:
http://webosose.org/develop/ls2-api/ls2-api-reference/com-webos-service-settings/

com.webos.service.settings

Thanks.

**Comment by merdok** [comment]
Unfortunately, if i am correct, this API is not for TVs...

**Comment by rooi** [comment]
Hi,

Hope you don't mind me responding to this old topic, but it may be easier than opening a new one.
I was thinking it may be possible to achieve using a remoteControlButtons sequence while there does not seem to be an api for it.
I'm using the music player and the zz icon to turn off the screen since the display off energy saving seems missing in 4K/HDR mode. Perhaps it is possible to send HOME, RIGHT, RIGHT, OK, UP, RIGHT, RIGHT, OK with a delay after each command to mimic the remote. Placing such a sequence in a single homekit button could be nice.
What do you think?

**Comment by merdok** [comment]
@rooi 
This is actually a good idea. I think sending command sequences might be useful for many other scenarios. I will have a look at it and see if i can implement it. 
Does the sequence which you specified turns off the screen?

**Comment by rooi** [comment]
Cool, I've used a command scheduler in my receiver's plugin to assure the commands are executed in the specified sequence and with an optional delay. It's an old plugin, so there may be better examples available but here it is: https://github.com/rooi/homebridge-marantz-rs232

I just tested the command sequence, but it was not full prove. Something like HOME, UP, UP, UP, UP, OK, UP, RIGHT, RIGHT, OK seems to work better. It turn of the screen using webos's music app on my OLED55E6D with firmware 05.30.60

**Comment by merdok** [comment]
A sequence is now implemented. I did not release an update yet since i want to add some more stuff before i do that.

**Comment by merdok** [comment]
Sequence added in the 1.6.1 update 👍 Let me know if it works as expected.

**Comment by rooi** [comment]
Thanks, works great!

It took some tweaking to make it handle most situations (start conditions), but the following config works. The interval of 1000 is needed to allow the music app to open before continuing the sequence.

"sequence": ["EXIT", "HOME", "UP", "UP", "UP", "UP", "RIGHT", "RIGHT", "LEFT", "LEFT", "ENTER", "UP", "RIGHT", "RIGHT", "ENTER"],
                    "name": "screen_off",
                    "interval": 1000

The only drawback is that it takes quite some time to execute the full sequence. A refinement could allow customizing the delay after each sequence, but that would significantly lengthen the config.

This works good enough and when automating the whole sequence, one would not even pay attention to the long sequence.

**Comment by merdok** [comment]
Good to hear that it works! Thanks for letting me know.
I was thinking about an delay after each command but i decided against it because, like you said, it would just make the config more bigger and complicated.

**Comment by thealpa** [comment]
A workaround to get different delays between commands is to set your sequence's interval low and start inserting blank commands between those that require a high delay.

**Comment by xinyang-creates** [comment]
hey I found this issue via a Google search. I am using Home Assistant and able to turn the screen off using Node-RED sequence. The drawback is that the button sequence would not work across different system version.

<img width="1554" alt="Screenshot 2020-05-22 at 8 54 07 PM" src="https://user-images.githubusercontent.com/64649350/82679651-cbaa4480-9c7d-11ea-8272-90e34c33459a.png">
