### ISSUE TITLE
wake-on-lan not working

### ISSUE THREAD

**Issue by masgar** [merdok/homebridge-webos-tv#63]
Hi,

installed plugin and works fine if the TV is already on. I'm not able to switch on the TV. When I tap on TV power switch in Home app, I get lot of this messages in homebridge log:

webOS - connecting to TV

but nothing happen.

If I try to wake TV from server running homebridge, using linux command ether-wake, it works fine.

Any suggestion?

Thanks

**Comment by merdok** [comment]
Probably your firewall is blocking the call, also do you have mobile TV on enabled on your TV?

**Comment by masgar** [comment]
No firewall, mobile TV is on and if I use ether-wake on server running homebridge the TV switch on and this is a proof that is not a network issue or TV config. Maybe is a problem with wake_on_lan module, because when TV is ON your plugin works like a charm.

**Comment by merdok** [comment]
Then probably it is a problem with the wake_on_lan plugin. Make sure that it is installed also you can try to manually use the plugin as a test.

**Comment by merdok** [comment]
Do you have "mobile tv on" and "LG Connect Apps" enabled on your tv? This is crucial to make it work. Also what webOS version is your TV running?

**Comment by wstyres** [comment]
Both settings are on and the webOS version is 4.70.50. Like the user above, it works absolutely fine when the TV is on but has trouble turning the TV back on.

**Comment by wstyres** [comment]
Oh my mistake, running home bridge on Ubuntu Server with about 2 GB of RAM and 2.6 Ghz processor.

**Comment by merdok** [comment]
Then i guess this has something to do with your Ubuntu Server, maybe there is a firewall which blocks the wol packets? Did you try to manually send a wol packet from your ubuntu server?

**Comment by wstyres** [comment]
I am able to send a wol packet using `wakeonlan` from the server

**Comment by merdok** [comment]
Please try to use the same package which is used by my plugin:
https://github.com/agnat/node_wake_on_lan

**Comment by wstyres** [comment]
Using the command line utility provided by that package, I'm able to wake the TV.

**Comment by merdok** [comment]
In that there are just a few other possible causes why it is not working for you with the plugin:
- incorrect nodejs configuration/permissions
- incorrect homebridge configuration/permissions
- or maybe your plugin config file has issues
Please double check those and make sure that all of them are fine. I do cannot think of any other stuff which might cause the issues for you.

**Comment by wstyres** [comment]
Figured it out! It ended up being an issue with me running homebridge as a separate user so when I was changing the config, I was changing it in my user directory instead of the configuration that is used by the homebridge user.

**Comment by merdok** [comment]
Good to hear that you have found the issue. Maybe @masgar has the same issue?
