### ISSUE TITLE
Adjust the sound of the soundbar and TV LG

### ISSUE THREAD

**Issue by johngrinders** [merdok/homebridge-webos-tv#64]
There is a TV that is perfectly managed by homebridge-webos-tv, absolutely all functions work. But there was a problem, the LH soundbar is connected to the TV and when adjusting the sound with switches all are fine (parallel to the slider, too, the volume level changes). But when I try to change the volume level only on the slider, nothing happens. But if I switch the sound cleanly to TV, the slider starts working right away. What could be the reason? Maybe this is how to fix it? Unfortunately, I do not really understand the code myself. Thank you!!!

**Comment by merdok** [comment]
Hi,

the switches were introduced to be able to control external devices like a soundbar since the slider doesn't work for that. So if you want to change the volume of your soundbar then you need to use the switches.
See #34 

Greets
