### ISSUE TITLE
Settings controls

### ISSUE THREAD

**Issue by willsthompson** [merdok/homebridge-webos-tv#65]
Is it possible through the WebOS API to make changes to settings? I.e.: Presets for light/dark room calibration settings.

**Comment by merdok** [comment]
Currently i did not find any way to do this, i suppose this is not possible.
I leave this issue open for now, maybe someone else knows a way how to do that?

**Comment by willsthompson** [comment]
@merdok I have been looking through the WebOS API docs, and there is a key code for `AV Mode`. It's unclear how it would work, since there are always more than 2 AV modes. Maybe it will simply toggle to the next AV Mode on the list? Display the menu? Ideally there would be a way to select a specific mode.

http://developer.lgappstv.com/TV_HELP/index.jsp?topic=%2Flge.tvsdk.references.book%2Fhtml%2FUDAP%2FUDAP%2FAnnex+A+Table+of+virtual+key+codes+on+remote+Controller.htm

**Comment by merdok** [comment]
@willsthompson This is some different API then I am using, so I probably do not have access to that. Besides that i do not think `AV Mode` is what we are looking for...

**Comment by willsthompson** [comment]
Ah I see, thanks. I will post an issue in the `lgtv2` repo.
