### ISSUE TITLE
Switching apps

### ISSUE THREAD

**Issue by Dexwell** [merdok/homebridge-webos-tv#66]
Now that Siri Shortcuts is here, it would be pretty neat if we could make shortcuts that launch apps on the TV, e.g. by telling HomeKit to activate a scene. Any timeline on this? 🙏🏼

**Comment by merdok** [comment]
You can already launch any app that you want. You just have to create a switch with your desired app and then i assume that you just turn that switch on with Siri Shortcuts. Or do i misunderstand something?

**Comment by Dexwell** [comment]
Woops, sorry! Readme didn't expand on mobile, and last I checked it was only possible to configure one app switch. That's awesome man, I'm gonna tinker around!

**Comment by Dexwell** [comment]
Works flawlessly, thanks 🎉

**Comment by merdok** [comment]
Good to hear :)
