### ISSUE TITLE
Disable logging ?

### ISSUE THREAD

**Issue by neshala** [merdok/homebridge-webos-tv#69]
Plugin works just fine for me, but when i switch TV off, i see a lot of messages similar to this.

[11/23/2018, 3:33:52 PM] [My webOS tv] webOS - Error: connect EHOSTDOWN 192.168.0.15:3000 - Local (192.168.0.14:60848)

How i can disable this kind of logs, is there some config param for that?

**Comment by merdok** [comment]
The error logs cannot be disabled currently. Do you have pollingEnabled enabled or disabled?

**Comment by neshala** [comment]
pollingEnabled was true, with changing it to false those messages are gone. 
Thanks.

**Comment by merdok** [comment]
Good to hear :) Thanks for letting me know.
