### ISSUE TITLE
Turning off TV hangs Homebridge

### ISSUE THREAD

**Issue by PrzemyslawKlys** [merdok/homebridge-webos-tv#70]
I have OLED E8 version. I have Mobile TV options On (both of them). 

- turning off works - instantly - but puts Homekit in loop where all devices hang - until you turn back TV (with a pilot) 
- turning on - doesn't work

Any ideas on how I could fix it?

**Comment by PrzemyslawKlys** [comment]
I've connected LAN instead of WIFI, reset connection (deleted lg file) and it seems to work.

But turning off TV and turning it back on

```
[11/25/2018, 9:55:07 AM] [LG TV] webOS - disconnected from TV
[11/25/2018, 9:55:09 AM] [Air Quality] [2018-11-25T09:55:09.173Z] airQualityIndex = no value
[11/25/2018, 9:55:09 AM] [Air Quality] [2018-11-25T09:55:09.174Z] humidity = no value
[11/25/2018, 9:55:09 AM] [Air Quality] [2018-11-25T09:55:09.174Z] temperature = no value
[11/25/2018, 9:55:28 AM] [LG TV] webOS - Error: connect ECONNREFUSED 192.168.240.214:3000
[11/25/2018, 9:55:39 AM] [LG TV] webOS - connected to TV
[11/25/2018, 9:55:39 AM] [LG TV] webOS - app launched, current appId: com.webos.app.livetv
[11/25/2018, 9:55:40 AM] [LG TV] webOS - audio status changed
[11/25/2018, 9:55:40 AM] [LG TV] webOS - current volume: 19
[11/25/2018, 9:55:40 AM] [LG TV] webOS - muted: No
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250
    throw new Error("Cannot update reachability on non-bridged accessory!");
          ^
Error: Cannot update reachability on non-bridged accessory!
    at Accessory.updateReachability (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:250:11)
    at PlatformAccessory.updateReachability (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:129:34)
    at ActivityAccessory.refreshConnection (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/hub-accessory-base.js:56:17)
    at emitOne (events.js:121:20)
    at HubConnection.emit (events.js:211:7)
    at HubConnection._OnConnectionChanged (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:161:7)
    at HubConnection.refreshAsync (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:150:7)
    at HubConnection.refresh (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:142:7)
    at HubConnection._HandleConnectionOffline (/usr/local/lib/node_modules/homebridge-harmonyhub/lib/hub-connection.js:137:14)
    at emitNone (events.js:106:13)
    at Client.emit (events.js:208:7)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/node-xmpp-client/lib/Client.js:157:12)
    at emitOne (events.js:121:20)
    at Connection.emit (events.js:211:7)
    at Socket.onDisconnect (/usr/local/lib/node_modules/homebridge-harmonyhub/node_modules/reconnect-core/index.js:59:17)
    at emitNone (events.js:111:20)
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Failed with result 'exit-code'.
pam_unix(sudo:session): session closed for user root
pam_unix(sudo:session): session closed for user root
homebridge.service: Service hold-off time over, scheduling restart.
homebridge.service: Scheduled restart job, restart counter is at 4.
Stopped homebridge.service.
Started homebridge.service.
```

Causes HomeBridge to crash. I've again reset HomeBridge because this error seems to be popping out for different reason and it seems to work now.

**Comment by merdok** [comment]
So if everything working now? The error seems not to come from my plugin...

**Comment by PrzemyslawKlys** [comment]
Well yes and no. It works as in turning it on/off. But it occasionally stops working, as in LG is not responding. 

```
Nov 25 15:24:08 evoservices homebridge[5317]: [11/25/2018, 3:24:08 PM] [LG TV] webOS - Error: connect ECONNREFUSED 192.168.240.214:3000
Nov 25 15:24:17 evoservices homebridge[5317]: [11/25/2018, 3:24:17 PM] [LG TV] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of SomeSpecialValueREmoved
Nov 25 15:24:18 evoservices homebridge[5317]: [11/25/2018, 3:24:18 PM] [LG TV] webOS - connected to TV
Nov 25 15:24:18 evoservices homebridge[5317]: [11/25/2018, 3:24:18 PM] [LG TV] webOS - app launched, current appId: com.webos.app.livetv
Nov 25 15:24:19 evoservices homebridge[5317]: [11/25/2018, 3:24:19 PM] [LG TV] webOS - audio status changed
Nov 25 15:24:19 evoservices homebridge[5317]: [11/25/2018, 3:24:19 PM] [LG TV] webOS - current volume: 20
Nov 25 15:24:19 evoservices homebridge[5317]: [11/25/2018, 3:24:19 PM] [LG TV] webOS - muted: No
```

I went for a walk and came back to not working LG, 5 minutes later it works. Now it doesn't work.

**Comment by merdok** [comment]
Do you have polling enabled?

**Comment by PrzemyslawKlys** [comment]
```
            "accessory": "webostv",
            "name": "LG TV",
            "ip": "192.168.240.214",
            "mac": "000000000...",
            "keyFile": "/var/homebridge/lgtvKeyFile",
            "volumeControl": "slider",
            "mediaControl": false,
            "pollingEnabled": true,
            "appSwitch": [
                "youtube.leanback.v4",
                "com.webos.app.hdmi1",
                "com.webos.app.hdmi2",
                "com.webos.app.livetv"
            ]
```

**Comment by merdok** [comment]
Try to disable polling if it is making trouble.

**Comment by plainsane** [comment]
> Well yes and no. It works as in turning it on/off. But it occasionally stops working, as in LG is not responding.
> 
> ```
> Nov 25 15:24:08 evoservices homebridge[5317]: [11/25/2018, 3:24:08 PM] [LG TV] webOS - Error: connect ECONNREFUSED 192.168.240.214:3000
> Nov 25 15:24:17 evoservices homebridge[5317]: [11/25/2018, 3:24:17 PM] [LG TV] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of SomeSpecialValueREmoved
> Nov 25 15:24:18 evoservices homebridge[5317]: [11/25/2018, 3:24:18 PM] [LG TV] webOS - connected to TV
> Nov 25 15:24:18 evoservices homebridge[5317]: [11/25/2018, 3:24:18 PM] [LG TV] webOS - app launched, current appId: com.webos.app.livetv
> Nov 25 15:24:19 evoservices homebridge[5317]: [11/25/2018, 3:24:19 PM] [LG TV] webOS - audio status changed
> Nov 25 15:24:19 evoservices homebridge[5317]: [11/25/2018, 3:24:19 PM] [LG TV] webOS - current volume: 20
> Nov 25 15:24:19 evoservices homebridge[5317]: [11/25/2018, 3:24:19 PM] [LG TV] webOS - muted: No
> ```
> I went for a walk and came back to not working LG, 5 minutes later it works. Now it doesn't work. 3 minutes later it works again... so something is off

im seeing this as well with a b7

**Comment by PrzemyslawKlys** [comment]
I have disabled polling and it's a bit better, however, now LG is not really updated as it should so I guess it's not updating at all. Just now I've started HomeKit to see my LG turned off (while I can see it's running). So I press turn off and I get the exclamation mark. Clearly, it's not a solution. I'm just not sure whether this is not somehow related 

```
[11/26/2018, 9:24:40 AM] [LG TV] webOS - Error: read EHOSTUNREACH
[11/26/2018, 9:24:40 AM] [LG TV] webOS - disconnected from TV
[11/26/2018, 9:24:46 AM] [LG TV] webOS - Error: connect EHOSTUNREACH 192.168.240.214:3000
```

```
[11/26/2018, 8:26:18 AM] [LG TV] webOS - Error: connect ECONNREFUSED 192.168.240.214:3000
[11/26/2018, 8:26:30 AM] [LG TV] webOS - connected to TV
[11/26/2018, 8:26:30 AM] [LG TV] webOS - app launched, current appId: com.webos.app.livetv
[11/26/2018, 8:26:31 AM] [LG TV] webOS - audio status changed
[11/26/2018, 8:26:31 AM] [LG TV] webOS - current volume: 16
[11/26/2018, 8:26:31 AM] [LG TV] webOS - muted: No
[11/26/2018, 8:26:34 AM] [LG TV] webOS - audio status changed
[11/26/2018, 8:26:34 AM] [LG TV] webOS - current volume: 14
[11/26/2018, 8:26:34 AM] [LG TV] webOS - muted: No
[11/26/2018, 8:26:34 AM] [LG TV] webOS - audio status changed
[11/26/2018, 8:26:34 AM] [LG TV] webOS - current volume: 9
[11/26/2018, 8:26:34 AM] [LG TV] webOS - muted: No
[11/26/2018, 8:26:35 AM] [LG TV] webOS - audio status changed
[11/26/2018, 8:26:35 AM] [LG TV] webOS - current volume: 8
[11/26/2018, 8:26:35 AM] [LG TV] webOS - muted: No
```

What I've noticed however is that when I enabled Ethernet, WIFI disabled itself but somehow my Unifi was showing it under same IP address (thou different mac). Overnight after turning off my TV I noticed the IP is no longer alive. I was a bit surprised that it didn't stay up. I guess you're using WOL to wake up TV. When it did wake up both WIFI and LAN came up again with the same IP (which is super weird), now I've noticed that my IP is different (.215). I have switched off WIFI permanently in the morning and only LAN is up. When testing now on/off, channels seem to be working. I'll see how it works now. 

Maybe "Sec-WebSocket-Accept header from server didn't match expected value of" TV is reporting header value in the wrong way or expecting it differently? 

@merdok  Maybe there's debug mode we could run for this?

**Comment by merdok** [comment]
@plainsane 
@PrzemyslawKlys 
The "Sec-WebSocket-Accept header from server didn't match expected value of" i also have and i do not think that this makes any trouble, so I guess this can be simply ignored. I guess this comes from the underlying lgtv2 Node.js module.

For your other issue, you should assign a static IP address to your TV in your router, that way it will always have the same IP, maybe this is the problem why it sometimes doesn't work? 
The TV leaves the network interface alive for some time (usually around 8 minutes, till the pixel refresh runs through) after you turn it off, so that is why the TV is still responds even if it is turned off.

**Comment by PrzemyslawKlys** [comment]
Well, for me it looks like it's crashing whole homebridge. Not just LG. With polling on / off, it doesn't matter. I turned off TV, and in 2 minutes whole homekit was offline (for homebridge devices). 

Also 

```
[11/26/2018, 5:45:01 PM] [LG TV] webOS - Trying to launch com.webos.app.livetv but TV is off, attempting to power on the TV
```
This line actually showed up, and tv turned on. Than this shows up even thou TV is already on. 
```
[11/26/2018, 5:45:10 PM] [LG TV] webOS - Error: connect ECONNREFUSED 192.168.240.215:3000
[11/26/2018, 5:45:21 PM] [LG TV] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of XXX
[11/26/2018, 5:45:21 PM] [LG TV] webOS - connected to TV
[11/26/2018, 5:45:21 PM] [LG TV] webOS - app launched, current appId: com.webos.app.livetv
[11/26/2018, 5:45:22 PM] [LG TV] webOS - audio status changed
[11/26/2018, 5:45:22 PM] [LG TV] webOS - current volume: 11
[11/26/2018, 5:45:22 PM] [LG TV] webOS - muted: No
```

Problem is when it becomes unresponsive (LG + Sony + Dyson - so whole Homebridge) there are no logs in HomeBridge saying that something is wrong. I guess disabling polling just hides the issue because it doesn't do this frequently. 

Is there a way to better debug this? I would like to help. I guess I could start learning typescript :-) 

As for static vs dhcp I have 86400 seconds so long enough to not change IP. I can of course force it to static but still this is not a problem.

**Comment by merdok** [comment]
I suppose when your homebridge is crashing then it must be some other issue. You should try to search for the homebridge logs to be sure about that.

Yes, the logs correctly. That is what should show up when the tv is turned on. Like i said the "didn't match" error can be ignored, it sometimes comes up and should not affect the plugin...

Some people already posted similar issues here and I suppose that most of them are related to the environment like the network or the device on which homebridge is running. It can also be that some plugins have a conflict?

**Comment by PrzemyslawKlys** [comment]
I guess I could spin up separate homebridge VM and see how it works totally separated from anything else.

**Comment by merdok** [comment]
You could try that. On what device do you run your homebridge?

**Comment by PrzemyslawKlys** [comment]
Windows 10, Hyper-V, Ubuntu 18.04. 4GB ram, 4 CPU. Thanks to this it's faster than all "dedicated" homekit boxes

**Comment by merdok** [comment]
Oh, ok. Well i never tested this running on a ubuntu machine...

**Comment by PrzemyslawKlys** [comment]
Ok, I've made a clone of VM, moved only LG to new clone and it seems s to work much better. I've also noticed that my Dyson when is disconnected from Power basically hangs homebridge, where everything is in Updating state until it's connected back to Power. I've now enabled back Polling and testing if it changes anything but it seems Homebridge is really bad at handling plugins "problems".

**Comment by merdok** [comment]
Ok, thanks for the update.

**Comment by PrzemyslawKlys** [comment]
When it's alone it's usable. It still shows up with Updating from time to time. I have polling enabled. What actually polling does? When it's disabled how it affects setup?

**Comment by merdok** [comment]
Polling does automatically check the status of the TV every 5 seconds. When you disable polling then the checks are only done when you actually try do an action like turn on tv or change channel.

**Comment by merdok** [comment]
@PrzemyslawKlys 
Could you please update to version 1.2.0 and test if your issues are solved?

**Comment by PrzemyslawKlys** [comment]
When I press "Power off", the tv turns off and like one second later everything in HomeKit is shown as enabled. 

![image](https://user-images.githubusercontent.com/15063294/50793816-abb4f380-12c9-11e9-9d6a-f5aa44414212.png)

Even things that normally don't do that. I've just tested it again and when I pressed to turn off everything went down as it should. I press Power On again, it lights up but buttons "light down" like I didn't press them at all. Then I see TV starting up and like 10 seconds later the TV goes up it shows as started and everything updates correctly.

**Comment by merdok** [comment]
As for your first problem, i assume that you have an OLED TV, those TVs run a pixel refresh (every 4 hours of run time) after you turn them off for approx 9 minutes. In those 9 minutes the TV appear to be off but it is not, the network interface is still available and it is possible still to connect to the TV. Unfortunately this is a state which i still didn't find a way to reliable detect so for this reason the TV appears to be ON after you turned it off. This bug is already since a long time in my plugin on OLED TVs but as soon as i will find a away to detect that the TV is running the pixel refresher then i will fix this!

The second "problem" is because of my recent changes. Before the plugin blocked homebridge till the TV responded when you pressed the ON switch. Now the plugin is not waiting for the TV to turn on, instead as soon as the TV turns on the correct status will be send to homebridge. The status might change back to off because the polling in the background did not detect the TV to be turned on yet, so it sets the switch back to OFF. When you increase the polling interval then this will not occur that much.

**Comment by PrzemyslawKlys** [comment]
Seems logical ;-) Will update polling. Channel stuff is great btw. 

Have you seen news from CES that HomeKit is coming to LG TV's? https://9to5mac.com/2019/01/07/lg-tv-homekit-airplay-2/

**Comment by merdok** [comment]
Good to hear :)

Yes, i have read that and that sounds good. But last year they have promised alexa support for their TVs and i am still waiting for that, so i take it skeptical :p

**Comment by nope89** [comment]
It seems my problem is the same as TS mentions. My power state is changing back to on when i turn off my OLED 556V. So the automatic scenes do not get proper instructions and enable/disable at random. Do you have any solution for this to solve? Great work by the way. Thanks!

**Comment by merdok** [comment]
@nope89 You have a OLED so will run into the pixel refresher issue. More about it [here](https://github.com/merdok/homebridge-webos-tv/issues/70#issuecomment-452091946). Unfortunately there is no API to detect that state so i cannot easily fix that.

**Comment by nope89** [comment]
Yes i saw the topic. Was hoping that there was any fix available yet. So if the power state changes also while the TV is on is normal behavior? There isn't beside a API from LG a possibility to make use of scenes together with the TV? Thank you.

**Comment by merdok** [comment]
Basically during the time the pixel refresher is running the TV is still ON, just the screen is turned off. This is a normal behavior of the OLED TVs. Your scenes will possibly not work when the pixel refresher is running until i can find a way to solve that.
