### ISSUE TITLE
Switched TV from Wifi to Ethernet wake-on-lan not working 

### ISSUE THREAD

**Issue by MrRobotoGit** [merdok/homebridge-webos-tv#72]
Hi,

Switched the tv from wifi to eth now I'm not able to turn on the tv anymore. Was working fine before. I did a repair and changed the IP address in config file.

{
                  "accessory": "webostv",
                  "name": "Oled TV",
                  "ip": "192.168.1.126",
                  "mac": "04:4e:af:26:7f:92",
                  "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                  "volumeControl": "switch",
                  "mediaControl": false,
                  "channelControl": false,
                  "pollingEnabled": true,
                  "appSwitch":[
                     "com.webos.app.hdmi2",
                     "com.webos.app.livetv",
                     "netflix",
                     "com.atlas.tv"
                  ]

                }

**Comment by MrRobotoGit** [comment]
OK, I'm stupid. Forgot to update mac address also. Figured it out when pasted the config here.

**Comment by merdok** [comment]
Yes, most probably your IP has changed when you switch interfaces :) You need to set a static IP address for your TV in your router to avoid that.
