### ISSUE TITLE
Time shift / Live playback

### ISSUE THREAD

**Issue by padman74** [merdok/homebridge-webos-tv#73]
Hi Merdok,

thanks for your plugin - much appreciated. 
I'm looking for a solution to enable live playback remotely. Scenario: It happens that I can't manage to arrive home on time for a TV movie/show. It would be nice to tell my TV remotely (via Homekit) to start a channel and enable "live playback". When I arrive home I could rewind back and see the movie/show from beginning.
Alternatively I could record it but with current LG software I'm not able to start watching before the show is completly recorded. And there is no remote solution.

Best regards
Volker

**Comment by merdok** [comment]
This is can already partially be done now. You can turn on the TV remotely and pause the channel. Of course you have to already have your channel preset or alternatively if you know what was the last channel you can navigate to it with the channel selection. Isn't that what you want?

**Comment by padman74** [comment]
Thanks for guiding me to the media control option. Yes, this might work, but navigation is impossible if you don‘t know which program is present. Is there a chance to add a characteristic to the „TV on“ switch to optionally define a channel number? You could define a scene (with Eve app) to start with a particular channel or you could define a scene for each of your favorite channels.  I‘ve seen such a characteristic within my onkyo plugin to select the input channel.

**Comment by merdok** [comment]
This might be added in a future update, but i do not really see it as a priority currently since it would just further complicate the plugin.
