### ISSUE TITLE
Is it possible to change to specific channel?

### ISSUE THREAD

**Issue by PrzemyslawKlys** [merdok/homebridge-webos-tv#76]
I saw https://github.com/merdok/homebridge-webos-tv/issues/60

But what I wanted is ability  to set buttons for static channels. For example HBO = channel 50, some other channel = channel 7. I usually watch about 6 channels in total so having button per each one wouldn't be a problem.

**Comment by merdok** [comment]
Currently not, maybe such feature will be added in a future update.

**Comment by PrzemyslawKlys** [comment]
@merdok Thank you! I noticed the new version has what I need! Great work. Works!

**Comment by merdok** [comment]
Good to hear 👍
