### ISSUE TITLE
Find out AppIDs?

### ISSUE THREAD

**Issue by palasinio** [merdok/homebridge-webos-tv#79]
Hi, thx for this nice one :)
Can you tell me how I can fin out the app ids - for example of Amazon Prime?

And like others ask: It would be really nice to have switches to set a specific channel or app or volume.

Regards,

**Comment by merdok** [comment]
From the README: 

>  To get the app ID simply open an app on your TV and check the homebridge console. 

Switches for apps area already there. For volume you already have a slider and buttons from which you can choose from. And as for channels i might add that feature soon...
