### ISSUE TITLE
3D button

### ISSUE THREAD

**Issue by siobhanellis** [merdok/homebridge-webos-tv#82]
Can we get a switch that enables you to cycle between the 3D modes?

Off/Horizontal/vertical.

I just realized it is one of the few things I need to do, but can't.

Thanks.

**Comment by merdok** [comment]
That would be certainly possible. I will try to add it in the next update...

**Comment by merdok** [comment]
Unfortunately this will not be possible to implement. Although it is possible to enable or disable 3D, there is no way for me to determine the current status if 3D is enabled. It is also not possible to switch between the various modes. Also 3D is not anymore present on new LG Tv models, mine also do not have it anymore so i cannot test this further. For this reasons i currently decided to not implement it.

**Comment by siobhanellis** [comment]
Hi. I noticed you are using lgtv2, which supports the 3D buttons. Could you at least make it an option to show them on or not? I'm more than happy to be a tester. I know this is not in the new LG TV's, but those of us that are fans of 3D, this is one of the best TV's around (If you can still find one!)

I'd do it myself, but I don't even know how to start :-(

Thanks for consideration

**Comment by merdok** [comment]
As far as i remember, like i said before i cannot determine the current 3D state of the tv and it is not possible to do the testing for me since my TV doe snot have 3D.

**Comment by siobhanellis** [comment]
Yes, I understand that. However, I offered to be a test, and you can make it hidden by default and turn them on as an option, with the caveat. 

With your ability to do a level of automation now, it would be possible to set up a sequence of Power On and switch off 3D., for example.

**Comment by merdok** [comment]
Thanks for offering to test but that does not really help anything since before something is finished i update the version multiple times to test everything well. Without direct access to a TV this would take a lot of time. The other problem would be that i could not assure that this feature is working in future updates since i would have no way to test that.

**Comment by siobhanellis** [comment]
You are using something else that already supports it though. So, all you are doing is calling something else.



I wish I knew how to do this, as I’d do it myself.

But then we’d have to keep remerging.
