### ISSUE TITLE
Latch Notification Buttons

### ISSUE THREAD

**Issue by creinhart** [merdok/homebridge-webos-tv#85]
Thank you so much for the Notification feature. Really cool to have a pop-up notification when the front door unlocks. And thanks for the recent updates that have definitely made this plugin more stable with Siri. But I was wondering if it would be possible to latch the notification buttons so that they stay on and don't automatically turn off. The reason is that the notification doesn't stay on the TV for long at all. Like maybe 5 secs. If we had a notification that could stay on indefinitely when triggered, then we could tell it when to turn off via Apple's Home app since that's one of the settings when setting up Automations. We can choose how many minutes we'd perhaps like for it to be viewable. Just a thought.

**Comment by merdok** [comment]
Unfortunately as far as i know this is not possible, at least there is nothing public about this. LG only allows to display a notification without any possibility to modify it.

**Comment by merdok** [comment]
Theoretically it is possible, but during my testing I did not get it to work. When i will get it to work then i will add it to the plugin.

**Comment by Hussamfhaily** [comment]
it would be very useful. I have seen many icons when I use the tv remote.
