### ISSUE TITLE
channelButtons not working

### ISSUE THREAD

**Issue by bierkules** [merdok/homebridge-webos-tv#88]
Hi, first of all thanks for the great work on this plugin!

I have an issue with the channelButtons. The plugin loads fine, and everythng is working as expected, including app switching, volme controle and channelcontrol via channel up and channel down
but if I click on a channelButton nothing happens, I don't even see anything in my homebridge logfile.

This is my config:

 {
                        "accessory": "webostv",
                        "name": "My webOS tv",
                        "ip": "192.168.x.x",
                        "mac": "xx:xx:xx:xx:xx:xx",
                        "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
                        "mediaControl": false,
                        "volumeControl": "slider",
                        "channelControl": true,
                        "pollingEnabled": true,
                        "pollingInterval": 1,
                        "appSwitch":[
                           "com.webos.app.livetv",
                           "com.webos.app.tvguide",
                           "com.webos.app.hdmi1",
                           "com.webos.app.hdmi2",
                           "com.webos.app.hdmi3"
                        ],
                        "channelButtons": [1,2,303,305,506]
                }
Did I do something wrong? Any help is much appreciated!

Thank you and kind regards.

**Comment by merdok** [comment]
I do not see anything wrong with your config.json, what source do you use for live tv?

**Comment by bierkules** [comment]
I use cable tv (Germany) from Unity media.
If I switch channels with the channel up or channel down buttons, I also see the channel number and the channel name in the homebridge log file

**Comment by merdok** [comment]
Cable TV straight from TV or do you use a Set-Top-Box?
What TV do you have and what webOS version? Does your TV switch input or turn on when you try to open a channel?

**Comment by bierkules** [comment]
Yes cable TV straight from the TV, no Set-Top-Box
It's an LG55LF6329 the tv displays 04.06.25 as software version.
If I'm on HDMI for example and hit a channel button it switches to live tv but to the last channel that was watched on the TV. 
If I use the LG TV Plus App for iOS, i cann directly switch to a channel from the channel list within this apps. That's why I'm thinking the tv is supporting that feature, but I'm not sure of course.

**Comment by merdok** [comment]
When the tv switches to live lv when you hit the channel button then it means that the code is working and the request was successfully send to the TV. I think that webos2 does support this feature. My best guess is that this is simply some configuration issue or some settings with the TV. You probably have something enabled on the TV which prevents the channel switch.

**Comment by bierkules** [comment]
Thank you for your effort! It's much appreciated. 

Any idea how I could debug that a litlle bit more?

**Comment by merdok** [comment]
I just tried it right now, the LG TV Plus App uses different commands to switch channels. That makes me think that indeed it might be possible that webos2 does not support the command for switching a channel which I use. 
I will try to add some debug info in the next update which will hopefully give me some more info about what is happening on your TV. It would be also good if someone else with a webos2 TV would let me know if the channel switch is working for them.

**Comment by palasinio** [comment]
What’s the fastest way to figure out the webos version?

**Comment by merdok** [comment]
@palasinio thanks for the info.
@bierkules well, then i guess this is simply a configuration issue on your side. I suspect you have some setting enabled or disabled on your TV which prevents that.

**Comment by merdok** [comment]
@bierkules 
I have added more debug information in the latest update, please try to run hombridge with the -D parameter to see additional debug output. You can try to reproduce this issue and post the results here.

As an alternative remote control emulation is now possible, you could try to emulate the remote control number buttons for the channels. Please read the readme for more information.

**Comment by bierkules** [comment]
@merdok thanks for the update. I just tried it with homebridge -D and the output is:
[2019-1-13 14:23:40] [My webOS tv] webOS - channel button service - switching to channel number 303
[2019-1-13 14:23:40] [My webOS tv] webOS - open channel - error while switching channel
[2019-1-13 14:23:40] [My webOS tv] webOS - open channel - error message: db: no index for query

Remote Control emulation works after a very quick test for single digit channels for me!

**Comment by merdok** [comment]
As of the error, i suppose the channel 303 does not exist. Maybe you have a different channel list open?

**Comment by merdok** [comment]
@Hussamfhaily you can also post your debug result here with the -D parameter so i can see if this is the same issue. But most probably you have a custom channel list active or the specified channels doesn't exist.

**Comment by Hussamfhaily** [comment]
[2019-1-13 22:47:43] [TV] webOS - TV current appId: com.webos.app.livetv
[2019-1-13 22:47:43] [TV] webOS - TV current channel: 8, Channel 21 Shop
[2019-1-13 22:47:43] [TV] webOS - system info:
{
  "features": {
    "3d": false,
    "dvr": true
  },
  "receiverType": "dvb",
  "modelName": "49LF6309-ZA"
}
[2019-1-13 22:47:43] [TV] webOS - open channel - error while switching channel
[2019-1-13 22:47:43] [TV] webOS - open channel - error message: requires channelNumber or channelId
[2019-1-13 22:47:43] [TV] webOS - TV current channel: 8, Channel 21 Shop
[2019-1-13 22:47:43] [TV] webOS - service list:
{
  "services": [
    {
      "name": "api",
      "version": 1
    },
    {
      "name": "audio",
      "version": 1
    },
    {
      "name": "media.controls",
      "version": 1
    },
    {
      "name": "media.viewer",
      "version": 1
    },
    {
      "name": "pairing",
      "version": 1
    },
    {
      "name": "system",
      "version": 1
    },
    {
      "name": "system.launcher",
      "version": 1
    },
    {
      "name": "system.notifications",
      "version": 1
    },
    {
      "name": "tv",
      "version": 1
    },
    {
      "name": "webapp",
      "version": 2
    }
  ]
}
.
.
.
.
[2019-1-13 22:51:36] [TV] webOS - channel button service - switching to channel number 13
[2019-1-13 22:51:36] [TV] webOS - open channel - error while switching channel
[2019-1-13 22:51:36] [TV] webOS - open channel - error message: db: no index for query
[2019-1-13 22:51:37] [TV] webOS - channel button service - switching to channel number 15
[2019-1-13 22:51:37] [TV] webOS - open channel - error while switching channel
[2019-1-13 22:51:37] [TV] webOS - open channel - error message: db: no index for query
[2019-1-13 22:51:38] [TV] webOS - channel button service - switching to channel number 16
[2019-1-13 22:51:38] [TV] webOS - open channel - error while switching channel
[2019-1-13 22:51:38] [TV] webOS - open channel - error message: db: no index for query
[2019-1-13 22:51:38] [TV] webOS - TV state: On

**Comment by merdok** [comment]
@Hussamfhaily this is the same error as @bierkules has.
I suppose this has something to do with your channel list or some configuration on your TV. You would need to do some investigation, probably reset everything to default and then see if that fixes the issue.

**Comment by bierkules** [comment]
Just to let you guys know, I did some more testing.
I tried to switch my channel list from all tot DTV and also tried tu use a channel list with favs but switching channels with the channel buttons always results in the error I mentioned.

What is interesting thoug is, if I switch to channel that I have configured a channel button for. This channel button switches to activated in the home app. The debug log also shows the correct channel:
[2019-1-14 12:36:49] [LG] webOS - TV current channel: 3, ProSieben

But switching to another channel and then use channel button 3 to switch back results again in:

[2019-1-14 12:40:19] [LG] webOS - channel button service - switching to channel number 3
[2019-1-14 12:40:19] [LG] webOS - open channel - error while switching channel
[2019-1-14 12:40:19] [LG] webOS - open channel - error message: db: no index for query

The channel list within the LG TV Plus App on iOS does also work.

As I only need like 5 or 6 different channels I moved then to single digit channel numbers and use the remote control emulation to switch to the different channels. This works just fine for me.

Hope that does help in any way.

**Comment by Hussamfhaily** [comment]
Thanks for the answer. I don’t know what settings could be. I will try to search.

**Comment by Hussamfhaily** [comment]
@bierkules i have exactly the same

**Comment by palasinio** [comment]
I guess, you can‘t use favorite lists. You have to use the ‚real‘ channel number from the initial channel search. Further it’s normal, that the (homebridge) switch of the active channel shows ‚on‘.

**Comment by Hussamfhaily** [comment]
we use the normal tv list not the favorite list

**Comment by merdok** [comment]
@bierkules @Hussamfhaily I have honestly no idea why the switching does not work. I can only guess that this has something to do with your TV or TV settings. This is seems really odd because the channel detection works correctly since the switch goes to on. 
If one of you has time and willing to investigate this issue more, we can setup a live communication channel (irc, discord or whatever) and do some debugging together. Since i do not have access to the TVs which you have i cannot test it by myself.

**Comment by Hussamfhaily** [comment]
@merdok thank you very much

**Comment by bierkules** [comment]
@merdok thanks I would be willing to do some debugging together, but I'm travelling this week.I'll be back to you next week so that we can arrange something.
Thx for your help!

**Comment by merdok** [comment]
Sure, just let me know here when you are able to debug with me.

**Comment by marcodesantis71** [comment]
I have the same problem

**Comment by bierkules** [comment]
I'm getting back to this issue as I promised to be willing to do debugging with live communication.
I'd be available for example on sunday how would you like to proceed @merdok ?

**Comment by merdok** [comment]
@bierkules How about around this time on sunday? What timezone are you on?

**Comment by bierkules** [comment]
Tomorrow would be ok for me. I’m living in Germany so my timezone is
Berlin/CET

What do I have to prepare ?

Marcin <notifications@github.com> schrieb am Fr. 8. Feb. 2019 um 18:25:

**Comment by merdok** [comment]
Ok, i will post a link tomorrow at 18:00 here. You do not need to prepare anything, just make sure you have access to the device running homebridge.

**Comment by bierkules** [comment]
Ok I’ll watch for your link at 18:00 today

Marcin <notifications@github.com> schrieb am Sa. 9. Feb. 2019 um 12:09:

**Comment by bierkules** [comment]
I’m very sorry but we’ll have to postpone our appointment. My Internet
Connection at home is dead.

Andreas Wenzel <ajwenzel@gmail.com> schrieb am So. 10. Feb. 2019 um 08:18:

**Comment by merdok** [comment]
Sure, just let me know whenever you want to do the debugging. But i guess this issue has likely to be the case because the webos version does not support this.

**Comment by Tomfox91** [comment]
In case anyone is still interested in this: I had the same problem and I solved it by calling `openChannel` with `channelId` instead of `channelNumber` (index.js, line 1056). Channel ids look something line 7_458_346_0_1002_5001_1.
