### ISSUE TITLE
Starting TV with Channels button broken

### ISSUE THREAD

**Issue by PrzemyslawKlys** [merdok/homebridge-webos-tv#89]
I've defined channels in the new version. If you start TV by choosing a channel I've noticed that:

- The TV will turn on 
- The TV will turn on the last channel it was
- Channel that I clicked is constantly "work in progress" in a HomeKit
- I can press another channel but nothing changes and it comes into work in progress as well
- After 20+ seconds finally, all other "proper" buttons get highlighted (before even thou TV was on, it went unnoticed)
- the 2 channels that I pressed earlier show not responding
- when I click on them they work and everything gets refreshed.

**Comment by merdok** [comment]
Everything looks ok to me. Does it happen every time you try to do it? What TV do you have? What webos version?

**Comment by PrzemyslawKlys** [comment]
I tried it once, it happened once and I reported. Will observe. `LG Oled 65 E8 PLA`, webos 04.10.15.

I also have small problems with it (not related to Homebridge) where when playing games it sometimes turns off screen (it's like it's switching between HDR and non-hdr even during a game). With Sony's OLED it wasn't visible and switch happened without turning the screen off. 

As a side note: 
- would it be possible to make section like 'defaultButtons' where it would create 10 numbers so if press quickly 123 it would switch to 123 channel? I know it's not maybe great but potentially an option. Seeing as LG will support homekit, airplay only on 2019+ I guess everyone is going to stick with Homebridge after all :-)

**Comment by merdok** [comment]
I guess this has something to do with your environment (homebridge or the device which homebridge runs on), I have no other explanation for this now. Maybe i will add some more debug info in the next update so you can paste it here and i can see what is actually happening at your setup.

Yes, it is possible to emulate the remote control but i did not have time to have a look at that. So i guess that your use case would be possible.

**Comment by PrzemyslawKlys** [comment]
Thanks! I really appreciate your help.

**Comment by merdok** [comment]
I have added more debug information in the latest update, please try to run hombridge with the -D parameter to see additional debug output. You can try to reproduce this issue and post the results here.

Also remote control emulation is now possible. Please read the readme for more information.

**Comment by PrzemyslawKlys** [comment]
```
root@evoservices:~# npm outdated -g --depth 0
Package               Current  Wanted  Latest  Location
homebridge-webos-tv  1.2.0            1.2.0  1.4.0
undefined
root@evoservices:~# npm update -g
root@evoservices:~# npm outdated -g --depth 0
Package               Current  Wanted  Latest  Location
homebridge-webos-tv  1.2.0            1.2.0  1.4.0
undefined
```

Weirdly it doesn't let me update to new version

**Comment by merdok** [comment]
Well, then i guess that there is something wrong with your setup. As i see you still have version 1.2.0...

**Comment by PrzemyslawKlys** [comment]
:-) Ye, but it says Latest is 1.2.0 while location (whatever that means 1.4.0)

**Comment by PrzemyslawKlys** [comment]
```
npm i homebridge-webos-tv -g 
```
This fixed it. Will report back
