### ISSUE TITLE
Volume Slide and volumeLimit not working

### ISSUE THREAD

**Issue by Xusqui** [merdok/homebridge-webos-tv#90]
Hi, neighbours and friends...

I have already seen that is a known "issue" that slide doesn't work when an external source is connected (SoudBar), and that's why the switches are for (kind of annoying...). But is it normal that the volumeLimit also doesn't work?

My config is:

{
           "accessory": "webostv",
            "name": "La tele",
            "ip": "192.168.x.x",
            "mac": "xx:xx:xx:xx:xx:xx",
            "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
            "volumeControl": true,
            "mediaControl": true,
            "channelControl": true,
            "volumeLimit": 50,
            "pollingInterval": 10,
            "appSwitch": [
                "com.webos.app.livetv",
                "com.webos.app.tvguide",
                "youtube.leanback.v4",
                "com.webos.app.hdmi1",
                "com.webos.app.hdmi2",
                "com.webos.app.hdmi3",
                "com.webos.app.hdmi4",
                "com.webos.app.externalinput.component",
                "netflix",
                "amazon",
                "canal.yomvi"
            ],
            "channelButtons": [1,2,3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20],
            "notificationButtons": [
                "User A arrived",
                "User B arrived"
            ]
}

When the volumeLimit is reached (50), if I press volume up in the remote or in the "Home Switch", the slide keeps on going up, until it reaches 100.

I guess is the same "issue" as the 'not-working-slide-for-external-devices'. Am I right?

Thank you!

**Comment by merdok** [comment]
I would guess that this is the case here. Since you are using an external audio device, most probably the plugin cannot get the current volume. 
Please try to run homebridge in debug mode with the parameter -D, then try to reproduce the issue and paste the homebridge lg here. That way i can have a look what is actually happening there.

**Comment by Xusqui** [comment]
Ok... Her's a pastebin of the logs!

https://pastebin.com/raw/Ey6Z34re

**Comment by Xusqui** [comment]
Ok... Here's a pastern with the Debug logs

https://pastebin.com/raw/sx9eweX5

**Comment by merdok** [comment]
I guess i understand now, the volume limit only works when you use the provided by my plugin volume slider or switch.  Did you expect it to work when you change the volume with the remote?

**Comment by joseeduardoperes** [comment]
I have a home theater (external speaker connect thru HDMI ARC) connected to my webostv, the volume slider doesn't work when the external speaker is selected, otherwise the volume buttons work normal with external speaker. Is there a fix for this?
