### ISSUE TITLE
TV inputs not working in iOS 12.2 beta?

### ISSUE THREAD

**Issue by viticci** [merdok/homebridge-webos-tv#98]
Updated to the latest 1.50 version today, but it appears that TV inputs aren't working correctly in the Home app. Having set them as such:

```
      "inputs": [
          {
            "appId": "youtube.leanback.v4",
            "name": "YouTube"
          },
          {
              "appId": "com.webos.app.tvguide",
              "name": "TV Guide"
            }
      ]
```

The inputs do show up in the accessory's settings screen (both default and custom inputs), but when clicking the Input button, the whole list is empty (see screenshots).

![img_2565](https://user-images.githubusercontent.com/2583235/51804624-d4def900-2263-11e9-9803-c52533475a5c.jpg)
![img_2566](https://user-images.githubusercontent.com/2583235/51804626-d4def900-2263-11e9-92bf-1c56c4daddd9.jpg)

**Comment by basvdploeg** [comment]
Had the same issue. Removing Homebridge from HomeKit (and adding it back) fixed it for me.

Probably a weird caching thing.

**Comment by merdok** [comment]
@viticci 
Yes, this is basically because iOS 12.2 is still a beta so it has issues so there is some strange behavior. Restarting homebridge and/or force closing the Home app and opening it  back again should fix it.

**Comment by viticci** [comment]
Got it. A combination of force-quitting the Home app and rebooting the iPhone fixed it. 

As a side note not related to this, I would suggest not including any inputs as defaults. When I rename something like "HDMI 1" in the Home app, the name is overwritten the next time I restart homebridge.

I ended up creating custom inputs for HDMI 1, HDMI 2, etc. just to use my custom names, but this means I now have default inputs as duplicates in the list.

**Comment by WestCoast5550** [comment]
Is there any way to remove default inputs and replace them by custom one?

**Comment by merdok** [comment]
@viticci @WestCoast5550 
I added those default inputs as convenience so popele do not have to add them by hand. Currently there is no way to remove or hide them, but based on the API i suppose Apple will let you hide them from the list. It is just the first beta which Apple released and more TV stuff should come in the next betas.

**Comment by WestCoast5550** [comment]
@merdok I think it would be nice to add some boolean variable that can hide them.

**Comment by merdok** [comment]
I guess the only inputs which i can remove are AV and Component, i guess nobody really uses them now anymore... 

The HDMI's and Live TV i would still leave in, and see if Apple will provide a way to hide them in one of the next releases. I mean this is still in beta and things will certainly change.

**Comment by merdok** [comment]
@viticci 
Just noticed that the default inputs revert back to original name after a homebridge restart like you said, this is pretty annoying. For this reason i removed all the default inputs in the latest update.

**Comment by viticci** [comment]
Thank you. Works great.
