### ISSUE TITLE
Picture Configuration Settings

### ISSUE THREAD

**Issue by kapps7** [merdok/homebridge-webos-tv#99]
Hey thanks for the plugin,

Is there an api available for Picture ie Standard, Bright, User 1 etc.
Would be useful for different forms of content eg. Sport, Movies etc.
Thanks

**Comment by merdok** [comment]
The current TV implementation in HomeKit does not let you change the picture settings. This might change in the next betas. 
Another issue here is that LG has no public documentation available that shows how to do that. I suppose there is a undocumented way to do it but we first have to find it...
